/// 可执行 Operator 的唯一注册表。
///
/// 知识节点只声明 operator id；路由、Trial 页面与测试都从这里读取同一份
/// 输入、动作、完成定义、复盘触发和替代动作，避免未实现的 operator 静默
/// 降级为“做一个小动作”。
class EvidenceOperatorSpec {
  const EvidenceOperatorSpec({
    required this.id,
    required this.label,
    required this.instruction,
    required this.completion,
    required this.reviewTrigger,
    required this.inputPrompts,
    required this.alternatives,
    this.minimumMinutes = 0,
    this.needsCommitment = false,
    this.needsExposureLevel = false,
  });

  final String id;
  final String label;
  final String instruction;
  final String completion;
  final String reviewTrigger;
  final List<String> inputPrompts;
  final List<String> alternatives;
  final int minimumMinutes;
  final bool needsCommitment;
  final bool needsExposureLevel;
}

EvidenceOperatorSpec _spec(
  String id,
  String label,
  String instruction,
  String completion,
  String reviewTrigger, {
  List<String> inputs = const <String>[],
  List<String> alternatives = const <String>[],
  int minutes = 0,
  bool commitment = false,
  bool exposure = false,
}) =>
    EvidenceOperatorSpec(
      id: id,
      label: label,
      instruction: instruction,
      completion: completion,
      reviewTrigger: reviewTrigger,
      inputPrompts: inputs,
      alternatives: alternatives,
      minimumMinutes: minutes,
      needsCommitment: commitment,
      needsExposureLevel: exposure,
    );

class EvidenceGrowthOperatorRegistry {
  EvidenceGrowthOperatorRegistry._();

  static final Map<String, EvidenceOperatorSpec> specs = <String, EvidenceOperatorSpec>{
    for (final item in <EvidenceOperatorSpec>[
      _spec('SOURCE_PRACTICE', '原知识练习', '按当前节点的原始 How-to 执行。',
          '完成节点规定的练习并记录现实结果。', '练习完成后'),
      _spec('BELIEF_TO_TESTABLE_HYPOTHESIS', '把信念改写成假设',
          '把“我/别人/世界一定……”改写成：在什么情境、做什么动作、多久内会看到什么可观察结果。',
          '形成一条含情境、动作、结果与窗口的可证伪假设。', '观察窗口到期后',
          inputs: ['原信念', '可能推翻它的证据'], alternatives: ['先分开事实与解释', '只测试最小一部分']),
      _spec('REALITY_CALIBRATION', '希望与现实校准',
          '各写一条支持希望的事实、限制条件和下一项可控动作，不把积极感受当作结果保证。',
          '希望、残酷事实和可控动作同时被记录。', '动作产生现实反馈后',
          inputs: ['支持事实', '限制事实'], alternatives: ['降低承诺强度', '保持为待验证假设']),
      _spec('PROBABILITY_LEDGER', '概率账本',
          '把“肯定/绝不”换成 0–100% 概率，写下支持与反对证据及下一次更新条件。',
          '保存概率、正反证据和更新阈值。', '出现预先约定的新证据时',
          inputs: ['当前概率', '上调条件', '下调条件'], alternatives: ['暂记 50%', '先收集一个样本']),
      _spec('ALTERNATIVE_EVIDENCE', '补全证据视野',
          '列出三条可观察事实：支持原解释、反对原解释、仍未知；暂不做身份结论。',
          '至少出现一条反向证据和一项未知。', '获得新事实后',
          inputs: ['原解释'], alternatives: ['请可信对象核对事实', '先停止灾难化措辞']),
      _spec('TESTABLE_GROWTH_RULE', '可检验成长规则',
          '把“只要努力”改为“采用哪种策略、获得何种反馈、何时求助”，并做一轮小测试。',
          '策略、反馈和求助条件均明确。', '一轮练习结束后',
          inputs: ['要发展的能力', '反馈来源'], alternatives: ['换策略', '降低难度']),
      _spec('FACT_INFERENCE_SPLIT', '事实与解释分栏',
          '只写摄像机能记录的事实，再单独写解释和情绪；为解释标注“待验证”。',
          '事实与推断没有混写，并保留至少一个替代解释。', '新事实出现后',
          inputs: ['可观察事实', '当前解释'], alternatives: ['询问在场者', '保持未知']),
      _spec('SELF_CONCORDANCE_CHECK', '目标自我和谐检查',
          '分别写出“我真正重视什么、谁期待我这样做、即使无人看见是否仍愿意”，再决定保留或改写目标。',
          '目标与价值、外部压力和个人选择被分开。', '目标确认后',
          inputs: ['价值', '外部期待'], alternatives: ['缩小目标', '暂停非自主目标']),
      _spec('GAP_OPERATOR', '目标差距操作',
          '各写一句目标状态、当前状态和最大可改变差距，只做一个让差距今天变小的动作。',
          '动作产生现实输出或反馈，而非新增清单。', '动作完成后',
          inputs: ['目标状态', '当前状态', '最大差距'], alternatives: ['先补必要前提', '缩到十分钟']),
      _spec('GOAL_ROLE_CHECK', '目标角色检查',
          '检查目标是在提供方向、证明身份还是承诺幸福；把结果目标改写为可实践的过程。',
          '目标不再承担“达到后才值得/幸福”的身份保证。', '完成一次过程行动后',
          inputs: ['目标承诺了什么'], alternatives: ['保留方向，删除身份条件', '转为过程指标']),
      _spec('COMMITMENT_LADDER', '承诺阶梯',
          '从私下记录、告诉一位可信对象、小额可撤回承诺、公开承诺四级中，选择最低但足以促进行动的一档。',
          '承诺等级、退出方式、损失上限和见证人已保存。', '承诺动作到期或完成后',
          inputs: ['最低有效承诺', '退出方式', '损失上限'], alternatives: ['只做私下记录', '降低受众', '取消金钱惩罚'], commitment: true),
      _spec('PREREQUISITE_CHECK', '必要前提检查',
          '列出动作必须具备的条件，区分“缺了不能做”和“有更好”；先补最早缺失的一项。',
          '必要条件被验证，或生成一个前提子目标。', '前提补齐后',
          inputs: ['必要条件', '当前是否具备'], alternatives: ['缩小到不依赖该前提的版本', '寻求资源']),
      _spec('PRIORITY_CUT', '优先级切割',
          '只保留一个当前主目标，并明确写下本窗口“不做”的目标及重新评估日期。',
          '一个主目标与一份暂不做清单被保存。', '当前观察窗口结束后',
          inputs: ['主目标', '暂不做'], alternatives: ['缩短优先窗口', '降低次要目标标准']),
      _spec('OBSERVATION_WINDOW', '观察窗口',
          '定义何时开始、何时结束、期间看哪一项信号；窗口结束前使用 OBSERVE，不提前判失败。',
          '起止时间和信号明确。', '窗口到期时',
          inputs: ['观察信号', '窗口结束时间'], alternatives: ['延长一次并说明理由', '改用更早期信号']),
      _spec('START_5_MIN', '五分钟起飞',
          '现在只做 5 分钟：打开真正需要的材料并完成第一个可见动作；到点允许停。',
          '已进入任务并留下可观察痕迹，不要求完成整件事。', '5 分钟后',
          inputs: ['第一个可见痕迹'], alternatives: ['缩成 2 分钟', '只打开材料', '请可信对象见证'], minutes: 5),
      _spec('RECOVER', '恢复优先',
          '先做有明确起止的恢复：停止输入、补水、闭眼或睡眠；恢复后只重新进入原任务 2 分钟。',
          '恢复有起止时间，并重新检查身体状态与能否进入任务。', '恢复窗口结束后',
          inputs: ['睡眠/身体状态', '恢复窗口'], alternatives: ['补完整睡眠', '降低今日强度', '暂停高风险决定'], minutes: 20),
      _spec('BODY_FIRST', '身体先行',
          '选择一个安全的身体动作（站起、走动、呼吸、洗脸）持续 2 分钟，再记录情绪与行动准备度变化。',
          '身体动作完成并记录前后变化。', '2 分钟后',
          inputs: ['当前身体感受'], alternatives: ['更轻动作', '先休息']),
      _spec('SAFE_EXPOSURE', '安全现实暴露',
          '把 80% 版本交给一位可信且风险低的对象，本轮只获取一条具体反馈。',
          '真实发送、展示或提出请求并记录回应。', '回应出现或窗口到期后',
          inputs: ['暴露对象', '预计焦虑 0–10', '退出方式'], alternatives: ['只展示局部', '选择更安全对象', '降低受众'], exposure: true),
      _spec('EXPOSURE_LADDER', '渐进暴露阶梯',
          '列出 0–10 强度的三个层级，只做 3–6 分的 Stretch 层；记录预测焦虑、峰值、实际与恢复时间。',
          '完成一个非 Panic 层级并保存预测、实际与恢复数据。', '焦虑回落或约定窗口结束后',
          inputs: ['三个暴露层级', '预计焦虑', '停止信号'], alternatives: ['下降一个层级', '加入支持者', '改为模拟'], exposure: true),
      _spec('DIVIDE_NEXT_STEP', '缩小下一步',
          '持续把动作减半，直到 10 分钟内可以开始且能留下可见痕迹；立即做第一步。',
          '最小步骤完成并留下文件、消息、记录或到场痕迹。', '第一步完成后',
          inputs: ['当前大动作', '最小可见痕迹'], alternatives: ['先补一个前提', '只做两分钟']),
      _spec('CONTEXT_REDESIGN', '情境重设计',
          '只改一个线索或摩擦：让正确行为少一步，或让旧行为多一步；保持稳定情境观察 7 天。',
          '一个环境变量已改变，并记录至少三次相同情境。', '7 天或三次情境后',
          inputs: ['稳定情境', '要改的单一线索'], alternatives: ['移除旧线索', '提前放好工具', '增加可见反馈']),
      _spec('VISIBLE_TRACE', '可见行动痕迹',
          '把“努力”改为一次可验证的提交、发送、到场、练习记录或作品片段。',
          '存在可回看的现实痕迹。', '痕迹产生后',
          inputs: ['痕迹形式'], alternatives: ['保存截图', '请他人确认']),
      _spec('PROCESS_ACTION', '过程行动',
          '选择一项只反映练习质量、不用于展示形象的动作，并记录注意是否回到过程。',
          '完成过程动作且未新增形象证明任务。', '动作结束后',
          inputs: ['过程动作', '形象诱因'], alternatives: ['隐藏点赞数据', '缩小受众']),
      _spec('RECOVER_REENTER', '恢复后重返',
          '为恢复设结束点；到点只做原任务两分钟，若仍有明显身体风险则继续恢复或求助。',
          '记录恢复效果和是否重新进入。', '恢复结束点',
          inputs: ['结束点', '重返动作'], alternatives: ['延长恢复并说明依据', '降低任务强度']),
      _spec('RISK_DOWNSCALE', '风险降级',
          '写最坏结果、可逆性和是否保留下一轮；把规模降到三项均可接受。',
          '损失封顶、可撤回且保留下一轮资格。', '风险条件变化时',
          inputs: ['最坏结果', '撤回方式', '损失上限'], alternatives: ['模拟', '分阶段投入', '退出']),
      _spec('ROLE_MODEL_TRANSFER', '榜样机制迁移',
          '只提取榜样一个可观察行为，写出依赖条件和自身差异，再测试最小迁移动作。',
          '完成机制迁移，而不是复制整个人生。', '迁移动作完成后',
          inputs: ['具体行为', '依赖条件', '自身差异'], alternatives: ['降低强度', '选择起点相近的榜样']),
      _spec('FAILURE_REFRAME', '失败信息重构',
          '把结果分成事实、策略/情境信息、非身份结论；只提取一条下一轮可验证变化。',
          '结果与身份分开，并形成一个可检验变化。', '分类完成后',
          inputs: ['发生的事实', '身份化解释'], alternatives: ['检查是否观察过早', '缩小下一轮']),
      _spec('FAILURE_CLASSIFY', '失败分类',
          '将结果标为未行动、观察中、基本、可预防、复杂、聪明失败或 Ruin 风险，再匹配修复动作。',
          '失败类型、证据和对应动作明确。', '分类后',
          inputs: ['失败类型', '分类证据'], alternatives: ['补足事实', '暂记未分类']),
      _spec('OPTIMALIST_CHECK', '优秀主义检查',
          '检查标准是否同时允许错误、休息、反馈和弯路；删除一个不必要的完美条件。',
          '高标准保留，至少一个僵化条件被移除。', '现实反馈后',
          inputs: ['必要标准', '完美条件'], alternatives: ['定义 80% 版本', '限定修改次数']),
      _spec('PERMISSION_TO_BE_HUMAN', '允许成为人',
          '命名当前情绪与身体感受，允许其存在 90 秒；不要求立即积极，再选择安全下一步。',
          '情绪被记录且未被当作事实或命令。', '情绪强度变化后',
          inputs: ['情绪', '身体感受'], alternatives: ['与可信对象共处', '先恢复']),
      _spec('COMPASSIONATE_ACCOUNTABILITY', '关怀式负责',
          '用不羞辱的语言写事实、责任和下一修复动作；既不否认影响，也不攻击身份。',
          '事实、责任和修复动作三项齐全。', '修复动作完成后',
          inputs: ['事实', '责任', '修复'], alternatives: ['先停止自责循环', '请他人核对']),
      _spec('RECOVERY_MEASURE', '恢复时间测量',
          '记录受挫时点、恢复到可行动时点和帮助恢复的条件。',
          '恢复时长与关键条件被保存。', '重新进入行动时',
          inputs: ['受挫时点', '重返时点'], alternatives: ['次日补记', '使用时间范围']),
      _spec('SAFE_IMPERFECTION', '安全不完美练习',
          '选择一个低风险瑕疵，限定修改次数后交付；不用于医疗、法律、财务或安全关键任务。',
          '在安全边界内交付含可控瑕疵的版本。', '收到反馈后',
          inputs: ['可接受瑕疵', '安全边界'], alternatives: ['选择更低风险材料', '只给可信对象']),
      _spec('PDSA_REVIEW', 'PDSA 证据复盘',
          '保留原预测，依次记录实际事实、预测误差、学习和下一轮只改变的一个变量。',
          '原预测未改写，并形成可执行规则更新。', '现在完成',
          inputs: ['实际事实', '最大意外', '单一变量'], alternatives: ['先分开事实与解释', '情绪过强先恢复']),
      _spec('POSITIVE_REPLAY', '积极经验重播',
          '重建当时的情境、身体、行为、支持条件和意义，再安排一次最小复现。',
          '可复制条件和下一次复现已保存。', '复现后',
          inputs: ['具体情境', '支持条件'], alternatives: ['只复现一个条件', '用文字重播']),
      _spec('PREDICTION_LEDGER', '预测完整性账本',
          '在行动前锁定预测、概率、观察信号和窗口；结果后只能新增记录，不能改写原预测。',
          '预测版本已锁定且可与结果逐项比较。', '窗口到期后',
          inputs: ['预测', '概率', '观察信号'], alternatives: ['降低预测精度', '保持未知']),
      _spec('STOP_RUMINATION', '停止反刍',
          '若重复内容没有新事实或新动作，先离开记录 10 分钟，做恢复；回来只写一个新事实或结束复盘。',
          '循环停止，产生新事实/动作或明确结束。', '10 分钟后',
          inputs: ['是否有新事实'], alternatives: ['身体活动', '联系可信支持']),
      _spec('ONE_VARIABLE_CHANGE', '只改一个变量',
          '列出可能变量，选择影响最大且可逆的一项，其余保持不变。',
          '单一变量、保持项和观察窗口明确。', '窗口到期后',
          inputs: ['改变变量', '保持不变'], alternatives: ['缩小变量幅度', '先补基线']),
      _spec('POSITIVE_RESULT_AUDIT', '积极结果审计',
          '记录有效结果、可能偶然因素、必要条件和复现测试，避免一次成功直接升级成普遍规律。',
          '成功条件与复现计划被保存。', '复现样本出现后',
          inputs: ['成功事实', '可能偶然因素'], alternatives: ['保持为弱证据', '再取一个样本']),
      _spec('SURPRISE_CAPTURE', '意外捕捉',
          '写下与预测差异最大的一个事实，以及它挑战了哪条假设。',
          '意外事实和被挑战假设形成对应关系。', '写完后',
          inputs: ['最大意外', '原假设'], alternatives: ['暂不解释', '补一项观察']),
      _spec('ACT_ADJUST_EXIT', 'ACT / ADJUST / EXIT',
          '整理支持信号、关键反证、继续成本和观察窗口，选择继续、只改一个变量、退出或继续观察。',
          '保存决定、理由及下一动作；EXIT 保存 Hypothesis Closed。', '证据整理完成后',
          inputs: ['支持信号', '关键反证', '继续成本'], alternatives: ['ACT 再取样', 'ADJUST 单变量', 'EXIT 保存学习', 'OBSERVE 到窗口']),
      _spec('EXCEPTION_REPLAY', '例外时刻重播',
          '找到问题未发生的一次，拆出情境、线索、行为和支持条件，只复现其中一个可控条件。',
          '例外被转成一个可重复条件。', '复现后',
          inputs: ['例外时刻', '不同条件'], alternatives: ['寻找更小例外', '请他人补充']),
      _spec('NEXT_TRIAL', '创建下一轮试验',
          '把本轮学习转成下一轮的单一假设、低风险动作、预测和复盘时间。',
          '新 Trial 与上一轮建立链接。', '新 Trial 窗口到期后',
          inputs: ['新假设', '单一变化'], alternatives: ['先观察', '关闭路线']),
      _spec('REPETITION_PLAN', '适量重复计划',
          '选择稳定线索、最小动作和可持续频率；安排三次重复后再评价。',
          '三次重复及记录方式已安排。', '三次重复后',
          inputs: ['稳定线索', '频率'], alternatives: ['降低频率', '减少动作']),
      _spec('PERSONAL_FIT_UPDATE', '个人适配更新',
          '仅依据本人、当前情境的完成率、结果和可重复性调整节点适配度，不修改公共知识。',
          '个人适配证据已更新且公共节点未改变。', '新增样本后',
          inputs: ['当前情境', '个人结果'], alternatives: ['保持原分数', '继续取样']),
      _spec('PREMORTEM', '事前验尸',
          '限时 7 分钟：假设项目已失败，列五个原因；只为概率×损失最高的一项设置护栏。',
          '产生一个预防动作和一个早期信号，然后停止分析。', '7 分钟到点',
          inputs: ['失败原因', '最高风险项'], alternatives: ['降低规模', '设置备用方案', '延迟不可逆承诺'], minutes: 7),
      _spec('CAUSAL_LEVEL_CHECK', '因果层级检查',
          '把结论标为观察到的关联，设计只改变一个变量的低风险测试，暂不宣布因果。',
          '关联、干预、共同原因与结果被分别保存。', '完成一轮干预后',
          inputs: ['观察关联', '可能共同原因'], alternatives: ['继续收集样本', '保持为假设']),
      _spec('THEORY_IN_USE_CHECK', '口头规则与实际规则',
          '分别写“我说自己相信什么”和“行为显示我实际遵守什么”，选择一个现实动作检验差距。',
          '口头规则、行动规则和检验动作明确。', '动作完成后',
          inputs: ['口头规则', '行为证据'], alternatives: ['请他人观察', '缩小检验动作']),
      _spec('SYSTEM_SCAN', '系统分层扫描',
          '在参数、信息流、规则和目标中只选择一层、一个变量做实验，不同时重构全部系统。',
          '一个系统变量已改变并有明确观察窗口。', '窗口到期后',
          inputs: ['当前系统层', '单一变量'], alternatives: ['先查信息流', '先查规则', '先查反馈延迟']),
    ])
      item.id: item,
  };

  static EvidenceOperatorSpec? maybeById(String id) => specs[id];

  static EvidenceOperatorSpec byId(String id) {
    final spec = specs[id];
    if (spec == null) {
      throw StateError('Operator $id 未在 EvidenceGrowthOperatorRegistry 注册');
    }
    return spec;
  }

  static Set<String> get ids => specs.keys.toSet();
}
