import 'yangming_models.dart';

YangmingLesson _lesson({
  required String id,
  required String group,
  required String title,
  required String source,
  required List<String> core,
  required List<String> problems,
  required List<String> cases,
  required List<String> actions,
  required String missionTitle,
  required String world,
  required String setup,
  required List<YangmingMissionChoice> choices,
  required List<String> reviews,
}) {
  return YangmingLesson(
    id: id,
    group: group,
    title: title,
    source: source,
    originalTextSlot: '这里显示该段《传习录》原文。',
    detailedExplanationSlot: '这里显示该段对应的详细解释。',
    coreConcepts: core,
    problemTypes: problems,
    scenarioCases: cases,
    actionPlans: actions,
    missionTitle: missionTitle,
    missionWorld: world,
    missionSetup: setup,
    missionChoices: choices,
    reviewPrompts: reviews,
  );
}

List<YangmingMissionChoice> _choices({required String passLabel, required String failLabel, required String middleLabel, required String passFeedback, required String failFeedback, required String middleFeedback}) {
  return <YangmingMissionChoice>[
    YangmingMissionChoice(id: 'A', label: failLabel, feedback: failFeedback, willDelta: -1, awarenessDelta: -1, integrationDelta: -1),
    YangmingMissionChoice(id: 'B', label: middleLabel, feedback: middleFeedback, willDelta: 1, awarenessDelta: 2, integrationDelta: 0),
    YangmingMissionChoice(id: 'C', label: passLabel, feedback: passFeedback, willDelta: 3, awarenessDelta: 2, integrationDelta: 3),
  ];
}

final List<YangmingLesson> yangmingLessons = <YangmingLesson>[
  _lesson(
    id: 'ZX-01', group: '知行合一', title: '知行合一第1段', source: '徐爱录 005',
    core: <String>['知而不行只是未知', '知是行之始', '私欲会隔断知行本体'],
    problems: <String>['知道很多却总不做', '把理解误当成完成'],
    cases: <String>['该沟通却拖了三周', '总说知道该运动却不开始'],
    actions: <String>['把一句“我知道”改写成今天5分钟动作', '今天至少执行一个拖延任务的最小起步'],
    missionTitle: '我都知道', world: '书院·现实任务大厅', setup: '你面对一件拖延很久但明知应做的事。',
    choices: _choices(passLabel: '立即拆成5分钟动作并执行', failLabel: '继续搜集道理', middleLabel: '先写下为什么没做', passFeedback: '你从口头知道进入了行动启动，真知开始成形。', failFeedback: '你把“知道”继续用作拖延外衣。', middleFeedback: '你开始看见阻碍，但还没真正跨入行动。'),
    reviews: <String>['今天哪件事我其实并没有真知道？', '我最常用什么理由把知道伪装成完成？'],
  ),
  _lesson(
    id: 'ZX-02', group: '知行合一', title: '知行合一第2段', source: '徐爱录 006',
    core: <String>['工夫要有下手处', '本体与工夫要分层理解', '初学不应追最高境界'],
    problems: <String>['总想一步到位', '高目标替代现实下手'],
    cases: <String>['学很多理论却没一件事落地', '开口就谈圆融却没有日常训练'],
    actions: <String>['今天只选一个现实场景做工夫', '把“彻底改变”降成一个行为守持'],
    missionTitle: '下手处', world: '书院·课程树', setup: '眼前同时出现高境界词汇与一件具体事务。',
    choices: _choices(passLabel: '进入一个现实事务开始练', failLabel: '直奔最高境界', middleLabel: '请AI帮我找下手处', passFeedback: '你抓住了初学真正能落脚的工夫入口。', failFeedback: '你又用高境界逃避低处下手。', middleFeedback: '你开始愿意落地，但还需要亲自下手。'),
    reviews: <String>['我最近是否在拿高目标逃避低处下手？', '今天我的本原下手处是什么？'],
  ),
  _lesson(
    id: 'ZX-03', group: '知行合一', title: '知行合一第3段', source: '陆澄录 027',
    core: <String>['圣学只一个功夫', '学习与实践不可割裂'],
    problems: <String>['先学完再做', '课程与生活分家'],
    cases: <String>['学完课程没任何行为变化', '总在准备阶段打转'],
    actions: <String>['每学一段立即绑定一个现实动作', '禁止出现“先学完再说”'],
    missionTitle: '不是两门课', world: '书院·学习塔', setup: '你可以一直停在学习塔，也可以学一点就进入行动场。',
    choices: _choices(passLabel: '学一点就行动验证', failLabel: '一直停在学习塔', middleLabel: '行动后再回来修正理解', passFeedback: '你正在形成知行回路。', failFeedback: '你把圣学拆成了两门互不相干的课。', middleFeedback: '你开始循环，但还需更稳定地来回验证。'),
    reviews: <String>['今天哪次学习自然带出了行动？', '我是否仍把知与行当成两个阶段？'],
  ),
  _lesson(
    id: 'ZX-04', group: '知行合一', title: '知行合一第4段', source: '答顾东桥书 133',
    core: <String>['意念发动就是行之始', '亲历才能完成真知'],
    problems: <String>['以为想想不算', '低估起心动念'],
    cases: <String>['起嫉妒心却说没做出来不算', '想做却一直只停留在想'],
    actions: <String>['记录3次念头刚起的时刻', '把“准备做”改成“现在做第一步”'],
    missionTitle: '念起之时', world: '心念秘境', setup: '瞬时念头不断闪现：逃避、比较、拖延。',
    choices: _choices(passLabel: '命名念头并立刻转成动作', failLabel: '忽略它', middleLabel: '先观察并命名', passFeedback: '你在行之始处就进入了工夫。', failFeedback: '忽略的念头会慢慢长成行为。', middleFeedback: '觉察已经开始，但还未进入转化。'),
    reviews: <String>['今天最值得警惕的一念是什么？', '我是否还把“还没做”当作免责理由？'],
  ),
  _lesson(
    id: 'ZX-05', group: '知行合一', title: '知行合一第5段', source: '答顾东桥书 134',
    core: <String>['知之真切笃实处即是行', '理不外吾心'],
    problems: <String>['价值原则停在口头', '说一套做一套'],
    cases: <String>['常说尊重却在冲突时讥讽', '常说真诚却总包装自己'],
    actions: <String>['选择一句最常说的原则，今天行为兑现一次', '写下最常说但最少做的一句话'],
    missionTitle: '你真的相信吗', world: '价值镜厅', setup: '系统展示你常说的原则，并安排压力测试。',
    choices: _choices(passLabel: '在压力里照原则行动', failLabel: '继续宣讲原则', middleLabel: '对比说过的话和做过的事', passFeedback: '原则开始从口头转入生命。', failFeedback: '你把理停在嘴上，未曾活在心里。', middleFeedback: '你看见了落差，但还需要一次兑现。'),
    reviews: <String>['哪条原则在真实压力下最容易失效？', '我讲得最多、活得最少的道理是什么？'],
  ),
  _lesson(
    id: 'ZX-06', group: '知行合一', title: '知行合一第6段', source: '答顾东桥书 137',
    core: <String>['问思辨也在行中', '学若不行不成其学'],
    problems: <String>['讨论代替实践', '分析包装拖延'],
    cases: <String>['研究沟通技巧却不沟通', '研究健身计划却不运动'],
    actions: <String>['把一个正在研究的主题变成实际验证', '为每个新知识建立验证场景'],
    missionTitle: '永远在准备', world: '方法迷宫', setup: '你持续收到更多资料、更多比较、更多准备建议。',
    choices: _choices(passLabel: '立刻做一个小实验', failLabel: '继续收集资料', middleLabel: '让AI生成验证场景', passFeedback: '你让学问重新回到了行里。', failFeedback: '资料越来越多，行动越来越远。', middleFeedback: '工具有了，还差真正开始实验。'),
    reviews: <String>['我今天哪次思考其实只是延迟行动？', '我是否把问思辨变成了逃避现实的外衣？'],
  ),
  _lesson(
    id: 'ZX-07', group: '知行合一', title: '知行合一第7段', source: '答顾东桥书 138',
    core: <String>['意之所在便是物', '格物在具体事务中展开'],
    problems: <String>['只想改观念不肯进事情', '抽象成长逃避现实处理'],
    cases: <String>['想修身却逃避家庭沟通', '想成长却连作息也不整理'],
    actions: <String>['写下今天真正该格的“物”', '不再空谈改变，直接挑一件具体事务'],
    missionTitle: '你的物在哪里', world: '事务地图', setup: '抽象成长按钮和具体现实事务同时摆在你面前。',
    choices: _choices(passLabel: '进入一件现实事务处理', failLabel: '继续点抽象成长按钮', middleLabel: '先标记我意之所在', passFeedback: '你终于进入了真正可格的物。', failFeedback: '抽象满足没有把你带进真实工夫。', middleFeedback: '你看见了意向，但还需落入具体事。'),
    reviews: <String>['今天哪件现实事务就是我该格的物？', '我是否还在逃向空泛自我感动？'],
  ),
  _lesson(
    id: 'ZX-08', group: '知行合一', title: '知行合一第8段', source: '答顾东桥书 140',
    core: <String>['良知是复杂情境的尺度', '不行不可以为致知'],
    problems: <String>['一复杂就失去判断', '借复杂性拖延决策'],
    cases: <String>['不断搜资料却不决断', '极端案例讨论替代眼前原则'],
    actions: <String>['先写一句当前第一原则', '在有限条件下做一件最好决策'],
    missionTitle: '复杂局面', world: '城市治理', setup: '一个没有完美答案的高压事件突然发生。',
    choices: _choices(passLabel: '写下第一原则并做决定', failLabel: '继续无限搜集信息', middleLabel: '先列清判断准绳', passFeedback: '你回到了尺度，而不是困在复杂性里。', failFeedback: '复杂情境被你用来回避承担。', middleFeedback: '准绳开始明晰，但决断仍需落地。'),
    reviews: <String>['今天我是否借复杂性拖延决断？', '我此刻真正的准绳是什么？'],
  ),
  _lesson(
    id: 'ZX-09', group: '知行合一', title: '知行合一第9段', source: '答顾东桥书 141',
    core: <String>['多闻多见是第二义', '见闻要服从致良知'],
    problems: <String>['信息越多心越散', '把见闻积累当成长本身'],
    cases: <String>['刷很多知识内容却无行动', '观点看得越多越混乱'],
    actions: <String>['今天减少一半输入，只保留一个执行点', '输入后必须输出或行动'],
    missionTitle: '知识洪流', world: '信息市集', setup: '课程、观点、案例在你眼前不断涌入。',
    choices: _choices(passLabel: '只保留一条并立即行动', failLabel: '继续浏览全部内容', middleLabel: '只保留一条最相关内容', passFeedback: '你让见闻回到了本心与行动。', failFeedback: '见闻堆积让心越来越散。', middleFeedback: '你开始聚焦，但还要真正落地。'),
    reviews: <String>['今天摄入的知识，哪一条真正改变了行为？', '我是否把见闻积累当成成长本身？'],
  ),
  _lesson(
    id: 'ZX-10', group: '知行合一', title: '知行合一第10段', source: '答陆原静书（二）165',
    core: <String>['本体上人人有良知', '工夫上有深浅难易'],
    problems: <String>['因失败否定自己', '把工夫困难误判成本体无能'],
    cases: <String>['一遇反复就说我不适合', '看到别人自然就觉得自己没希望'],
    actions: <String>['把“我不行”改写成“我还在困知勉行”', '缩小动作重新训练'],
    missionTitle: '本体未坏', world: '修炼场·挫败区', setup: '你连续几次训练失败，系统弹出“也许你根本不适合”。',
    choices: _choices(passLabel: '调整难度继续练', failLabel: '认定自己就是不行', middleLabel: '承认自己在困知勉行阶段', passFeedback: '你把失败重新放回工夫层，而不是身份层。', failFeedback: '你误把一时失手当成整体定论。', middleFeedback: '认知已经转正，还需要继续练。'),
    reviews: <String>['今天我在哪件事上因失败误判了自己？', '我需要的是否定自己，还是加深工夫？'],
  ),
  _lesson(
    id: 'ZX-11', group: '知行合一', title: '知行合一第11段', source: '答欧阳崇一 168',
    core: <String>['良知不离见闻也不滞于见闻', '互动中也要回心判断'],
    problems: <String>['被外界带跑', '逃进内在玄想'],
    cases: <String>['一被评价就失衡', '只讲内在成长却对现实麻木'],
    actions: <String>['在一次互动中记录自己如何没有被带走', '不把外界刺激直接等于真相'],
    missionTitle: '不离不滞', world: '社交回廊', setup: '评价、互动、反馈持续袭来。',
    choices: _choices(passLabel: '在互动中回心判断', failLabel: '迎合外界情绪', middleLabel: '先短暂停顿觉察', passFeedback: '你既没有逃开世界，也没有丢掉主心。', failFeedback: '你把外界当成了内在准则。', middleFeedback: '你开始暂停，但还需稳定判断。'),
    reviews: <String>['今天我在哪个场景里被外界带跑了？', '我有没有误把外部信息当成内在准则？'],
  ),
  _lesson(
    id: 'ZX-12', group: '知行合一', title: '知行合一第12段', source: '黄直录 226',
    core: <String>['一念发动处便即是行', '恶念要在方萌时克治'],
    problems: <String>['只做事后补救', '纵容不善念潜伏'],
    cases: <String>['情绪刚起不处理，等爆发后才后悔', '嫉妒、推责心起时自我放过'],
    actions: <String>['记录一个本来可以在起念时就拦住的瞬间', '设计一条拦截句和替代动作'],
    missionTitle: '方萌', world: '方萌室', setup: '嫉妒、怨、饰非、推责等念头在心里刚刚冒头。',
    choices: _choices(passLabel: '识别并替换动作', failLabel: '任其发展', middleLabel: '先当场识别它', passFeedback: '你把修养前移到了念头发生处。', failFeedback: '放过方萌，后面只会更难。', middleFeedback: '你已经看见，还要继续克治。'),
    reviews: <String>['今天哪一念若不及时处理会酿成更大问题？', '我最常在哪类起念上放过自己？'],
  ),
  _lesson(
    id: 'ZX-13', group: '知行合一', title: '知行合一第13段', source: '黄省曾录 291',
    core: <String>['自然来自熟练工夫', '知行都需笨功夫'],
    problems: <String>['想一步到位', '抗拒重复训练'],
    cases: <String>['嫌基础动作枯燥', '看到自己不自然就否定道路'],
    actions: <String>['选择一个最基础的动作连续练7天', '记录本周最有价值的一次笨功夫'],
    missionTitle: '笨功夫', world: '重复训练场', setup: '守时、记录、沟通、反思这些基础动作需要反复训练。',
    choices: _choices(passLabel: '坚持小动作重复', failLabel: '跳过基础训练', middleLabel: '失败后当天重启', passFeedback: '自然感正在由重复工夫慢慢长出来。', failFeedback: '你想跳过训练直接成熟。', middleFeedback: '你开始接受反复，但还需更稳定。'),
    reviews: <String>['我今天最抗拒的笨功夫是什么？', '我是不是总想跳过训练直接成熟？'],
  ),
  _lesson(
    id: 'ZX-14', group: '知行合一', title: '知行合一第14段', source: '钱德洪录 321',
    core: <String>['难不在知，在致', '被触动不等于已经改变'],
    problems: <String>['深受启发却不行动', '浅层认知感动很多'],
    cases: <String>['读完文章很有感触但生活无变化', '总说我其实知道原因'],
    actions: <String>['任何让你有触动的点，都绑定一个现实动作', '把认同感受变成代价明确的行动'],
    missionTitle: '触动之后', world: '洞见长廊', setup: '你不断获得“深受启发”的时刻。',
    choices: _choices(passLabel: '立刻绑定一个现实动作', failLabel: '收藏感动就结束', middleLabel: '写下心得', passFeedback: '你从“被触动”走向了“致出来”。', failFeedback: '你把启发留在了情绪层。', middleFeedback: '心得帮助理解，但还没完成转化。'),
    reviews: <String>['今天“明白了”的事情里，有哪件真正致出来了？', '我逃避的是不知道，还是落实的代价？'],
  ),
  _lesson(
    id: 'ZX-15', group: '知行合一', title: '知行合一第15段', source: '钱德洪录 322',
    core: <String>['博学、笃行、知及、仁守是一条工夫', '关键在守'],
    problems: <String>['理解不差但守不住', '一时热情高后面就散'],
    cases: <String>['一周冲很猛第二周归零', '知道该做什么却持续不了'],
    actions: <String>['选一个最小原则连续守7天', '中断后当天重启'],
    missionTitle: '守', world: '守持回廊', setup: '你已经懂了原则，但要连续多天把它守住。',
    choices: _choices(passLabel: '连续守住并中断后重启', failLabel: '只靠一时热情', middleLabel: '今天先守住一次', passFeedback: '你把理解转成了守持。', failFeedback: '热情的起伏代替不了工夫的持续。', middleFeedback: '第一天开始不错，但关键在连续。'),
    reviews: <String>['我本周最需要提升的是理解，还是守持？', '我通常在哪个节点开始松掉？'],
  ),
  _lesson(
    id: 'LZ-01', group: '立志', title: '立志第1段', source: '陆澄录 016',
    core: <String>['立志是内在定向', '念念存天理即是立志'],
    problems: <String>['目标很多方向很乱', '把立志误成成功规划'],
    cases: <String>['每个月换新目标', '追求结果却不知为何而做'],
    actions: <String>['写一句当前最重要的内在方向', '删掉一个不服务于主志的目标'],
    missionTitle: '志是什么', world: '志向大厅', setup: '成功、地位、认可、自由与存天理同时出现在你面前。',
    choices: _choices(passLabel: '选内在原则并写出为何而做', failLabel: '只选外在目标', middleLabel: '请AI追问我的主志', passFeedback: '你的志开始从结果转向方向。', failFeedback: '外在目标很容易变化，难以承载长期工夫。', middleFeedback: '你在接近主志，还需要一句明确表达。'),
    reviews: <String>['我今天追逐的是结果，还是方向？', '我的志到底是内在原则，还是外部想要？'],
  ),
  _lesson(
    id: 'LZ-02', group: '立志', title: '立志第2段', source: '陆澄录 025',
    core: <String>['持志如心痛', '真正重要的事要进入注意力中心'],
    problems: <String>['重要的事总被次要事挤掉', '口头重视不够真切'],
    cases: <String>['一天到晚都很忙但真正重要的事没动', '总被消息和闲事打断'],
    actions: <String>['给主志安排30分钟绝对不被打断时间', '把次要事后移'],
    missionTitle: '心痛', world: '分心风暴', setup: '通知、闲事、社交邀请不断涌入，你只有有限精力。',
    choices: _choices(passLabel: '设不可打断时段并守住', failLabel: '顺着干扰走', middleLabel: '先收回一次注意力', passFeedback: '你开始像守住心痛一样守住主志。', failFeedback: '分心暴露了志并未真正进入中心。', middleFeedback: '你短暂回来了，还要拉长守住的时间。'),
    reviews: <String>['今天我最重要的事被什么轻易打断了？', '我真的像心痛一样在意自己的志吗？'],
  ),
  _lesson(
    id: 'LZ-03', group: '立志', title: '立志第3段', source: '陆澄录 031',
    core: <String>['立志用功如种树', '先根后枝叶花果'],
    problems: <String>['急于求成', '总盯结果不肯扎根'],
    cases: <String>['习惯刚开始就幻想逆袭', '还没培根就频繁切方向'],
    actions: <String>['接下来7天只做基础动作不评价结果', '今天只做“浇水”不做结果想象'],
    missionTitle: '种树', world: '培根园', setup: '你经营一棵树，可以培根，也可以不断查看是否开花。',
    choices: _choices(passLabel: '稳定培根浇水', failLabel: '频繁查看结果', middleLabel: '先减少结果焦虑', passFeedback: '真正的成长正从根部开始。', failFeedback: '你把心力耗在了枝叶幻象上。', middleFeedback: '你开始看见焦虑，但还需回到动作。'),
    reviews: <String>['我最近最想看见结果的地方，是不是正该回到根上？', '今天我做的是枝叶工程还是根部工夫？'],
  ),
  _lesson(
    id: 'LZ-04', group: '立志', title: '立志第4段', source: '陆澄录 054',
    core: <String>['长立此善念而已', '善念出现时要护住根芽'],
    problems: <String>['善念一来就拖延', '在善念外加太多戏'],
    cases: <String>['想道歉却拖着不去', '想做正事却先设计复杂仪式'],
    actions: <String>['善念一起立刻执行第一步', '每天记录一念善及其落实情况'],
    missionTitle: '护住善念', world: '善芽庭院', setup: '道歉、感谢、承担、节制等善念不断在你心里生起。',
    choices: _choices(passLabel: '立刻做第一步', failLabel: '先拖一拖', middleLabel: '先记录这念善', passFeedback: '你把善念护成了行动的根芽。', failFeedback: '善念在拖延里快速衰减。', middleFeedback: '记录有帮助，但更重要的是立即落地。'),
    reviews: <String>['今天哪一念善我没有护住？', '我有没有在善念之外加太多自我表演？'],
  ),
  _lesson(
    id: 'LZ-05', group: '立志', title: '立志第5段', source: '薛侃录 096—097',
    core: <String>['总是志未切', '不是理不明，多半是志不真'],
    problems: <String>['总说还没想清楚', '以不确定掩盖不承担'],
    cases: <String>['其实知道该面对什么却一直回避', '说自己迷茫但关键时刻又很清楚'],
    actions: <String>['写一件其实早知道却没面对的事', '把“还没想明白”改成一个动作'],
    missionTitle: '你不是不知道', world: '真实回廊', setup: '系统回放你反复说“还不确定”的场景。',
    choices: _choices(passLabel: '承认其实知道并做第一步', failLabel: '继续说不确定', middleLabel: '先写下真实答案', passFeedback: '你把伪不确定拆开，开始承担。', failFeedback: '不确定成了逃避的掩体。', middleFeedback: '你已经更诚实了，下一步是行动。'),
    reviews: <String>['我今天哪件事不是不明白，而是不够切？', '我最常用哪种“还没想清楚”来掩盖逃避？'],
  ),
  _lesson(
    id: 'LZ-06', group: '立志', title: '立志第6段', source: '薛侃录 116',
    core: <String>['立志贵专一', '外好会漏泄精神'],
    problems: <String>['主轴弱而支线太多', '忙得很满却没真正推进'],
    cases: <String>['各种内容都想学却没有一条主线', '大量时间给了无关消遣'],
    actions: <String>['本周砍掉一个分心源', '每天固定一段主志时间块'],
    missionTitle: '删枝', world: '主干森林', setup: '成长树不断长出诱人支线，你的主干在变弱。',
    choices: _choices(passLabel: '删掉一项分心源并保护主干', failLabel: '全部都想保留', middleLabel: '先标记主要分心源', passFeedback: '你在用专一养护主志的主干。', failFeedback: '支线越多，主干越弱。', middleFeedback: '识别已经开始，接下来要真正删枝。'),
    reviews: <String>['我今天最典型的外好是什么？', '哪一件事最该成为我当前唯一主轴？'],
  ),
  _lesson(
    id: 'LZ-07', group: '立志', title: '立志第7段', source: '答周道通书 144',
    core: <String>['为学紧要大头脑只是立志', '修养最终不能外包'],
    problems: <String>['离开监督就松', '靠群体和提醒维持'],
    cases: <String>['有人陪伴就做，独处就散', '总把坚持不住归因于环境'],
    actions: <String>['今天独立完成一项修养任务', '建立个人晚间自检机制'],
    missionTitle: '离群之后', world: '独行坡', setup: '导师与同伴全部退场，只剩你自己。',
    choices: _choices(passLabel: '自主设检并完成今日任务', failLabel: '继续等别人提醒', middleLabel: '先写晚间自检', passFeedback: '你开始拥有不靠外界维持的主心骨。', failFeedback: '你把修养仍旧托付给环境。', middleFeedback: '结构搭好了，接下来要自己执行。'),
    reviews: <String>['今天哪些努力是靠外部推着走？', '如果没人提醒，我还愿意坚持什么？'],
  ),
  _lesson(
    id: 'LZ-08', group: '立志', title: '立志第8段', source: '黄修易录 240',
    core: <String>['志于道一句含后面功夫', '无志而游艺只是门面'],
    problems: <String>['技能多道心弱', '爱形式和技巧不重根本'],
    cases: <String>['表达不错但内里没主轴', '做事越来越精致，内在越来越空'],
    actions: <String>['写下一项技能究竟服务于什么更深目标', '砍掉一个只是门面的练习'],
    missionTitle: '房子与装饰', world: '书院建设', setup: '你可以先建根基，也可以先买装饰和皮肤。',
    choices: _choices(passLabel: '先立根基并让技能服务主志', failLabel: '先做外观装饰', middleLabel: '先分析技能与主志关系', passFeedback: '你让“艺”开始服务于“道”。', failFeedback: '门面快速好看，但根基依旧空。', middleFeedback: '意识到了关系，还需要做一次真实调整。'),
    reviews: <String>['我现在最像在建房，还是在买装饰？', '我的技能真正服务于什么？'],
  ),
  _lesson(
    id: 'LZ-09', group: '立志', title: '立志第9段', source: '黄修易录 241',
    core: <String>['志立得时千事万为只是一事', '不是事情累人，是得失累人'],
    problems: <String>['把现实事务当修养借口', '多线程生活中主轴丢失'],
    cases: <String>['工作忙就不修身', '家庭责任重就放弃整顿自己'],
    actions: <String>['把最不想碰的现实事务改写成修养场', '问这件事里我该守的良知是什么'],
    missionTitle: '一事', world: '多线生活地图', setup: '工作、家庭、学习、关系同时压来。',
    choices: _choices(passLabel: '找出共同主轴并在一事中练良知', failLabel: '继续把事务当借口', middleLabel: '先写出共同主轴', passFeedback: '你开始看见千事万为背后的同一条线。', failFeedback: '你让忙碌替你挡住了工夫。', middleFeedback: '主轴开始浮现，接下来要进入一件事。'),
    reviews: <String>['哪件现实事务我本可以拿来修身，却拿来当借口？', '我真正被事情拖累，还是被得失拖累？'],
  ),
  _lesson(
    id: 'LZ-10', group: '立志', title: '立志第10段', source: '黄省曾录 254',
    core: <String>['志若不在天理关键处会坍塌', '利害会揭示真实排序'],
    problems: <String>['一遇利害就退', '平时讲原则关键时刻让位'],
    cases: <String>['怕得罪人就不说真话', '怕失去利益就做违心事'],
    actions: <String>['写出最容易牺牲原则的场景', '在一个小利害冲突里守一次底线'],
    missionTitle: '利害当前', world: '抉择门', setup: '说真话可能受损，沉默更安全。',
    choices: _choices(passLabel: '守住原则', failLabel: '优先自保', middleLabel: '先写清底线', passFeedback: '利害来时，你让志站回了天理一边。', failFeedback: '自保成了最高原则，志便开始动摇。', middleFeedback: '底线开始清晰，接下来需要在现实中守一次。'),
    reviews: <String>['今天我在哪个地方把原则让给了利害？', '我的志在关键时刻到底站在哪一边？'],
  ),
  _lesson(
    id: 'LZ-11', group: '立志', title: '立志第11段', source: '黄省曾录 257',
    core: <String>['圣人教人不是做成一个模子', '因材成就而不失其道'],
    problems: <String>['人格模仿', '把修养做成姿态扮演'],
    cases: <String>['觉得自己不像标准好学生就怀疑不能修身', '模仿别人风格越来越不自然'],
    actions: <String>['写下自己的气质优点与偏差', '设计一条适合自己性格的修养路径'],
    missionTitle: '不是同一个模子', world: '人格工坊', setup: '系统提供不同人格底色，你必须决定如何成就自己。',
    choices: _choices(passLabel: '因材修正并成就', failLabel: '继续模仿别人', middleLabel: '先识别自己的气质偏差', passFeedback: '你开始在自己的材质上做真正的工夫。', failFeedback: '你在表演一个不属于自己的样子。', middleFeedback: '认识自己是必要一步，但还要形成路径。'),
    reviews: <String>['我最近是否在表演某种“正确样子”？', '我的真实气质应如何被纳入修养？'],
  ),
  _lesson(
    id: 'LZ-12', group: '立志', title: '立志第12段', source: '黄省曾录 260',
    core: <String>['未是必为圣人之志耳', '主志旁不得留别念挂带'],
    problems: <String>['志不够纯', '一边想变一边保留太多退路'],
    cases: <String>['想成长又舍不得旧习惯', '想正直又想讨好所有人'],
    actions: <String>['写出当前最大的别念挂带', '做一个真实切断动作'],
    missionTitle: '别念挂带', world: '决断台', setup: '你口头上要真正改变，但体面、懒惰、讨好、旧习惯都在拉你。',
    choices: _choices(passLabel: '命名并切断最大的挂带', failLabel: '一边立志一边保留退路', middleLabel: '先识别当前最大的挂带', passFeedback: '你的主志因为真实取舍而开始变定。', failFeedback: '别念不断，主志就永远虚弱。', middleFeedback: '识别是开始，关键是做一次切断。'),
    reviews: <String>['我最影响主志的一条挂带是什么？', '我是真的想变，还是只想保留体面地想变？'],
  ),
];

List<YangmingLesson> get zhixingLessons => yangmingLessons.where((e) => e.group == '知行合一').toList();
List<YangmingLesson> get lizhiLessons => yangmingLessons.where((e) => e.group == '立志').toList();
