import 'belief_models.dart';

/// Concepts: 把 57 段内容按逻辑关系组织成可学习、可重演、可行动的“知识单元”。
///
/// 说明：
/// - segmentKeys 指向已入库的 57 段（如 "L6#12"）。
/// - episodeIds/missionIds 对应下面的 episodes / missions。
const List<BeliefConcept> beliefConcepts = [
  // ========== 信念与现实（基础） ==========
  BeliefConcept(
    id: 'c0_overview',
    group: '信念与现实',
    order: 0,
    title: '自我实现预言：全局框架',
    oneLiner: '信念不是魔法，而是一套会改变行动、互动与注意力的机制。',
    detail: '对应课程“Belief as Self-Fulfilling Prophecies”的总览：信念能改变现实，但不是因为“想就会有”，而是它会改变你愿不愿意上场、你怎么解释、你会看到什么、以及你怎么对待自己和别人。',
    segmentKeys: ['L5#1', 'L6#10', 'L6#12'],
    episodeIds: [],
    missionIds: ['m_overview_chain_log'],
  ),
  BeliefConcept(
    id: 'c1_limit_break',
    group: '信念与现实',
    order: 1,
    title: '信念的“可能性开关”',
    oneLiner: '先相信“可能”，才会愿意投入足够的努力与试错。',
    detail: 'Bannister 破 4 分钟一英里说明：很多“上限”一半在身体、一半在信念。信念改变后，训练方式、坚持程度与试错频率都会改变，现实才有机会被改写。',
    segmentKeys: ['L5#2', 'L6#8', 'L6#15'],
    episodeIds: ['e_bannister', 'e_edison'],
    missionIds: ['m_possibility_switch'],
  ),
  BeliefConcept(
    id: 'c1b_self_help_boundary',
    group: '信念与现实',
    order: 2,
    title: '自助的边界：信念≠万能',
    oneLiner: '“相信”要配合行动与现实条件，否则容易变成自欺或受害。',
    detail: '课程专门纠偏：自助运动抓到“信念重要”的部分真相，但常过度承诺（例如把吸引力法则当万能钥匙）。正确用法是：用信念支持行动与恢复，而不是替代行动与现实约束。',
    segmentKeys: ['L5#3', 'L6#6', 'L6#7', 'L6#9', 'L6#10'],
    episodeIds: [],
    missionIds: ['m_self_help_boundary'],
  ),
  BeliefConcept(
    id: 'c1c_efficacy_selfesteem',
    group: '信念与现实',
    order: 3,
    title: '自我效能与自尊：从“做得到”长出来',
    oneLiner: '真正稳的自信来自“行动→证据→效能感”，而不是口号式自尊。',
    detail: 'Bandura 的自我效能强调“我能做到”的证据来自行动与反馈；William James 提出过自尊公式（成功/期待），但研究显示简单“降低期待”并不能解决问题。更靠谱的路径是：把目标拆小、做出证据、让效能感上升。',
    segmentKeys: ['L5#4', 'L6#25', 'L7#7', 'L7#8'],
    episodeIds: [],
    missionIds: ['m_efficacy_evidence'],
  ),

  // ========== 关系与期待 ==========
  BeliefConcept(
    id: 'c2_expectation',
    group: '关系与期待',
    order: 0,
    title: '期待效应（皮格马利翁）',
    oneLiner: '你怎样看一个人，会改变你怎样对待他，也改变他怎样成为。',
    detail: '从 Rosenthal 到 Jamison：期待会通过“更细致的关注/更高质量的反馈/更耐心的等待”传递出去，形成自我实现链条。它既发生在教育，也发生在职场与亲密关系。',
    segmentKeys: ['L5#5', 'L5#6', 'L5#7', 'L5#8'],
    episodeIds: ['e_rosenthal', 'e_jamison'],
    missionIds: ['m_expectation_upgrade'],
  ),
  BeliefConcept(
    id: 'c2b_see_potential',
    group: '关系与期待',
    order: 1,
    title: '看见潜能：注意力会“浇水”',
    oneLiner: '你关注什么，就更可能把什么培养出来：潜能需要被看见。',
    detail: '课程用“车上的孩子”比喻：潜能常常本来就在，但被忽略。你开始看见并强化那一点点好的证据，就会形成正反馈（对自己/对别人都一样）。',
    segmentKeys: ['L5#7'],
    episodeIds: [],
    missionIds: ['m_see_potential'],
  ),

  // ========== 情境与环境 ==========
  BeliefConcept(
    id: 'c3_situation_power',
    group: '情境与环境',
    order: 0,
    title: '情境的力量：人常被环境推着走',
    oneLiner: '很多时候不是“人坏”，而是“情境强”；要学会拆解与重建情境。',
    detail: '从从众/服从/监狱实验到现实事件：强情境会改变普通人的行为。理解这一点，是为了更聪明地设计制度、边界与环境线索，而不是单靠意志硬扛。',
    segmentKeys: ['L5#9'],
    episodeIds: ['e_situation_mirror', 'e_langer_1959', 'e_langer_pilot'],
    missionIds: ['m_positive_situation_build'],
  ),
  BeliefConcept(
    id: 'c3b_positive_situation',
    group: '情境与环境',
    order: 1,
    title: '正向情境：角色与环境能把你“带回更好的自己”',
    oneLiner: '换一个环境/角色脚本，你可能就像换了一个人。',
    detail: 'Ellen Langer 的研究提示：当环境不断启动“我能/我年轻/我负责”的脚本，人会更接近那个版本。关键是把抽象的“变好”落到具体线索：空间、物品、音乐、仪式、身份提示。',
    segmentKeys: ['L5#10', 'L6#2'],
    episodeIds: [],
    missionIds: ['m_role_environment'],
  ),
  BeliefConcept(
    id: 'c4_priming',
    group: '情境与环境',
    order: 2,
    title: '启动效应：环境在暗中塑造你',
    oneLiner: '你每天看到/听到/触到的线索，会在无意识层面推着你走。',
    detail: 'Priming 研究说明：词语、形象、角色描述会启动行为脚本，影响表现、速度、坚持。既然无法避免被启动，更有效的策略是：刻意布置能启动你“想成为的人”的线索。',
    segmentKeys: ['L5#11', 'L6#1', 'L6#3', 'L6#4', 'L6#5'],
    episodeIds: ['e_priming_walk', 'e_office_priming'],
    missionIds: ['m_priming_homework'],
  ),

  // ========== 身心机制 ==========
  BeliefConcept(
    id: 'c5_placebo',
    group: '身心机制',
    order: 0,
    title: '安慰剂效应：信念如何影响身体',
    oneLiner: '信念很强，但不是万能；关键是用它去支持行动与恢复。',
    detail: 'Placebo 说明：期待会影响生理反应（疼痛、过敏、症状等）。这能帮助我们理解“心身连接”，也提醒我们避免把它神化：最佳用法是让信念成为治疗/训练的一部分，而不是替代医学与行动。',
    segmentKeys: ['L6#11'],
    episodeIds: ['e_placebo', 'e_allergy_leaf'],
    missionIds: ['m_placebo_protocol'],
  ),

  // ========== 认知机制 ==========
  BeliefConcept(
    id: 'c6_mechanisms',
    group: '认知机制',
    order: 0,
    title: '总览：信念变现实的三条“心理齿轮”',
    oneLiner: '动机更努力；一致性会逼你调整；注意力会过滤你看到的现实。',
    detail: '这一组把课程的关键机制放在一起：动机机制（更投入）、一致性/认知失调（要么改信念要么改现实）、以及注意力过滤（聚焦会放大某些证据）。下面几个子概念会把它们拆开讲清。',
    segmentKeys: ['L6#12', 'L6#13', 'L6#14'],
    episodeIds: ['e_dissonance', 'e_focus_filter'],
    missionIds: ['m_reality_alignment'],
  ),
  BeliefConcept(
    id: 'c6a_dissonance',
    group: '认知机制',
    order: 1,
    title: '一致性与认知失调：你会想“让自己说得通”',
    oneLiner: '当现实与信念冲突，人会被迫调整其一来恢复一致。',
    detail: '认知失调不是“坏事”，它是驱动改变的发动机：你做了一次小行动，就更容易把自己看成“能做到的人”；你公开承诺一次，就更容易持续下去。关键在于：把失调用在“向上调整现实”。',
    segmentKeys: ['L6#12'],
    episodeIds: [],
    missionIds: ['m_dissonance_microcommit'],
  ),
  BeliefConcept(
    id: 'c6b_confirmation_bias',
    group: '认知机制',
    order: 2,
    title: '确认偏误：我们会只看想看的',
    oneLiner: '你先有立场，再找证据；这会让信念越来越“自洽”。',
    detail: '政治例子只是最明显的版本。日常里我们也会：只注意支持自己信念的信息、忽略反例。改善方法不是“更用力相信”，而是建立反证与多视角检查。',
    segmentKeys: ['L6#13'],
    episodeIds: [],
    missionIds: ['m_disconfirming_evidence'],
  ),
  BeliefConcept(
    id: 'c6c_focus_filter',
    group: '认知机制',
    order: 3,
    title: '聚焦创造现实：注意力过滤器',
    oneLiner: '你聚焦什么，就更容易在生活里“看到更多它”。',
    detail: '当你开始寻找某种证据（例如“我在进步”或“我不行”），注意力会像筛子一样过滤信息，让你不断强化同一个结论。训练点是：把聚焦从“结果焦虑”转到“过程指标与可控行动”。',
    segmentKeys: ['L6#14', 'L7#1'],
    episodeIds: [],
    missionIds: ['m_focus_filter_metrics'],
  ),

  // ========== 失败与乐观 ==========
  BeliefConcept(
    id: 'c7_fail_to_learn',
    group: '失败与乐观',
    order: 0,
    title: '学会失败：把挫折变成学习',
    oneLiner: '最成功的人往往失败最多：失败不是相反面，而是路径。',
    detail: '爱迪生式解释：失败=排除法的数据。课程核心是把“失败恐惧”改写为“试错系统”，让你敢于进入高反馈的练习循环。',
    segmentKeys: ['L6#15', 'L6#16', 'L7#9'],
    episodeIds: ['e_fail_loop'],
    missionIds: ['m_fail_log'],
  ),
  BeliefConcept(
    id: 'c8_explanatory_style',
    group: '失败与乐观',
    order: 1,
    title: '解释风格：把失败说成“暂时且特定”',
    oneLiner: '同一件事，不同解释，会导向不同命运。',
    detail: '解释风格的三个维度（永久/暂时、普遍/特定、个人/外部）会影响你的情绪、坚持与复原。它不是性格宿命，而是可训练的习惯。',
    segmentKeys: ['L6#18', 'L6#19', 'L6#20'],
    episodeIds: ['e_biondi', 'e_exam_story'],
    missionIds: ['m_style_rewrite'],
  ),
  BeliefConcept(
    id: 'c8b_define_optimism',
    group: '失败与乐观',
    order: 2,
    title: '乐观的定义与目标策略',
    oneLiner: '短期乐观可以“不现实”，但长期必须现实：目标与解释要分层。',
    detail: 'Seligman 提醒：短期（上场/坚持）需要更积极的信念；长期（策略/复盘）必须面向事实。把两者分开，你就不会在“盲目乐观”和“过度悲观”之间摇摆。',
    segmentKeys: ['L6#17', 'L7#5'],
    episodeIds: [],
    missionIds: ['m_define_optimism'],
  ),
  BeliefConcept(
    id: 'c9_realistic_optimism',
    group: '失败与乐观',
    order: 3,
    title: '现实乐观：Stockdale 悖论',
    oneLiner: '坚定相信能赢 + 严格面对残酷事实，二者缺一不可。',
    detail: '不切实际的乐观会让人忽视风险；而只有残酷现实会让人熄火。Stockdale 悖论要求你同时做两件事：不动摇地相信最终能成功，同时每天面对当下最残酷的问题并采取行动。',
    segmentKeys: ['L6#21', 'L6#22', 'L6#23', 'L6#24'],
    episodeIds: ['e_stockdale'],
    missionIds: ['m_stockdale_plan'],
  ),

  // ========== 幸福与应对 ==========
  BeliefConcept(
    id: 'c11_happiness_baseline',
    group: '幸福与应对',
    order: 0,
    title: '幸福基线：我们会回弹，但也能被抬高',
    oneLiner: '好事坏事后我们会“回到基线”，关键问题是：基线能不能上移？',
    detail: '研究显示：自尊与幸福对事件有反应，但会较快回归基线（适应）。这既是好消息（会恢复），也是难题（为什么总回去）。后续概念会给出一个可实践的方向：选择应对，而不是回避。',
    segmentKeys: ['L6#26', 'L6#27'],
    episodeIds: [],
    missionIds: ['m_happiness_baseline'],
  ),
  BeliefConcept(
    id: 'c12_coping_vs_avoid',
    group: '幸福与应对',
    order: 1,
    title: '应对 vs 回避：抬高幸福基线的起点',
    oneLiner: '选择应对，会让你更敢上场、更能学习、也更不怕失败。',
    detail: '课程给出三条理由解释“为什么应对有效”：自我知觉（做过就更像那种人）、失败没想象可怕、成功来自试错。关键是从最小行动开始，让应对变成习惯。',
    segmentKeys: ['L6#28', 'L7#2', 'L7#3', 'L7#4'],
    episodeIds: [],
    missionIds: ['m_coping_vs_avoid'],
  ),

  // ========== 工具箱（落地方法） ==========
  BeliefConcept(
    id: 'c10_tools',
    group: '工具箱',
    order: 0,
    title: '工具箱总览：行动 / 可视化 / 认知疗法',
    oneLiner: '把“信念”做出来：做、看见、再把扭曲拉回现实。',
    detail: '这一组把课程最后给出的三套方法放在一起：行动（建立效能证据）、可视化（提前在脑中排练）、认知疗法（纠偏扭曲）。下面三个子概念分别把它们讲细。',
    segmentKeys: ['L7#6'],
    episodeIds: ['e_visualization', 'e_3ms_zoomout'],
    missionIds: ['m_visualize_and_do', 'm_3ms_training'],
  ),
  BeliefConcept(
    id: 'c10a_action_mastery',
    group: '工具箱',
    order: 1,
    title: '方法一：行动——用“证据”建立自我效能',
    oneLiner: '做一次就多一份证据：证据越多，效能感越稳。',
    detail: '核心循环：努力→成功/进步→自我效能上升→更愿意努力。注意：盲目自尊运动可能让人逃避反馈；真正的自信来自行动与复盘。',
    segmentKeys: ['L7#7', 'L7#8', 'L7#10', 'L6#24'],
    episodeIds: [],
    missionIds: ['m_action_mastery'],
  ),
  BeliefConcept(
    id: 'c10b_visualization',
    group: '工具箱',
    order: 2,
    title: '方法二：可视化——把大脑当“模拟器”',
    oneLiner: '别只想终点：把过程、情绪与细节一起可视化，行动更容易发生。',
    detail: 'Kosslyn 研究提示：大脑对“真实看到”和“想象看到”反应相近。持续、具体的可视化会推动现实贴合内部图式。但必须把“旅程/过程”也想清楚，并把情绪带进去（emotion→motion）。',
    segmentKeys: ['L7#11', 'L7#12', 'L7#13', 'L7#14', 'L7#15', 'L7#16'],
    episodeIds: [],
    missionIds: ['m_visualization_protocol'],
  ),
  BeliefConcept(
    id: 'c10c_cbt_3ms',
    group: '工具箱',
    order: 3,
    title: '方法三：认知疗法——3Ms + 纠偏两种陷阱',
    oneLiner: '把自动化想法拉回现实：先识别扭曲，再做更准确的解释。',
    detail: '认知疗法有效，但需要长期练习。课程用 3Ms（事件/想法/感受）并点出两类常见陷阱：放大与缩小。你要做的不是“更积极”，而是“更准确”。',
    segmentKeys: ['L7#17', 'L7#18'],
    episodeIds: [],
    missionIds: ['m_3ms_daily'],
  ),
];

/// Episodes = “案例重演”关卡：尽量复刻课程原案例的结构，让用户在 App 里把链条走一遍。
const List<BeliefEpisode> beliefEpisodes = [
  BeliefEpisode(
    id: 'e_bannister',
    conceptId: 'c1_limit_break',
    title: '重演：四分钟一英里（Bannister）',
    subtitle: '把“不可能”改写成“可以尝试”，然后安排试错与训练。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '场景',
        body: '你生活中有没有一个“4分钟屏障”？它可能不是体育，而是：英语口语、转岗、写作、社交、减脂、创业、考试等。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '写下你的“4分钟屏障”',
        body: '用一句话描述：我目前相信自己做不到的是……（越具体越好）',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.singleChoice,
        title: '把信念从“硬上限”拉回“可训练”',
        body: '课程的关键不是“坐着相信”，而是把“可能性”打开，让努力与试错得以发生。',
        choices: [
          BeliefChoice(id: 'a', text: '我愿意把它从“绝对不可能”改成“我还没找到方法”', score: 2),
          BeliefChoice(id: 'b', text: '我觉得这仍是硬上限（暂时不改）', score: 0),
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.checklist,
        title: '做一个“解锁式训练计划”（7天）',
        body: '选择你能做到的最小可行动作：让努力与反馈发生。',
        checklist: [
          '把目标拆成 3 个可衡量指标（如：次数/分钟/页数/对话数）',
          '安排 7 天内至少 3 次练习（每次 10–30 分钟）',
          '为每次练习设一个“允许失败”的指标（如：只要开始就算成功）',
          '每次练习后写 1 句“我学到了什么”',
        ],
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.rating,
        title: '现在的可能性感（0–5）',
        body: '你此刻对“我能推进它”的相信程度是？',
        minRating: 0,
        maxRating: 5,
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你刚完成了一次“把信念落到行动结构”的重演：信念→动机→行动→反馈→更强信念。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_rosenthal',
    conceptId: 'c2_expectation',
    title: '重演：Rosenthal 期待效应（fast spurters）',
    subtitle: '把“看见潜能”变成可执行的互动方式。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '场景',
        body: '你可以选择一个对象：孩子/伴侣/同事/下属/自己。你的“期待”会通过行为传递出去。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '选择对象',
        body: '写下这个人的称呼（如：小王/我自己/我的孩子）。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.singleChoice,
        title: '你更常给他的期待是？',
        body: '期待会改变你的语气、关注点、机会给法。',
        choices: [
          BeliefChoice(id: 'a', text: '更像“他不行/会出错/不靠谱”', score: 0),
          BeliefChoice(id: 'b', text: '更像“他能学会/能成长/有潜力”', score: 2),
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.checklist,
        title: '把“高期待”翻译成 4 个具体动作（7天内做）',
        body: '像老师对 fast spurters 那样“多一点关注+多一点机会+多一点反馈”。',
        checklist: [
          '每天至少一次“具体表扬”（表扬努力/策略/进步，不是空喊你真棒）',
          '给一次更难一点的任务/机会（在伸展区）',
          '给一次高质量反馈：指出一处做得好 + 一处可改进 + 下一步建议',
          '做一次“看见潜能”的记录：今天我看到了他/我自己的哪一点潜力？',
        ],
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.input,
        title: '写下你的“潜能句”',
        body: '把对方当成“他能成为的样子”：一句话写出你希望他更靠近的版本。',
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '关键不是“骗自己”，而是用更完整的现实（潜能也属于现实）去指导互动。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_jamison',
    conceptId: 'c2_expectation',
    title: '重演：反向期待（Jamison 1997）',
    subtitle: '先相信对方更好，你会看见更多证据，关系与表现一起上升。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '场景',
        body: '在实验里：学生被告知老师很优秀→学生投入更多→成绩更好→老师评价更高。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '选一个你常“挑刺”的人',
        body: '写下名字/称呼（也可以是你自己）。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.checklist,
        title: '7 天“找证据挑战”',
        body: '每天强制自己找 2 条证据：他/我其实哪里做得不错？',
        checklist: [
          '证据 1：一个具体行为/选择/努力',
          '证据 2：一个具体能力/品质/潜力',
          '写下：如果我把他当成“更好的他”，我今天会怎么说/怎么做？',
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.singleChoice,
        title: '你愿意做一次“更高期待”的互动吗？',
        body: '只做一件事：说一句更高期待的话/给一个更高期待的机会。',
        choices: [
          BeliefChoice(id: 'a', text: '愿意，今天就做', score: 2),
          BeliefChoice(id: 'b', text: '暂时不做', score: 0),
        ],
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.input,
        title: '写下那一句话',
        body: '例如：“我相信你能把这件事推进到更好，我愿意给你/给自己这个机会。”',
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你刚练的是：先改变“看法”，再改变“互动”，让现实有机会跟上。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_situation_mirror',
    conceptId: 'c3_situation_power',
    title: '重演：情境镜像（负向情境 vs 正向情境）',
    subtitle: '同一个人放进不同情境，会像变了一个人。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '课程提示',
        body: 'Milgram / Zimbardo 让我们看到负向情境的强；Langer 让我们看到正向情境也同样强。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.singleChoice,
        title: '你最近更像被哪种情境推着走？',
        body: '选你更贴近的那一项。',
        choices: [
          BeliefChoice(id: 'a', text: '负向：压力、盯错、苛责、对比、羞耻', score: 0),
          BeliefChoice(id: 'b', text: '正向：鼓励、节奏、清晰边界、可见进步', score: 2),
        ],
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.checklist,
        title: '把情境拆开：哪 3 个线索在推你？',
        body: '情境不是空气，它由具体线索构成。',
        checklist: [
          '线索 1：某个地方/桌面/房间/手机屏幕/人',
          '线索 2：某种语言（你对自己说的话/别人说的话）',
          '线索 3：某种制度（deadline、打卡、排名、奖励/惩罚）',
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.input,
        title: '写下一个“正向替代情境”',
        body: '只改动 1 个线索：例如把苛责换成“进步记录”，把混乱桌面换成“唯一任务卡”。',
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.rating,
        title: '你愿意把它试 3 天吗？',
        body: '0=完全不愿意，5=非常愿意',
        minRating: 0,
        maxRating: 5,
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你完成了一次“情境拆解→替代线索→小范围试验”的关卡。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_langer_1959',
    conceptId: 'c3_situation_power',
    title: '重演：Langer “1959 退修营”',
    subtitle: '用角色与环境，把自己带回“更有能力的我”。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '核心机制',
        body: '当环境不再不断提醒“你老了/你不行”，人会更像“更年轻/更有力”的自己。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '选一个你想“回到的自己”',
        body: '例如：刚入行时的好奇、学生时代的专注、某段高峰期的自信。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.checklist,
        title: '搭建“7天角色房间”（低成本版）',
        body: '把环境布置成能“启动那个自己”的样子。',
        checklist: [
          '找 1 张“那时的照片/象征物”放在桌面可见处',
          '找 1 首“那时常听的音乐”作为工作/学习启动曲',
          '把手机壁纸/锁屏改成“那个自己”的关键字',
          '写 1 句角色台词：今天我以“那个我”的方式行动',
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.input,
        title: '你的角色台词',
        body: '写下那句台词（越具体越好）。',
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.checklist,
        title: '每天 10 分钟“进入角色行动”',
        body: '选择 1 个动作：读/写/练/沟通/运动，像那个自己一样做。',
        checklist: [
          '今天我要做的动作是：____（填空）',
          '我将如何像“那个自己”去做：____（填空）',
        ],
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你把“角色×情境”的研究，变成了可执行的 7 天游戏。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_langer_pilot',
    conceptId: 'c3_situation_power',
    title: '重演：飞行员情境与视力表',
    subtitle: '身份情境会改变你对任务的调用方式。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '实验提示',
        body: '同一张视力表、同样距离，换成飞行员制服+模拟器，表现就变了。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '选一个你想提升的能力',
        body: '例如：演讲、自律、社交、代码、写作、跑步。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.singleChoice,
        title: '给自己一个“身份外壳”',
        body: '你更喜欢哪种方式？',
        choices: [
          BeliefChoice(id: 'a', text: '装备/穿着（如：运动服/工位仪式）', score: 1),
          BeliefChoice(id: 'b', text: '空间/道具（如：特定桌面/特定音乐）', score: 1),
          BeliefChoice(id: 'c', text: '语言身份（如：我是今天的“飞行员/教练/作家”）', score: 1),
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.input,
        title: '写下你的身份句',
        body: '例：“现在我是‘飞行员’，我的任务是稳定地完成这一段飞行（30分钟专注）。”',
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.checklist,
        title: '做一次 20 分钟“身份任务”',
        body: '只做一件事，计时 20 分钟。',
        checklist: [
          '设定计时器 20 分钟',
          '只做这一件事（不切换）',
          '结束后写 1 句：身份外壳对我有什么影响？',
        ],
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你完成了“身份情境→任务表现”的一次小型复制实验。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_priming_walk',
    conceptId: 'c4_priming',
    title: '重演：Bargh 老年词启动 → 走路变慢',
    subtitle: '你以为你在“自由选择”，其实很多是被线索牵引。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '要点',
        body: '启动可以无意识发生：词语/图像/暗示能改变记忆、速度、坚持。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.singleChoice,
        title: '你更常被什么“启动”？',
        body: '选一个你最近的典型线索。',
        choices: [
          BeliefChoice(id: 'a', text: '负向词（累、差、来不及、完蛋）', score: 0),
          BeliefChoice(id: 'b', text: '正向词（进步、坚持、今天只做一步）', score: 2),
        ],
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.input,
        title: '写下你最常出现的 3 个“启动词”',
        body: '越口头越好（就是你脑海里自动冒出来的那种）。',
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.checklist,
        title: '把 1 个负向词改写成“行动词”',
        body: '例：把“完蛋了”→“我先做第一步”。',
        checklist: [
          '选择 1 个负向启动词',
          '写出 1 个替代行动词',
          '把替代词设置为手机小组件/桌面便签（可拍照留存）',
        ],
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.rating,
        title: '今天你愿意试几次？',
        body: '0=不试，5=至少试 5 次以上',
        minRating: 0,
        maxRating: 5,
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你把“启动”从不可控，变成了可被设计的环境变量。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_office_priming',
    conceptId: 'c4_priming',
    title: '重演：我的办公室启动装置',
    subtitle: '把你的空间变成“把你推向更好”的机器。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '课程提示',
        body: '老师用雕塑/名言等物品提醒自己：别只想，要行动；保持热情。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.checklist,
        title: '建立你的“3件套启动装置”',
        body: '只要 3 个就够：看见→被启动→去做。',
        checklist: [
          '1 个视觉启动（壁纸/照片/一句话）',
          '1 个动作启动（计时器/开场音乐/喝水仪式）',
          '1 个价值启动（你最在乎的 1 句话/1 个原则）',
        ],
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.input,
        title: '写下你的“价值启动句”',
        body: '例：Talk is no substitute for action。',
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.checklist,
        title: '放置并拍照',
        body: '把它们放到你每天一定会看到的地方（桌面/锁屏/门上）。',
        checklist: [
          '放置完成',
          '拍照留存（可选）',
          '明天同一时间再看一次：它有没有启动你？',
        ],
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你完成了“环境设计作业”的 App 版本。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_placebo',
    conceptId: 'c5_placebo',
    title: '重演：安慰剂（糖丸也能止吐）',
    subtitle: '信念能影响身体，但要把它用在“恢复与坚持”上。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '课程要点',
        body: '安慰剂组也改善：信念会调动身体反应，但不等于“想什么就来什么”。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.singleChoice,
        title: '你现在更需要哪种“身体层面的支持”？',
        body: '选一个最贴近的。',
        choices: [
          BeliefChoice(id: 'a', text: '压力与睡眠', score: 1),
          BeliefChoice(id: 'b', text: '体能与精力', score: 1),
          BeliefChoice(id: 'c', text: '疼痛/不适管理', score: 1),
        ],
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.checklist,
        title: '做一个“安慰剂仪式”（3天）',
        body: '给身体一个明确的“恢复信号”，并配合行动。',
        checklist: [
          '固定一个时间点（如睡前）',
          '固定一个“信号动作”（热水澡/热茶/拉伸 5 分钟）',
          '固定一句“身体启动句”（如：现在进入恢复模式）',
          '记录 1 个可观察指标（入睡时间/心率/疼痛评分）',
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.input,
        title: '你的身体启动句',
        body: '写一句你愿意每天对身体说的话。',
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你把“信念影响身体”落到一个可重复的恢复协议。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_allergy_leaf',
    conceptId: 'c5_placebo',
    title: '重演：过敏叶子（被告知有毒就起疹）',
    subtitle: '标签与解释会影响身体反应：别把“想法”当事实。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '要点',
        body: '同一片叶子，换个解释，身体反应就变了：说明“解释”会塑造体验。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '写下你最近一个“被标签化”的体验',
        body: '例：我最近总觉得自己“很差/很慢/不行”。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.singleChoice,
        title: '它更像事实还是解释？',
        body: '很多痛苦来自把解释当事实。',
        choices: [
          BeliefChoice(id: 'a', text: '更像事实', score: 0),
          BeliefChoice(id: 'b', text: '更像解释（我可以换一种解释）', score: 2),
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.input,
        title: '做一次“换标签”',
        body: '把它从“自我标签”换成“情境描述”。例：“我很蠢”→“我这次没准备好”。',
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你完成了一次把“解释”与“事实”拆开的练习。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_dissonance',
    conceptId: 'c6_mechanisms',
    title: '重演：一致性机制（认知失调）',
    subtitle: '当现实和信念冲突，你会怎么做？',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '四种修复方式',
        body: '更新信念 / 忽略信息 / 找支持证据（确认偏误）/ 改变现实（行动）。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '写下一个你正在“卡住”的冲突',
        body: '例：我想更健康，但我总熬夜；我想转岗，但我不投简历。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.singleChoice,
        title: '你最常用哪种修复方式？',
        body: '诚实选择即可。',
        choices: [
          BeliefChoice(id: 'a', text: '忽略/拖延：当作没看见', score: 0),
          BeliefChoice(id: 'b', text: '找理由：为现状辩护', score: 0),
          BeliefChoice(id: 'c', text: '改信念：降低期待/放弃', score: 0),
          BeliefChoice(id: 'd', text: '改现实：做一个行动让它变真', score: 2),
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.checklist,
        title: '设计一个“改现实”的最小行动（24小时内）',
        body: '让现实开始贴合你想要的信念。',
        checklist: [
          '写下最小行动（≤10分钟）',
          '设定触发条件（例如：今晚 9 点）',
          '做完立即记录结果',
        ],
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你把“失调的不适”转化成“改变现实的一步”。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_focus_filter',
    conceptId: 'c6_mechanisms',
    title: '重演：注意力过滤（公交车上的孩子）',
    subtitle: '你没看见的那部分现实，仍然在影响你。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '要点',
        body: '我们会漏看：潜能、积极证据、可行路径。焦点在哪，现实就被“剪辑”成那样。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.singleChoice,
        title: '你最近更常聚焦哪里？',
        body: '选一个更贴近的。',
        choices: [
          BeliefChoice(id: 'a', text: '问题/缺陷/失败', score: 0),
          BeliefChoice(id: 'b', text: '进步/潜能/可行路径', score: 2),
        ],
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.checklist,
        title: '做一次“镜头拉远（zoom out）”',
        body: '把比例找回来。',
        checklist: [
          '列出 3 个“我做对了/在进步”的事实',
          '列出 1 个“我真正要解决的问题”',
          '列出 1 个“下一步可行动作”',
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你练习的是：让注意力成为工具，而不是牢笼。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_fail_loop',
    conceptId: 'c7_fail_to_learn',
    title: '重演：learn to fail, or fail to learn',
    subtitle: '把失败当成“数据点”，而不是“人格判决”。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '课程要点',
        body: 'Edison / Simonton：成功者往往失败最多；失败是学习机制的一部分。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '写下一个你最近的失败',
        body: '越具体越好（时间、地点、发生了什么）。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.singleChoice,
        title: '你更像哪种解释？',
        body: '选更贴近的。',
        choices: [
          BeliefChoice(id: 'a', text: '我不行（人格判决）', score: 0),
          BeliefChoice(id: 'b', text: '我排除了一个不行的方法（数据点）', score: 2),
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.input,
        title: '把它改写成“排除法句子”',
        body: '参考 Edison：我不是失败了，而是发现了一个行不通的方法，所以我下一次将……',
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.checklist,
        title: '把失败变成下一次实验',
        body: '做一个更小的版本再试一次。',
        checklist: [
          '把任务缩小 50%',
          '只改动 1 个变量（方法/时间/环境/伙伴）',
          '设定一次“只要开始就算成功”的标准',
        ],
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你完成了把“失败→学习→下一次实验”的闭环。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_biondi',
    conceptId: 'c8_explanatory_style',
    title: '重演：Biondi 的“稳定乐观”翻盘',
    subtitle: '把失败解释为“暂时+特定”，继续回到赛场。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '课程要点',
        body: '稳定乐观者把失败看作暂时、特定；而不是永久、普遍。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '写下你最近一次“没达到期待”的事件',
        body: '像 Biondi 前两项没拿金牌那样：你被期待做什么？发生了什么？',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.singleChoice,
        title: '你的解释更像哪种？',
        body: '选一项。',
        choices: [
          BeliefChoice(id: 'a', text: '永久+普遍：我不行/我什么都不行', score: 0),
          BeliefChoice(id: 'b', text: '暂时+特定：这次没准备好/策略不对', score: 2),
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.input,
        title: '写出“暂时+特定”的解释句',
        body: '例如：这次我在____做得不够，所以我下一次要____。',
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.checklist,
        title: '回到赛场：下一次行动清单',
        body: '像 Biondi 一样继续比赛。',
        checklist: [
          '我下一次尝试的时间是：____',
          '我会改动的 1 个策略是：____',
          '我会如何给自己反馈：____',
        ],
      ),
      BeliefStep(
        id: 's6',
        type: BeliefStepType.summary,
        title: '完成',
        body: '解释风格不是嘴硬，而是给行动腾出空间。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_exam_story',
    conceptId: 'c8_explanatory_style',
    title: '重演：考试失利的两种解释',
    subtitle: '把“我很蠢”换成“这次没准备好”。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '两条轴',
        body: '永久/暂时、普遍/特定。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '写下一个你常用的负面解释句',
        body: '比如：我就是不行 / 我永远学不会 / 我什么都做不好。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.input,
        title: '把它改写成“暂时+特定”',
        body: '例如：这次我在____没做好，因为____，下一次我会____。',
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你完成了“解释风格改写”的最小练习。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_stockdale',
    conceptId: 'c9_realistic_optimism',
    title: '重演：Stockdale 悖论（信念 + 残酷现实）',
    subtitle: '既不绝望，也不自欺：用两条腿走路。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '两条原则',
        body: '1) 坚信最终会赢；2) 严格面对当下残酷事实与纪律。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '写下你正在面对的一件“残酷现实”',
        body: '例：时间不够/资金有限/能力缺口/关系冲突。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.input,
        title: '写下你的“最终信念”',
        body: '例：我相信我会在____之前把____做到____。',
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.checklist,
        title: '把残酷现实翻译成纪律',
        body: '纪律=你每天要做的具体动作。',
        checklist: [
          '纪律 1：每天固定____分钟/次 做____',
          '纪律 2：每周复盘一次，调整策略',
          '纪律 3：不再靠“希望圣诞出狱”，而是靠行动积累',
        ],
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你完成了“现实乐观”模板：信念给方向，现实给策略，纪律给力量。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_visualization',
    conceptId: 'c10_tools',
    title: '重演：可视化（终点 + 过程）',
    subtitle: '把大脑当模拟器：先在脑内跑通，再回到现实跑步。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '课程要点',
        body: 'Kosslyn：想象与真实看到会激活相似神经网络；Taylor：只想终点不如把过程一起想。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '选择一个你要完成的目标',
        body: '越近期越好（7–14天内）。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.checklist,
        title: '写一份“过程可视化脚本”',
        body: '把过程写成可看可感的画面。',
        checklist: [
          '我在哪个地点开始？（视觉）',
          '我开始的第一动作是什么？（动作）',
          '我遇到阻力时怎么继续？（策略）',
          '我完成后的画面是什么？（终点）',
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.rating,
        title: '你愿意每天演练 2 分钟吗？',
        body: '0=不愿意，5=非常愿意',
        minRating: 0,
        maxRating: 5,
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你把“可视化”从鸡汤变成了可练的脚本。',
      ),
    ],
  ),

  BeliefEpisode(
    id: 'e_3ms_zoomout',
    conceptId: 'c10_tools',
    title: '重演：3Ms（放大/缩小）与 Zoom out',
    subtitle: '从“一个点毁一切”回到“真实比例”。',
    steps: [
      BeliefStep(
        id: 's1',
        type: BeliefStepType.info,
        title: '课程要点',
        body: 'Magnifying：一次挫折=世界末日；Minimizing：隧道视野只盯负面点。解决：zoom out。',
      ),
      BeliefStep(
        id: 's2',
        type: BeliefStepType.input,
        title: '写下你最近一次反刍的“那一句话/那一个点”',
        body: '像老师上节目后反刍那句后悔的话一样。',
      ),
      BeliefStep(
        id: 's3',
        type: BeliefStepType.singleChoice,
        title: '它更像放大还是缩小？',
        body: '选一项。',
        choices: [
          BeliefChoice(id: 'a', text: '放大：把一次当全部', score: 1),
          BeliefChoice(id: 'b', text: '缩小：忽略大量积极事实', score: 1),
        ],
      ),
      BeliefStep(
        id: 's4',
        type: BeliefStepType.checklist,
        title: 'Zoom out 三步',
        body: '把现实比例拉回来。',
        checklist: [
          '列 3 条“更大的事实”（积极或中性都行）',
          '列 1 条“我能改进的具体点”',
          '列 1 个“我现在就能做的下一步”',
        ],
      ),
      BeliefStep(
        id: 's5',
        type: BeliefStepType.summary,
        title: '完成',
        body: '你完成了一次“认知回归现实”的训练。',
      ),
    ],
  ),
];

/// Missions = “现实行动”关卡：把课程知识转成可执行的日常任务 + 复盘。
const List<BeliefMission> beliefMissions = [
  BeliefMission(
    id: 'm_possibility_switch',
    conceptId: 'c1_limit_break',
    title: '行动：可能性开关（7天）',
    subtitle: '把“硬上限”换成“可训练”，并安排 3 次试错。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.info, title: '规则', body: '7 天内完成至少 3 次练习；每次练习后写 1 句学习。'),
      BeliefStep(id: 'i2', type: BeliefStepType.input, title: '你的目标是什么？', body: '一句话写下你的“4分钟屏障”。'),
      BeliefStep(id: 'i3', type: BeliefStepType.checklist, title: '三次练习安排', body: '勾选你已经安排好的练习。', checklist: ['练习 1 已安排', '练习 2 已安排', '练习 3 已安排']),
      BeliefStep(id: 'i4', type: BeliefStepType.input, title: '失败学习句', body: '写一句：今天我排除了什么不行的方法？'),
      BeliefStep(id: 'i5', type: BeliefStepType.summary, title: '完成', body: '完成后你会发现：信念不是起点，而是结果的一部分。'),
    ],
  ),
  BeliefMission(
    id: 'm_expectation_upgrade',
    conceptId: 'c2_expectation',
    title: '行动：期待升级（7天）',
    subtitle: '把“更高期待”翻译成日常互动。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '对象', body: '选择一个对象：同事/伴侣/孩子/自己。'),
      BeliefStep(id: 'i2', type: BeliefStepType.checklist, title: '每天 3 分钟', body: '每天做一次：看见潜能+给机会+给反馈。', checklist: ['具体表扬努力/策略/进步', '给一次伸展区机会', '给一次高质量反馈', '记录今天看见的潜能']),
      BeliefStep(id: 'i3', type: BeliefStepType.input, title: '复盘', body: '7 天后：这段关系/表现发生了什么变化？'),
      BeliefStep(id: 'i4', type: BeliefStepType.summary, title: '完成', body: '你把“期待效应”从理论变成互动习惯。'),
    ],
  ),
  BeliefMission(
    id: 'm_positive_situation_build',
    conceptId: 'c3_situation_power',
    title: '行动：正向情境搭建（3天）',
    subtitle: '只改一个线索，让你更像“更好的自己”。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.checklist, title: '选一个线索', body: '选择你要改的线索（只改一个）。', checklist: ['空间（桌面/房间）', '语言（自我对话/他人对话）', '制度（时间/奖励/边界）']),
      BeliefStep(id: 'i2', type: BeliefStepType.input, title: '替代方案', body: '写下你的正向替代线索。'),
      BeliefStep(id: 'i3', type: BeliefStepType.rating, title: '三天后评分', body: '0=没变化，5=明显更好', minRating: 0, maxRating: 5),
      BeliefStep(id: 'i4', type: BeliefStepType.summary, title: '完成', body: '你完成了一次“情境微调”的小实验。'),
    ],
  ),
  BeliefMission(
    id: 'm_priming_homework',
    conceptId: 'c4_priming',
    title: '行动：积极启动作业（7天）',
    subtitle: '把环境变成“自动推你行动”的系统。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.checklist, title: '3件套', body: '建立你的 3 件套启动装置。', checklist: ['视觉启动', '动作启动', '价值启动']),
      BeliefStep(id: 'i2', type: BeliefStepType.input, title: '价值启动句', body: '写一句你每天都愿意看到的话。'),
      BeliefStep(id: 'i3', type: BeliefStepType.input, title: '观察记录', body: '7 天后：这些线索有没有改变你的行为？具体有哪些？'),
      BeliefStep(id: 'i4', type: BeliefStepType.summary, title: '完成', body: '你把 priming 变成了可被设计的变量。'),
    ],
  ),
  BeliefMission(
    id: 'm_placebo_protocol',
    conceptId: 'c5_placebo',
    title: '行动：恢复协议（3天）',
    subtitle: '用“信念+仪式+指标”支持身体恢复。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '选择指标', body: '选一个可观察指标：睡眠/心率/疼痛评分/精力。'),
      BeliefStep(id: 'i2', type: BeliefStepType.checklist, title: '固定仪式', body: '每天同一时间做一次。', checklist: ['固定时间', '固定动作', '固定启动句', '记录指标']),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你把“信念影响身体”变成了可复用方案。'),
    ],
  ),
  BeliefMission(
    id: 'm_reality_alignment',
    conceptId: 'c6_mechanisms',
    title: '行动：一致性对齐（24小时）',
    subtitle: '用一个最小行动把现实拉向你的信念。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '冲突', body: '写下你的“信念-现实冲突”。'),
      BeliefStep(id: 'i2', type: BeliefStepType.input, title: '最小行动', body: '写下 ≤10 分钟的最小行动。'),
      BeliefStep(id: 'i3', type: BeliefStepType.input, title: '完成记录', body: '做完后写 1 句：我学到了什么？'),
      BeliefStep(id: 'i4', type: BeliefStepType.summary, title: '完成', body: '从今天开始，你在用行动修复失调。'),
    ],
  ),
  BeliefMission(
    id: 'm_fail_log',
    conceptId: 'c7_fail_to_learn',
    title: '行动：失败学习日志（7天）',
    subtitle: '每天记录 1 个失败→1 个学到的东西→1 个下一步。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.checklist, title: '每天三行', body: '坚持 7 天。', checklist: ['失败是什么？', '我学到了什么？', '下一步我改动一个变量再试一次']),
      BeliefStep(id: 'i2', type: BeliefStepType.summary, title: '完成', body: '7 天后你会拥有一份“成长证据”。'),
    ],
  ),
  BeliefMission(
    id: 'm_style_rewrite',
    conceptId: 'c8_explanatory_style',
    title: '行动：解释风格改写（7天）',
    subtitle: '把“永久+普遍”改成“暂时+特定”。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '原句', body: '写下你常用的负面解释句。'),
      BeliefStep(id: 'i2', type: BeliefStepType.input, title: '改写句', body: '改成暂时+特定（包含原因与下一步）。'),
      BeliefStep(id: 'i3', type: BeliefStepType.rating, title: '改写后情绪下降了吗？', body: '0=没有，5=明显下降', minRating: 0, maxRating: 5),
      BeliefStep(id: 'i4', type: BeliefStepType.summary, title: '完成', body: '解释风格的改变，会把你推回行动。'),
    ],
  ),
  BeliefMission(
    id: 'm_stockdale_plan',
    conceptId: 'c9_realistic_optimism',
    title: '行动：Stockdale 两栏计划（7天）',
    subtitle: '左边写残酷现实，右边写纪律行动。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '残酷现实', body: '写 3 条你必须面对的事实。'),
      BeliefStep(id: 'i2', type: BeliefStepType.input, title: '最终信念', body: '写一句你对最终胜利的信念。'),
      BeliefStep(id: 'i3', type: BeliefStepType.checklist, title: '纪律清单', body: '把现实翻译成行动。', checklist: ['每天固定行动 1', '每天固定行动 2', '每周复盘与调整']),
      BeliefStep(id: 'i4', type: BeliefStepType.summary, title: '完成', body: '你把“希望”升级成了“纪律”。'),
    ],
  ),
  BeliefMission(
    id: 'm_visualize_and_do',
    conceptId: 'c10_tools',
    title: '行动：2分钟可视化 + 10分钟行动（7天）',
    subtitle: '每天先在脑内跑通，再做最小行动。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '目标', body: '写下你要推进的目标。'),
      BeliefStep(id: 'i2', type: BeliefStepType.checklist, title: '每日流程', body: '每天重复一次。', checklist: ['2 分钟：过程+终点可视化', '10 分钟：最小行动', '1 句：今天我学到了什么']),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你把可视化从幻想变成了执行。'),
    ],
  ),
  BeliefMission(
    id: 'm_3ms_training',
    conceptId: 'c10_tools',
    title: '行动：3Ms 训练（7天）',
    subtitle: '每天抓一个扭曲，把镜头拉远。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '今日扭曲', body: '写下今天的一个“放大/缩小”时刻。'),
      BeliefStep(id: 'i2', type: BeliefStepType.checklist, title: 'Zoom out', body: '把比例拉回来。', checklist: ['3 条更大事实', '1 条可改进点', '1 个下一步行动']),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你在训练“大脑的剪辑台”。'),
    ],
  ),

  // ======== 新增：细分概念的行动任务（与 57 段资料库一致） ========
  BeliefMission(
    id: 'm_overview_chain_log',
    conceptId: 'c0_overview',
    title: '行动：自我实现链条观察（3天）',
    subtitle: '每天找一个“信念→注意→解释→互动→结果”的闭环，并写下证据。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.info, title: '目标', body: '不是“相信就有”，而是把机制看清：信念如何通过行为与互动改变现实。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '每天一条链',
        body: '连续 3 天，每天完成一次。',
        checklist: ['信念是什么？', '我注意到了什么？', '我怎么解释？', '我做了什么互动？', '现实结果是什么证据？'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你获得了一份“机制证据”，后续可直接转成行动模板。'),
    ],
  ),
  BeliefMission(
    id: 'm_self_help_boundary',
    conceptId: 'c1b_self_help_boundary',
    title: '行动：自助边界校准（3天）',
    subtitle: '把一句“万能信念”改写成“可行动、可验证、尊重现实约束”的版本。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '原句', body: '写下你曾经相信的一个“只要想就能有”的句子。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.input,
        title: '改写句（可执行）',
        body: '改成：我愿意做 X 行动，在 Y 约束下，用 Z 指标验证；若失败我调整变量再试。',
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你把“自助神话”落回现实行动。'),
    ],
  ),
  BeliefMission(
    id: 'm_efficacy_evidence',
    conceptId: 'c1c_efficacy_selfesteem',
    title: '行动：效能证据积累（7天）',
    subtitle: '每天做一个 ≤10 分钟可完成的微任务，累积“我能做到”的证据。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '选择领域', body: '选一个你缺乏自信的领域（学习/工作/健康/社交）。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '每日微证据',
        body: '连续 7 天，每天完成 1 个微任务。',
        checklist: ['任务≤10分钟', '完成即记录证据', '困难→拆更小', '每天复盘1句：我做成了什么？'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '自我效能来自证据，而不是口号。'),
    ],
  ),
  BeliefMission(
    id: 'm_see_potential',
    conceptId: 'c2b_see_potential',
    title: '行动：看见潜能的“浇水”练习（7天）',
    subtitle: '每天找一个“微小进步证据”，并用一次具体反馈把它放大。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '对象', body: '选择对象：自己/孩子/同事/伴侣（任选其一）。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '每天一滴水',
        body: '连续 7 天。',
        checklist: ['找到1个微小证据', '给出1句具体反馈（描述事实）', '提出1个下一步可做的小任务', '记录对方/自己的反应'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你的注意力开始塑造现实的增长方向。'),
    ],
  ),
  BeliefMission(
    id: 'm_role_environment',
    conceptId: 'c3b_positive_situation',
    title: '行动：角色脚本 + 环境线索（3天）',
    subtitle: '把“更好的自己”写成一个角色，并用 3 个线索在现实中启动它。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '角色名', body: '给你想要的状态起一个角色名（例如：冷静执行者/温柔坚定者）。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '三线索启动',
        body: '连续 3 天，每天用线索把你带回角色。',
        checklist: ['空间线索（摆设/桌面）', '物品线索（衣服/物件）', '仪式线索（音乐/口令/动作）', '记录：进入角色后行为有什么不同？'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你学会用情境把自己推向更好的版本。'),
    ],
  ),
  BeliefMission(
    id: 'm_dissonance_microcommit',
    conceptId: 'c6a_dissonance',
    title: '行动：失调→微承诺（24小时）',
    subtitle: '利用认知失调，把“我想做”变成“我已经开始做”。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '失调点', body: '写下一个“我说想要，但没做”的点。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.input,
        title: '微承诺',
        body: '写下一个不可太大、但不可太模糊的行动：≤10分钟、可验证、今天必须做。',
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你用行动修复了失调，也为下一步铺路。'),
    ],
  ),
  BeliefMission(
    id: 'm_disconfirming_evidence',
    conceptId: 'c6b_confirmation_bias',
    title: '行动：反证搜索（7天）',
    subtitle: '每天找 1 条“反例/反证”，打破确认偏误。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '我的结论', body: '写一个你很确信的判断（关于自己/别人/世界）。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '每日反证',
        body: '连续 7 天。',
        checklist: ['找1个反例', '问1个反问题（如果相反成立会怎样？）', '把结论改成更具体的条件句', '写1句：我忽略了什么？'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你开始拥有更接近现实的信念。'),
    ],
  ),
  BeliefMission(
    id: 'm_focus_filter_metrics',
    conceptId: 'c6c_focus_filter',
    title: '行动：焦点过滤器改写（7天）',
    subtitle: '把注意力从“结果焦虑”切到“过程指标”。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '结果焦点', body: '写下你最焦虑的一个结果指标（例如：考试分数/绩效/体重）。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '过程指标',
        body: '连续 7 天，只记录过程指标。',
        checklist: ['定义2个过程指标（分钟/次数/页数）', '每天记录一次', '只评估“是否完成过程”', '第7天再看结果变化'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你把过滤器调到了“可控的过程”。'),
    ],
  ),
  BeliefMission(
    id: 'm_define_optimism',
    conceptId: 'c8b_define_optimism',
    title: '行动：乐观的定义练习（3天）',
    subtitle: '把“乐观”从鸡汤还原成：短期上场、长期复盘。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '我的鸡汤句', body: '写下你对“乐观”的一句模糊理解。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '三天两步',
        body: '连续 3 天。',
        checklist: ['短期：今天必须上场的最小行动', '长期：晚上复盘一件学到的东西', '把失败解释改成暂时+特定', '写明天一个更小的改动'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你用定义把乐观变成可训练能力。'),
    ],
  ),
  BeliefMission(
    id: 'm_happiness_baseline',
    conceptId: 'c11_happiness_baseline',
    title: '行动：幸福基线回拉（7天）',
    subtitle: '用“体验放大 + 反适应”把幸福拉回现实。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.info, title: '背景', body: '人会适应好事/坏事，幸福会回到基线。策略不是追刺激，而是训练体验。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '每日两件事',
        body: '连续 7 天。',
        checklist: ['1次“品味”：把一个小体验放慢 30 秒', '1次“感恩”：写下今天的一个具体事实', '1次“反适应”：刻意不做一个习惯动作（换路线/换座位）'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你在训练幸福，而不是等待幸福。'),
    ],
  ),
  BeliefMission(
    id: 'm_coping_vs_avoid',
    conceptId: 'c12_coping_vs_avoid',
    title: '行动：应对 vs 逃避分辨（7天）',
    subtitle: '每天把一个行为标注为“应对/逃避”，并把逃避改成最小应对。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '我的逃避', body: '写下你最常见的一种逃避方式（刷手机/拖延/沉默）。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '每日转换',
        body: '连续 7 天。',
        checklist: ['识别触发情绪', '把逃避行为命名', '选择一个最小应对动作（≤5分钟）', '记录结果：情绪是否下降？问题是否推进？'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你学会把能量用在“解决”，而不是“躲开”。'),
    ],
  ),
  BeliefMission(
    id: 'm_action_mastery',
    conceptId: 'c10a_action_mastery',
    title: '行动：掌控感循环（7天）',
    subtitle: '每天做一件“能掌控的小事”，用证据修复无力感。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '最小可控', body: '写 3 件你能掌控的小事（整理/运动/学习10分钟）。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '每日完成',
        body: '连续 7 天。',
        checklist: ['每天选1件', '完成即打勾', '写1句证据：我掌控了什么？', '若失败：把任务拆更小'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '掌控感来自可验证的行动证据。'),
    ],
  ),
  BeliefMission(
    id: 'm_visualization_protocol',
    conceptId: 'c10b_visualization',
    title: '行动：过程可视化协议（7天）',
    subtitle: '每天可视化“过程+障碍+应对”，然后立刻做最小行动。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '目标', body: '写下你要推进的一个目标。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '每日协议',
        body: '连续 7 天。',
        checklist: ['2分钟：想象过程步骤', '30秒：想象一个障碍', '30秒：想象应对动作', '10分钟：最小行动', '写1句：证据是什么？'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你把可视化变成“预演+执行”。'),
    ],
  ),
  BeliefMission(
    id: 'm_3ms_daily',
    conceptId: 'c10c_cbt_3ms',
    title: '行动：3Ms 每日纠偏（7天）',
    subtitle: '每天抓一个“放大/缩小”，把镜头拉回真实比例。',
    steps: [
      BeliefStep(id: 'i1', type: BeliefStepType.input, title: '今日事件', body: '写下今天让你情绪波动的一件事（尽量客观）。'),
      BeliefStep(
        id: 'i2',
        type: BeliefStepType.checklist,
        title: '3Ms',
        body: '完成三步纠偏。',
        checklist: ['Minimize：我在夸大了什么？', 'Maximize：我在忽略了什么？', 'Many：还有哪些事实/可能性？', '写一个下一步最小行动'],
      ),
      BeliefStep(id: 'i3', type: BeliefStepType.summary, title: '完成', body: '你在训练“认知剪辑台”。'),
    ],
  ),
];

BeliefConcept getConceptById(String id) => beliefConcepts.firstWhere((c) => c.id == id);
BeliefEpisode getEpisodeById(String id) => beliefEpisodes.firstWhere((e) => e.id == id);
BeliefMission getMissionById(String id) => beliefMissions.firstWhere((m) => m.id == id);
