import 'belief_action_models.dart';

/// 推荐行动模板（种子数据）。
///
/// 这些模板是把“概念”转写为现实可执行步骤的一种“通用范式”，
/// 用户可在 App 内自定义/复制/改写。
const List<BeliefActionTemplate> beliefActionTemplates = [
  // c1 可能性开关
  BeliefActionTemplate(
    id: 't_c1_daily_micro',
    conceptId: 'c1_limit_break',
    title: '日常：7天“最小可行动作”解锁',
    version: '基础版',
    categoryPath: '日常生活/自我提升/解锁计划',
    mode: 'planned',
    operationalDefinition: '把“我做不到”改写为“我还没找到方法”，并用 7 天内至少 3 次练习让反馈发生。',
    successCriteria: '7 天内完成 ≥3 次练习；每次练习后记录 1 句学习点；可能性感评分提升或更稳定。',
    actionChecklist: [
      '选择一个“4分钟屏障”（越具体越好）',
      '把目标拆成 3 个可衡量指标（次数/分钟/页数/对话数）',
      '安排 7 天内至少 3 次练习（每次 10–30 分钟）',
      '每次练习设一个“允许失败”的最低标准（只要开始就算成功）',
      '每次练习后写 1 句：我学到了什么？',
    ],
    refSegmentKeys: ['L5#1', 'L5#2', 'L6#8', 'L6#15'],
    learningTags: ['行为塑造', '强化', '分解任务'],
    changePath: '触发→最小动作→即时反馈→记录→下一次更容易开始。',
  ),
  BeliefActionTemplate(
    id: 't_c1_work_training',
    conceptId: 'c1_limit_break',
    title: '工作：把“不可能”改成“可训练”的试错脚手架',
    version: '进阶版',
    categoryPath: '工作/能力提升/试错脚手架',
    mode: 'planned',
    operationalDefinition: '将目标拆成可训练子技能，用“短周期试错”验证方法，而不是靠意志硬扛。',
    successCriteria: '明确 1 个子技能 + 3 次试错实验；至少 1 个实验产出可复用策略。',
    actionChecklist: [
      '写下目标：我想提升的子技能是（例：写周报、口语、写需求）',
      '列出 3 个最可能有效的方法（每个≤1句话）',
      '为每个方法设计 1 次 20 分钟试验（可衡量结果）',
      '试验后记录：有效/无效的证据是什么？',
      '把有效方法固化为“下次直接照做”的清单',
    ],
    refSegmentKeys: ['L5#1', 'L5#2', 'L6#15'],
    learningTags: ['实验', '反馈', '任务分解'],
    changePath: '把失败当数据：每次试错都输出一条“可复用规则”。',
  ),

  // c2 期待效应
  BeliefActionTemplate(
    id: 't_c2_family_expectation',
    conceptId: 'c2_expectation',
    title: '家庭/亲子：把“高期待”翻译成4个可见动作',
    version: '基础版',
    categoryPath: '家庭/亲子/期待升级',
    mode: 'planned',
    operationalDefinition: '不是口头鼓励，而是：更多关注+更多机会+更高质量反馈+更一致的对待。',
    successCriteria: '7 天内完成 4 类动作各≥1次；对象的参与度或情绪明显改善。',
    actionChecklist: [
      '每天一次“具体表扬”（努力/策略/进步）',
      '给一次稍难一点的任务/机会（在伸展区）',
      '给一次高质量反馈：好在哪里 + 可改进 + 下一步',
      '写一条“潜能句”：我相信你可以更靠近……',
    ],
    refSegmentKeys: ['L5#5', 'L5#6', 'L5#7', 'L5#8'],
    learningTags: ['强化', '反馈', '塑造'],
    changePath: '把“挑刺”替换为“抓对并放大”：先找一处做对的证据，再给下一步。',
  ),
  BeliefActionTemplate(
    id: 't_c2_love_dialog',
    conceptId: 'c2_expectation',
    title: '爱情/伴侣：一次“看见潜能”的对话脚本',
    version: '进阶版',
    categoryPath: '爱情/沟通/看见潜能',
    mode: 'quick',
    operationalDefinition: '用结构化对话把“我相信你能更好”传递出去，并把它落到一个具体下一步。',
    successCriteria: '完成一次对话；达成一个可执行的小约定；对话后关系紧张度下降。',
    actionChecklist: [
      '先说事实：最近我们在……上有摩擦（只描述，不评价）',
      '说期待：我更希望我们变成……（描述更好的版本）',
      '说证据：我看见你其实有……能力/意图（举1个例子）',
      '给机会：这周我们试一个小实验：……（可衡量）',
      '约复盘：下次我们用 10 分钟复盘：哪里更好/哪里要调',
    ],
    refSegmentKeys: ['L5#5', 'L5#7', 'L5#8'],
    learningTags: ['沟通', '正向反馈'],
    changePath: '先承认现实→再指出潜能→最后落到一次可验证的小实验。',
  ),

  // c3 情境力量
  BeliefActionTemplate(
    id: 't_c3_work_situation',
    conceptId: 'c3_situation_power',
    title: '工作：搭一个“正向情境装置”（3天）',
    version: '基础版',
    categoryPath: '工作/效率/情境装置',
    mode: 'planned',
    operationalDefinition: '承认情境强：用环境与流程把“正确行为”变得更容易发生。',
    successCriteria: '3 天内完成 1 个情境改造；目标行为发生频率上升。',
    actionChecklist: [
      '写下你想增加的目标行为（例：专注写作 20 分钟）',
      '找出最常见的干扰/阻力（例：手机/噪音/没准备材料）',
      '做 1 个环境改造（例：手机放远、桌面只留材料、定时器）',
      '做 1 个流程改造（例：开始前 2 分钟准备清单）',
      '每天记录：目标行为发生了吗？发生了多久？',
    ],
    refSegmentKeys: ['L5#9', 'L5#10', 'L6#2'],
    learningTags: ['刺激控制', '环境设计'],
    changePath: '把“自控”外包给环境：减少触发，增加提示。',
  ),
  BeliefActionTemplate(
    id: 't_c3_home_family',
    conceptId: 'c3_situation_power',
    title: '家庭：为冲突热点设计“降温情境”',
    version: '进阶版',
    categoryPath: '家庭/关系/降温情境',
    mode: 'planned',
    operationalDefinition: '把“容易吵起来的情境”拆成触发线索，并提前布置一个更容易和平的替代情境。',
    successCriteria: '1 周内热点冲突次数下降；出现冲突时能更快回到理性对话。',
    actionChecklist: [
      '列出最近 3 次冲突：发生在什么时间/地点/主题/状态？',
      '找共同触发线索（疲惫、饥饿、赶时间、孩子在场…）',
      '为触发线索设计替代情境（例：先吃饭再谈、约定“暂停词”）',
      '写“暂停流程”：暂停→各自冷静 10 分钟→再谈 1 个点',
      '复盘：这周最有效的一个情境改造是什么？',
    ],
    refSegmentKeys: ['L5#9', 'L5#10'],
    learningTags: ['情境重塑', '触发管理'],
    changePath: '先改情境，再谈对错：情境变了，行为才有空间改变。',
  ),

  // c4 启动效应
  BeliefActionTemplate(
    id: 't_c4_daily_priming',
    conceptId: 'c4_priming',
    title: '日常：用“启动线索”把习惯推上正轨',
    version: '基础版',
    categoryPath: '日常生活/习惯/启动线索',
    mode: 'planned',
    operationalDefinition: '把你想要的行为绑定到可见线索（提醒物/环境摆放/文字）上，让无意识也站在你这边。',
    successCriteria: '7 天内目标行为触发次数显著提升；拖延减少。',
    actionChecklist: [
      '选 1 个目标行为（例：读书 15 分钟）',
      '选 1 个强线索（例：把书放在枕边/桌面正中）',
      '移除 1 个坏线索（例：手机放到另一个房间）',
      '给线索加一句话（例：先做 5 分钟也算）',
      '记录：线索出现时，我有没有开始？',
    ],
    refSegmentKeys: ['L5#11', 'L6#1', 'L6#3', 'L6#4', 'L6#5'],
    learningTags: ['刺激控制', '线索-反应'],
    changePath: '线索先于意志：改摆放/改提示语/改摩擦成本。',
  ),
  BeliefActionTemplate(
    id: 't_c4_work_office',
    conceptId: 'c4_priming',
    title: '工作：办公室/桌面启动改造（30分钟）',
    version: '进阶版',
    categoryPath: '工作/效率/桌面启动',
    mode: 'quick',
    operationalDefinition: '通过视觉与流程线索，让“下一步正确动作”在你抬眼的一刻就出现。',
    successCriteria: '改造后当天就能更快进入工作；干扰切换次数下降。',
    actionChecklist: [
      '把桌面清到只剩“今天最重要的一件事”的材料',
      '把“下一步”写在便签上放在键盘前',
      '把聊天/社媒快捷入口移出首屏',
      '给开始设置倒计时：2 分钟准备 + 20 分钟专注',
      '结束时把“明天第一步”写好并摆出来',
    ],
    refSegmentKeys: ['L6#1', 'L6#3', 'L6#4'],
    learningTags: ['环境提示', '减少摩擦'],
    changePath: '让正确动作“可见”，让错误动作“不可见”。',
  ),

  // c5 安慰剂
  BeliefActionTemplate(
    id: 't_c5_health_placebo',
    conceptId: 'c5_placebo',
    title: '健康：安慰剂式恢复协议（不迷信版）',
    version: '基础版',
    categoryPath: '日常生活/健康/恢复协议',
    mode: 'planned',
    operationalDefinition: '把信念当作恢复的“助推器”，同时把可执行的睡眠/运动/复查行动做起来。',
    successCriteria: '一周内遵守恢复清单≥5天；主观症状/精力评分改善。',
    actionChecklist: [
      '写一句“恢复信念句”（现实且不夸张）',
      '每天 1 个微恢复动作：散步 10 分钟/拉伸/晒太阳',
      '睡眠优先：固定入睡前 30 分钟无屏幕',
      '记录症状/精力 0–5 分，观察趋势而非单点',
      '如有需要：预约检查/咨询，把不确定性变成信息',
    ],
    refSegmentKeys: ['L6#11'],
    learningTags: ['自我强化', '监测'],
    changePath: '信念不是替代治疗，而是让你更愿意执行恢复行为。',
  ),
  BeliefActionTemplate(
    id: 't_c5_anxiety_reframe',
    conceptId: 'c5_placebo',
    title: '情绪：把“焦虑预期”改成“可执行的应对脚本”',
    version: '进阶版',
    categoryPath: '日常生活/情绪/应对脚本',
    mode: 'planned',
    operationalDefinition: '承认身体反应，同时提前准备一个可执行的应对流程，降低不确定性。',
    successCriteria: '面对触发情境时能按脚本做 1–2 步；焦虑恢复更快。',
    actionChecklist: [
      '列出 1 个触发场景（开会/社交/考试前）',
      '写下身体信号（心跳/出汗/胃紧）',
      '写 3 步应对：呼吸 60 秒→做一件小事→求助/切换',
      '准备“证据卡”：过去我也挺过来的 2 个例子',
      '复盘：脚本哪一步最有效？',
    ],
    refSegmentKeys: ['L6#11'],
    learningTags: ['暴露', '应对反应'],
    changePath: '把“感觉很糟”改成“我知道下一步做什么”。',
  ),

  // c6 两条路：动机与一致性
  BeliefActionTemplate(
    id: 't_c6_alignment',
    conceptId: 'c6_mechanisms',
    title: '现实对齐：两栏计划（信念 vs 证据）',
    version: '基础版',
    categoryPath: '工作/自我管理/现实对齐',
    mode: 'planned',
    operationalDefinition: '用“一致性压力”：要么修正信念，要么修正现实，让两者能对齐。',
    successCriteria: '写出 3 条证据 + 1 个行动实验；一周内执行并复盘。',
    actionChecklist: [
      '左栏：我目前的信念/担忧是……',
      '右栏：现实证据（支持/反驳）各写 2 条',
      '找 1 个最小实验：24–72 小时能验证的动作',
      '执行后更新两栏：证据变了吗？信念需要改吗？',
      '写一句新结论（更贴近现实）',
    ],
    refSegmentKeys: ['L6#12', 'L6#13', 'L6#14'],
    learningTags: ['行为实验', '认知一致性'],
    changePath: '用实验替代内耗：让现实给答案。',
  ),
  BeliefActionTemplate(
    id: 't_c6_focus_filter',
    conceptId: 'c6_mechanisms',
    title: '注意力过滤：把“我看不见机会”改成“我每天收集证据”',
    version: '进阶版',
    categoryPath: '日常生活/心态/证据收集',
    mode: 'planned',
    operationalDefinition: '通过持续收集“支持性证据”，改变注意力过滤器，让你更容易看见可行路径。',
    successCriteria: '连续 7 天每天记录 ≥2 条支持证据；行动启动更顺畅。',
    actionChecklist: [
      '确定一个你想增强的信念（例：我能学会英语）',
      '每天记录 2 条“支持证据”（努力/进步/机会）',
      '每 2 天做 1 个小行动，把证据变多（例：跟读 10 分钟）',
      '第 7 天总结：证据密度变了吗？我更愿意行动了吗？',
    ],
    refSegmentKeys: ['L6#12', 'L6#14'],
    learningTags: ['自我监测', '强化'],
    changePath: '先改变你看见什么，再改变你做什么。',
  ),

  // c7 学会失败
  BeliefActionTemplate(
    id: 't_c7_fail_log',
    conceptId: 'c7_fail_to_learn',
    title: '失败日志：把一次挫折变成下一次的策略',
    version: '基础版',
    categoryPath: '工作/学习/失败复盘',
    mode: 'planned',
    operationalDefinition: '失败不是终点，而是“数据点”：提炼可复用策略，进入下一轮试验。',
    successCriteria: '记录 ≥3 次失败；每次输出 1 条可复用规则；下一次尝试更快开始。',
    actionChecklist: [
      '写下失败事件（只写事实）',
      '写 3 个原因：可控/不可控/信息缺失',
      '写 1 条“下次我会……”的策略',
      '把策略变成一个 24–72 小时的小实验',
      '复盘：策略有效吗？要迭代吗？',
    ],
    refSegmentKeys: ['L6#16', 'L6#28', 'L7#4', 'L7#9'],
    learningTags: ['强化', '迭代'],
    changePath: '失败→策略→实验→反馈→更强信念。',
  ),
  BeliefActionTemplate(
    id: 't_c7_school_exam',
    conceptId: 'c7_fail_to_learn',
    title: '学校：一次考试失利的“学习化”流程',
    version: '进阶版',
    categoryPath: '学校/考试/失败学习化',
    mode: 'planned',
    operationalDefinition: '把“情绪+归因”拉回“可训练的薄弱点”，并安排针对练习。',
    successCriteria: '提炼 3 个薄弱点；对应安排 7 天练习；下次测验在薄弱点上有提升。',
    actionChecklist: [
      '把错题分三类：概念不懂/步骤疏忽/时间管理',
      '每类选 1 个代表错题写出“正确过程”',
      '为每类安排 2 次针对练习（每次 20–30 分钟）',
      '设定“允许失败”的指标：按流程做对 1 步也算进步',
      '一周后做一次小测验并复盘',
    ],
    refSegmentKeys: ['L6#16', 'L7#4', 'L7#9'],
    learningTags: ['分步强化', '反馈'],
    changePath: '把失败从“自我评价”变成“训练计划”。',
  ),

  // c8 解释风格
  BeliefActionTemplate(
    id: 't_c8_rewrite',
    conceptId: 'c8_explanatory_style',
    title: '解释风格重写：把失败说成“暂时且特定”',
    version: '基础版',
    categoryPath: '日常生活/心态/解释风格',
    mode: 'quick',
    operationalDefinition: '把“永久且普遍”的解释改写为“暂时且特定”，并给出一个可执行补救动作。',
    successCriteria: '完成 1 次重写；立刻安排 1 个补救动作；情绪下降、行动恢复。',
    actionChecklist: [
      '写下原解释（我失败了，因为……）',
      '标注：这是“永久/普遍”还是“暂时/特定”？',
      '改写成暂时且特定版本（只针对当次/当点）',
      '写 1 个补救动作（24 小时内能做）',
      '执行并记录：情绪/行动是否恢复？',
    ],
    refSegmentKeys: ['L6#17', 'L6#18', 'L6#19', 'L6#20', 'L7#5'],
    learningTags: ['认知重评', '行为激活'],
    changePath: '先改解释，再改行动：解释变了，行动更容易回来。',
  ),
  BeliefActionTemplate(
    id: 't_c8_team_feedback',
    conceptId: 'c8_explanatory_style',
    title: '工作：面对批评的“特定化”回应',
    version: '进阶版',
    categoryPath: '工作/沟通/批评回应',
    mode: 'quick',
    operationalDefinition: '把“我不行”拆成“这一个点还没做好”，并把它转成 1 个具体改进动作。',
    successCriteria: '完成一次回应：澄清问题点→确认标准→约定下一步；自尊受损降低。',
    actionChecklist: [
      '复述批评内容为“一个具体点”（避免上升人格）',
      '确认标准：什么算做好？（请对方给例子）',
      '提出下一步：我会在 X 时间内做 Y 调整',
      '约复盘：下次一起看结果',
    ],
    refSegmentKeys: ['L6#17', 'L6#18', 'L7#5'],
    learningTags: ['反馈处理', '任务明确化'],
    changePath: '把“人格评价”降维成“任务标准”。',
  ),

  // c9 现实乐观 / Stockdale
  BeliefActionTemplate(
    id: 't_c9_stockdale_plan',
    conceptId: 'c9_realistic_optimism',
    title: 'Stockdale 两段式计划：信念 + 残酷事实',
    version: '基础版',
    categoryPath: '工作/目标/现实乐观',
    mode: 'planned',
    operationalDefinition: '同时写出“我会赢”的坚定信念与“现实最残酷事实”，并把事实转成行动计划。',
    successCriteria: '形成 1 份两段式计划；一周内推进 3 个可控动作；焦虑降低、掌控感上升。',
    actionChecklist: [
      '信念段：我相信最终我会……（结果愿景）',
      '事实段：目前最残酷的事实是……（列 3 条）',
      '可控段：对每条事实写 1 个可控动作',
      '安排时间：7 天内至少执行 3 个动作',
      '复盘：事实有没有变化？行动需要调整吗？',
    ],
    refSegmentKeys: ['L6#21', 'L6#22', 'L6#23', 'L6#24'],
    learningTags: ['计划', '问题解决'],
    changePath: '不靠幻想减压，而靠“可控动作”减压。',
  ),
  BeliefActionTemplate(
    id: 't_c9_relationship',
    conceptId: 'c9_realistic_optimism',
    title: '人际：一段关系的“残酷事实清单”与修复动作',
    version: '进阶版',
    categoryPath: '人际关系/修复/现实乐观',
    mode: 'planned',
    operationalDefinition: '不逃避问题，同时保持关系可修复的信念，并设计可验证的修复动作。',
    successCriteria: '明确 2 条残酷事实 + 2 个修复动作；完成一次沟通并复盘。',
    actionChecklist: [
      '写愿景：我希望关系变成……（现实可达）',
      '写事实：目前阻碍是什么？（只写事实）',
      '写动作：我能做的 2 个修复动作（可观察）',
      '安排一次沟通：只谈 1 个点 + 约下次复盘',
    ],
    refSegmentKeys: ['L6#21', 'L6#23', 'L6#24'],
    learningTags: ['沟通', '问题解决'],
    changePath: '把“希望”落在“具体动作”，而不是落在对方必须改变。',
  ),

  // c10 三套工具：行动/可视化/认知疗法
  BeliefActionTemplate(
    id: 't_c10_3ms',
    conceptId: 'c10_tools',
    title: '3Ms 缩放训练：从灾难化拉回现实',
    version: '基础版',
    categoryPath: '日常生活/情绪/3Ms训练',
    mode: 'quick',
    operationalDefinition: '用“放大/缩小/维持”的视角切换，让你从灾难化回到可行动的现实层。',
    successCriteria: '完成一次 3Ms 书写；选择 1 个下一步行动；情绪下降、行动恢复。',
    actionChecklist: [
      '写下让我痛苦的事件（事实）',
      '放大：最糟会怎样？（把它写清）',
      '缩小：现实证据是什么？概率/边界是什么？',
      '维持：无论如何我能做的下一步是什么？',
      '立刻执行 1 个最小下一步',
    ],
    refSegmentKeys: ['L7#6', 'L7#7', 'L7#8', 'L7#10'],
    learningTags: ['认知疗法', '行为激活'],
    changePath: '先把世界缩回真实尺度，再做下一步。',
  ),
  BeliefActionTemplate(
    id: 't_c10_visualize_do',
    conceptId: 'c10_tools',
    title: '可视化 + 行动：把“想象成功”改成“想象+执行”',
    version: '进阶版',
    categoryPath: '工作/学习/可视化行动',
    mode: 'planned',
    operationalDefinition: '可视化不是做梦：用“过程可视化”引导一次真实的执行。',
    successCriteria: '完成 1 次过程可视化 + 1 次执行；执行阻力下降。',
    actionChecklist: [
      '选一个你想做但拖延的任务',
      '闭眼 60 秒想象“开始的前 2 分钟”细节（环境/动作）',
      '写下“开始脚本”：我会先……再……',
      '立刻执行 10 分钟',
      '复盘：阻力点在哪里？下次如何更容易开始？',
    ],
    refSegmentKeys: ['L7#12', 'L7#14', 'L7#17', 'L7#18'],
    learningTags: ['过程可视化', '启动'],
    changePath: '把想象锁定在“过程”，而不是只想象结果。',
  ),

  // ====== 追加：更多领域/更多版本（基于 10 个概念 + 57 段资料库） ======

  // c1 可能性开关：学校/考试
  BeliefActionTemplate(
    id: 't_c1_school_breakthrough',
    conceptId: 'c1_limit_break',
    title: '学校：把“我不行”改成“我还没找到方法”的 7 天突破计划',
    version: '进阶版',
    categoryPath: '学校/考试/可能性开关',
    mode: 'planned',
    operationalDefinition: '把“能力硬上限”的信念改写为“可训练”，并用 7 天的可衡量练习让反馈发生。',
    successCriteria: '完成 7 天内至少 3 次练习；每次记录证据与改进点；第 7 天能复述“我学到的策略”。',
    actionChecklist: [
      '选 1 个最卡的科目/题型（要具体到题型）',
      '把目标写成“可衡量指标”（题数/分钟/正确率/复述次数）',
      '安排 7 天内至少 3 次练习（每次 15–30 分钟）',
      '每次练习后写 1 句：我这次学到的策略是什么？',
      '第 7 天做一次小测/复盘：下一轮我要改什么？',
    ],
    refSegmentKeys: ['L5#1', 'L5#2', 'L6#8', 'L6#15'],
    learningTags: ['行为激活', '刻意练习'],
    changePath: '把注意力从“天赋判断”转到“策略迭代”。',
  ),

  // c2 期待效应：爱情/伴侣
  BeliefActionTemplate(
    id: 't_c2_love_expectation',
    conceptId: 'c2_expectation',
    title: '爱情：把“期待”变成 3 个可观察的关怀与信任动作',
    version: '进阶版',
    categoryPath: '爱情/沟通/期待升级',
    mode: 'quick',
    operationalDefinition: '把“你会更好/我们能更好”的期待，落实为具体的语气、机会、反馈与边界。',
    successCriteria: '完成 1 次具体表扬 + 1 次伸展区机会 + 1 次高质量反馈；关系氛围更稳定。',
    actionChecklist: [
      '今天做 1 次“具体表扬”（表扬努力/策略/进步，不夸空洞品质）',
      '给 1 次“伸展区机会”：邀请对方参与一个更重要/更被信任的任务',
      '给 1 次高质量反馈：做得好 + 可改进 + 下一步建议（只谈 1 个点）',
      '写 1 句“潜能句”：我相信你能成为……（现实可达）',
    ],
    refSegmentKeys: ['L5#5', 'L5#6', 'L5#7', 'L5#8'],
    learningTags: ['沟通', '强化'],
    changePath: '减少“否定性预判”，用可执行的支持动作替代。',
  ),

  // c3 情境力量：职场/协作
  BeliefActionTemplate(
    id: 't_c3_work_situation',
    conceptId: 'c3_situation_power',
    title: '工作：为协作设计一个“正向情境”',
    version: '进阶版',
    categoryPath: '工作/协作/情境设计',
    mode: 'planned',
    operationalDefinition: '识别当前让你卡住的情境因素，并通过规则/环境/流程微调来“让好行为更容易发生”。',
    successCriteria: '明确 3 个情境变量；完成 1 次微改造；一周内观察到目标行为增加。',
    actionChecklist: [
      '写下当前最糟的情境触发点（时间/地点/人/流程）',
      '列 3 个可控变量（例如：会议结构、任务拆分、反馈节奏）',
      '选 1 个变量做最小改造（例如：站会 10 分钟 + 结论落任务）',
      '设 1 个可观察指标（例如：本周按期交付次数）',
      '一周后复盘：变量是否有效？下周怎么继续调整？',
    ],
    refSegmentKeys: ['L5#9', 'L5#10', 'L6#2'],
    learningTags: ['情境控制', '行为设计'],
    changePath: '先改环境，再谈意志力。',
  ),

  // c4 启动效应：手机/信息流
  BeliefActionTemplate(
    id: 't_c4_phone_priming',
    conceptId: 'c4_priming',
    title: '日常：用“反启动”降低刷手机冲动',
    version: '进阶版',
    categoryPath: '日常生活/手机/启动效应',
    mode: 'quick',
    operationalDefinition: '识别让你自动刷手机的线索（启动），并用环境改造把它替换为更好的默认行为。',
    successCriteria: '完成 2 个环境改造；当天刷手机总时长下降或启动次数减少；能复盘触发点。',
    actionChecklist: [
      '找出最常触发刷手机的 1 个线索（无聊/通知/床上）',
      '做 1 个环境改造：关闭非必要通知/把 App 移出首屏/灰阶',
      '做 1 个替代线索：把“要做的下一步”写成便签放在锁屏旁',
      '当冲动出现时，先做 30 秒替代动作（喝水/站起来/深呼吸）',
      '晚上复盘：今天触发点是什么？我怎么改更有效？',
    ],
    refSegmentKeys: ['L5#11', 'L6#3', 'L6#4', 'L6#5'],
    learningTags: ['环境改造', '习惯回路'],
    changePath: '减少线索暴露 + 增加替代行为的可得性。',
  ),

  // c5 安慰剂：表现前仪式
  BeliefActionTemplate(
    id: 't_c5_preperformance_placebo',
    conceptId: 'c5_placebo',
    title: '工作/考试：建立一个“安慰剂式”表现前稳定仪式',
    version: '进阶版',
    categoryPath: '工作/学校/表现/安慰剂仪式',
    mode: 'quick',
    operationalDefinition: '用一个可重复的小仪式稳定注意力与自我效能，但把核心放回行动与准备。',
    successCriteria: '完成 1 次表现前仪式 + 10 分钟有效准备；紧张下降；进入状态更快。',
    actionChecklist: [
      '选 1 个 60 秒仪式（固定呼吸/热身/自我暗示）',
      '写 1 句现实暗示：我能控制的是准备与执行',
      '做 10 分钟关键准备（复习提纲/演练开头/整理材料）',
      '执行后复盘：仪式是否帮助？下次要保留哪一步？',
    ],
    refSegmentKeys: ['L6#11'],
    learningTags: ['自我效能', '注意力'],
    changePath: '把“相信”当作启动器，而不是替代品。',
  ),

  // c6 两条路：关系中的现实对齐
  BeliefActionTemplate(
    id: 't_c6_relationship_alignment',
    conceptId: 'c6_mechanisms',
    title: '爱情：用“两栏对齐”把猜测变成可验证的现实',
    version: '进阶版',
    categoryPath: '爱情/信任/现实对齐',
    mode: 'planned',
    operationalDefinition: '把“我以为/我相信”的故事与“我看到/我听到”的证据分开，并设计一个可验证的沟通行动。',
    successCriteria: '写清两栏；完成一次沟通；得到可观察证据；下一步行动明确。',
    actionChecklist: [
      '栏 A：写下我相信的故事（不评判）',
      '栏 B：写下现实证据（只写可观察事实）',
      '找出差距：哪个部分是我脑补的？哪个部分是真问题？',
      '设计 1 个可验证的沟通问题（开放式 + 只谈 1 点）',
      '沟通后复盘：事实更新了吗？我下一步做什么？',
    ],
    refSegmentKeys: ['L6#12', 'L6#13', 'L6#14'],
    learningTags: ['认知重评', '沟通'],
    changePath: '用“可验证”替代“想当然”。',
  ),

  // c7 学会失败：面试
  BeliefActionTemplate(
    id: 't_c7_interview_fail_log',
    conceptId: 'c7_fail_to_learn',
    title: '工作：面试失败 → 学习闭环（记录、拆因、再试）',
    version: '进阶版',
    categoryPath: '工作/面试/失败学习',
    mode: 'planned',
    operationalDefinition: '把一次失败拆成可学习的变量，并形成下一轮可执行的改进动作。',
    successCriteria: '完成 1 条失败记录；提炼 3 条可控改进；安排下一次练习/投递并执行。',
    actionChecklist: [
      '写事实：发生了什么？（只写事实）',
      '写情绪：我当时最强烈的感受是什么？',
      '拆变量：准备/表达/案例/沟通/运气，各占多少？',
      '提炼 3 条可控改进（下一次可做）',
      '安排下一次练习或投递（写日期/时间）',
    ],
    refSegmentKeys: ['L6#16', 'L6#28', 'L7#4', 'L7#9'],
    learningTags: ['复盘', '迭代'],
    changePath: '把“失败=身份”改为“失败=数据”。',
  ),

  // c8 解释风格：家庭冲突
  BeliefActionTemplate(
    id: 't_c8_family_rewrite',
    conceptId: 'c8_explanatory_style',
    title: '家庭：把“他永远都这样”改写成“暂时且特定”',
    version: '进阶版',
    categoryPath: '家庭/冲突/解释风格',
    mode: 'quick',
    operationalDefinition: '把冲突解释从“永久/普遍/内在缺陷”改为“暂时/特定/可改变因素”，并设计 1 个修复动作。',
    successCriteria: '完成一次改写；情绪下降；做出 1 个修复动作并记录结果。',
    actionChecklist: [
      '写原解释：我在心里怎么说这件事？（原话）',
      '改写为：暂时（这只是这次）+ 特定（只在某情境）+ 可改（有变量）',
      '找 1 条证据：什么时候不是这样？',
      '设计 1 个修复动作（一句话沟通/一个小行动）',
      '复盘：冲突是否缓和？我学到了什么？',
    ],
    refSegmentKeys: ['L6#17', 'L6#18', 'L6#19', 'L6#20', 'L7#5'],
    learningTags: ['解释风格', '认知重评'],
    changePath: '先改“解释”，再改“互动脚本”。',
  ),

  // c9 现实乐观：长期项目
  BeliefActionTemplate(
    id: 't_c9_long_project_stockdale',
    conceptId: 'c9_realistic_optimism',
    title: '工作：长期项目的 Stockdale 双线计划',
    version: '进阶版',
    categoryPath: '工作/长期项目/现实乐观',
    mode: 'planned',
    operationalDefinition: '同时保持“最终会赢”的信念与“今天的残酷事实”，并把事实转成具体的下一步。',
    successCriteria: '写清 2 条事实 + 1 条信念；输出 3 个下一步；执行其中 1 个并复盘。',
    actionChecklist: [
      '写最终信念：我相信我们最终会……（具体）',
      '写残酷事实：目前最阻碍的 2 件事是什么？',
      '把事实转行动：每个事实对应 1 个可执行动作',
      '选 1 个动作立刻推进（15–30 分钟）',
      '复盘：事实有变化吗？下周怎么继续？',
    ],
    refSegmentKeys: ['L6#21', 'L6#22', 'L6#23', 'L6#24'],
    learningTags: ['计划', '问题解决'],
    changePath: '用“事实”逼近现实，用“信念”维持方向。',
  ),

  // c10 工具：自动思维记录（CBT）
  BeliefActionTemplate(
    id: 't_c10_cbt_record',
    conceptId: 'c10_tools',
    title: '认知疗法：一次“自动思维记录”',
    version: '进阶版',
    categoryPath: '日常生活/认知疗法/记录',
    mode: 'quick',
    operationalDefinition: '把自动想法写出来，寻找证据与替代想法，再把替代想法落实为行动。',
    successCriteria: '完成 1 次记录；找到至少 1 条证据与 1 个替代想法；执行 1 个行动。',
    actionChecklist: [
      '写触发事件（事实）',
      '写自动想法（原话）',
      '写情绪（0–10）',
      '写证据：支持/反对各 1 条',
      '写替代想法：更真实、更能行动',
      '选 1 个最小行动去验证替代想法',
    ],
    refSegmentKeys: ['L7#6', 'L7#7', 'L7#8', 'L7#10'],
    learningTags: ['认知疗法', '行为实验'],
    changePath: '把“想法”从真理降级为假设，然后去验证。',
  ),


  // ======== 新增：细分概念的推荐行动模板（与概念/段落一致） ========

  // c0 概览：自我实现/预言性信念链
  BeliefActionTemplate(
    id: 't_c0_chain_daily',
    conceptId: 'c0_overview',
    title: '信念→行动→结果：一天一条链',
    version: '基础版',
    categoryPath: '日常生活/自我实现/观察',
    mode: 'quick',
    operationalDefinition: '用一个真实事件，把“信念如何通过行动与互动影响结果”写成一条可验证链条。',
    successCriteria: '写清 1 条链；指出 1 个可调整变量；第二天能复现一次。',
    actionChecklist: [
      '写事件（事实）',
      '写我当时的信念/预期（原句）',
      '写我因此做了什么（行为/互动）',
      '写现实结果（证据）',
      '写一个可调整变量：下次我换一个小动作试试',
    ],
    refSegmentKeys: ['L5#1', 'L6#10'],
    learningTags: ['观察', '证据'],
    changePath: '把抽象概念落回“可观察证据”。',
  ),
  BeliefActionTemplate(
    id: 't_c0_work_team_loop',
    conceptId: 'c0_overview',
    title: '团队预期循环：把“预言”写成管理动作',
    version: '工作版',
    categoryPath: '工作/团队/自我实现',
    mode: 'planned',
    operationalDefinition: '识别你对某个同事/项目的预期，并设计一个能改变互动质量的小行动。',
    successCriteria: '写清预期；输出 2 个具体互动动作；执行 1 次并记录证据。',
    actionChecklist: [
      '写我的预期（例：他不靠谱/项目会失败）',
      '写预期导致的互动方式（回避/挑刺/不授权）',
      '写一个反向动作（更清晰目标/更具体支持/更明确边界）',
      '执行一次互动（10–20分钟）',
      '记录证据：对方行为/结果有什么变化？',
    ],
    refSegmentKeys: ['L5#1', 'L6#12'],
    learningTags: ['沟通', '实验'],
    changePath: '改变互动方式，就是在改变被验证的“现实”。',
  ),
  BeliefActionTemplate(
    id: 't_c0_relationship_expect',
    conceptId: 'c0_overview',
    title: '关系预期校准：把想象变成证据',
    version: '亲密关系版',
    categoryPath: '爱情/沟通/预期',
    mode: 'quick',
    operationalDefinition: '把你对对方的一个预期改成“可验证请求”，用沟通获得真实证据。',
    successCriteria: '提出 1 个具体请求；得到 1 个明确答复；记录结果与下一步。',
    actionChecklist: [
      '写我的预期（他应该懂我/她总是不在意我）',
      '把预期改成一个具体请求（例：今晚散步20分钟）',
      '提出请求（用事实+感受+请求）',
      '得到答复并确认边界',
      '记录：结果如何？我学到了什么？',
    ],
    refSegmentKeys: ['L5#1', 'L6#10'],
    learningTags: ['沟通', '边界'],
    changePath: '从猜测回到可验证的互动。',
  ),

  // c1b 自助边界：避免“万能自助”导致的失望/责备
  BeliefActionTemplate(
    id: 't_c1b_rewrite_mantra',
    conceptId: 'c1b_self_help_boundary',
    title: '把自助口号改成可执行方案',
    version: '基础版',
    categoryPath: '日常生活/自助/校准',
    mode: 'quick',
    operationalDefinition: '把一句“万能信念”改成：行动+约束+指标+复盘。',
    successCriteria: '输出 1 句可执行规则；包含指标；能在 24h 内执行一次。',
    actionChecklist: [
      '写口号原句（例：我想要就一定能）',
      '写现实约束（时间/资源/技能/他人）',
      '写最小行动（≤10分钟）',
      '写成功指标（可观察）',
      '写失败时的变量调整（下次改哪一个）',
    ],
    refSegmentKeys: ['L5#3', 'L6#9'],
    learningTags: ['现实校准', '复盘'],
    changePath: '把“信念”从魔法还原为行动策略。',
  ),
  BeliefActionTemplate(
    id: 't_c1b_guilt_to_design',
    conceptId: 'c1b_self_help_boundary',
    title: '从自责到设计：失败时改变量',
    version: '进阶版',
    categoryPath: '日常生活/失败学习/变量',
    mode: 'planned',
    operationalDefinition: '当你失败时，不归因为人格，而改成“变量实验”。',
    successCriteria: '列出 3 个变量；选择 1 个改动；执行下一轮并记录证据。',
    actionChecklist: [
      '写失败事实（发生了什么）',
      '写自责解释（原句）',
      '列 3 个可改变量（环境/动作/频率/难度）',
      '选 1 个变量改小一点再试',
      '记录：结果变化了吗？',
    ],
    refSegmentKeys: ['L6#6', 'L6#7', 'L6#10'],
    learningTags: ['失败', '实验'],
    changePath: '失败不是道德审判，而是工程迭代。',
  ),
  BeliefActionTemplate(
    id: 't_c1b_reality_contract',
    conceptId: 'c1b_self_help_boundary',
    title: '现实契约：把愿望写成计划',
    version: '工作/学习版',
    categoryPath: '工作/目标/现实契约',
    mode: 'planned',
    operationalDefinition: '把一个愿望写成“现实契约”：目标、资源、风险、最小行动。',
    successCriteria: '写清 4 要素；当日执行 1 个最小行动；给出风险预案。',
    actionChecklist: [
      '目标：我想得到什么（具体）',
      '资源：我有什么/缺什么',
      '风险：可能失败的 2 个点',
      '最小行动：今天能做的 10 分钟',
      '预案：若失败，下一步怎么调？',
    ],
    refSegmentKeys: ['L5#3', 'L6#9', 'L6#10'],
    learningTags: ['计划', '风险'],
    changePath: '用契约替代幻想。',
  ),

  // c1c 自我效能/自尊：证据驱动
  BeliefActionTemplate(
    id: 't_c1c_micro_evidence',
    conceptId: 'c1c_efficacy_selfesteem',
    title: '7天微证据：我能做到',
    version: '基础版',
    categoryPath: '日常生活/自我效能/证据',
    mode: 'planned',
    operationalDefinition: '每天完成一个微任务，累积可验证的“我能做到”证据。',
    successCriteria: '7 天≥5天完成；每次都有记录；自评效能提升 ≥1 分（0–5）。',
    actionChecklist: [
      '选领域（学习/工作/健康/社交）',
      '定义微任务（≤10分钟）',
      '每天完成并记录证据（截图/打勾/文字）',
      '失败→拆更小；不做自责解释',
      '第7天自评效能（0–5）',
    ],
    refSegmentKeys: ['L5#4', 'L7#7', 'L7#8'],
    learningTags: ['证据', '习惯'],
    changePath: '效能来自证据累积。',
  ),
  BeliefActionTemplate(
    id: 't_c1c_skill_ladder',
    conceptId: 'c1c_efficacy_selfesteem',
    title: '技能梯子：从容易到困难',
    version: '学习版',
    categoryPath: '学校/学习/技能梯子',
    mode: 'planned',
    operationalDefinition: '把一个技能拆成 5 阶梯，确保每一步都有成功体验。',
    successCriteria: '写清 5 阶梯；完成前 2 阶；记录每阶证据。',
    actionChecklist: [
      '选技能（例：英语口语/写作/算法题）',
      '拆成 5 阶（从最容易开始）',
      '今天完成第1阶（≤15分钟）',
      '明天完成第2阶',
      '每阶记录：我做成了什么？',
    ],
    refSegmentKeys: ['L7#7', 'L7#8'],
    learningTags: ['分级任务', '学习'],
    changePath: '用可达成台阶积累自尊。',
  ),
  BeliefActionTemplate(
    id: 't_c1c_social_proof',
    conceptId: 'c1c_efficacy_selfesteem',
    title: '外部证据：请求一次具体反馈',
    version: '人际版',
    categoryPath: '人际关系/自尊/反馈',
    mode: 'quick',
    operationalDefinition: '向可信的人请求一次“具体、可观察”的反馈，修正自我评价。',
    successCriteria: '提出请求；得到1条具体反馈；写下1个下一步。',
    actionChecklist: [
      '选1个可信对象',
      '提出请求：请给我 1 条具体优点 + 1 条可改进点（基于事实）',
      '记录反馈原话',
      '写下一步微行动（≤10分钟）',
      '自评：自我评价是否更接近现实？',
    ],
    refSegmentKeys: ['L6#25', 'L7#7'],
    learningTags: ['反馈', '现实校准'],
    changePath: '用事实反馈替代空泛自我否定。',
  ),

  // c2b 看见潜能：把注意力变成增长
  BeliefActionTemplate(
    id: 't_c2b_growth_log',
    conceptId: 'c2b_see_potential',
    title: '潜能证据日志（7天）',
    version: '基础版',
    categoryPath: '日常生活/成长/潜能',
    mode: 'planned',
    operationalDefinition: '每天记录一个微小进步证据，并给自己一个下一步任务。',
    successCriteria: '7 天≥5天记录；每次包含证据+下一步。',
    actionChecklist: [
      '记录1个微进步证据（可观察）',
      '写1句具体肯定（基于事实）',
      '写1个下一步微任务（≤10分钟）',
      '执行或安排到日程',
      '第7天回看：证据是否累积？',
    ],
    refSegmentKeys: ['L5#7'],
    learningTags: ['成长', '反馈'],
    changePath: '你看到什么，什么就更容易长出来。',
  ),
  BeliefActionTemplate(
    id: 't_c2b_parent_feedback',
    conceptId: 'c2b_see_potential',
    title: '家庭/亲子：一次“证据型表扬”',
    version: '家庭版',
    categoryPath: '家庭/亲子/潜能',
    mode: 'quick',
    operationalDefinition: '把“你真棒”改成：事实证据+过程行为+下一步。',
    successCriteria: '给出 1 次表扬；包含证据；对方愿意再做一次。',
    actionChecklist: [
      '选一个具体行为（例：主动写作业/帮忙）',
      '描述证据（我看到你……）',
      '指出过程（你用了什么方法/坚持了多久）',
      '给出下一步小挑战（≤10分钟）',
      '观察反应并记录',
    ],
    refSegmentKeys: ['L5#7'],
    learningTags: ['沟通', '强化'],
    changePath: '证据型反馈=浇水。',
  ),
  BeliefActionTemplate(
    id: 't_c2b_work_coach',
    conceptId: 'c2b_see_potential',
    title: '工作教练：把“潜力”翻译成任务',
    version: '工作版',
    categoryPath: '工作/管理/潜能',
    mode: 'planned',
    operationalDefinition: '为某个同事设计一个“可胜任的小挑战”，用任务引出潜能。',
    successCriteria: '定义挑战；明确成功指标；给出支持与复盘。',
    actionChecklist: [
      '选对象与技能点',
      '设计小挑战（可在一周内完成）',
      '写成功指标（可观察）',
      '提供资源/支持（模板/协作）',
      '一周后复盘：证据与下一步',
    ],
    refSegmentKeys: ['L5#7'],
    learningTags: ['管理', '成长'],
    changePath: '潜能通过任务被唤醒。',
  ),

  // c3b 积极情境：用线索启动更好的自己
  BeliefActionTemplate(
    id: 't_c3b_env_design',
    conceptId: 'c3b_positive_situation',
    title: '环境设计：3个线索启动',
    version: '基础版',
    categoryPath: '日常生活/环境/线索',
    mode: 'planned',
    operationalDefinition: '用空间/物品/仪式三类线索，让自己更容易进入目标状态。',
    successCriteria: '设定 3 个线索；连续 3 天触发；记录行为变化。',
    actionChecklist: [
      '写目标状态（例：专注/温柔/执行）',
      '设置空间线索（桌面/灯光）',
      '设置物品线索（书/衣服/物件）',
      '设置仪式线索（音乐/口令/动作）',
      '连续3天记录：行为有什么不同？',
    ],
    refSegmentKeys: ['L5#10', 'L6#2'],
    learningTags: ['情境', '习惯'],
    changePath: '先改环境，再改行为。',
  ),
  BeliefActionTemplate(
    id: 't_c3b_role_script',
    conceptId: 'c3b_positive_situation',
    title: '角色脚本：我在这个情境里怎么做？',
    version: '进阶版',
    categoryPath: '人际关系/角色/脚本',
    mode: 'quick',
    operationalDefinition: '写一个“角色脚本”，在关键情境里用它替换旧反应。',
    successCriteria: '写清脚本；当日执行 1 次；自评一致性 ≥3/5。',
    actionChecklist: [
      '写关键情境（触发场景）',
      '写旧反应（自动）',
      '写角色脚本（我将如何说/如何做）',
      '立即执行一次（哪怕很小）',
      '评分一致性（0–5）并复盘',
    ],
    refSegmentKeys: ['L6#2', 'L5#10'],
    learningTags: ['脚本', '执行'],
    changePath: '让“情境”触发新脚本。',
  ),
  BeliefActionTemplate(
    id: 't_c3b_school_exam_room',
    conceptId: 'c3b_positive_situation',
    title: '学校/考试：把考场变成“熟悉情境”',
    version: '学生版',
    categoryPath: '学校/考试/情境',
    mode: 'planned',
    operationalDefinition: '用模拟与线索让大脑把考场识别为“熟悉”，降低恐惧反应。',
    successCriteria: '完成 2 次模拟；固定启动仪式；记录紧张度下降。',
    actionChecklist: [
      '准备模拟环境（桌椅/计时器/纸笔）',
      '固定启动仪式（口令/呼吸/动作）',
      '做一次 20 分钟模拟',
      '记录紧张度（0–10）',
      '第二次模拟重复并比较',
    ],
    refSegmentKeys: ['L5#10', 'L6#2'],
    learningTags: ['暴露', '仪式'],
    changePath: '把陌生变熟悉，恐惧就会下降。',
  ),

  // c6a 认知失调：用微承诺拉动信念
  BeliefActionTemplate(
    id: 't_c6a_micro_commit',
    conceptId: 'c6a_dissonance',
    title: '失调→微承诺：今天必须做的10分钟',
    version: '基础版',
    categoryPath: '日常生活/认知失调/承诺',
    mode: 'quick',
    operationalDefinition: '选一个“我说想做但没做”的点，用 10 分钟行动制造一致性压力。',
    successCriteria: '完成一次微行动；记录证据；下一步更容易开始。',
    actionChecklist: [
      '写失调点（我说想要……但我没做……）',
      '写微行动（≤10分钟）',
      '现在就做（计时）',
      '记录证据（打勾/截图/文字）',
      '写下一步：明天加 10% 难度',
    ],
    refSegmentKeys: ['L6#12'],
    learningTags: ['启动', '承诺'],
    changePath: '先做一点点，再让信念追上行动。',
  ),
  BeliefActionTemplate(
    id: 't_c6a_public_record',
    conceptId: 'c6a_dissonance',
    title: '公开记录：用“被看见”增加一致性',
    version: '人际版',
    categoryPath: '人际关系/承诺/公开',
    mode: 'planned',
    operationalDefinition: '选择可信对象，公开你的微计划与复盘方式，制造温和的社会压力。',
    successCriteria: '发出1次公开承诺；完成1次复盘；下一次更易执行。',
    actionChecklist: [
      '选1个可信对象/群',
      '写承诺：我会在 X 时间做 Y（可验证）',
      '执行并发证据',
      '复盘1句：今天学到什么？',
      '约定下一次微升级',
    ],
    refSegmentKeys: ['L6#12'],
    learningTags: ['社会支持', '承诺'],
    changePath: '用社会线索稳定行为。',
  ),
  BeliefActionTemplate(
    id: 't_c6a_identity_sentence',
    conceptId: 'c6a_dissonance',
    title: '身份句：把行动绑定到“我是谁”',
    version: '进阶版',
    categoryPath: '日常生活/身份/一致性',
    mode: 'quick',
    operationalDefinition: '写一句身份句，并立刻做一个能证明它的小行动。',
    successCriteria: '写身份句；做1次证明行动；一致性评分≥3/5。',
    actionChecklist: [
      '写身份句（例：我是会坚持的人）',
      '写证明行动（≤10分钟）',
      '立刻执行',
      '记录证据',
      '一致性评分（0–5）并复盘',
    ],
    refSegmentKeys: ['L6#12'],
    learningTags: ['身份', '启动'],
    changePath: '让行为成为身份的证据。',
  ),

  // c6b 确认偏误：反证训练
  BeliefActionTemplate(
    id: 't_c6b_disconfirm_daily',
    conceptId: 'c6b_confirmation_bias',
    title: '每日反证：为自己的结论找反例',
    version: '基础版',
    categoryPath: '日常生活/思维偏差/反证',
    mode: 'planned',
    operationalDefinition: '针对一个强烈结论，每天找 1 条反例并改写为条件句。',
    successCriteria: '7天≥5天完成；结论从绝对句变成条件句；行动更清晰。',
    actionChecklist: [
      '写强烈结论（原句）',
      '找1条反例/反证',
      '把结论改成更具体条件句',
      '写一个可验证行动去测试',
      '记录证据与更新',
    ],
    refSegmentKeys: ['L6#13'],
    learningTags: ['批判性思维', '证据'],
    changePath: '让“结论”对证据负责。',
  ),
  BeliefActionTemplate(
    id: 't_c6b_three_views',
    conceptId: 'c6b_confirmation_bias',
    title: '三视角：我、对方、旁观者',
    version: '人际版',
    categoryPath: '人际关系/冲突/视角',
    mode: 'quick',
    operationalDefinition: '在冲突中强制写三种解释，避免只收集支持自己的证据。',
    successCriteria: '写出3种解释；每种至少1条证据；选1个更现实的行动。',
    actionChecklist: [
      '写冲突事实（不评价）',
      '写“我视角”的解释+证据',
      '写“对方视角”的解释+证据',
      '写“旁观者视角”的解释+证据',
      '选一个最小行动（沟通/边界/请求）',
    ],
    refSegmentKeys: ['L6#13'],
    learningTags: ['冲突', '视角'],
    changePath: '多视角=更接近现实。',
  ),
  BeliefActionTemplate(
    id: 't_c6b_ask_to_refute',
    conceptId: 'c6b_confirmation_bias',
    title: '求反驳：让别人指出我错在哪里',
    version: '工作版',
    categoryPath: '工作/决策/反驳',
    mode: 'quick',
    operationalDefinition: '在做决定前，主动邀请别人提出反对意见，收集反证。',
    successCriteria: '得到≥1条反对意见；修正方案≥1点；决策更稳。',
    actionChecklist: [
      '写决定选项（A/B）',
      '请1人：你觉得我哪里可能错？',
      '记录反对意见（原话）',
      '修正方案（至少1点）',
      '写最终决定与理由（含反证）',
    ],
    refSegmentKeys: ['L6#13'],
    learningTags: ['决策', '反证'],
    changePath: '把反对意见当作资产。',
  ),

  // c6c 焦点过滤器：注意力/过程指标
  BeliefActionTemplate(
    id: 't_c6c_process_metrics',
    conceptId: 'c6c_focus_filter',
    title: '过程指标卡：把焦点放在可控',
    version: '基础版',
    categoryPath: '日常生活/专注/过程指标',
    mode: 'planned',
    operationalDefinition: '把一个结果目标改写为 2 个过程指标，并只跟踪过程。',
    successCriteria: '定义2个过程指标；7天记录；第7天复盘结果与情绪变化。',
    actionChecklist: [
      '写结果目标（例：通过考试/减脂）',
      '写2个过程指标（分钟/次数/页数）',
      '每天记录过程指标',
      '只评价“是否完成过程”',
      '第7天复盘：结果与情绪的变化',
    ],
    refSegmentKeys: ['L6#14', 'L7#1'],
    learningTags: ['专注', '习惯'],
    changePath: '焦点在过程，行动就会持续。',
  ),
  BeliefActionTemplate(
    id: 't_c6c_attention_budget',
    conceptId: 'c6c_focus_filter',
    title: '注意力预算：今天只给3件事',
    version: '工作版',
    categoryPath: '工作/时间管理/焦点',
    mode: 'quick',
    operationalDefinition: '把注意力当资源，今天只选择 3 件最重要的事并给出时间块。',
    successCriteria: '选出3件事；安排时间块；完成≥2件并复盘。',
    actionChecklist: [
      '列 6 件待办',
      '只选 3 件（最重要）',
      '给每件事分配时间块（起止）',
      '执行第1块时关闭干扰',
      '复盘：我把注意力给了哪里？',
    ],
    refSegmentKeys: ['L6#14'],
    learningTags: ['时间管理', '专注'],
    changePath: '过滤器决定你看到什么、做什么。',
  ),
  BeliefActionTemplate(
    id: 't_c6c_reframe_signal',
    conceptId: 'c6c_focus_filter',
    title: '把焦虑当信号：立刻切回下一步',
    version: '情绪版',
    categoryPath: '日常生活/情绪/下一步',
    mode: 'quick',
    operationalDefinition: '当焦虑出现时，不解释它，而把它当“切回下一步行动”的信号。',
    successCriteria: '识别1次焦虑；执行1次下一步（≤5分钟）；焦虑下降≥1分。',
    actionChecklist: [
      '标注：我现在焦虑（0–10）',
      '问：下一步最小动作是什么？',
      '做 5 分钟',
      '记录：证据是什么？',
      '再评焦虑（0–10）',
    ],
    refSegmentKeys: ['L7#1'],
    learningTags: ['情绪', '行动'],
    changePath: '用行动替代反刍。',
  ),

  // c8b 乐观定义：短期上场+长期复盘
  BeliefActionTemplate(
    id: 't_c8b_short_long',
    conceptId: 'c8b_define_optimism',
    title: '短期上场 + 长期复盘',
    version: '基础版',
    categoryPath: '日常生活/乐观/复盘',
    mode: 'planned',
    operationalDefinition: '白天必须上场做最小行动；晚上用解释风格复盘并微调。',
    successCriteria: '连续3天完成；每晚输出1条更真实解释+1个微调行动。',
    actionChecklist: [
      '白天：选1个最小行动（≤10分钟）',
      '执行并记录证据',
      '晚上：写负面解释原句',
      '改写为暂时+特定（含原因/下一步）',
      '写明天一个微调动作',
    ],
    refSegmentKeys: ['L6#17', 'L7#5'],
    learningTags: ['复盘', '解释风格'],
    changePath: '乐观是训练出来的执行策略。',
  ),
  BeliefActionTemplate(
    id: 't_c8b_woop',
    conceptId: 'c8b_define_optimism',
    title: 'WOOP：愿望-结果-障碍-计划',
    version: '工具版',
    categoryPath: '工作/目标/WOOP',
    mode: 'planned',
    operationalDefinition: '把乐观与现实结合：既看见结果，也正视障碍并写If-Then计划。',
    successCriteria: '输出 WOOP；写 2 条 If-Then；执行 1 个行动。',
    actionChecklist: [
      'W：愿望（具体）',
      'O：最好的结果（可视化）',
      'O：最大障碍（现实）',
      'P：If-Then 计划（2条）',
      '立刻做最小行动（10分钟）',
    ],
    refSegmentKeys: ['L6#17'],
    learningTags: ['计划', '目标'],
    changePath: '现实乐观=想象+障碍+计划。',
  ),
  BeliefActionTemplate(
    id: 't_c8b_worst_best_likely',
    conceptId: 'c8b_define_optimism',
    title: '最坏/最好/最可能：降低灾难化',
    version: '认知版',
    categoryPath: '日常生活/焦虑/现实评估',
    mode: 'quick',
    operationalDefinition: '用三栏把灾难化拉回现实，并写一个下一步行动。',
    successCriteria: '完成三栏；最可能方案更具体；输出1个下一步。',
    actionChecklist: [
      '写最坏（不逃避）',
      '写最好（允许希望）',
      '写最可能（基于证据）',
      '写一个下一步（≤10分钟）',
      '复盘：我更能行动了吗？',
    ],
    refSegmentKeys: ['L7#5'],
    learningTags: ['现实评估', '焦虑'],
    changePath: '把想象变成可行动的概率评估。',
  ),

  // c11 幸福基线：反适应与品味
  BeliefActionTemplate(
    id: 't_c11_savoring',
    conceptId: 'c11_happiness_baseline',
    title: '30秒品味：放大一个小幸福',
    version: '基础版',
    categoryPath: '日常生活/幸福/品味',
    mode: 'planned',
    operationalDefinition: '每天挑一个小体验，放慢30秒并记录感官细节。',
    successCriteria: '7天≥5天完成；每次记录≥3个细节；幸福感自评提升。',
    actionChecklist: [
      '选一个小体验（喝水/阳光/饭菜）',
      '放慢 30 秒，注意 3 个感官细节',
      '写下细节（文字）',
      '写一句感谢（具体事实）',
      '自评幸福感（0–10）',
    ],
    refSegmentKeys: ['L6#26'],
    learningTags: ['正念', '感恩'],
    changePath: '幸福不是刺激，而是体验能力。',
  ),
  BeliefActionTemplate(
    id: 't_c11_dehabit',
    conceptId: 'c11_happiness_baseline',
    title: '反适应：刻意打破一个小习惯',
    version: '进阶版',
    categoryPath: '日常生活/幸福/新鲜化',
    mode: 'planned',
    operationalDefinition: '每天改变一个小惯性，避免对生活麻木。',
    successCriteria: '7天≥5天完成；记录变化后的体验；基线回拉。',
    actionChecklist: [
      '选一个小惯性（路线/座位/顺序）',
      '今天刻意改变一次',
      '记录：体验有什么不同？',
      '写一句感恩（事实）',
      '第7天回看：幸福感变化',
    ],
    refSegmentKeys: ['L6#27'],
    learningTags: ['新鲜化'],
    changePath: '不让幸福被适应偷走。',
  ),
  BeliefActionTemplate(
    id: 't_c11_help_others',
    conceptId: 'c11_happiness_baseline',
    title: '助人一件事：用意义提升基线',
    version: '社会版',
    categoryPath: '人际关系/幸福/助人',
    mode: 'quick',
    operationalDefinition: '做一件具体的助人行为，并记录对双方的影响。',
    successCriteria: '完成一次助人；记录证据；自评幸福提升≥1分。',
    actionChecklist: [
      '选一个具体助人行为（≤15分钟）',
      '执行（不求回报）',
      '记录对方反应/事实结果',
      '记录自己感受变化（0–10）',
      '写一句意义：我为什么愿意这样做？',
    ],
    refSegmentKeys: ['L6#26', 'L6#27'],
    learningTags: ['意义', '社会连接'],
    changePath: '幸福基线与意义/连接相关。',
  ),

  // c12 应对 vs 逃避：把逃避改成最小应对
  BeliefActionTemplate(
    id: 't_c12_label_and_switch',
    conceptId: 'c12_coping_vs_avoid',
    title: '标注逃避→切换最小应对',
    version: '基础版',
    categoryPath: '日常生活/压力/应对',
    mode: 'planned',
    operationalDefinition: '每天把一个行为标注为逃避或应对，并把逃避改成最小应对动作。',
    successCriteria: '7天≥5天完成；逃避减少；问题推进至少1步。',
    actionChecklist: [
      '识别触发情绪（0–10）',
      '命名：我在逃避什么？',
      '写最小应对动作（≤5分钟）',
      '立刻做',
      '记录：情绪/问题是否变化？',
    ],
    refSegmentKeys: ['L6#28', 'L7#2', 'L7#3'],
    learningTags: ['压力', '行为替代'],
    changePath: '应对=推进问题；逃避=短期止痛。',
  ),
  BeliefActionTemplate(
    id: 't_c12_exposure_step',
    conceptId: 'c12_coping_vs_avoid',
    title: '情绪暴露阶梯：从小到大面对',
    version: '进阶版',
    categoryPath: '日常生活/恐惧/暴露',
    mode: 'planned',
    operationalDefinition: '把害怕的情境拆成阶梯，从最小暴露开始，避免用逃避强化恐惧。',
    successCriteria: '写3阶梯；完成第1阶；恐惧下降≥1分。',
    actionChecklist: [
      '写害怕情境（例：打电话/发消息）',
      '拆 3 阶梯（从最小开始）',
      '完成第1阶（≤5分钟）',
      '记录恐惧（0–10）前后变化',
      '写下一阶的最小动作',
    ],
    refSegmentKeys: ['L7#4', 'L7#3'],
    learningTags: ['暴露', '行为主义'],
    changePath: '用暴露替代逃避，恐惧会下降。',
  ),
  BeliefActionTemplate(
    id: 't_c12_help_seeking',
    conceptId: 'c12_coping_vs_avoid',
    title: '求助脚本：把“难受”转成请求',
    version: '人际版',
    categoryPath: '人际关系/求助/脚本',
    mode: 'quick',
    operationalDefinition: '把情绪与问题写成一个清晰请求，向可信的人求助。',
    successCriteria: '完成一次求助；得到明确答复；问题推进1步。',
    actionChecklist: [
      '写事实：发生了什么',
      '写感受：我现在是什么情绪',
      '写需求：我需要什么支持',
      '写请求：你能否……（具体）',
      '记录答复与下一步',
    ],
    refSegmentKeys: ['L7#2', 'L7#3'],
    learningTags: ['沟通', '社会支持'],
    changePath: '求助是应对，不是软弱。',
  ),

  // c10a 行动掌控：用可控证据修复无力感
  BeliefActionTemplate(
    id: 't_c10a_control_one',
    conceptId: 'c10a_action_mastery',
    title: '每日可控一件事（7天）',
    version: '基础版',
    categoryPath: '日常生活/行动/掌控',
    mode: 'planned',
    operationalDefinition: '每天完成一个可控小动作，用证据积累掌控感。',
    successCriteria: '7天≥5天完成；每次有证据；无力感下降。',
    actionChecklist: [
      '列 3 个可控小动作',
      '每天选 1 个（≤10分钟）',
      '完成即记录证据',
      '失败→拆更小',
      '第7天复盘：掌控感变化（0–5）',
    ],
    refSegmentKeys: ['L7#7', 'L7#8', 'L7#10'],
    learningTags: ['掌控感', '证据'],
    changePath: '掌控感=可验证的完成。',
  ),
  BeliefActionTemplate(
    id: 't_c10a_evidence_wall',
    conceptId: 'c10a_action_mastery',
    title: '证据墙：把做成的事可视化',
    version: '进阶版',
    categoryPath: '日常生活/行动/证据墙',
    mode: 'quick',
    operationalDefinition: '把“我做成了什么”变成可见材料，强化持续行动。',
    successCriteria: '建立证据墙；放入 ≥3 条证据；每天补 1 条。',
    actionChecklist: [
      '选择载体（便签/相册/Notion）',
      '写 3 条已完成证据（事实）',
      '给每条证据标一个关键词（努力/坚持/学习）',
      '每天补 1 条',
      '每周复盘：我更相信什么？',
    ],
    refSegmentKeys: ['L7#7', 'L7#8'],
    learningTags: ['强化', '自我效能'],
    changePath: '让证据变得看得见。',
  ),
  BeliefActionTemplate(
    id: 't_c10a_failure_variable',
    conceptId: 'c10a_action_mastery',
    title: '失败变量改动：下次只改一个点',
    version: '失败学习版',
    categoryPath: '工作/复盘/变量',
    mode: 'quick',
    operationalDefinition: '当行动失败时，只改一个变量再试，避免陷入无力感。',
    successCriteria: '列出变量；选择1个改动；执行下一轮并记录。',
    actionChecklist: [
      '写失败事实',
      '列 3 个变量（环境/动作/频率）',
      '只选 1 个改动（更小/更具体/更频繁）',
      '执行下一轮（≤10分钟）',
      '记录：结果变化了吗？',
    ],
    refSegmentKeys: ['L6#24', 'L7#10'],
    learningTags: ['复盘', '迭代'],
    changePath: '用迭代替代自责。',
  ),

  // c10b 可视化：预演+执行
  BeliefActionTemplate(
    id: 't_c10b_process_visual',
    conceptId: 'c10b_visualization',
    title: '过程可视化：先跑通再开做',
    version: '基础版',
    categoryPath: '日常生活/可视化/过程',
    mode: 'planned',
    operationalDefinition: '每天 2 分钟在脑内跑通过程步骤，然后立刻做 10 分钟最小行动。',
    successCriteria: '7天≥5天完成；每次有证据；拖延下降。',
    actionChecklist: [
      '写目标（具体）',
      '2分钟：想象过程步骤（从第一步到结束）',
      '30秒：想象一个障碍',
      '30秒：想象应对动作',
      '10分钟：最小行动并记录证据',
    ],
    refSegmentKeys: ['L7#11', 'L7#12', 'L7#13'],
    learningTags: ['预演', '执行'],
    changePath: '可视化必须接到行动。',
  ),
  BeliefActionTemplate(
    id: 't_c10b_backwards',
    conceptId: 'c10b_visualization',
    title: '逆向可视化：从结果倒推步骤',
    version: '计划版',
    categoryPath: '工作/计划/逆向',
    mode: 'planned',
    operationalDefinition: '从目标结果倒推 5 个步骤，并为第一步设置开始线索。',
    successCriteria: '写清5步；第一步在24h执行；记录证据。',
    actionChecklist: [
      '写目标结果（可验证）',
      '倒推 5 步（越具体越好）',
      '选择第1步（最小）',
      '设置开始线索（时间/地点/物品）',
      '执行并记录证据',
    ],
    refSegmentKeys: ['L7#14', 'L7#15'],
    learningTags: ['计划', '启动线索'],
    changePath: '把未来变成可走的台阶。',
  ),
  BeliefActionTemplate(
    id: 't_c10b_pressure_rehearsal',
    conceptId: 'c10b_visualization',
    title: '压力预演：在脑内经历一次困难',
    version: '抗压版',
    categoryPath: '学校/考试/可视化',
    mode: 'quick',
    operationalDefinition: '预演一次“最难时刻”，并写出应对脚本，减少临场崩溃。',
    successCriteria: '写应对脚本；现场使用一次；紧张下降≥1分。',
    actionChecklist: [
      '选一个压力情境（面试/考试/谈判）',
      '想象最难时刻（30秒）',
      '写应对脚本（我将怎么做/怎么说）',
      '写一个最小动作（准备/练习5分钟）',
      '记录：紧张变化（0–10）',
    ],
    refSegmentKeys: ['L7#16', 'L7#12'],
    learningTags: ['抗压', '脚本'],
    changePath: '预演困难，现实就更稳。',
  ),

  // c10c CBT-3Ms：认知纠偏
  BeliefActionTemplate(
    id: 't_c10c_3ms_card',
    conceptId: 'c10c_cbt_3ms',
    title: '3Ms 一张卡：缩放比例回到现实',
    version: '基础版',
    categoryPath: '日常生活/认知疗法/3Ms',
    mode: 'quick',
    operationalDefinition: '对一个情绪事件做 3Ms：Minimize/Maximize/Many，并写一个下一步行动。',
    successCriteria: '完成 1 次 3Ms；输出 1 个下一步；情绪下降≥1分。',
    actionChecklist: [
      '写事件（事实）',
      'Minimize：我在夸大什么？',
      'Maximize：我在忽略什么？',
      'Many：还有哪些事实/可能性？',
      '写一个下一步最小行动（≤10分钟）',
    ],
    refSegmentKeys: ['L7#17', 'L7#18'],
    learningTags: ['认知纠偏', '行为实验'],
    changePath: '把“剪辑”拉回真实比例。',
  ),
  BeliefActionTemplate(
    id: 't_c10c_scale_meter',
    conceptId: 'c10c_cbt_3ms',
    title: '尺度计：这件事在一年后有多大？',
    version: '进阶版',
    categoryPath: '日常生活/焦虑/尺度',
    mode: 'quick',
    operationalDefinition: '用时间尺度把灾难化降低，并找到一个可控行动。',
    successCriteria: '完成尺度评估；写1个可控行动；焦虑下降≥1分。',
    actionChecklist: [
      '写事件（事实）',
      '1天后影响？1周后？1年后？',
      '我能控制的 1 个点是什么？',
      '写最小行动（≤10分钟）',
      '记录：焦虑（0–10）前后变化',
    ],
    refSegmentKeys: ['L7#17'],
    learningTags: ['尺度', '焦虑'],
    changePath: '时间尺度=认知缩放器。',
  ),
  BeliefActionTemplate(
    id: 't_c10c_many_facts',
    conceptId: 'c10c_cbt_3ms',
    title: 'Many：列出 5 条事实反平衡',
    version: '训练版',
    categoryPath: '日常生活/认知/事实',
    mode: 'planned',
    operationalDefinition: '每天列 5 条事实，把注意力从单点灾难拉到整体现实。',
    successCriteria: '连续 3 天完成；每次≥5条事实；情绪更稳定。',
    actionChecklist: [
      '写今天的一个负面点（事实）',
      '列出 5 条更大事实（支持/资源/可改变量）',
      '写 1 条替代想法（更真实）',
      '写 1 个下一步行动',
      '记录执行证据',
    ],
    refSegmentKeys: ['L7#18'],
    learningTags: ['训练', '事实'],
    changePath: '用“多事实”纠偏单点放大。',
  ),

];

