import 'meditation_models.dart';

class MeditationSeedData {
  static const List<String> stateOptions = [
    '心很乱',
    '被外界影响',
    '焦虑紧张',
    '疲惫无力',
    '想专注',
    '睡前放松',
    '日常练习',
    '被羞辱后反刍',
    '自责羞耻',
    '行动卡住',
    '身体紧绷',
    '需要定力',
    '价值感受挫',
    '早晨起不来',
    '面试或上班前想逃',
    '得到机会后犹豫',
    '害怕新工作不适应',
    '完美主义卡住',
    '害怕进入不舒服',
    '决策瘫痪',
    '因失业怕被看见',
    '害怕别人评价',
    '错失机会后悔',
    '经济压力很大',
    '感到孤独或思念',
    '冲动很强',
    '学了很多却做不到',
  ];

  static const List<MeditationSessionTemplate> sessions = [
    MeditationSessionTemplate(
      key: 'breath_anchor_3m',
      title: '3分钟回到呼吸',
      type: '呼吸稳定',
      category: '新手入门',
      description: '用最短时间把注意力带回身体和呼吸。',
      durationSeconds: 180,
      steps: [
        MeditationStep(startSecond: 0, text: '现在给自己三分钟。坐稳，让背部和双脚有支撑；眼睛可以闭上，也可以柔和地看着前方。', intent: 'arrival'),
        MeditationStep(startSecond: 22, text: '自然吸气，知道气息正在进入；慢慢呼气。再来一次，不需要吸得很用力。', intent: 'breath'),
        MeditationStep(startSecond: 45, text: '留意此刻身体最明显的一处，也许胸口紧、肩膀沉，或只是有些乱。先只感觉这一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 68, text: '允许这个感觉暂时存在。念头若出现，不必赶走；发现自己走神，就已经有了回来的入口。', intent: 'allow_experience'),
        MeditationStep(startSecond: 92, text: '把注意力放在鼻尖、胸口或腹部的起伏，只选一个。感受自己可以从念头回到一个真实触点。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 116, text: '想象稍后再次心乱时，你停一下，摸到脚底，完成一轮呼吸，再看眼前要做的事。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 140, text: '如果不用消灭所有念头，只需回来一次，此刻会轻一点吗？记住你选择的那个呼吸触点。', intent: 'integration'),
        MeditationStep(startSecond: 162, text: '最后缓慢呼气，感受身体被支撑。睁开眼，看见周围，让注意力跟你一起回到现在。', intent: 'closing'),
      ],
      endingReflection: '你不是失败于分心，而是在每一次回来中训练自己。',
    ),
    MeditationSessionTemplate(
      key: 'rumination_stop_5m',
      title: '5分钟反刍中断',
      type: '反刍中断',
      category: '反刍中断',
      description: '当脑中反复争辩、回想、内耗时，先把注意力交还给自己。',
      durationSeconds: 300,
      steps: [
        MeditationStep(startSecond: 0, text: '现在先暂停那场脑内对话。坐稳，让脚、腿和背部得到支撑；这五分钟不要求把事情彻底想明白。', intent: 'arrival'),
        MeditationStep(startSecond: 35, text: '自然吸气，缓慢呼气。再来一次。画面或对话若重播，只标记“反刍来了”，然后回到呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 72, text: '反复思考时，身体哪里最累？也许头胀、胸口紧、下巴用力。选一处，感受它正在承受什么。', intent: 'body_emotion'),
        MeditationStep(startSecond: 108, text: '允许不甘、愤怒或担心在这里。允许感受，不等于继续喂养故事，也不等于立刻采取冲动行为。', intent: 'allow_experience'),
        MeditationStep(startSecond: 145, text: '呼气时松开一点下巴和手掌。你不需要在脑中赢回那件事，才能把此刻的注意力带回自己。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 185, text: '想象今天又出现那个触发：你发现回放，脚底落地，完成一轮呼吸，再把手放回正在做的任务。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 228, text: '如果那件事可以暂存十分钟，你想把这十分钟还给什么？只选一件很小、能在现实里完成的事。', intent: 'integration'),
        MeditationStep(startSecond: 270, text: '最后缓慢呼气，睁眼看见周围。念头可能还在，而你的注意力和下一步已经回到自己手里。', intent: 'closing'),
      ],
      endingReflection: '你已经看见自己被念头带走，也正在把注意力交还给自己。',
    ),
    MeditationSessionTemplate(
      key: 'emotion_untangle_5m',
      title: '5分钟情绪脱钩',
      type: '情绪脱钩',
      category: '情绪脱钩',
      description: '愤怒、羞耻、焦虑出现时，练习感受它，但不立刻服从它。',
      durationSeconds: 300,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入一次情绪脱钩练习。坐稳，让身体有支撑；闭眼或保留视线都可以，先不用处理情绪背后的全部故事。', intent: 'arrival'),
        MeditationStep(startSecond: 35, text: '自然吸气，慢慢呼气。再来一轮。思绪若开始解释和争辩，只把注意力送回呼气。', intent: 'breath'),
        MeditationStep(startSecond: 72, text: '情绪现在最明显地落在哪里？胸口、喉咙、腹部或肩膀？它是紧、热、酸、沉，还是快？', intent: 'body_emotion'),
        MeditationStep(startSecond: 108, text: '允许这股情绪存在和变化。允许感受，不等于让它命令全部行为；你正在为反应之前留出空间。', intent: 'allow_experience'),
        MeditationStep(startSecond: 145, text: '每次呼气，都让身体多一点位置。感受“情绪正在发生”和“我整个人就是情绪”之间出现一点距离。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 185, text: '想象稍后在一句话或一个画面中被触发：你先停住手，呼气，命名身体感觉，再决定是否回应。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 228, text: '如果情绪可以被听见，却不用立刻服从，你希望下一步更接近什么：保护边界、离开现场，还是继续手边的事？', intent: 'integration'),
        MeditationStep(startSecond: 270, text: '最后缓慢呼气，睁眼看向周围。把情绪带在身边，也把选择权带回接下来的行动。', intent: 'closing'),
      ],
      endingReflection: '情绪可以出现，但你不需要把整个人都交给情绪。',
    ),
    MeditationSessionTemplate(
      key: 'focus_return_5m',
      title: '5分钟专注回收',
      type: '专注回收',
      category: '专注回收',
      description: '学习或工作前，把散乱的注意力收回来。',
      durationSeconds: 300,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“只做眼前一件事”。坐稳，把手机和无关页面放远，让双脚和背部有清楚支撑。', intent: 'arrival'),
        MeditationStep(startSecond: 35, text: '注意一轮呼吸的开始、中间和结束。再来一轮。分心出现时不责备，只说“分心了”，然后回来。', intent: 'breath'),
        MeditationStep(startSecond: 72, text: '想到要开始的任务，身体是什么感觉？也许躁、沉、抗拒或疲惫。选一种，看看它落在哪里。', intent: 'body_emotion'),
        MeditationStep(startSecond: 108, text: '允许不想做和想逃开的感觉先存在。允许感受，不等于打开新的干扰；你仍能把手留在选择的位置。', intent: 'allow_experience'),
        MeditationStep(startSecond: 145, text: '吸气，知道自己在这里；呼气，把注意力从“整件事有多难”收回到第一个可见动作。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 185, text: '想象练习结束后的画面：打开唯一需要的页面，写第一行、看第一题或处理第一项，其他窗口保持关闭。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 228, text: '如果开始不必完美，下一步究竟是哪一下？把动作、页面和起点在心里说清楚。', intent: 'integration'),
        MeditationStep(startSecond: 270, text: '最后缓慢呼气，睁眼看向眼前任务。把手放到起点，只做刚才选定的那一件事。', intent: 'closing'),
      ],
      endingReflection: '专注不是没有分心，而是分心后知道如何回来。',
    ),
    MeditationSessionTemplate(
      key: 'body_scan_10m',
      title: '10分钟身体扫描',
      type: '身体扫描',
      category: '身体扫描',
      description: '从头到脚扫描身体，让紧绷慢慢被看见。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入一次从头到脚的身体扫描。找一个有支撑的姿势，衣物和姿势尽量舒服；眼睛可以闭上，也可以柔和地睁着。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '自然吸气，感觉身体微微扩展；缓慢呼气。再来一轮。思绪若跑远，只把它送回呼吸和支撑面。', intent: 'breath'),
        MeditationStep(startSecond: 115, text: '先问问自己此刻怎样。也许疲惫、紧张或麻木。感受头顶、额头、眼周、脸颊和下巴，只观察最明显的一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 180, text: '允许紧绷或没有感觉都存在。扫描不是考试，也不要求身体立刻放松；你只是重新听见它。', intent: 'allow_experience'),
        MeditationStep(startSecond: 250, text: '把注意力移到肩膀、手臂和手掌，再到胸口与背部。感受重量、温度和呼吸起伏，让身体不必继续表演坚强。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 330, text: '继续来到腹部、腰、骨盆、大腿、小腿、脚踝和脚底。每到一处，只感受接触和重量，不寻找标准答案。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 420, text: '想象下一次工作或思考得太久时，你停三十秒，从肩膀、手掌到脚底扫一遍，再调整姿势和任务。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 510, text: '如果身体不是拖累，而是会给你疲惫、紧绷和需要休息的信号，你愿意先回应哪一个信号？', intent: 'integration'),
        MeditationStep(startSecond: 570, text: '最后感受整个身体一起呼吸。缓慢睁开眼，看看周围；带着对身体多一点听见，回到接下来的生活。', intent: 'closing'),
      ],
      endingReflection: '你不是一台一直运转的机器，你也可以回到身体里休息。',
    ),
    MeditationSessionTemplate(
      key: 'sleep_release_10m',
      title: '停止反刍入睡',
      type: '睡前放松',
      category: '睡眠',
      description: '睡前不再继续喂养白天的念头，让身体进入夜晚。',
      durationSeconds: 600,
      isSleep: true,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入夜晚的休息。躺好或舒服地靠着，让床和枕头接住身体；如果安全舒适，可以轻轻闭眼。', intent: 'arrival'),
        MeditationStep(startSecond: 65, text: '自然吸气，呼气稍微长一点。再来一轮。白天的画面若出现，只说“我知道了”，再回来听见呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 130, text: '留意此刻最难放下的感觉，也许焦虑、遗憾、疲惫，或脑中仍很亮。找到身体最明显的一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 195, text: '允许事情还没有处理完，也允许心里暂时不安。允许这些存在，不等于今晚继续解决；休息也是现实需要。', intent: 'allow_experience'),
        MeditationStep(startSecond: 270, text: '从额头、眼睛、脸颊到下巴，慢慢松一点；再到肩膀、手臂和手掌。感受“不必再值班”落进身体。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 355, text: '想象明早醒来，未完成的事仍在一个可处理的位置。今晚的你把手机放下、灯光调暗，让腹部、腿和脚安静下来。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 450, text: '如果今晚不用靠继续思考来保护明天，你愿意把哪件事交给醒来后的自己？现在只保留休息这一件事。', intent: 'integration'),
        MeditationStep(startSecond: 540, text: '最后听几次自然呼吸。无需睁眼，也无需等待一句结束；让声音渐渐退远，身体可以继续休息或进入睡眠。', intent: 'closing'),
      ],
      endingReflection: '今天已经到这里。剩下的事，可以交给明天的你。',
    ),
    MeditationSessionTemplate(
      key: 'self_acceptance_6m',
      title: '6分钟自我接纳',
      type: '自我接纳',
      category: '自我接纳',
      description: '失败、自责、羞耻之后，先停止继续攻击自己。',
      durationSeconds: 360,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入一次不再继续攻击自己的练习。坐稳，把一只手轻放在胸口或腹部，感受身体的温度和支撑。', intent: 'arrival'),
        MeditationStep(startSecond: 42, text: '自然吸气，知道身体还在这里；缓慢呼气。再来一轮。批评的声音若出现，只带回手掌下的触感。', intent: 'breath'),
        MeditationStep(startSecond: 85, text: '此刻最明显的感受是什么？也许羞耻、失望、难过或害怕。它在胸口、脸上还是胃里？只选一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 128, text: '允许难受先存在。允许感受，不等于否认错误；你可以承担具体后果，而不把整个人判成没有价值。', intent: 'allow_experience'),
        MeditationStep(startSecond: 175, text: '感受手掌的温度。把“我做错了一件事”和“我整个人都是错的”分开，看看身体是否多出一点呼吸空间。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 225, text: '想象今天再次想起失败：你先摸到胸口，承认发生过什么，然后写下一个补救动作，而不是继续辱骂自己。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 275, text: '如果温和并不会取消责任，什么行动既照顾自己、又面对现实？把它缩小成今天能够完成的一步。', intent: 'integration'),
        MeditationStep(startSecond: 325, text: '最后缓慢呼气，睁眼看见周围。带着真实的责任，也带着仍可重新开始的自己，回到那一步。', intent: 'closing'),
      ],
      endingReflection: '接纳不是放弃改变，而是停止在改变之前先摧毁自己。',
    ),

    MeditationSessionTemplate(
      key: 'attention_sovereignty_8m',
      title: '8分钟注意力主权恢复',
      type: '注意力主权',
      category: '个性化恢复',
      description: '被外界刺激、羞辱或捉弄后，把注意力从对方那里收回来。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“把注意力收回来”的练习。坐稳，让背部和双脚有支撑；暂时不用证明什么，也不用在脑中反击。', intent: 'arrival'),
        MeditationStep(startSecond: 35, text: '自然吸气，缓慢呼气。再来一次。对方的表情或话语若出现，只标记“回放来了”，然后回到呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 75, text: '被影响时，身体哪里最明显？也许脸热、胸口紧、腿僵，或心跳加快。选一处，承认自己确实被触发了。', intent: 'body_emotion'),
        MeditationStep(startSecond: 120, text: '允许委屈、愤怒或想赢回来的冲动存在。允许感受，不等于立刻反击，也不等于把余下时间继续交给对方。', intent: 'allow_experience'),
        MeditationStep(startSecond: 165, text: '感受脚底、手掌或腹部的起伏。对方的刺激在记忆里，而你的身体在这里；注意力可以一小部分一小部分回来。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 210, text: '在心里说：我看见这个刺激，也看见自己仍有方向。让脊背得到支撑，体验“不跟随”并不是软弱。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 260, text: '想象今天再次听见恶意评价：你注意到脸热，呼气，离开争辩，把手放回求职、工作或眼前任务。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 315, text: '对方的声音也许还在脑中，你却不再用整天为它提供回音。看见自己连续完成眼前十分钟。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 370, text: '如果主动权不是让对方消失，而是决定注意力接下来服务什么，你愿意把它交给哪一件小事？', intent: 'integration'),
        MeditationStep(startSecond: 430, text: '最后缓慢呼气，睁眼看见周围。把注意力放到那件小事的起点，带着自己的节奏回去。', intent: 'closing'),
      ],
      endingReflection: '你把注意力从外界刺激中收回了一次，这就是重新掌握自己的开始。',
    ),
    MeditationSessionTemplate(
      key: 'shame_self_blame_release_9m',
      title: '9分钟羞耻与自责松绑',
      type: '自责松绑',
      category: '自我接纳',
      description: '当内疚、自责、羞耻开始攻击自己时，练习负责但不自毁。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“负责，但不摧毁自己”的练习。坐稳，一只手放在胸口或腹部，让身体先知道此刻不是审判席。', intent: 'arrival'),
        MeditationStep(startSecond: 40, text: '自然吸气，感觉手掌的温度；缓慢呼气。再来一次。批判声若出现，只把注意力送回这个触点。', intent: 'breath'),
        MeditationStep(startSecond: 85, text: '自责出现时，你现在是什么感觉？也许胸口沉、脸上热、胃里缩，心里只剩“我不好”。选一处感受。', intent: 'body_emotion'),
        MeditationStep(startSecond: 130, text: '允许羞耻和内疚存在。允许它们，不等于逃避错误；也不需要把一次行为扩大成对整个人的最终判决。', intent: 'allow_experience'),
        MeditationStep(startSecond: 180, text: '呼气时，对身体少一点用力。感受“我没有做好”与“我整个人都是失败”之间出现一道界线。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 235, text: '把手掌轻轻压向身体，体验一种更有力量的责任：承认事实、修补能修补的部分，同时停止继续伤害自己。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 295, text: '想象下一次错过约定或做错事情：你先承认后果，写下断点，联系相关的人或安排补救，而不是躲起来辱骂自己。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 355, text: '批判声再次说“你没用”时，你回答：“我听见了，现在处理具体行为。”看见身体转向那件可修补的事。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 420, text: '如果恢复力量比证明自己有多坏更能承担责任，接下来哪个行动既诚实、又不继续伤害自己？', intent: 'integration'),
        MeditationStep(startSecond: 490, text: '最后缓慢呼气，睁眼看见现在。带着手掌的温度和清楚的责任，去完成那个补救动作。', intent: 'closing'),
      ],
      endingReflection: '接纳不是逃避责任，而是让你不用通过摧毁自己来证明自己有责任感。',
    ),
    MeditationSessionTemplate(
      key: 'dignity_softening_10m',
      title: '10分钟体面防御安放',
      type: '体面安放',
      category: '个性化恢复',
      description: '当强烈体面感让你必须独自硬撑时，练习把尊严从防御中放松出来。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“尊严不必等于独自硬撑”的练习。坐着，让背部被支撑，双脚落地；此刻不用表现坚强。', intent: 'arrival'),
        MeditationStep(startSecond: 45, text: '自然吸气，感受胸口；缓慢呼气，让肩膀放下一点重量。再来一次，走神时轻轻回来。', intent: 'breath'),
        MeditationStep(startSecond: 105, text: '想到求人、暴露困难或被人看见时，身体哪里最抗拒？也许胸口顶住、喉咙紧，或脸上发热。', intent: 'body_emotion'),
        MeditationStep(startSecond: 165, text: '允许戒备、怕丢脸和想独自解决的冲动存在。它们曾保护尊严，但此刻不必自动拒绝每一种帮助。', intent: 'allow_experience'),
        MeditationStep(startSecond: 230, text: '把重量交给椅背。体验一个新的区别：接受合适帮助，不会拿走尊严；照顾自己的限度，也可以是尊严的一部分。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 300, text: '对身体说：“我不是放弃体面，只是不再一直战斗。”看看肩膀、胸口和呼吸是否愿意松开一点。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 370, text: '想象现实中的一幕：住宿、工作或钱的压力超出承受，你向可信的人说明一个具体困难，只请求一项边界清楚的帮助。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 440, text: '再看见自己仍保留选择：可以问清条件、拒绝不合适的要求，也可以接受真正减少风险的支持。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 510, text: '如果不再用紧绷证明自尊，今天哪一个真实选择能减轻负担，同时保留边界和自主？', intent: 'integration'),
        MeditationStep(startSecond: 565, text: '最后缓慢呼气，睁眼看见周围。让背部记住被支撑的感觉，带着尊严去做那个小选择。', intent: 'closing'),
      ],
      endingReflection: '你不是放弃尊严，而是在把尊严从孤立硬撑中慢慢解放出来。',
    ),
    MeditationSessionTemplate(
      key: 'body_home_after_pain_8m',
      title: '8分钟痛苦承受后的身体回家',
      type: '身体回家',
      category: '身体扫描',
      description: '经历疼痛、疲惫或长期紧绷后，让身体知道现在可以慢慢恢复。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“让身体回到现在”的练习。选择相对舒服、有支撑的姿势；眼睛可以睁着，不要求自己一定放松。', intent: 'arrival'),
        MeditationStep(startSecond: 35, text: '自然吸气，不追求很深；缓慢呼气。再来一轮。思绪若跑向过去的疼痛，只把它带回支撑面。', intent: 'breath'),
        MeditationStep(startSecond: 85, text: '身体现在哪里最需要被听见？也许紧、酸、沉、热、麻，或带着疲惫与害怕。只选择一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 135, text: '允许不舒服存在，也允许暂时没有变化。允许感受，不等于忽视需要处理的健康问题；此刻只停止与身体对抗。', intent: 'allow_experience'),
        MeditationStep(startSecond: 190, text: '感受脚底、腿部、腹部和腰部。每到一处，只确认身体仍在支撑你，让呼气传递“这一刻不用继续备战”。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 245, text: '继续来到胸口、肩膀、背部、脸和额头。轻轻命名感觉，再回到呼吸；身体不是敌人，它在提供信号。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 305, text: '想象下一次疼痛或疲惫让你紧张：你先坐稳，检查安全，调整姿势，喝水或休息；需要时寻求现实医疗支持。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 365, text: '如果身体不只是一处痛苦现场，也是一路陪你活到现在的伙伴，你愿意先回应它哪一个具体需要？', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '最后感受整个身体一起呼吸，缓慢睁眼看见周围。带着更诚实的身体感受回到接下来的生活。', intent: 'closing'),
      ],
      endingReflection: '你的身体不只是痛苦的现场，也是你一步步恢复的地方。',
    ),
    MeditationSessionTemplate(
      key: 'action_start_stability_9m',
      title: '9分钟行动启动前稳定',
      type: '行动启动',
      category: '专注回收',
      description: '当任务堆积、拖延、内耗时，先稳定身体，再启动一个最小行动。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“先启动一个动作”的练习。坐稳，让脚底和座椅承托身体；所有任务暂时不必同时涌进来。', intent: 'arrival'),
        MeditationStep(startSecond: 40, text: '自然吸气，知道自己有压力；缓慢呼气。再来一次。思绪若在任务间奔跑，只把它带回身体。', intent: 'breath'),
        MeditationStep(startSecond: 85, text: '想到要开始时，身体是什么感觉？也许沉、乱、紧、疲惫，或只想躲开。找到最明显的一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 135, text: '允许“太多了、来不及了、我不想做”的声音存在。允许它们，不等于让今天停住；这只是压力正在说话。', intent: 'allow_experience'),
        MeditationStep(startSecond: 190, text: '把脚掌压向地面。你不需要先恢复全部力量；身体可以先做一个很小动作，再从动作里找回一点状态。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 250, text: '想象具体场景：打开求职页面、写第一行、整理一个文件，或穿鞋走到门口。画面里只保留这一步。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 315, text: '看见自己没有完美状态，手仍点击、书写或拿起物品。第一次动作完成后，再决定是否继续第二步。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 380, text: '继续呼气，让注意力从“整个人生怎么办”回到手、脚和眼前位置。此刻只需要一个开始信号。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 450, text: '如果力量可以在开始之后回来，而不必提前全部到场，练习结束后你先做什么？把它完整说出来。', intent: 'integration'),
        MeditationStep(startSecond: 505, text: '最后缓慢呼气，睁眼看向行动起点。带着不完美的状态，让手或脚完成刚才说出的第一下。', intent: 'closing'),
      ],
      endingReflection: '行动不需要等到完全有力量才开始；很多时候，力量是在开始之后慢慢回来。',
    ),
    MeditationSessionTemplate(
      key: 'scarcity_safety_rebuild_10m',
      title: '10分钟匮乏记忆安全感重建',
      type: '安全感重建',
      category: '个性化恢复',
      description: '当旧的匮乏、饥饿、无助感被激活时，练习把身体带回当下的安全。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '这次练习可以一直睁着眼。慢慢环顾周围，说出所在地点，找出三件真实物品，让眼睛确认：我在今天。', intent: 'arrival'),
        MeditationStep(startSecond: 50, text: '呼吸保持自然。吸气时看着一个物体，呼气时感受脚底；再重复一次。旧画面若来，就让视线回到房间。', intent: 'breath'),
        MeditationStep(startSecond: 110, text: '匮乏或无助被触发时，身体哪里先紧起来？也许胃里空、胸口缩，心里怕被抛下。只感受一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 175, text: '允许旧警报响起，也允许自己随时暂停。允许感受，不等于重新进入过去；眼睛仍看着当下真实存在的东西。', intent: 'allow_experience'),
        MeditationStep(startSecond: 245, text: '一只手放在胸口或腹部，脚底贴住地面。过去的危险信号值得理解，而此刻的事实也值得身体重新学习。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 315, text: '逐一确认现在的资源：可以喝的水、门锁、灯、手机、钱的实际数字，或一个可联系的人。安全来自具体事实。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 385, text: '想象最坏结果又在脑中展开：你先说日期和地点，摸到支撑物，再检查今天真正要处理的一项现实风险。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 455, text: '如果现在可以用信息、边界和求助保护自己，而不只靠独自硬撑，今天最需要补足的资源是什么？', intent: 'integration'),
        MeditationStep(startSecond: 530, text: '最后自然呼气，再看一遍三件物品。身体不必立刻忘记过去，只需确认此刻已经多了一种保护自己的方式。', intent: 'closing'),
      ],
      endingReflection: '曾经的匮乏说明你承受过很多；现在的练习，是让身体重新学习安全。',
    ),
    MeditationSessionTemplate(
      key: 'calm_mountain_8m',
      title: '8分钟清风拂山岗定力',
      type: '定力练习',
      category: '个性化恢复',
      description: '训练“不慌不忙、不被打乱节奏”的内在稳定。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入一次不被立刻带走的定力练习。坐稳，背部自然伸展，双脚落地；让身体像一处有根基的位置。', intent: 'arrival'),
        MeditationStep(startSecond: 35, text: '吸气时感受身体微微向上，呼气时感受重量向下。再来一次。走神了，就温和地回到脚底。', intent: 'breath'),
        MeditationStep(startSecond: 80, text: '想到外界的声音、评价或挑衅，身体怎样反应？也许胸口顶起、脸热、手想动。只观察最明显的一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 125, text: '允许被影响和想反击的冲动存在。允许感受，不是麻木或忍气吞声；你只是在行动之前保留自己的节奏。', intent: 'allow_experience'),
        MeditationStep(startSecond: 170, text: '把注意力放回脊背和脚底。外界像风一样经过，而身体仍有落点；体验“我知道发生了什么，也不必立刻移动”。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 225, text: '呼吸来，又走；念头也来，又走。让那句“清风拂过，根基仍在”成为身体感受，而不是强迫自己坚硬。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 285, text: '想象再次面对一句挑衅：你感觉脸热，脚底落地，先停一口气，再决定离开、设边界或平静回应。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 350, text: '如果定力是把反应推迟到自己重新拥有选择，今天哪一种场景最值得练习这一口停顿？', intent: 'integration'),
        MeditationStep(startSecond: 420, text: '最后缓慢呼气，睁眼看见周围。带着自己的速度回到今天：慢一点，稳一点，再做决定。', intent: 'closing'),
      ],
      endingReflection: '你练习的不是压抑反应，而是在反应之前保留自己的节奏。',
    ),
    MeditationSessionTemplate(
      key: 'self_worth_repair_11m',
      title: '11分钟价值感修复',
      type: '自尊修复',
      category: '自我接纳',
      description: '当长期挫败、能力受限或被现实卡住时，重新区分“受阻”与“无价值”。',
      durationSeconds: 660,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入一次不靠证明来恢复价值感的练习。坐稳，让背部和双脚有支撑；这几分钟不要求交出成绩单。', intent: 'arrival'),
        MeditationStep(startSecond: 50, text: '自然吸气，知道身体还在；缓慢呼气。再来一次。证明自己的压力若出现，只把注意力带回支撑。', intent: 'breath'),
        MeditationStep(startSecond: 115, text: '长期受阻、没有工作或机会失去时，身体哪里最痛？也许胸口沉、脸热、心里空，或只剩疲惫。', intent: 'body_emotion'),
        MeditationStep(startSecond: 185, text: '允许失望、羞耻和不甘存在。允许这些感受，不等于认定自己无能；道路受阻与整个人没有价值并不是同一件事。', intent: 'allow_experience'),
        MeditationStep(startSecond: 255, text: '把注意力放到双手。它们工作过、学习过、忍耐过、重新尝试过。感受这些真实经历仍留在身体里。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 330, text: '当“我不如别人、我浪费了时间”出现时，呼气，把它认作受挫后的自我否定；脊背仍被支撑，愿望也还在。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 405, text: '想象今天打开招聘页面，看见条件或失败记录。你注意到胸口发沉，却没有关闭页面，而是完成一份高匹配投递。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 480, text: '再看见自己完成一个真实行动后休息。一次结果没有给出全部价值，也没有拿走继续学习、工作和连接的能力。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 550, text: '如果价值感可以通过每天一个真实行动慢慢重建，而不等成功后才出现，今天哪一步最能支持你？', intent: 'integration'),
        MeditationStep(startSecond: 620, text: '最后缓慢吸气和呼气，睁眼看见周围。带着双手记得的能力，去完成那一个真实而可见的行动。', intent: 'closing'),
      ],
      endingReflection: '现实可能让一条路受阻，但它不能证明你整个人没有价值。',
    ),
    MeditationSessionTemplate(
      key: 'morning_leave_bed_7m',
      title: '7分钟从被窝到站起来',
      type: '起床启动',
      category: '行动与执行',
      description: '闹钟响后不再和“不想起”辩论，让身体先完成离床。',
      durationSeconds: 420,
      steps: [
        MeditationStep(startSecond: 0, text: '现在，让我们进入“从被窝回到今天”的几分钟。眼睛可以睁着，让后背感到床的支撑；先不用判断自己想不想起。', intent: 'arrival'),
        MeditationStep(startSecond: 45, text: '自然吸气，感觉腹部微微起伏；慢慢呼气。再来一次。思绪若跑到一整天的压力上，只把它带回这一口呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 95, text: '留意身体最不愿移动的地方，也留意那份抗拒、疲惫或害怕。它现在是什么感觉？沉、紧，还是只想缩回去？', intent: 'body_emotion'),
        MeditationStep(startSecond: 145, text: '允许“不想起”先在这里。允许这个感受，不等于今天继续交给它；你只是停止和它争吵，给身体留出一点选择。', intent: 'allow_experience'),
        MeditationStep(startSecond: 200, text: '轻轻动脚趾和脚踝，再把手掌压向床面。感受一个新的事实：动力还没有到齐，身体仍可以先移动一厘米。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 255, text: '想象闹钟刚响的真实早晨：手掌支撑，上身抬起，双脚碰到地面。地面也许凉、硬；你坐在那里，不必同时扛起整天。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 315, text: '如果允许自己不情愿、却仍完成第一个动作，会有什么不同？选一个看得见的下一步：站起、走到洗手间，或穿上衣服。', intent: 'integration'),
        MeditationStep(startSecond: 375, text: '再吸一口气，呼气时身体向前，脚底承重，慢慢站起。睁眼看清房间，让今天从这个真实的站立开始。', intent: 'closing'),
      ],
      endingReflection: '起床不是先获得意愿再行动；这一次，你让身体先替自己打开了路。',
    ),
    MeditationSessionTemplate(
      key: 'appointment_courage_8m',
      title: '8分钟面试与上班前赴约',
      type: '赴约行动',
      category: '行动与执行',
      description: '出发前很想逃时，把任务从“表现完美”还原为“准时到场”。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“先去到现场”的练习。坐直或站稳，让背部有支撑，双脚贴住地面；眼睛可以轻轻闭上，也可以看着前方。', intent: 'arrival'),
        MeditationStep(startSecond: 50, text: '自然吸气，再把呼气放慢一点。重复一次。若脑中已经开始预演失败，只说“我听见了”，然后回到脚底和呼气。', intent: 'breath'),
        MeditationStep(startSecond: 105, text: '现在留意胸口、腹部或喉咙。害怕也许是紧、热、发空。先只感受最明显的一处，不急着解释它。', intent: 'body_emotion'),
        MeditationStep(startSecond: 160, text: '允许紧张跟你待一会儿。允许害怕，不等于取消赴约；它说明这件事重要，也说明身体正在准备面对未知。', intent: 'allow_experience'),
        MeditationStep(startSecond: 220, text: '感受双脚稳稳承重。今天的任务不是证明自己完美，而是准时到场、看见真实情况。让肩膀在这个更小的任务里松一点。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 285, text: '在心里走一遍具体场景：穿鞋，拿钥匙和材料，关门，走到楼下，再到车站或约定地点。每一幕只做眼前一步。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 350, text: '如果可以带着紧张去收集真实信息，而不是提前签下一生的合同，身体会怎样变化？现在说出路线的第一段。', intent: 'integration'),
        MeditationStep(startSecond: 420, text: '最后吸气，感受脚底；缓慢呼气，睁眼看向门和要带的物品。拿起它们，完成出发的第一个动作。', intent: 'closing'),
      ],
      endingReflection: '勇敢不是没有逃跑冲动，而是让“到场”先于冲动成为事实。',
    ),
    MeditationSessionTemplate(
      key: 'opportunity_commitment_8m',
      title: '8分钟机会到来后的停止反悔',
      type: '承诺稳定',
      category: '行动与执行',
      description: '面试通过或机会确定后，阻止焦虑把已做好的决定重新拖回零点。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在，让身体在这个已经到来的机会旁边坐稳。背部有依靠，双脚接触地面；暂时不重新审判整个选择。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '吸气，感觉腹部有一点空间；呼气，放松下巴。再做一轮。思绪若开始挑错，只温和地回到呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 110, text: '机会靠近时，身体也许会紧，心里既高兴又害怕。找到最明显的一处，看看它是热、硬、发快，还是想后退。', intent: 'body_emotion'),
        MeditationStep(startSecond: 170, text: '让兴奋、怀疑和退缩同时存在。允许害怕改变，不等于让害怕用缺席替你决定；此刻只容纳它，不服从它。', intent: 'allow_experience'),
        MeditationStep(startSecond: 230, text: '把手放在腿上，感受真实触点。紧张不一定说明机会错误，也可能说明生活正在改变。先体验，再依据事实评估。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 295, text: '想象下一项已经约定的场景：按时体检、准备材料、走进报到地点。看见自己一边不确定，一边把动作完成。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 360, text: '如果不用现在保证它完美，只给现实一次被体验的机会，会有什么不同？说出下一步的时间、地点和出门触发器。', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '再缓慢呼气，让双脚记住向前的方向。睁开眼，看向日程或材料；决定先封存，身体按已约定的下一步行动。', intent: 'closing'),
      ],
      endingReflection: '你不需要保证机会一定完美，只需要不给恐惧提前取消现实的权力。',
    ),
    MeditationSessionTemplate(
      key: 'new_job_adaptation_10m',
      title: '10分钟允许自己不会与不适应',
      type: '适应新环境',
      category: '行动与执行',
      description: '面对新工作、陌生流程和通勤压力时，允许适应发生在进入之后。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“允许自己慢慢适应”的空间。坐稳，让背部有支撑，双脚舒服地着地；眼睛可以闭上，也可以保留一点视线。', intent: 'arrival'),
        MeditationStep(startSecond: 60, text: '自然吸气，缓慢呼气。再来一次。若大脑一次搬来所有困难，只说“这是还没发生的第一天”，再回到呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 120, text: '新岗位靠近时，你现在是什么感觉？也许胃里紧、手心热、肩膀僵，或心里发怵。选一处，安静陪它几秒。', intent: 'body_emotion'),
        MeditationStep(startSecond: 185, text: '允许不熟、动作慢和想退缩先存在。允许这些感受，不等于放弃责任；它们只是学习开始时身体真实的反应。', intent: 'allow_experience'),
        MeditationStep(startSecond: 250, text: '轻轻活动双手。它们曾经从不会到会。把“第一天就证明自己”放下，感受“今天只学一个流程”带来的那一点空间。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 320, text: '想象到岗的场景：穿衣、通勤、打卡，听到一个陌生步骤。你停一下，记下来，向现场的人问清一个问题，再继续做。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 390, text: '再想象完成一个班次后离开。位置和辛苦是真实成本，但现在已有真实体验可供判断，不再只有猜测。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 460, text: '如果允许自己先做几天观察者，而不是第一天决定能否坚持一生，身体会不会松一点？选好进入现场的第一个动作。', intent: 'integration'),
        MeditationStep(startSecond: 525, text: '吸气，允许不熟练；呼气，松开必须立刻证明自己的压力。睁眼看清周围，带着“穿衣、出门、打卡”回到今天。', intent: 'closing'),
      ],
      endingReflection: '你不必在开始之前就适应；你只需给真实的自己一次进入和学习的机会。',
    ),
    MeditationSessionTemplate(
      key: 'good_enough_action_8m',
      title: '8分钟从完美退到可完成',
      type: '不完美行动',
      category: '行动与执行',
      description: '标准高到无法开始时，把任务还原成今天可以交付的一版。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“先让第一版出现”的练习。坐稳，感受椅子托住身体，双脚放平；把眼前任务先放在一旁几分钟。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '自然吸气，缓慢呼气。再重复一次。思绪若去检查更多细节，只温和地说“稍后再改”，然后回到呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 110, text: '想到开始或交付，哪里最紧？也许额头绷住、肩膀抬起，心里怕被批评或丢脸。只观察这一处反应。', intent: 'body_emotion'),
        MeditationStep(startSecond: 170, text: '允许害怕粗糙、害怕评价在这里。允许这种保护反应，不等于继续被它卡住；它可以陪着你，手仍可以开始。', intent: 'allow_experience'),
        MeditationStep(startSecond: 230, text: '把手掌放松，想象它们正在做一份不完美的初稿。感受“可修改的第一版”比“尚不存在的完美版”更真实。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 295, text: '进入具体场景：打开文件，只写标题和三行；或拨出电话，只说明第一件事。二十分钟后停下，眼前已经有一个可见痕迹。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 360, text: '如果今天只需完成核心，而不需证明自己毫无缺点，会发生什么？现在选定文件、电话或地点这一个起步动作。', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '再吸气，感受双脚；呼气，松开肩膀。睁眼看向要开始的位置，让双手直接完成第一下，不再增加准备条件。', intent: 'closing'),
      ],
      endingReflection: '完成一小版，比在脑中守护一个完美幻影更接近你真正想要的人生。',
    ),
    MeditationSessionTemplate(
      key: 'learning_zone_exposure_9m',
      title: '9分钟进入学习区而非逃离',
      type: '面对不适',
      category: '行动与执行',
      description: '把可承受的不舒服识别为学习信号，同时尊重恐慌区的边界。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“可承受的学习区”。坐直但不僵硬，让背部和双脚得到支撑；眼睛可以闭上，也可以看着一个安稳的物体。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '自然吸气，缓慢呼气。再来一轮。思绪若急着逃走或证明自己，只把注意力轻轻带回呼吸的起伏。', intent: 'breath'),
        MeditationStep(startSecond: 115, text: '想到那个让你不舒服的行动，身体哪里先反应？心跳、胃部、肩膀，还是腿想离开？给这份不适一个零到十分的分数。', intent: 'body_emotion'),
        MeditationStep(startSecond: 180, text: '允许紧张在这里变化。允许它，不是逼自己忍受危险，也不是立刻逃离；你正在寻找既有挑战、又仍能保持基本稳定的位置。', intent: 'allow_experience'),
        MeditationStep(startSecond: 245, text: '让呼气稍长，感受脚底。把“有不适就说明不该做”转成一次身体经验：我可以不舒服，也可以判断剂量、获得支持。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 315, text: '想象一个具体场景：按下申请按钮、走进面试地点、问出一个问题，或在新岗位完成今天。看见自己紧张，却没有马上离开。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 385, text: '再把保护放进画面：清楚路线、一个可联系的人、必要时缩小任务、结束后的休息。面对不是孤立无援地硬撑。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 455, text: '如果目标不是消灭恐惧，而是给身体一次“我能接近、承受并恢复”的新经验，今天最合适的挑战剂量是什么？', intent: 'integration'),
        MeditationStep(startSecond: 510, text: '最后吸气，感觉身体仍在这里；呼气，睁眼看向周围。带着支持和边界，开始那个可承受的小风险。', intent: 'closing'),
      ],
      endingReflection: '成长发生在可承受的不适里；你可以接近，也可以调节剂量。',
    ),
    MeditationSessionTemplate(
      key: 'decision_grounding_9m',
      title: '9分钟决策瘫痪时回到事实',
      type: '决策落地',
      category: '行动与执行',
      description: '选项在脑中打架时，先稳定身体，再分清事实、预测和底线。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '现在先从反复比较里退半步。坐稳，让椅子托住身体，双脚落地；这几分钟不追求一个毫无风险的答案。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '吸气时感受腹部，呼气时放松额头。再重复一次。新的比较若出现，先记下“又在求确定”，然后回到呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 115, text: '想到几个选项时，你现在是什么感觉？胸口发紧、头脑发胀，还是害怕选错后的羞耻？只选择一处陪它几秒。', intent: 'body_emotion'),
        MeditationStep(startSecond: 175, text: '允许不确定和害怕后悔先存在。允许这些感受，不等于随便选择；它只是让判断不再被“立刻消除焦虑”接管。', intent: 'allow_experience'),
        MeditationStep(startSecond: 240, text: '感受脚底的重量。你不需要预测全部未来，只需要在已知事实、现实底线和可承受代价中，做一个能解释、能复盘的选择。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 310, text: '把真实场景放到眼前：旅馆费用、住处安全、工作机会或体检时间。先看确定的数字和期限，再把“别人会笑、一定失败”放到预测一栏。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 375, text: '想象自己完成一次最小验证：打电话、看现场、算七天成本或按时体检。让现实多给你一条证据，而不是继续在脑中开庭。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 440, text: '如果不再寻找完全不痛的选项，哪个选择更保护底线、代价更可逆？给它一个截止时间，并说出截止后的第一步。', intent: 'integration'),
        MeditationStep(startSecond: 505, text: '最后完成一轮缓慢呼吸，睁眼看清手边环境。把决定写下或执行验证动作，让身体离开循环，走向事实。', intent: 'closing'),
      ],
      endingReflection: '好的决定不是永远不会后悔，而是在有限信息下保护底线并让现实继续提供证据。',
    ),
    MeditationSessionTemplate(
      key: 'unemployment_visibility_10m',
      title: '10分钟失业时允许自己被看见',
      type: '羞耻安放',
      category: '羞耻与自尊',
      description: '听见邻居上班回家便不敢出声时，停止把存在本身当作罪证。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“我也可以在这里”的练习。坐得有支撑，双脚落地；眼睛可以睁着，安静看一看这个你真实生活着的房间。', intent: 'arrival'),
        MeditationStep(startSecond: 60, text: '自然吸气，听见近处或门外的声音；缓慢呼气。再来一次。思绪若猜别人怎么看你，只带回这一口气和眼前房间。', intent: 'breath'),
        MeditationStep(startSecond: 125, text: '当隔壁有人回家、走动或做饭时，身体哪里开始缩紧？也许动作变轻、胸口发窄，心里出现羞耻或不安。', intent: 'body_emotion'),
        MeditationStep(startSecond: 190, text: '允许这份羞耻被看见。它可以存在，却不等于你真的失去占用空间的资格；感受可以在，躲藏不必自动发生。', intent: 'allow_experience'),
        MeditationStep(startSecond: 255, text: '把脚掌轻轻压向地面，背部靠住支撑。失业是正在承受的处境，不是身体需要消失的判决。感受自己仍完整地占据这个位置。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 325, text: '想象熟悉的一幕：门外传来脚步，你仍自然放下杯子、走几步、打开水龙头。声音不大，也不刻意；你只是正常地生活。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 395, text: '接着看见自己拿起手机，投一份匹配岗位、打一通咨询电话，或出门看现场。行动在解决处境，羞辱自己没有。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 465, text: '如果不用先剥夺尊严，才配努力改变，身体会怎样？今天选择一个正常生活动作，也选择一个具体求职动作。', intent: 'integration'),
        MeditationStep(startSecond: 535, text: '最后缓慢吸气和呼气，睁眼看清房间。别人存在时，你也可以存在；带着这个位置感，开始今天那一步。', intent: 'closing'),
      ],
      endingReflection: '你需要改变处境，但不需要先把自己从世界里藏起来，才有资格改变。',
    ),
    MeditationSessionTemplate(
      key: 'social_evaluation_release_8m',
      title: '8分钟从他人眼光回到自己的位置',
      type: '评价脱钩',
      category: '羞耻与自尊',
      description: '害怕被评论、轻视或嘲笑时，区分他人的看法与你的行动方向。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“从他人眼光回到自己的位置”。坐稳，背部自然伸展，双脚贴地；眼睛可以轻闭，也可以柔和看向前方。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '吸气，感觉胸廓展开一点；呼气，让脸和喉咙松一点。再来一次。脑中若重播别人的话，只温和回到呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 110, text: '想到被评论、轻视或嘲笑的时刻，身体哪里最明显？也许脸发热、心跳加快，或腹部缩紧。只承认：这会痛。', intent: 'body_emotion'),
        MeditationStep(startSecond: 170, text: '允许受伤、愤怒或羞耻在这里。允许情绪不等于认同对方，也不等于立刻反击；你在为自己保留选择。', intent: 'allow_experience'),
        MeditationStep(startSecond: 230, text: '把脊背交给支撑，脚底交给地面。别人的评价是一条外来的声音，不是你全部人生的所有权。感受身体仍在自己的位置。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 295, text: '想象再次遇到一个观察或议论你的场景：你注意到脸热，呼气，站稳，不解释全部人生，然后继续投递、工作或走自己的路。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 360, text: '如果今天没有观众，你认为什么行动真正服务生活？把它说得具体，并感受注意力从对方身上回到双手和下一步。', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '最后缓慢呼气，睁眼看见周围三样东西。评价可以留在外面；把今天剩下的注意力带回你的真实选择。', intent: 'closing'),
      ],
      endingReflection: '他人的眼光会影响你，却不必替你决定今天往哪里走。',
    ),
    MeditationSessionTemplate(
      key: 'introvert_connection_8m',
      title: '8分钟内向者的安静连接',
      type: '社交安定',
      category: '关系与连接',
      description: '担心无话可说时，不强迫表演外向，练习真实、简短地靠近他人。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入一次安静的连接练习。坐稳，让身体有支撑，双脚舒服地落地；先不用准备下一次谈话的全部内容。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '自然吸气，慢慢呼气。再来一轮。思绪若开始排练十分钟后的话，只带它回到此刻的呼吸和身体。', intent: 'breath'),
        MeditationStep(startSecond: 110, text: '想到与人见面，胸口、喉咙或脸上有什么感觉？也许紧张、怕冷场、怕被认为无趣。只选最明显的一种感受。', intent: 'body_emotion'),
        MeditationStep(startSecond: 170, text: '允许紧张和短暂空白出现。允许安静，不等于关闭连接；你不必表演外向，仍可以真诚地靠近一个人。', intent: 'allow_experience'),
        MeditationStep(startSecond: 230, text: '感受呼气时喉咙稍微松开。连接不要求不停说话；认真听、看向对方、给出一句真实回应，也能让关系发生。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 295, text: '想象下一次见到同事、熟人或店员：看向对方，打个招呼，问一句与当下有关的问题。对方回答后，你先听，不抢着填满停顿。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 360, text: '如果不再检查“我表现得怎样”，而是真正好奇对方此刻在说什么，会有什么变化？只练习多停留十秒、多表达一句。', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '最后吸气，感受身体仍有自己的节奏；呼气，睁开眼。带着安静而真实的自己，去完成一次很小的连接。', intent: 'closing'),
      ],
      endingReflection: '连接不靠不停说话建立；真诚的注意和一句真实回应，也能让关系开始。',
    ),
    MeditationSessionTemplate(
      key: 'missed_chance_regret_10m',
      title: '10分钟错失机会后的重新站立',
      type: '后悔修复',
      category: '羞耻与自尊',
      description: '没有赴约、没有体检或再次退缩后，承担结果但停止无尽自罚。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '现在，为那次错失的机会留出一个不再自罚的空间。坐稳，背部有支撑，双脚落地；不美化，也不把自己推上审判席。', intent: 'arrival'),
        MeditationStep(startSecond: 60, text: '自然吸气，缓慢呼气。再来一次。脑中若响起“为什么又这样”，只听见它，再回到身体被支撑的感觉。', intent: 'breath'),
        MeditationStep(startSecond: 125, text: '后悔现在落在哪里？胸口沉、胃里紧、脸上发热，还是心里发空？选最明显的一处，允许它被你感觉到。', intent: 'body_emotion'),
        MeditationStep(startSecond: 190, text: '允许难过、羞耻和失望存在。允许这些情绪，不等于否认责任；也不需要再加一句“所以我永远没用”来证明教训重要。', intent: 'allow_experience'),
        MeditationStep(startSecond: 255, text: '把手放在腿上，感受体温和力量。损失已经真实，继续攻击自己只会扩大损失；承担可以是找到断点、重建流程。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 325, text: '轻轻回到那次具体断点：闹钟后没起、回家后反复犹豫，或没有按时体检。只看摄像机能拍到的动作，不做人格判决。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 395, text: '再想象下一次机会：前一晚封存决定，材料放门边，提前到附近，必要时请人电话提醒。看见身体按流程出门，而不是临场再辩论。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 465, text: '如果后悔的作用是保护下一次，而不是惩罚余生，今天会做哪一个补救？重新联系、继续投递、预约，或写下出发触发器。', intent: 'integration'),
        MeditationStep(startSecond: 535, text: '最后吸气，承认失去；呼气，把今天从昨天手里收回来。睁眼看向周围，去完成选定的补救动作。', intent: 'closing'),
      ],
      endingReflection: '承担，是把教训变成新流程；自罚，只会让同一次失误继续夺走更多机会。',
    ),
    MeditationSessionTemplate(
      key: 'financial_pressure_grounding_8m',
      title: '8分钟经济压力下先稳住',
      type: '现实安定',
      category: '现实压力',
      description: '钱越来越少、住宿与工作冲突时，不否认风险，也不让恐慌接管全部判断。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“压力里先看清今天”的练习。坐在有支撑的位置，双脚落地；钱和住处的压力是真实的，这里不要求假装轻松。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '自然吸气，慢慢呼气。再做一轮。若所有最坏结果一起涌来，只把注意力带回脚底和眼前这一刻。', intent: 'breath'),
        MeditationStep(startSecond: 110, text: '钱越来越少时，身体哪里最害怕？胃里收紧、胸口发窄，还是心跳加快？先只感受这一处，不急着解决一年。', intent: 'body_emotion'),
        MeditationStep(startSecond: 170, text: '允许恐慌和羞耻先存在。允许它们，不等于让它们替你决定；现实风险需要数字和保护，不需要再加一层自我羞辱。', intent: 'allow_experience'),
        MeditationStep(startSecond: 230, text: '感受地面托住双脚。把注意力从全部未来收回到三个事实：现有余额、确定支出、安全底线。身体只承担今天这一页。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 295, text: '想象自己打开记事本：算七天费用，比较安全住处，询问包住岗位，保管贵重物品，或联系可信的人。一次只完成一项。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 360, text: '如果先保护基本生存和安全，而把面子与理想方案放到后面，今天哪一步最能延长选择时间？把它说得具体。', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '最后缓慢呼气，睁眼看向手机或纸笔。先完成最紧急的数字或电话，再回来处理下一步；此刻不用同时解决全部。', intent: 'closing'),
      ],
      endingReflection: '稳定不是否认经济风险，而是让你能用真实数字保护自己，而不是被恐慌拖走。',
    ),
    MeditationSessionTemplate(
      key: 'fear_carry_forward_8m',
      title: '8分钟带着恐惧向前',
      type: '恐惧容纳',
      category: '情绪恢复',
      description: '不等待恐惧消失，练习让它留在身体里而不替你掌舵。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在给恐惧一个可以被看见、却不用掌舵的位置。坐稳或站稳，让背部和双脚找到支撑，视线可以柔和地落在前方。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '自然吸气，不追求很深；缓慢呼气。再重复一次。念头若跑向失败或丢脸，只把它带回脚底和呼气。', intent: 'breath'),
        MeditationStep(startSecond: 115, text: '恐惧在身体哪里最明显？紧、冷、快、空，还是想缩起来？只描述它的形状和强度，不急着解释原因。', intent: 'body_emotion'),
        MeditationStep(startSecond: 175, text: '允许恐惧在这里发出警报。允许它，不等于服从所有逃跑冲动；你可以听见警报，同时检查事实、保护自己。', intent: 'allow_experience'),
        MeditationStep(startSecond: 235, text: '轻轻把脚掌压向地面，感受身体仍能承重。你不需要先感觉勇敢，才有资格移动；害怕和动作可以同时存在。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 300, text: '想象眼前真实的一步：穿衣、拨号、提交、打开门或走进现场。心可能快、手可能抖；看见身体仍把这个动作做完。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 365, text: '如果恐惧可以同行，却不替你决定方向，接下来五分钟会做什么？把动作缩到清楚、可见、能够立刻开始。', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '最后吸气，感受脚底；呼气，睁眼看清眼前物体。让现实证据和你的价值决定下一步，现在开始那个小动作。', intent: 'closing'),
      ],
      endingReflection: '勇气不是身体里没有恐惧，而是恐惧出现时，行动通道仍然没有关闭。',
    ),
    MeditationSessionTemplate(
      key: 'resentment_unhook_9m',
      title: '9分钟不再让怨恨继续占用我',
      type: '怨恨脱钩',
      category: '情绪恢复',
      description: '受过不公平对待后，不强迫原谅，只停止让对方反复占据身心。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '现在，为受过的不公平留出一个安全位置。坐稳，让背部有依靠，双脚落地；这里不要求你说“没关系”，也不强迫原谅。', intent: 'arrival'),
        MeditationStep(startSecond: 60, text: '自然吸气，缓慢呼气。再来一次。脑中若重演那场争执，只说“我记得”，然后回到身体和这一口气。', intent: 'breath'),
        MeditationStep(startSecond: 120, text: '怨恨现在怎样住在身体里？也许下巴用力、胸口发热、手掌握紧。选一处，感受它正在努力保护什么。', intent: 'body_emotion'),
        MeditationStep(startSecond: 180, text: '允许愤怒、委屈和不甘存在。允许它们，不等于伤害别人，也不等于替对方开脱；你仍可以选择边界和行动。', intent: 'allow_experience'),
        MeditationStep(startSecond: 245, text: '呼气时松开一点下巴和手掌。感受一个区别：身体松开，不会改写事实；它只是停止让旧事此刻继续向身体收费。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 315, text: '想象再次收到对方的消息、看见相关的人或想起那句话。你先站稳，确认事实，然后选择远离、拒绝、保留证据或不回应。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 385, text: '再看见边界之后的自己，把手机放下，转身去做求职、吃饭、休息或联系值得的人。注意力开始回到你的生活。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 455, text: '如果记住伤害不再等于每分钟重演伤害，你想把今天剩下的生命力交给什么？选一件只属于你的事。', intent: 'integration'),
        MeditationStep(startSecond: 510, text: '最后缓慢呼气，睁眼看清现在的房间。事实和边界留在你手里；把身体与时间带回此刻的生活。', intent: 'closing'),
      ],
      endingReflection: '放下反刍不是宣布对方无罪，而是停止让旧伤每天继续向你收费。',
    ),
    MeditationSessionTemplate(
      key: 'permission_to_be_human_8m',
      title: '8分钟准许自己只是一个人',
      type: '准许为人',
      category: '情绪恢复',
      description: '不再要求自己像机器或上帝一样永远理性、坚强和正确。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“准许自己是一个真实的人”。坐得挺拔但不僵硬，让背部有依靠，双脚落地；眼睛可以闭上，也可以保持柔和视线。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '自然吸气，感觉腹部微微起伏；轻柔呼气。再重复一轮。思绪若跑远，只需把它带回这一口正在发生的呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 115, text: '现在问问自己：此刻到底怎样？也许焦虑、羞耻、疲惫、愤怒，或什么都说不清。找到身体里最明显的一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 175, text: '让这份体验先有位置，也允许下一刻发生变化。感受可以存在，并不表示每个冲动都要执行；你仍能选择怎样照顾自己与他人。', intent: 'allow_experience'),
        MeditationStep(startSecond: 235, text: '把手放在胸口或腹部，感觉体温。人会疲惫、害怕、需要别人，也会重新开始。让“有限而仍有价值”落到手掌下的身体里。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 300, text: '想象今天走进一个普通场景：听到别人回来、面对工作任务，或想起自己的失误。你注意到情绪，呼气，不再因有情绪而攻击自己。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 365, text: '如果真的不再和人性对抗，生活会少掉哪一层重量？在吃饭、休息、负责或重新出发中，选择此刻更健康的一步。', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '再完成一轮缓慢呼吸，感受脚底和房间。准备好时睁开眼，把有限、真实、仍能选择的自己带回生活。', intent: 'closing'),
      ],
      endingReflection: '准许为人不是放弃成长，而是让成长从真实的人性出发。',
    ),
    MeditationSessionTemplate(
      key: 'loneliness_connection_10m',
      title: '10分钟孤独时与世界重新连接',
      type: '孤独陪伴',
      category: '关系与连接',
      description: '觉得没有任何重要的人时，先让身体重新感到自己仍与世界相连。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '现在，为孤独留出一个不必假装的空间。坐着或躺着都可以，让身体得到支撑；眼睛可以闭上，也可以看着房间的一角。', intent: 'arrival'),
        MeditationStep(startSecond: 60, text: '自然吸气，感觉身体仍在呼吸；缓慢呼气。再来一次。思绪若说“永远都只有我”，先回到这一口气。', intent: 'breath'),
        MeditationStep(startSecond: 125, text: '此刻的孤独在哪里？也许胸口空、喉咙堵，或房间显得格外安静。选一种感觉，让它不必躲起来。', intent: 'body_emotion'),
        MeditationStep(startSecond: 190, text: '允许空、想念和无人靠近的痛存在。允许这些感受，不等于接受“未来不会再有连接”这个结论；痛苦正在说话，不是在预言。', intent: 'allow_experience'),
        MeditationStep(startSecond: 255, text: '感受椅子、床或地面托住身体，再听一两个远近的声音。此刻没有人拥抱你，世界仍通过触点、空气和声音与你相连。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 325, text: '把两只手轻轻相触，感受温度。先由现在的你陪着现在的你，不要求这种陪伴替代亲密关系，只让身体知道此刻没有被遗弃。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 395, text: '想象今天走到一个真实场景：给熟人发一句消息、去公共空间、问候店员，或在工作中请教一个问题。连接只需先发生十秒。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 465, text: '如果关系不必一开始就重要，只需先有一条细线，你愿意伸出怎样的一毫米？选择一个不会让自己负担过重的动作。', intent: 'integration'),
        MeditationStep(startSecond: 535, text: '最后缓慢呼气，睁眼看见周围。此刻的孤独是真实的，关系的未来仍未写完；带着自己去完成那次微小接触。', intent: 'closing'),
      ],
      endingReflection: '孤独是真实感受，却不是对余生的判决；新的连接可以从很小的接触开始。',
    ),
    MeditationSessionTemplate(
      key: 'relationship_longing_9m',
      title: '9分钟把思念安放在心里',
      type: '关系失落',
      category: '关系与连接',
      description: '想念一个已经离开或无法靠近的人时，不否定爱，也把生活还给自己。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '现在，为这份思念安排一个安稳的位置。坐好，让背部和双脚被支撑；眼睛可以闭上，也可以留一点光。', intent: 'arrival'),
        MeditationStep(startSecond: 60, text: '自然吸气，缓慢呼气。再来一次。那个人的名字或面容若出现，不追赶，也不推开，只回到呼吸。', intent: 'breath'),
        MeditationStep(startSecond: 120, text: '思念落在身体哪里？也许胸口空、喉咙紧、眼睛发酸。选一处，静静感觉它，不要求它马上减轻。', intent: 'body_emotion'),
        MeditationStep(startSecond: 180, text: '允许舍不得、遗憾和爱同时存在。允许思念，不等于继续控制对方的选择，也不等于永远停在原地。', intent: 'allow_experience'),
        MeditationStep(startSecond: 245, text: '一只手放在胸口。吸气，承认自己真心想靠近；呼气，承认有些未来没有发生。把爱留下，把控制不住的部分轻轻放回现实。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 315, text: '想象今天再次看到旧照片、名字或熟悉地点。你注意到胸口变化，轻声说“我知道你舍不得”，然后摸到桌面，回到现在的房间。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 385, text: '再看见自己起身吃饭、整理住处、准备工作或联系朋友。照顾正在生活的自己，不会抹掉曾经的在意。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 455, text: '如果温柔、在意和建立家庭的愿望仍属于你，而不只属于那段关系，今天会怎样保护其中一种能力？', intent: 'integration'),
        MeditationStep(startSecond: 510, text: '最后缓慢呼气，睁眼看见此刻。把那个人安放在心里一个不占满全部生活的位置；你可以记得，也可以继续。', intent: 'closing'),
      ],
      endingReflection: '放下不是删除爱，而是不再要求一段失去的关系承担你全部未来。',
    ),
    MeditationSessionTemplate(
      key: 'urge_surfing_7m',
      title: '7分钟冲动来临时先不服从',
      type: '冲动冲浪',
      category: '情绪恢复',
      description: '面对烟瘾、性冲动、刷手机或逃避冲动时，观察波峰而不是立即行动。',
      durationSeconds: 420,
      steps: [
        MeditationStep(startSecond: 0, text: '现在给冲动七分钟观察期。坐稳，双脚落地，把双手放在看得见的位置；先不执行，也不发誓永远不会再有。', intent: 'arrival'),
        MeditationStep(startSecond: 50, text: '自然吸气，缓慢呼气。再来一轮。脑中若不断出现目标画面，只注意“画面来了”，然后回到呼气和双手。', intent: 'breath'),
        MeditationStep(startSecond: 105, text: '找到冲动最强的位置：嘴、手、胸口或腹部。它是热、躁、紧，还是心里空？从零到十分给此刻一个分数。', intent: 'body_emotion'),
        MeditationStep(startSecond: 160, text: '允许想要和不舒服存在。允许冲动，不等于执行它；也不必用羞耻把它压住。此刻只练习让感受与动作之间多一点距离。', intent: 'allow_experience'),
        MeditationStep(startSecond: 220, text: '呼气时放松手指，感受冲动正在起伏。它也许升高、停留或变化；强烈是一种身体状态，不是一道必须照办的命令。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 280, text: '想象熟悉的触发场景：手机在手边、烟就在附近，或独处时想逃进习惯。你先把设备放远，站起，喝水，走到较公开的位置。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 340, text: '如果这股冲动正在替你处理无聊、孤独、压力或困倦，什么动作能更直接照顾真正需要？为接下来十分钟选一个。', intent: 'integration'),
        MeditationStep(startSecond: 395, text: '最后缓慢呼气，睁眼看向双手和出口。你可以有冲动，也可以暂时不执行；现在让环境帮助你完成新的选择。', intent: 'closing'),
      ],
      endingReflection: '自控不是从此没有欲望，而是在一次冲动里重新获得几分钟选择权。',
    ),
    MeditationSessionTemplate(
      key: 'knowledge_to_action_8m',
      title: '8分钟从懂得回到做到',
      type: '知行转换',
      category: '行动与执行',
      description: '理论越学越多却没有行动时，停止继续理解，完成一个可观察动作。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '现在进入“让一个道理穿过身体”的练习。坐稳，背部有支撑，双脚落地；把书、课程和新的方法先放到一旁。', intent: 'arrival'),
        MeditationStep(startSecond: 55, text: '自然吸气，慢慢呼气。再来一次。思绪若去寻找更有力量的一句话，只说“我已经知道不少”，然后回到身体。', intent: 'breath'),
        MeditationStep(startSecond: 110, text: '想到那件明知重要却一直没做的事，身体有什么反应？也许沉、紧、想逃，或觉得麻木。只感受最明显的一处。', intent: 'body_emotion'),
        MeditationStep(startSecond: 170, text: '允许抗拒、没动力和“不想被知识约束”的感觉存在。允许这些感受，不等于放弃方向；行动可以在认同尚未完整时开始。', intent: 'allow_experience'),
        MeditationStep(startSecond: 230, text: '轻轻活动手指，再把脚掌压向地面。知识此刻不再是一条压在头上的教条；它只需要变成手脚能够完成的一次真实经验。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 295, text: '把原则变成可拍到的画面：不是“面对困难”，而是九点走进面试地点；不是“自律”，而是闹钟响后双脚落地。看见动作开始。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 360, text: '如果今天不再多理解一层，只让已有知识成为一次事实，会选择哪个五分钟动作？说出它的地点、开始信号和第一下。', intent: 'integration'),
        MeditationStep(startSecond: 425, text: '最后吸气，感受双手和脚底；呼气，睁眼看向行动位置。现在起身完成第一下，让经验接过理论的位置。', intent: 'closing'),
      ],
      endingReflection: '真正改变你的不是今天又理解了多少，而是有一个观念终于穿过身体，成为了事实。',
    ),
    MeditationSessionTemplate(
      key: 'inner_survivor_safety_10m',
      title: '10分钟让曾经硬撑的自己休息',
      type: '生存模式安抚',
      category: '个性化恢复',
      description: '旧日贫困、远行、羞耻或无助被唤起时，留在当下，不重新沉入旧画面。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '这次练习请保持眼睛睁开。慢慢看一圈，轻声说出今天的日期、所在地点，再找出三件眼前真实存在的物品。', intent: 'arrival'),
        MeditationStep(startSecond: 65, text: '让呼吸保持自然，不必深。吸气时看着一个物体，呼气时感受脚底。再做一次；旧画面若来，只把视线带回现在。', intent: 'breath'),
        MeditationStep(startSecond: 130, text: '注意身体哪一处仍像危险就在附近：胸口紧、背部僵、胃里缩，或随时想躲。只选一处，也可以随时暂停。', intent: 'body_emotion'),
        MeditationStep(startSecond: 195, text: '允许警惕和旧日的害怕先存在。允许它们，不等于重新进入过去，也不要求你承受更多；眼睛继续看着现在的房间。', intent: 'allow_experience'),
        MeditationStep(startSecond: 260, text: '一只手轻放在手臂或胸口，感受清楚触点。曾经的警惕、隐忍和独自承担保护过你；此刻身体也可以学习新的保护方式。', intent: 'embodied_shift'),
        MeditationStep(startSecond: 330, text: '看见房间里具体的安全线索：门锁、灯光、水、手机，或一个可联系的人。逐一确认，它们是此刻真实存在的资源。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 400, text: '想象旧记忆在某个夜晚忽然出现。你不追进去，而是说出日期和地点，摸到桌面，打开灯，需要时联系可信的人。', intent: 'real_life_rehearsal'),
        MeditationStep(startSecond: 470, text: '如果过去可以被记得，而身体仍留在现在，你愿意给曾经硬撑的自己哪一种新支持？休息、求助、安全住处，或停止伤害自己。', intent: 'integration'),
        MeditationStep(startSecond: 535, text: '最后自然呼气，转动视线，再确认三件物品。你已经来到今天；带着眼前的资源，慢慢回到接下来的生活。', intent: 'closing'),
      ],
      endingReflection: '过去的你负责活下来；现在的你可以在安全、连接和现实支持中继续生活。',
    ),
  ];

  static MeditationSessionTemplate defaultForState(String state) {
    switch (state) {
      case '被外界影响':
      case '被羞辱后反刍':
        return byKey('attention_sovereignty_8m');
      case '自责羞耻':
        return byKey('shame_self_blame_release_9m');
      case '行动卡住':
        return byKey('action_start_stability_9m');
      case '身体紧绷':
        return byKey('body_home_after_pain_8m');
      case '需要定力':
        return byKey('calm_mountain_8m');
      case '价值感受挫':
        return byKey('self_worth_repair_11m');
      case '早晨起不来':
        return byKey('morning_leave_bed_7m');
      case '面试或上班前想逃':
        return byKey('appointment_courage_8m');
      case '得到机会后犹豫':
        return byKey('opportunity_commitment_8m');
      case '害怕新工作不适应':
        return byKey('new_job_adaptation_10m');
      case '完美主义卡住':
        return byKey('good_enough_action_8m');
      case '害怕进入不舒服':
        return byKey('learning_zone_exposure_9m');
      case '决策瘫痪':
        return byKey('decision_grounding_9m');
      case '因失业怕被看见':
        return byKey('unemployment_visibility_10m');
      case '害怕别人评价':
        return byKey('social_evaluation_release_8m');
      case '错失机会后悔':
        return byKey('missed_chance_regret_10m');
      case '经济压力很大':
        return byKey('financial_pressure_grounding_8m');
      case '感到孤独或思念':
        return byKey('loneliness_connection_10m');
      case '冲动很强':
        return byKey('urge_surfing_7m');
      case '学了很多却做不到':
        return byKey('knowledge_to_action_8m');
      case '焦虑紧张':
      case '心很乱':
        return byKey('breath_anchor_3m');
      case '疲惫无力':
        return byKey('body_scan_10m');
      case '想专注':
        return byKey('focus_return_5m');
      case '睡前放松':
        return byKey('sleep_release_10m');
      case '日常练习':
      default:
        return byKey('calm_mountain_8m');
    }
  }

  static MeditationSessionTemplate byKey(String key) {
    return sessions.firstWhere((e) => e.key == key, orElse: () => sessions.first);
  }

  static Map<String, List<MeditationSessionTemplate>> groupedByCategory({bool sleepOnly = false}) {
    final Map<String, List<MeditationSessionTemplate>> result = {};
    for (final session in sessions) {
      if (sleepOnly && !session.isSleep) continue;
      if (!sleepOnly && session.isSleep) continue;
      result.putIfAbsent(session.category, () => <MeditationSessionTemplate>[]).add(session);
    }
    return result;
  }
}
