import 'meditation_models.dart';

class MeditationSeedData {
  static const List<String> stateOptions = [
    '心很乱',
    '被外界影响',
    '焦虑紧张',
    '疲惫无力',
    '想专注',
    '睡前放松',
    '日常练习',
    '被羞辱后反刍',
    '自责羞耻',
    '行动卡住',
    '身体紧绷',
    '需要定力',
    '价值感受挫',
    '早晨起不来',
    '面试或上班前想逃',
    '得到机会后犹豫',
    '害怕新工作不适应',
    '完美主义卡住',
    '害怕进入不舒服',
    '决策瘫痪',
    '因失业怕被看见',
    '害怕别人评价',
    '错失机会后悔',
    '经济压力很大',
    '感到孤独或思念',
    '冲动很强',
    '学了很多却做不到',
  ];

  static const List<MeditationSessionTemplate> sessions = [
    MeditationSessionTemplate(
      key: 'breath_anchor_3m',
      title: '3分钟回到呼吸',
      type: '呼吸稳定',
      category: '新手入门',
      description: '用最短时间把注意力带回身体和呼吸。',
      durationSeconds: 180,
      steps: [
        MeditationStep(startSecond: 0, text: '现在，先不用解决任何问题。只是坐好，感受身体被支撑着。'),
        MeditationStep(startSecond: 20, text: '轻轻吸气，知道自己正在吸气。慢慢呼气，知道自己正在呼气。'),
        MeditationStep(startSecond: 45, text: '如果已经走神了，没有关系。看见走神，就是练习已经开始。'),
        MeditationStep(startSecond: 75, text: '把注意力放在鼻尖、胸口，或者腹部的起伏上。选择一个地方就够了。'),
        MeditationStep(startSecond: 110, text: '念头出现时，不需要赶走它。只是在心里说：我看见了，然后回来。'),
        MeditationStep(startSecond: 145, text: '最后几次呼吸，慢一点。让身体知道，此刻你正在回到自己。'),
      ],
      endingReflection: '你不是失败于分心，而是在每一次回来中训练自己。',
    ),
    MeditationSessionTemplate(
      key: 'rumination_stop_5m',
      title: '5分钟反刍中断',
      type: '反刍中断',
      category: '反刍中断',
      description: '当脑中反复争辩、回想、内耗时，先把注意力交还给自己。',
      durationSeconds: 300,
      steps: [
        MeditationStep(startSecond: 0, text: '先停一下。你不需要马上把那件事想明白。'),
        MeditationStep(startSecond: 25, text: '感受身体坐在这里。脚、腿、背部，都在此刻。'),
        MeditationStep(startSecond: 55, text: '如果脑中又开始播放那件事，只需要轻轻标记：这是反刍。'),
        MeditationStep(startSecond: 90, text: '我不需要继续和这个念头争辩。我先回到呼吸。'),
        MeditationStep(startSecond: 130, text: '吸气时，把注意力带回身体。呼气时，松开一点点紧绷。'),
        MeditationStep(startSecond: 175, text: '那件事可以暂时放在一边。现在最重要的是，把行动权交还给自己。'),
        MeditationStep(startSecond: 225, text: '如果又被带走，就再次回来。回来一次，就是一次训练。'),
        MeditationStep(startSecond: 270, text: '最后，感受一下：我在这里，我正在重新掌握自己的注意力。'),
      ],
      endingReflection: '你已经看见自己被念头带走，也正在把注意力交还给自己。',
    ),
    MeditationSessionTemplate(
      key: 'emotion_untangle_5m',
      title: '5分钟情绪脱钩',
      type: '情绪脱钩',
      category: '情绪脱钩',
      description: '愤怒、羞耻、焦虑出现时，练习感受它，但不立刻服从它。',
      durationSeconds: 300,
      steps: [
        MeditationStep(startSecond: 0, text: '把注意力放到身体里，看看情绪现在最明显的位置在哪里。'),
        MeditationStep(startSecond: 35, text: '也许在胸口、喉咙、腹部，或者肩膀。只需要观察。'),
        MeditationStep(startSecond: 70, text: '在心里说：情绪正在发生，但它不是我的全部。'),
        MeditationStep(startSecond: 110, text: '我可以感受到它，但不必立刻被它命令。'),
        MeditationStep(startSecond: 155, text: '每一次呼气，都给身体一点空间。不是压下情绪，而是给它空间。'),
        MeditationStep(startSecond: 205, text: '如果有故事出现，先回到身体感受：紧、热、酸、沉、快。'),
        MeditationStep(startSecond: 255, text: '最后，提醒自己：我可以带着情绪，仍然选择下一步行动。'),
      ],
      endingReflection: '情绪可以出现，但你不需要把整个人都交给情绪。',
    ),
    MeditationSessionTemplate(
      key: 'focus_return_5m',
      title: '5分钟专注回收',
      type: '专注回收',
      category: '专注回收',
      description: '学习或工作前，把散乱的注意力收回来。',
      durationSeconds: 300,
      steps: [
        MeditationStep(startSecond: 0, text: '先坐稳，放下手机或其他干扰。'),
        MeditationStep(startSecond: 25, text: '注意一轮完整呼吸：开始、中间、结束。'),
        MeditationStep(startSecond: 60, text: '分心出现时，不责备自己，只说：分心了，然后回来。'),
        MeditationStep(startSecond: 100, text: '把今天接下来最重要的一件事，轻轻放在心里。'),
        MeditationStep(startSecond: 145, text: '吸气，知道我在这里。呼气，准备做一件具体的事。'),
        MeditationStep(startSecond: 200, text: '不需要完美开始，只需要开始第一个小动作。'),
        MeditationStep(startSecond: 260, text: '最后，把注意力放回眼前：下一步，我只做一件事。'),
      ],
      endingReflection: '专注不是没有分心，而是分心后知道如何回来。',
    ),
    MeditationSessionTemplate(
      key: 'body_scan_10m',
      title: '10分钟身体扫描',
      type: '身体扫描',
      category: '身体扫描',
      description: '从头到脚扫描身体，让紧绷慢慢被看见。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '找一个舒服的姿势。让身体被支撑，不必用力维持。'),
        MeditationStep(startSecond: 40, text: '先感受头顶、额头和眼周。让眉心稍微松一点。'),
        MeditationStep(startSecond: 100, text: '感受脸颊、下巴和喉咙。如果紧绷，只要看见它。'),
        MeditationStep(startSecond: 170, text: '把注意力带到肩膀、手臂、手掌。感受重量和温度。'),
        MeditationStep(startSecond: 250, text: '感受胸口和背部。呼吸正在这里自然起伏。'),
        MeditationStep(startSecond: 330, text: '感受腹部、腰部和骨盆。允许身体暂时不需要表现。'),
        MeditationStep(startSecond: 420, text: '感受大腿、小腿、脚踝和脚底。脚底正在接触地面或床。'),
        MeditationStep(startSecond: 515, text: '现在感受整个身体作为一个整体，正在呼吸，正在存在。'),
        MeditationStep(startSecond: 570, text: '最后一小段时间，什么也不用做。只是安静地在这里。'),
      ],
      endingReflection: '你不是一台一直运转的机器，你也可以回到身体里休息。',
    ),
    MeditationSessionTemplate(
      key: 'sleep_release_10m',
      title: '停止反刍入睡',
      type: '睡前放松',
      category: '睡眠',
      description: '睡前不再继续喂养白天的念头，让身体进入夜晚。',
      durationSeconds: 600,
      isSleep: true,
      steps: [
        MeditationStep(startSecond: 0, text: '现在是睡前时间。今天没有处理完的事，可以先放到明天。'),
        MeditationStep(startSecond: 45, text: '感受身体躺着或坐着，被床、椅子或地面支撑。'),
        MeditationStep(startSecond: 110, text: '如果白天的画面出现，在心里说：我知道你来了，但现在我要休息。'),
        MeditationStep(startSecond: 180, text: '让呼气比吸气稍微长一点。慢慢呼气，像把一天放下来。'),
        MeditationStep(startSecond: 260, text: '从额头开始放松，然后是眼睛、脸颊、下巴。'),
        MeditationStep(startSecond: 350, text: '肩膀不需要再扛着今天。手臂、手掌可以慢慢变沉。'),
        MeditationStep(startSecond: 450, text: '腹部、腿、脚，也可以安静下来。'),
        MeditationStep(startSecond: 540, text: '如果又开始想事情，只要回来听见呼吸。今晚，先睡觉。'),
      ],
      endingReflection: '今天已经到这里。剩下的事，可以交给明天的你。',
    ),
    MeditationSessionTemplate(
      key: 'self_acceptance_6m',
      title: '6分钟自我接纳',
      type: '自我接纳',
      category: '自我接纳',
      description: '失败、自责、羞耻之后，先停止继续攻击自己。',
      durationSeconds: 360,
      steps: [
        MeditationStep(startSecond: 0, text: '先把手轻轻放在胸口或腹部，感受身体的温度。'),
        MeditationStep(startSecond: 35, text: '此刻也许并不容易。先承认：我正在经历困难。'),
        MeditationStep(startSecond: 80, text: '很多人都会有失败、自责、羞耻的时刻。我并不是唯一这样的人。'),
        MeditationStep(startSecond: 130, text: '吸气时，感受身体还在这里。呼气时，对自己少一点攻击。'),
        MeditationStep(startSecond: 190, text: '我可以为错误负责，但不必把自己整个人否定掉。'),
        MeditationStep(startSecond: 260, text: '愿我从这一刻开始，重新对自己温和一点，也更诚实一点。'),
        MeditationStep(startSecond: 325, text: '最后提醒自己：我可以重新开始，从一个小行动开始。'),
      ],
      endingReflection: '接纳不是放弃改变，而是停止在改变之前先摧毁自己。',
    ),

    MeditationSessionTemplate(
      key: 'attention_sovereignty_8m',
      title: '8分钟注意力主权恢复',
      type: '注意力主权',
      category: '个性化恢复',
      description: '被外界刺激、羞辱或捉弄后，把注意力从对方那里收回来。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '先坐稳。你不需要马上证明什么，也不需要立刻在脑中反击。'),
        MeditationStep(startSecond: 35, text: '感受脚底、腿、背部和身体的重量。你此刻在这里，不在那个人的眼光里。'),
        MeditationStep(startSecond: 75, text: '如果脑中出现对方的表情、话语、动作，只需轻轻标记：这是被触发后的回放。'),
        MeditationStep(startSecond: 120, text: '吸气，知道自己被影响了。呼气，先不继续把注意力交给他。'),
        MeditationStep(startSecond: 165, text: '在心里说：我看见这个刺激，但我不把今天剩下的时间献给它。'),
        MeditationStep(startSecond: 210, text: '让注意力回到身体最稳定的地方。也许是脚底，也许是手掌，也许是腹部的起伏。'),
        MeditationStep(startSecond: 260, text: '念头如果说：我要想明白、我要赢回来、我要证明他错了。只需要回答：现在先回来。'),
        MeditationStep(startSecond: 315, text: '真正的主动权，不是让对方消失，而是我不再继续用自己的注意力喂养他。'),
        MeditationStep(startSecond: 370, text: '感受一次完整的吸气，再感受一次完整的呼气。回来，不是软弱；回来，是收回主权。'),
        MeditationStep(startSecond: 430, text: '最后，把注意力放到今天还能做的一件小事上。只是一件，很小也可以。'),
      ],
      endingReflection: '你把注意力从外界刺激中收回了一次，这就是重新掌握自己的开始。',
    ),
    MeditationSessionTemplate(
      key: 'shame_self_blame_release_9m',
      title: '9分钟羞耻与自责松绑',
      type: '自责松绑',
      category: '自我接纳',
      description: '当内疚、自责、羞耻开始攻击自己时，练习负责但不自毁。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '把一只手轻轻放在胸口或腹部。先让身体知道：此刻不是审判时间。'),
        MeditationStep(startSecond: 40, text: '如果你正在责备自己，先承认：我现在很难受，我正在经历一股自我攻击。'),
        MeditationStep(startSecond: 85, text: '吸气时，感受手掌的温度。呼气时，对自己少一点用力。'),
        MeditationStep(startSecond: 130, text: '羞耻常常会说：我整个人都不够好。现在只需要看见，这是一种感受，不是最终判决。'),
        MeditationStep(startSecond: 180, text: '我可以承认错误、承认脆弱、承认没有做好，但不必把自己整个人判成失败。'),
        MeditationStep(startSecond: 235, text: '把注意力放回呼吸。每次呼气，都像从自责的绳子里松开一毫米。'),
        MeditationStep(startSecond: 295, text: '在心里说：我愿意为可以改变的部分负责，也愿意停止继续伤害自己。'),
        MeditationStep(startSecond: 355, text: '如果又出现批判的声音，只需要说：我听见了，但我现在选择一种更能恢复力量的方式。'),
        MeditationStep(startSecond: 420, text: '想象自己不是被审判的人，而是一个正在恢复、正在学习、正在重新站起来的人。'),
        MeditationStep(startSecond: 490, text: '最后，轻轻问自己：接下来一个善待自己、同时不逃避责任的小行动是什么？'),
      ],
      endingReflection: '接纳不是逃避责任，而是让你不用通过摧毁自己来证明自己有责任感。',
    ),
    MeditationSessionTemplate(
      key: 'dignity_softening_10m',
      title: '10分钟体面防御安放',
      type: '体面安放',
      category: '个性化恢复',
      description: '当强烈体面感让你必须独自硬撑时，练习把尊严从防御中放松出来。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '先不用表现坚强。此刻只需要坐着，感受身体被支撑。'),
        MeditationStep(startSecond: 45, text: '你可能习惯了独自解决、隐蔽承受、尽量不求人。先看见这个模式，不急着改变它。'),
        MeditationStep(startSecond: 105, text: '吸气时，感受胸口。呼气时，让肩膀放下一点点不必被别人看见的重量。'),
        MeditationStep(startSecond: 165, text: '体面曾经保护过你。它让你在困难中不轻易垮掉，也让你保存了一部分尊严。'),
        MeditationStep(startSecond: 230, text: '但此刻，你可以尝试区分：尊严不是必须一个人硬撑，尊严也可以包括照顾自己。'),
        MeditationStep(startSecond: 300, text: '如果心里出现抗拒，只需要说：我不是要丢掉体面，我只是让身体不再一直处于战斗。'),
        MeditationStep(startSecond: 370, text: '把注意力放到背部。感受背部被支撑，而不是永远独自支撑全部生活。'),
        MeditationStep(startSecond: 440, text: '在心里说：我可以保持尊严，也可以学习接受合适的帮助。两者并不矛盾。'),
        MeditationStep(startSecond: 510, text: '最后几次呼吸，让身体记住：真正稳固的自尊，不需要一直紧绷来证明。'),
        MeditationStep(startSecond: 565, text: '把今天一个可以减轻负担的小选择放在心里，不需要很大，只要真实。'),
      ],
      endingReflection: '你不是放弃尊严，而是在把尊严从孤立硬撑中慢慢解放出来。',
    ),
    MeditationSessionTemplate(
      key: 'body_home_after_pain_8m',
      title: '8分钟痛苦承受后的身体回家',
      type: '身体回家',
      category: '身体扫描',
      description: '经历疼痛、疲惫或长期紧绷后，让身体知道现在可以慢慢恢复。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '找一个让身体相对舒服的姿势。先不要求放松，只要求诚实地感受。'),
        MeditationStep(startSecond: 35, text: '也许身体曾经承受过很多疼痛、惊慌、无助和硬撑。现在先对身体说：我看见你了。'),
        MeditationStep(startSecond: 85, text: '把注意力放在脚底。感受接触、重量、温度。让脚底成为此刻的锚点。'),
        MeditationStep(startSecond: 135, text: '慢慢来到腿部。不是检查哪里有问题，而是感受身体仍然在支持你。'),
        MeditationStep(startSecond: 190, text: '来到腹部和腰部。呼吸经过这里时，让身体知道：现在不是紧急时刻。'),
        MeditationStep(startSecond: 245, text: '如果有不舒服，只在心里轻轻命名：紧、酸、沉、热、空。命名之后，回到呼吸。'),
        MeditationStep(startSecond: 305, text: '来到胸口、肩膀和背部。让每一次呼气都卸下一点长期防备。'),
        MeditationStep(startSecond: 365, text: '来到脸、额头和眼睛。让表情不必再替你承受全部压力。'),
        MeditationStep(startSecond: 425, text: '最后，感受整个身体。它不是你的敌人，它曾经陪你穿过很多难关。'),
      ],
      endingReflection: '你的身体不只是痛苦的现场，也是你一步步恢复的地方。',
    ),
    MeditationSessionTemplate(
      key: 'action_start_stability_9m',
      title: '9分钟行动启动前稳定',
      type: '行动启动',
      category: '专注回收',
      description: '当任务堆积、拖延、内耗时，先稳定身体，再启动一个最小行动。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '先停下来。你不需要一次解决全部任务，只需要重新回到可行动的状态。'),
        MeditationStep(startSecond: 40, text: '感受脚底和座椅。让身体先落地，头脑不必继续在所有任务之间奔跑。'),
        MeditationStep(startSecond: 85, text: '吸气时，知道自己有压力。呼气时，先不把压力解释成失败。'),
        MeditationStep(startSecond: 135, text: '如果脑中出现“太多了、来不及了、我又失败了”，只标记：这是压力语言。'),
        MeditationStep(startSecond: 190, text: '把今天所有任务暂时放远一点。现在只找一件最小、最具体、能开始的动作。'),
        MeditationStep(startSecond: 250, text: '这个动作可以小到打开页面、写第一行、整理一个文件、站起来走两分钟。'),
        MeditationStep(startSecond: 315, text: '在心里说：我不是靠情绪准备好才开始，我是通过开始一点点找回状态。'),
        MeditationStep(startSecond: 380, text: '继续呼吸。让注意力从“整个人生怎么办”回到“下一步做什么”。'),
        MeditationStep(startSecond: 450, text: '现在把那个最小动作在心里说清楚：练习结束后，我先做……'),
        MeditationStep(startSecond: 505, text: '最后一小段时间，感受身体的稳定。然后带着不完美，开始第一步。'),
      ],
      endingReflection: '行动不需要等到完全有力量才开始；很多时候，力量是在开始之后慢慢回来。',
    ),
    MeditationSessionTemplate(
      key: 'scarcity_safety_rebuild_10m',
      title: '10分钟匮乏记忆安全感重建',
      type: '安全感重建',
      category: '个性化恢复',
      description: '当旧的匮乏、饥饿、无助感被激活时，练习把身体带回当下的安全。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '先环顾一下周围。看见三个真实存在的物体，让眼睛告诉身体：我在现在。'),
        MeditationStep(startSecond: 50, text: '感受脚底或身体和支撑物的接触。此刻，你可以先不用逃、也不用马上解决全部问题。'),
        MeditationStep(startSecond: 110, text: '如果旧的匮乏感、无助感、被抛下的感觉出现，只需要说：这是旧记忆被激活了。'),
        MeditationStep(startSecond: 175, text: '吸气，感受现在的空气。呼气，告诉身体：那是过去的危险信号，不一定是此刻的全部事实。'),
        MeditationStep(startSecond: 245, text: '把一只手放在胸口或腹部，给身体一个明确的触点。让它知道：有人在这里照看我。'),
        MeditationStep(startSecond: 315, text: '你曾经用尽办法活下来。现在的练习，不是回到那些画面，而是把自己带离旧的紧急状态。'),
        MeditationStep(startSecond: 385, text: '慢慢呼气。每一次呼气，都像告诉身体：现在我可以用更安全的方式保护自己。'),
        MeditationStep(startSecond: 455, text: '如果头脑又开始预演最坏结果，轻轻回到触点、脚底、呼吸、房间里的声音。'),
        MeditationStep(startSecond: 530, text: '最后，在心里说：我正在从生存模式，慢慢走向生活模式。一步一步就够了。'),
      ],
      endingReflection: '曾经的匮乏说明你承受过很多；现在的练习，是让身体重新学习安全。',
    ),
    MeditationSessionTemplate(
      key: 'calm_mountain_8m',
      title: '8分钟清风拂山岗定力',
      type: '定力练习',
      category: '个性化恢复',
      description: '训练“不慌不忙、不被打乱节奏”的内在稳定。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '坐稳。想象自己不是在风中摇摆的草，而是一座安静的山。'),
        MeditationStep(startSecond: 35, text: '吸气时，感受身体向上。呼气时，感受身体向下落地。'),
        MeditationStep(startSecond: 80, text: '外界可以有声音、变化、评价、挑衅。你不需要马上跟着它们移动。'),
        MeditationStep(startSecond: 125, text: '在心里轻轻说：他强任他强，清风拂山岗。'),
        MeditationStep(startSecond: 170, text: '这不是麻木，也不是忍气吞声。而是在行动之前，先不让自己的节奏被夺走。'),
        MeditationStep(startSecond: 225, text: '如果念头想冲出去辩解、证明、反击，先把注意力放回脊背和脚底。'),
        MeditationStep(startSecond: 285, text: '让呼吸像山间的风，来，又走；念头也来，又走。你只需要稳稳坐着。'),
        MeditationStep(startSecond: 350, text: '真正的定力，是我知道发生了什么，也知道我不必立刻被它牵着走。'),
        MeditationStep(startSecond: 420, text: '最后几次呼吸，带着这份稳定回到今天：慢一点，稳一点，做自己的事。'),
      ],
      endingReflection: '你练习的不是压抑反应，而是在反应之前保留自己的节奏。',
    ),
    MeditationSessionTemplate(
      key: 'self_worth_repair_11m',
      title: '11分钟价值感修复',
      type: '自尊修复',
      category: '自我接纳',
      description: '当长期挫败、能力受限或被现实卡住时，重新区分“受阻”与“无价值”。',
      durationSeconds: 660,
      steps: [
        MeditationStep(startSecond: 0, text: '先坐下来。此刻不需要证明自己有价值，只需要给自己一点稳定空间。'),
        MeditationStep(startSecond: 50, text: '感受呼吸。吸气，身体还在。呼气，暂时放下那个“我必须马上证明自己”的压力。'),
        MeditationStep(startSecond: 115, text: '也许你曾经长期努力，却被某些现实限制、岗位限制、身体条件或机会卡住。先承认：这很痛。'),
        MeditationStep(startSecond: 185, text: '在心里说：受阻，不等于无能；没有被看见，不等于没有价值。'),
        MeditationStep(startSecond: 255, text: '把注意力放到双手。双手曾经工作、学习、忍耐、尝试，它们不是失败的证据。'),
        MeditationStep(startSecond: 330, text: '如果脑中出现“我不如别人、我浪费了时间、我没出息”，只标记：这是受挫后的自我否定。'),
        MeditationStep(startSecond: 405, text: '现在练习一个新的区分：我可以承认路走得很难，同时不把自己整个人否定掉。'),
        MeditationStep(startSecond: 480, text: '吸气，感受还没有消失的愿望。呼气，允许这个愿望用更现实、更稳的方式继续存在。'),
        MeditationStep(startSecond: 550, text: '价值感不是一次成功给你的，也不是一次失败拿走的。它可以通过每天一个真实行动慢慢重建。'),
        MeditationStep(startSecond: 620, text: '最后，问自己：今天我可以做哪一个很小但能支持自己的行动？'),
      ],
      endingReflection: '现实可能让一条路受阻，但它不能证明你整个人没有价值。',
    ),
    MeditationSessionTemplate(
      key: 'morning_leave_bed_7m',
      title: '7分钟从被窝到站起来',
      type: '起床启动',
      category: '行动与执行',
      description: '闹钟响后不再和“不想起”辩论，让身体先完成离床。',
      durationSeconds: 420,
      steps: [
        MeditationStep(startSecond: 0, text: '先不用问自己想不想起床。听见声音，感受后背、腿和被子的重量。你现在只做一个练习：让身体重新上线。'),
        MeditationStep(startSecond: 45, text: '慢慢呼气。承认此刻被窝很舒服，外面的事情让人抗拒。承认它，不等于服从它。'),
        MeditationStep(startSecond: 95, text: '把注意力放到脚趾。轻轻动一动脚趾，再动一动脚踝。不是准备好以后再动，而是用动作唤醒准备。'),
        MeditationStep(startSecond: 145, text: '现在把手掌压在床面上，感受手臂有力量。下一次呼气时，让上半身抬高一点。只做这一点。'),
        MeditationStep(startSecond: 200, text: '如果脑中说“再躺五分钟”，不要争辩。只回答一句：我知道你想继续躺，但双脚现在要落地。'),
        MeditationStep(startSecond: 255, text: '让双脚接触地面。感受凉、硬、压力或麻木。脚落地以后，坐着也可以，不必立刻完成整天。'),
        MeditationStep(startSecond: 315, text: '把今天缩小成一个动作：站起来，走到洗手间，或者穿上衣服。工作、面试和未来，暂时都不用一起扛。'),
        MeditationStep(startSecond: 375, text: '现在数三下。一，身体向前；二，脚底用力；三，站起来。让练习在站立中结束。'),
      ],
      endingReflection: '起床不是先获得意愿再行动；这一次，你让身体先替自己打开了路。',
    ),
    MeditationSessionTemplate(
      key: 'appointment_courage_8m',
      title: '8分钟面试与上班前赴约',
      type: '赴约行动',
      category: '行动与执行',
      description: '出发前很想逃时，把任务从“表现完美”还原为“准时到场”。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '先站着或坐直。你现在不需要证明自己一定能做好，只需要让身体准备出发。'),
        MeditationStep(startSecond: 50, text: '注意胸口、腹部或喉咙里的紧。对自己说：我正在害怕，这说明这件事对我重要。'),
        MeditationStep(startSecond: 105, text: '头脑可能正在预演失败、尴尬、不适应。轻轻标记：这是预测，不是已经发生的事实。'),
        MeditationStep(startSecond: 160, text: '把目标缩小：今天的成功标准不是被录用、表现完美或永不紧张，只是按时到达指定地点。'),
        MeditationStep(startSecond: 220, text: '感受脚底。你可以带着紧张穿鞋，可以带着怀疑拿钥匙，也可以带着不确定走出门。'),
        MeditationStep(startSecond: 285, text: '在心里说清楚路线的第一段：离开房间，走到楼下，或者骑到地铁站。只看第一段。'),
        MeditationStep(startSecond: 350, text: '如果内心要求“先确定这份工作值不值得”，提醒自己：到场只是收集真实信息，不是签下一生的合同。'),
        MeditationStep(startSecond: 420, text: '最后一次深呼吸。拿起必须物品，打开门。恐惧可以同行，但今天由赴约这个动作带路。'),
      ],
      endingReflection: '勇敢不是没有逃跑冲动，而是让“到场”先于冲动成为事实。',
    ),
    MeditationSessionTemplate(
      key: 'opportunity_commitment_8m',
      title: '8分钟机会到来后的停止反悔',
      type: '承诺稳定',
      category: '行动与执行',
      description: '面试通过或机会确定后，阻止焦虑把已做好的决定重新拖回零点。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '先承认：机会真的到来时，心里不一定只有高兴，也可能马上出现害怕、挑毛病和退缩。'),
        MeditationStep(startSecond: 55, text: '感受身体哪里在收紧。不要立刻把这份紧张解释成“这个机会不对”。紧张也可能只是改变正在靠近。'),
        MeditationStep(startSecond: 110, text: '把事实和预测分开。事实是已经通过、下一步是什么；预测是难做、会失败、也许还有更好。先只看事实。'),
        MeditationStep(startSecond: 170, text: '现在不重新审判整份工作。只确认下一项已经约定的动作：体检、报到、准备材料，或按时出发。'),
        MeditationStep(startSecond: 230, text: '对那个想退出的部分说：我知道你想避免失败和不适应。你可以害怕，但不能用缺席替我做最终决定。'),
        MeditationStep(startSecond: 295, text: '给自己一个公平规则：先亲自体验，再依据真实经历评估；不在尚未开始时，仅凭想象宣布失败。'),
        MeditationStep(startSecond: 360, text: '想象自己完成下一步后回到住处。无论结果怎样，你至少拥有了新的事实，而不是又留下一个空白。'),
        MeditationStep(startSecond: 425, text: '把下一步的时间、地点和出门动作在心里说一遍。决定暂时封存，身体按计划执行。'),
      ],
      endingReflection: '你不需要保证机会一定完美，只需要不给恐惧提前取消现实的权力。',
    ),
    MeditationSessionTemplate(
      key: 'new_job_adaptation_10m',
      title: '10分钟允许自己不会与不适应',
      type: '适应新环境',
      category: '行动与执行',
      description: '面对新工作、陌生流程和通勤压力时，允许适应发生在进入之后。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '坐稳，感受身体被支撑。新环境还没有开始，大脑却可能已经把所有困难一次性搬到眼前。'),
        MeditationStep(startSecond: 60, text: '轻轻说：我现在看见的是想象中的第一天，不是真实经历过的第一天。'),
        MeditationStep(startSecond: 120, text: '允许自己刚开始不熟、动作慢、会问问题。不会，是进入新工作的起点，不是不能胜任的判决。'),
        MeditationStep(startSecond: 185, text: '把“我能不能长期坚持”放到一边。今天只需要学习一个流程，记住一个人，完成一个班次。'),
        MeditationStep(startSecond: 250, text: '如果想到位置不方便、工作辛苦，承认这些是真实成本。冥想不抹掉成本，只帮你不要在体验前夸大全部成本。'),
        MeditationStep(startSecond: 320, text: '感受双手。它们过去学会过很多事情。陌生不会永远陌生，重复会慢慢把步骤交给身体。'),
        MeditationStep(startSecond: 390, text: '对自己说：我可以先做七天观察者。记录真实困难、真实收获和可调整之处，再决定下一步。'),
        MeditationStep(startSecond: 460, text: '把注意力带回呼吸。吸气，允许不熟练；呼气，放下必须第一天就证明自己的压力。'),
        MeditationStep(startSecond: 525, text: '最后，只保留进入现场所需的一个动作。穿衣、出门、打卡。适应要在现场发生。'),
      ],
      endingReflection: '你不必在开始之前就适应；你只需给真实的自己一次进入和学习的机会。',
    ),
    MeditationSessionTemplate(
      key: 'good_enough_action_8m',
      title: '8分钟从完美退到可完成',
      type: '不完美行动',
      category: '行动与执行',
      description: '标准高到无法开始时，把任务还原成今天可以交付的一版。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '先看见那个要求：必须想清楚、准备充分、一次做好，才配开始。不要赶走它，只要认出它。'),
        MeditationStep(startSecond: 55, text: '感受这个要求落在身体哪里。也许肩膀很硬，额头很紧，呼吸变浅。慢慢呼气。'),
        MeditationStep(startSecond: 110, text: '完美主义可能想保护你不被批评、不失败、不丢脸。谢谢它的用意，但今天不让它决定起跑线。'),
        MeditationStep(startSecond: 170, text: '把任务分成两个版本：理想版本以后改；可完成版本今天先出现。现在只为可完成版本工作。'),
        MeditationStep(startSecond: 230, text: '问自己：如果只允许用二十分钟，我会留下什么最核心的东西？那个答案就是第一步。'),
        MeditationStep(startSecond: 295, text: '在心里说：粗糙的第一版不是失败，它是现实里唯一能被修改的东西。不存在的完美版本无法成长。'),
        MeditationStep(startSecond: 360, text: '感受双手和脚底。准备结束后，立刻打开文件、拨出电话，或走到目的地，不再增加新的准备条件。'),
        MeditationStep(startSecond: 425, text: '最后给自己一个许可：今天可以不精彩，但必须留下一个真实、可见、完成过的痕迹。'),
      ],
      endingReflection: '完成一小版，比在脑中守护一个完美幻影更接近你真正想要的人生。',
    ),
    MeditationSessionTemplate(
      key: 'learning_zone_exposure_9m',
      title: '9分钟进入学习区而非逃离',
      type: '面对不适',
      category: '行动与执行',
      description: '把可承受的不舒服识别为学习信号，同时尊重恐慌区的边界。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '感受此刻的不舒服。不要先判断它好或坏，只观察身体：心跳、呼吸、胃部、肩膀。'),
        MeditationStep(startSecond: 55, text: '对自己说：舒适区很熟悉，学习区会有一点紧张；恐慌区则会让我失去基本稳定。我要寻找中间位置。'),
        MeditationStep(startSecond: 115, text: '给现在的不适从零到十分打分。三到六分，可以慢慢接近；八到十分，先缩小任务、增加支持。'),
        MeditationStep(startSecond: 180, text: '你不需要把自己扔进沸水。今天只把一只脚放进流动的水：做一个有挑战但可完成的动作。'),
        MeditationStep(startSecond: 245, text: '如果身体想逃，先延迟逃离九十秒。看着呼吸起伏，让不适有机会自己变化，而不是马上替你做决定。'),
        MeditationStep(startSecond: 315, text: '选择一个具体暴露：发出申请、进入面试地点、问一个问题、在新岗位待完今天。只选一个。'),
        MeditationStep(startSecond: 385, text: '提醒自己：面对不是喜欢痛苦，也不是证明我能忍；面对是为了让大脑获得“我可以承受并恢复”的新证据。'),
        MeditationStep(startSecond: 455, text: '把支持也放进计划：路线、联系人、退出条件、结束后的休息。勇敢不等于没有保护。'),
        MeditationStep(startSecond: 510, text: '最后呼气。练习结束后，直接进入那个可承受的小风险，不再等恐惧完全消失。'),
      ],
      endingReflection: '成长发生在可承受的不适里；你可以接近，也可以调节剂量。',
    ),
    MeditationSessionTemplate(
      key: 'decision_grounding_9m',
      title: '9分钟决策瘫痪时回到事实',
      type: '决策落地',
      category: '行动与执行',
      description: '选项在脑中打架时，先稳定身体，再分清事实、预测和底线。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '先暂停比较。此刻不要求立刻得出完美答案，只让大脑从高速循环降下来。'),
        MeditationStep(startSecond: 55, text: '感受脚底和座椅。连续比较会制造“再想一点就能确定”的感觉，但确定性可能并不存在。'),
        MeditationStep(startSecond: 115, text: '把选项轻轻放在心里，然后只问第一类问题：我已经知道的事实是什么？不加入猜测。'),
        MeditationStep(startSecond: 175, text: '再问第二类：哪些是我的预测，例如会很难、别人会笑、可能有更好的？承认预测有用，但它不是事实。'),
        MeditationStep(startSecond: 240, text: '问第三类：我的底线是什么？安全、基本生存、时间限制、不可承受的损失。底线比一时情绪更清楚。'),
        MeditationStep(startSecond: 310, text: '如果两个选择都不完美，不再寻找“完全不痛”的那个。比较哪一个代价可逆，哪一个能带来更多真实信息。'),
        MeditationStep(startSecond: 375, text: '给决定设置截止时间。截止前收集关键事实；截止后停止反复开庭，进入执行。'),
        MeditationStep(startSecond: 440, text: '现在选择一个最小验证动作：打电话、看现场、算七天成本、完成体检。用现实回答，而不是只用想象。'),
        MeditationStep(startSecond: 505, text: '最后感受一次完整呼吸。你不需要预测全部未来，只需要做出目前证据下可解释、可复盘的一步。'),
      ],
      endingReflection: '好的决定不是永远不会后悔，而是在有限信息下保护底线并让现实继续提供证据。',
    ),
    MeditationSessionTemplate(
      key: 'unemployment_visibility_10m',
      title: '10分钟失业时允许自己被看见',
      type: '羞耻安放',
      category: '羞耻与自尊',
      description: '听见邻居上班回家便不敢出声时，停止把存在本身当作罪证。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '听一听房间里的声音。也许门外有人走动、做饭、上班回来。先让声音只是声音。'),
        MeditationStep(startSecond: 60, text: '注意身体是否立刻收紧，动作变轻，像是不能让别人知道你在家。温和地说：羞耻被触发了。'),
        MeditationStep(startSecond: 125, text: '这股羞耻可能在说：没有工作的人不应该被看见，不应该占空间。听见它，但不要把它当成法律。'),
        MeditationStep(startSecond: 190, text: '感受脚底、墙面和空气。你正在一个真实房间里生活。暂时失业是处境，不是你失去存在资格的证明。'),
        MeditationStep(startSecond: 255, text: '允许自己做一个正常声音：放下杯子、走几步、打开水龙头。不是挑衅谁，只是不再把自己藏成不存在。'),
        MeditationStep(startSecond: 325, text: '如果脑中想象别人评价你，提醒自己：你没有听见他们的判断；现在出现的是你内在的审判声。'),
        MeditationStep(startSecond: 395, text: '对自己说：我确实需要找工作，也确实承受压力。但解决压力的方法是行动，不是先剥夺自己的尊严。'),
        MeditationStep(startSecond: 465, text: '把今天一个求职动作放在心里：投一份、打一通电话、出门看一个岗位。让行动服务现实，而不是服务羞耻。'),
        MeditationStep(startSecond: 535, text: '最后，正常地呼吸，正常地坐着。别人存在时，你也可以存在；别人工作时，你仍是一个正在寻找出路的人。'),
      ],
      endingReflection: '你需要改变处境，但不需要先把自己从世界里藏起来，才有资格改变。',
    ),
    MeditationSessionTemplate(
      key: 'social_evaluation_release_8m',
      title: '8分钟从他人眼光回到自己的位置',
      type: '评价脱钩',
      category: '羞耻与自尊',
      description: '害怕被评论、轻视或嘲笑时，区分他人的看法与你的行动方向。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '先感受身体。想到别人怎么看你时，哪里最紧？胸口、脸、喉咙，还是腹部？'),
        MeditationStep(startSecond: 55, text: '承认：被评价会痛。人需要归属，也会对排斥敏感。你不是软弱，只是一个会受影响的人。'),
        MeditationStep(startSecond: 110, text: '现在区分三件事：别人说了什么；你猜他们在想什么；你因此怎样评价自己。不要把三件事混成一个判决。'),
        MeditationStep(startSecond: 170, text: '别人的评价可能正确一部分、错误一部分，也可能带着恶意。它是一条信息，不是对你全部人生的所有权。'),
        MeditationStep(startSecond: 230, text: '把注意力放回脊背和脚底。在心里说：我可以听见评价，但我的身体仍站在自己的位置上。'),
        MeditationStep(startSecond: 295, text: '问自己：如果今天没有观众，我认为哪一步对生活有帮助？把答案说得具体一点。'),
        MeditationStep(startSecond: 360, text: '让那个动作成为方向。别人可能继续说话，但你不需要用整天的注意力为他们提供回音。'),
        MeditationStep(startSecond: 425, text: '最后呼气。把自己的价值从一张别人随时能改写的评分表上，慢慢收回到真实选择和行动里。'),
      ],
      endingReflection: '他人的眼光会影响你，却不必替你决定今天往哪里走。',
    ),
    MeditationSessionTemplate(
      key: 'introvert_connection_8m',
      title: '8分钟内向者的安静连接',
      type: '社交安定',
      category: '关系与连接',
      description: '担心无话可说时，不强迫表演外向，练习真实、简短地靠近他人。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '先不用想下一次该说什么。感受呼吸和身体，让社交暂时从考试变回人与人的相遇。'),
        MeditationStep(startSecond: 55, text: '也许你害怕冷场，怕别人觉得你无趣。承认这份紧张，不要求自己立刻变得健谈。'),
        MeditationStep(startSecond: 110, text: '安静不是缺陷。你可以少说，但认真听；可以不知道说什么，但提出一个真实的小问题。'),
        MeditationStep(startSecond: 170, text: '想象下一次见到一个人，只完成三个动作：看向对方，打招呼，问一句与当下有关的话。'),
        MeditationStep(startSecond: 230, text: '不预演十分钟对话。对方的回答会提供下一句话，你不必一个人提前生产全部话题。'),
        MeditationStep(startSecond: 295, text: '如果出现短暂停顿，让它存在两秒。停顿不是失败，两个人都可以在停顿里寻找下一步。'),
        MeditationStep(startSecond: 360, text: '把注意力从“我表现得怎样”移到“这个人此刻在表达什么”。好奇会替代一部分自我监视。'),
        MeditationStep(startSecond: 425, text: '最后对自己说：我不需要扮演外向的人。我只练习多停留一点，多表达一句真实的话。'),
      ],
      endingReflection: '连接不靠不停说话建立；真诚的注意和一句真实回应，也能让关系开始。',
    ),
    MeditationSessionTemplate(
      key: 'missed_chance_regret_10m',
      title: '10分钟错失机会后的重新站立',
      type: '后悔修复',
      category: '羞耻与自尊',
      description: '没有赴约、没有体检或再次退缩后，承担结果但停止无尽自罚。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '先坐稳。那次没有去、没有出发、没有抓住机会，确实已经发生。现在不美化，也不逃开。'),
        MeditationStep(startSecond: 60, text: '注意后悔落在身体哪里。也许胸口发沉，胃里发紧，脑中不断说“为什么又这样”。先感受，不跟着审问。'),
        MeditationStep(startSecond: 125, text: '对自己说：我失去了一次机会。这句话已经足够真实，不需要再加上“所以我永远没用”。'),
        MeditationStep(startSecond: 190, text: '后悔有一项工作：指出哪个环节需要改变。它不需要每天重复侮辱你，才能证明教训重要。'),
        MeditationStep(startSecond: 255, text: '回想断点，只找具体动作：闹钟后没起、回家后反复想、没有按时体检。把人格判决改写成可观察的环节。'),
        MeditationStep(startSecond: 325, text: '现在为下次设置一个外部动作：提前到附近、让人电话催促、先交押金、把“是否去”在前一晚封存。'),
        MeditationStep(startSecond: 395, text: '吸气，承认损失；呼气，停止继续扩大损失。今天仍在流逝，不让昨天再拿走今天。'),
        MeditationStep(startSecond: 465, text: '把手放在腿上，感受身体还有力量。你不能回到那一天，但可以让下一次的流程不再只靠临场意志。'),
        MeditationStep(startSecond: 535, text: '最后选择今天的一个补救动作：重新联系、继续投递、预约下一场，或写下新的出发触发器。'),
      ],
      endingReflection: '承担，是把教训变成新流程；自罚，只会让同一次失误继续夺走更多机会。',
    ),
    MeditationSessionTemplate(
      key: 'financial_pressure_grounding_8m',
      title: '8分钟经济压力下先稳住',
      type: '现实安定',
      category: '现实压力',
      description: '钱越来越少、住宿与工作冲突时，不否认风险，也不让恐慌接管全部判断。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '先承认现实：钱的压力会让人害怕，住宿和工作选择也可能真的很紧迫。这里不要求你假装轻松。'),
        MeditationStep(startSecond: 55, text: '感受脚底和呼吸。恐慌会把未来所有坏结果同时搬来；现在只处理今天能确认的数字和动作。'),
        MeditationStep(startSecond: 110, text: '在心里分开两栏：已经确定的支出和余额；脑中最坏的想象。两栏都重要，但不能混在一起。'),
        MeditationStep(startSecond: 170, text: '提醒自己：安全和基本生存优先。面子、别人可能的嘲笑、理想方案，暂时排在底线之后。'),
        MeditationStep(startSecond: 230, text: '慢慢呼气。你不需要今天解决一整年，只需要找到能延长安全时间、同时增加工作机会的一步。'),
        MeditationStep(startSecond: 295, text: '这个动作可能是计算七天成本、询问包住岗位、保管贵重物品、联系可信的人，或设定回家截止日期。'),
        MeditationStep(startSecond: 360, text: '不要用羞耻惩罚资金不足的自己。羞耻会让你躲起来，清楚的数字和行动才会让选择变多。'),
        MeditationStep(startSecond: 425, text: '最后把今天最紧急的一步说出来。练习结束后先完成它，再回来处理下一步。'),
      ],
      endingReflection: '稳定不是否认经济风险，而是让你能用真实数字保护自己，而不是被恐慌拖走。',
    ),
    MeditationSessionTemplate(
      key: 'fear_carry_forward_8m',
      title: '8分钟带着恐惧向前',
      type: '恐惧容纳',
      category: '情绪恢复',
      description: '不等待恐惧消失，练习让它留在身体里而不替你掌舵。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '把注意力放到恐惧最明显的位置。不要分析原因，只描述身体：紧、冷、快、空、想缩起来。'),
        MeditationStep(startSecond: 55, text: '对恐惧说：我知道你在提醒我可能受伤、失败或丢脸。谢谢你的警报，我会看事实，也会保护自己。'),
        MeditationStep(startSecond: 115, text: '恐惧不是命令。它是一股身体反应，可以坐在车里，但不必握方向盘。'),
        MeditationStep(startSecond: 175, text: '慢慢吸气，不追求很深；慢慢呼气，让脚底更清楚。你不必先变勇敢，才能移动。'),
        MeditationStep(startSecond: 235, text: '想一个现在需要做的动作，把它缩小到五分钟以内：穿衣、出门、拨号、提交、走进去。'),
        MeditationStep(startSecond: 300, text: '想象自己一边害怕，一边完成这个动作。手可能抖，心可能快，但动作仍然可以发生。'),
        MeditationStep(startSecond: 365, text: '如果恐惧升高，回到脚底、呼气和眼前物体。你不是要压住它，只是在它旁边保留一条行动通道。'),
        MeditationStep(startSecond: 425, text: '最后说：我允许恐惧跟来，但下一步由我和现实证据共同决定。现在开始那个小动作。'),
      ],
      endingReflection: '勇气不是身体里没有恐惧，而是恐惧出现时，行动通道仍然没有关闭。',
    ),
    MeditationSessionTemplate(
      key: 'resentment_unhook_9m',
      title: '9分钟不再让怨恨继续占用我',
      type: '怨恨脱钩',
      category: '情绪恢复',
      description: '受过不公平对待后，不强迫原谅，只停止让对方反复占据身心。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '先承认：你可能真的受过不公平、轻视或伤害。这里不要求你说“没关系”，也不要求马上原谅。'),
        MeditationStep(startSecond: 60, text: '感受怨恨在身体里的样子。也许下巴用力、胸口发热、手想握紧。只观察它怎样保护你。'),
        MeditationStep(startSecond: 120, text: '怨恨可能在说：不能忘，否则伤害就等于没有发生。告诉它：我可以记住边界，不必每分钟重演伤害。'),
        MeditationStep(startSecond: 180, text: '把事实留给自己，把反复争辩暂时放下。你知道发生过什么，不需要在脑中一遍遍赢回那场对话。'),
        MeditationStep(startSecond: 245, text: '呼气时松开一点下巴和手掌。松开身体，不等于替对方开脱；只是停止继续由自己的身体支付费用。'),
        MeditationStep(startSecond: 315, text: '问自己：我需要的边界是什么？远离、拒绝、保留证据、不再回应，或把时间给值得的人。'),
        MeditationStep(startSecond: 385, text: '让边界替代幻想中的报复。边界保护未来，反复想象只把注意力继续送回过去。'),
        MeditationStep(startSecond: 455, text: '把今天剩余的时间想象成握在自己手里。选择一件不属于那个人、只属于你生活的事。'),
        MeditationStep(startSecond: 510, text: '最后呼气：我不否认伤害，我也不再把全部生命力交给伤害。'),
      ],
      endingReflection: '放下反刍不是宣布对方无罪，而是停止让旧伤每天继续向你收费。',
    ),
    MeditationSessionTemplate(
      key: 'permission_to_be_human_8m',
      title: '8分钟准许自己只是一个人',
      type: '准许为人',
      category: '情绪恢复',
      description: '不再要求自己像机器或上帝一样永远理性、坚强和正确。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '感受呼吸自己进来，又自己出去。你没有创造这套身体，也不能命令它永远不疲惫、不害怕。'),
        MeditationStep(startSecond: 55, text: '承认一个简单事实：人会痛、会老、会失败、会需要别人，也会有不愿意行动的时候。'),
        MeditationStep(startSecond: 115, text: '这不是为一切行为找借口。准许感受存在，才有机会看清接下来怎样回应。'),
        MeditationStep(startSecond: 175, text: '如果今天有焦虑、羞耻、欲望或愤怒，对它说：你可以在这里，但你不必替我决定全部行为。'),
        MeditationStep(startSecond: 235, text: '把手放在胸口或腹部。感受体温。你是自然中的一个生命，不是必须无误运行的项目。'),
        MeditationStep(startSecond: 300, text: '允许今天的自己有边界：需要吃饭、睡觉、休息，也需要工作、负责和重新开始。两边都属于人。'),
        MeditationStep(startSecond: 365, text: '不再用“我怎么能这样”增加第二层痛苦。先说“原来我现在是这样”，再选择一个更健康的动作。'),
        MeditationStep(startSecond: 425, text: '最后让呼吸保持自然。你不需要成为上帝才配活着；作为一个有限的人，也可以认真走下一步。'),
      ],
      endingReflection: '准许为人不是放弃成长，而是让成长从真实的人性出发。',
    ),
    MeditationSessionTemplate(
      key: 'loneliness_connection_10m',
      title: '10分钟孤独时与世界重新连接',
      type: '孤独陪伴',
      category: '关系与连接',
      description: '觉得没有任何重要的人时，先让身体重新感到自己仍与世界相连。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '先不用说服自己“不孤独”。如果此刻就是很空、很静、没有人可以靠近，先承认它。'),
        MeditationStep(startSecond: 60, text: '感受身体和椅子、床或地面的接触。即使没有人抱住你，此刻仍有东西在支撑身体。'),
        MeditationStep(startSecond: 125, text: '听见远处和近处的声音。有人走路、车辆经过、风吹动空气。你不必认识他们，世界仍在你周围发生。'),
        MeditationStep(startSecond: 190, text: '孤独会说：没有重要的人，就没有继续生活的理由。把它认作痛苦发出的结论，不是唯一可能的事实。'),
        MeditationStep(startSecond: 255, text: '你和他人的关系不只来自血缘或已经拥有的亲密。关系也可以从一次问候、共同工作、帮助与被帮助开始。'),
        MeditationStep(startSecond: 325, text: '把手掌相对放在一起，感受温度。先由现在的你陪着现在的你，不要求这种陪伴替代所有人。'),
        MeditationStep(startSecond: 395, text: '想一个可以产生微小连接的动作：给熟人发消息、去公共空间、参加工作、问候店员，或接受一次帮助。'),
        MeditationStep(startSecond: 465, text: '连接不一定立刻变成重要关系。它可以先是一条很细的线，让你不再完全封闭在自己的房间和念头里。'),
        MeditationStep(startSecond: 535, text: '最后对自己说：此刻我很孤独，但我的关系史还没有结束。今天可以先伸出一毫米。'),
      ],
      endingReflection: '孤独是真实感受，却不是对余生的判决；新的连接可以从很小的接触开始。',
    ),
    MeditationSessionTemplate(
      key: 'relationship_longing_9m',
      title: '9分钟把思念安放在心里',
      type: '关系失落',
      category: '关系与连接',
      description: '想念一个已经离开或无法靠近的人时，不否定爱，也把生活还给自己。',
      durationSeconds: 540,
      steps: [
        MeditationStep(startSecond: 0, text: '允许那个人的名字或面容出现。你不需要马上忘记，也不需要因为还在想念而责备自己。'),
        MeditationStep(startSecond: 60, text: '感受思念在身体哪里。也许胸口空、喉咙紧、眼睛酸。让它有一个位置，而不是占满全部世界。'),
        MeditationStep(startSecond: 120, text: '对自己说：这段感情或期待对我很重要，所以失去联系会痛。痛不证明我必须永远停在这里。'),
        MeditationStep(startSecond: 180, text: '区分真实的人与脑中反复延伸的未来。尊重真实发生过的，也轻轻放下没有发生的那部分故事。'),
        MeditationStep(startSecond: 245, text: '吸气，承认我曾经想靠近；呼气，承认我不能控制另一个人的选择。'),
        MeditationStep(startSecond: 315, text: '把爱里属于你的能力留下：在意、期待、温柔、愿意建立家庭。这些能力没有随着一个人离开而全部消失。'),
        MeditationStep(startSecond: 385, text: '如果脑中又问“如果当初”，只回答：我知道你舍不得。然后回到手掌、胸口和现在的房间。'),
        MeditationStep(startSecond: 455, text: '想一个今天能照顾现实生活的动作。吃饭、工作、联系朋友、整理住处。不是背叛思念，而是保护仍在生活的自己。'),
        MeditationStep(startSecond: 510, text: '最后让那个人暂时退到心里一个安静的位置。你可以记得，同时继续向前。'),
      ],
      endingReflection: '放下不是删除爱，而是不再要求一段失去的关系承担你全部未来。',
    ),
    MeditationSessionTemplate(
      key: 'urge_surfing_7m',
      title: '7分钟冲动来临时先不服从',
      type: '冲动冲浪',
      category: '情绪恢复',
      description: '面对烟瘾、性冲动、刷手机或逃避冲动时，观察波峰而不是立即行动。',
      durationSeconds: 420,
      steps: [
        MeditationStep(startSecond: 0, text: '先不做，也不发誓永远不做。只给自己七分钟，观察这股冲动怎样出现在身体里。'),
        MeditationStep(startSecond: 50, text: '找到最强的位置：嘴、手、胸口、腹部，或脑中不断出现的画面。用“想要、紧、热、躁”来命名。'),
        MeditationStep(startSecond: 105, text: '冲动像一阵波。它会升高、停留、变化。现在的强烈，不等于它会永远保持同样强度。'),
        MeditationStep(startSecond: 160, text: '慢慢呼气，把双手放在看得见的地方。你不需要消灭欲望，只练习在欲望和动作之间留出距离。'),
        MeditationStep(startSecond: 220, text: '从零到十分给冲动打分。过一分钟再打一次。只记录变化，不要求分数必须下降。'),
        MeditationStep(startSecond: 280, text: '问自己：这股冲动还想替我解决什么？无聊、孤独、压力、困倦？选择一个更直接照顾需要的小动作。'),
        MeditationStep(startSecond: 340, text: '喝水、站起来、走到公共区域、把设备放远，或联系一个人。让环境帮助选择，而不是只靠忍。'),
        MeditationStep(startSecond: 395, text: '最后说：我可以有冲动，也可以暂时不执行它。现在再为接下来的十分钟做一次选择。'),
      ],
      endingReflection: '自控不是从此没有欲望，而是在一次冲动里重新获得几分钟选择权。',
    ),
    MeditationSessionTemplate(
      key: 'knowledge_to_action_8m',
      title: '8分钟从懂得回到做到',
      type: '知行转换',
      category: '行动与执行',
      description: '理论越学越多却没有行动时，停止继续理解，完成一个可观察动作。',
      durationSeconds: 480,
      steps: [
        MeditationStep(startSecond: 0, text: '先把所有理论暂时放在旁边。你不需要再找一句更有力量的话，才有资格开始。'),
        MeditationStep(startSecond: 55, text: '感受身体。知识存在于头脑里，行动要经过手、脚、时间和环境。现在把注意力带到这些地方。'),
        MeditationStep(startSecond: 110, text: '想一个你已经知道很久、却没有做到的原则。只选一个，不把整套人生哲学一起搬来。'),
        MeditationStep(startSecond: 170, text: '把原则翻译成摄像机能拍到的画面。不是“面对困难”，而是“九点走进面试地点”；不是“自律”，而是“闹钟响后双脚落地”。'),
        MeditationStep(startSecond: 230, text: '如果画面仍然太大，再缩小一次。让动作可以在五分钟内启动，并有清楚的开始标志。'),
        MeditationStep(startSecond: 295, text: '在心里说：知识今天只需要完成一次转移——从一句话，转移到一个身体动作。'),
        MeditationStep(startSecond: 360, text: '不等待自己完全认同、完全有动力。先让动作产生新经验，再用经验修正知识。'),
        MeditationStep(startSecond: 425, text: '最后明确说出：练习结束后，我立刻做的是……然后起身，不再继续阅读新的方法。'),
      ],
      endingReflection: '真正改变你的不是今天又理解了多少，而是有一个观念终于穿过身体，成为了事实。',
    ),
    MeditationSessionTemplate(
      key: 'inner_survivor_safety_10m',
      title: '10分钟让曾经硬撑的自己休息',
      type: '生存模式安抚',
      category: '个性化恢复',
      description: '旧日贫困、远行、羞耻或无助被唤起时，留在当下，不重新沉入旧画面。',
      durationSeconds: 600,
      steps: [
        MeditationStep(startSecond: 0, text: '先睁着眼看周围。说出今天的日期、你所在的地方，并找出三件眼前真实存在的物品。'),
        MeditationStep(startSecond: 65, text: '感受脚底和背部。现在的身体在这里，不在过去那个必须独自硬撑、想尽办法活下来的地方。'),
        MeditationStep(startSecond: 130, text: '如果旧画面出现，不追进去。只说：我记得那很难，但此刻我在这个房间里。'),
        MeditationStep(startSecond: 195, text: '把一只手放在胸口或手臂上，给身体清楚的触点。慢慢呼气，让眼睛继续看着现在。'),
        MeditationStep(startSecond: 260, text: '那个曾经的你学会警惕、隐忍、独自承担，因为当时资源很少。先感谢这些办法曾经保护生命。'),
        MeditationStep(startSecond: 330, text: '然后告诉他：现在不必每一刻都像危险马上回来。我们可以检查事实、寻找帮助、用新的方式保护自己。'),
        MeditationStep(startSecond: 400, text: '注意房间里一个相对安全的细节：门锁、灯光、水、手机、可以联系的人。让安全来自具体事实。'),
        MeditationStep(startSecond: 470, text: '不要求过去立刻消失。只让身体学习一个新经验：记忆可以出现，而我仍能留在现在。'),
        MeditationStep(startSecond: 535, text: '最后对曾经硬撑的自己说：你已经把我带到这里。接下来我会尽量不再只靠伤害自己来前进。'),
      ],
      endingReflection: '过去的你负责活下来；现在的你可以在安全、连接和现实支持中继续生活。',
    ),
  ];

  static MeditationSessionTemplate defaultForState(String state) {
    switch (state) {
      case '被外界影响':
      case '被羞辱后反刍':
        return byKey('attention_sovereignty_8m');
      case '自责羞耻':
        return byKey('shame_self_blame_release_9m');
      case '行动卡住':
        return byKey('action_start_stability_9m');
      case '身体紧绷':
        return byKey('body_home_after_pain_8m');
      case '需要定力':
        return byKey('calm_mountain_8m');
      case '价值感受挫':
        return byKey('self_worth_repair_11m');
      case '早晨起不来':
        return byKey('morning_leave_bed_7m');
      case '面试或上班前想逃':
        return byKey('appointment_courage_8m');
      case '得到机会后犹豫':
        return byKey('opportunity_commitment_8m');
      case '害怕新工作不适应':
        return byKey('new_job_adaptation_10m');
      case '完美主义卡住':
        return byKey('good_enough_action_8m');
      case '害怕进入不舒服':
        return byKey('learning_zone_exposure_9m');
      case '决策瘫痪':
        return byKey('decision_grounding_9m');
      case '因失业怕被看见':
        return byKey('unemployment_visibility_10m');
      case '害怕别人评价':
        return byKey('social_evaluation_release_8m');
      case '错失机会后悔':
        return byKey('missed_chance_regret_10m');
      case '经济压力很大':
        return byKey('financial_pressure_grounding_8m');
      case '感到孤独或思念':
        return byKey('loneliness_connection_10m');
      case '冲动很强':
        return byKey('urge_surfing_7m');
      case '学了很多却做不到':
        return byKey('knowledge_to_action_8m');
      case '焦虑紧张':
      case '心很乱':
        return byKey('breath_anchor_3m');
      case '疲惫无力':
        return byKey('body_scan_10m');
      case '想专注':
        return byKey('focus_return_5m');
      case '睡前放松':
        return byKey('sleep_release_10m');
      case '日常练习':
      default:
        return byKey('calm_mountain_8m');
    }
  }

  static MeditationSessionTemplate byKey(String key) {
    return sessions.firstWhere((e) => e.key == key, orElse: () => sessions.first);
  }

  static Map<String, List<MeditationSessionTemplate>> groupedByCategory({bool sleepOnly = false}) {
    final Map<String, List<MeditationSessionTemplate>> result = {};
    for (final session in sessions) {
      if (sleepOnly && !session.isSleep) continue;
      if (!sleepOnly && session.isSleep) continue;
      result.putIfAbsent(session.category, () => <MeditationSessionTemplate>[]).add(session);
    }
    return result;
  }
}
