import 'boundary_action_coach_models.dart';
import 'boundary_action_coach_prompt_config.dart';

class BoundaryActionCoachCatalog {
  static const List<String> actionLoop = <String>[
    '发生事件',
    'AI 识别边界类型',
    '区分我的/你的/共同责任',
    '判断 burdens 与 loads',
    '设计边界',
    '生成沟通话术',
    '预测阻力',
    '制定 24 小时与 7 天行动',
    '复盘成长',
  ];

  static const List<BoundaryFeatureModule> modules = <BoundaryFeatureModule>[
    BoundaryFeatureModule(
      title: '1. 边界诊断中心',
      problemSolved: '用户不知道自己哪里没边界。',
      coreValue: '真相、责任、成熟',
      promptId: BoundaryActionCoachPromptConfig.diagnosisId,
      releasePhase: 'MVP 1.0',
      landed: true,
      subFeatures: <String>['边界健康测评 10 维', '关系边界雷达图', '怨气警报器', '顺从/逃避/控制/不回应/自我边界风险识别'],
      aiOutputs: <String>['边界类型', '高风险关系领域', '怨气解释', '下一步小不练习'],
      dataObjects: <String>['BoundaryCase', 'RelationshipProfile', 'BoundaryGrowthStage'],
    ),
    BoundaryFeatureModule(
      title: '2. 责任归属地图',
      problemSolved: '混淆“我的责任”和“别人的责任”。',
      coreValue: '责任、自由、后果',
      promptId: BoundaryActionCoachPromptConfig.responsibilityMapId,
      releasePhase: 'MVP 1.0',
      landed: true,
      subFeatures: <String>['我的院子/你的院子分类器', 'burdens 与 loads 判断器', '后果错位检测', '有限帮助范围生成'],
      aiOutputs: <String>['三栏责任表', 'burden/load 判定', '后果当前承担者', '后果应回归对象'],
      dataObjects: <String>['ResponsibilityMap'],
    ),
    BoundaryFeatureModule(
      title: '3. 场景 AI 教练',
      problemSolved: '真实关系中不知道怎么做。',
      coreValue: '爱、真相、尊重',
      promptId: BoundaryActionCoachPromptConfig.commonSceneId,
      releasePhase: 'MVP 1.0',
      landed: true,
      subFeatures: <String>['原生家庭', '朋友', '婚姻/亲密关系', '育儿', '职场', '自我边界', '信仰/价值观', '阻力应对'],
      aiOutputs: <String>['场景摘要', '核心价值', '建议边界', '阻力预测', '行动计划'],
      dataObjects: <String>['BoundaryCase', 'RelationshipProfile', 'ResponsibilityMap'],
    ),
    BoundaryFeatureModule(
      title: '4. 沟通话术工坊',
      problemSolved: '不知道如何说“不”。',
      coreValue: '真实、尊重、温柔坚定',
      promptId: BoundaryActionCoachPromptConfig.scriptsId,
      releasePhase: 'MVP 1.0',
      landed: true,
      subFeatures: <String>['温柔拒绝型', '有限帮助型', '后果说明型', '关系保留型', '语气调节', '话术检查器'],
      aiOutputs: <String>['温柔版', '简短版', '高压重复版', '高冲突版', '检查提醒'],
      dataObjects: <String>['BoundaryScriptSet'],
    ),
    BoundaryFeatureModule(
      title: '5. 后果设计器',
      problemSolved: '边界没有实际执行力。',
      coreValue: '后果、行动、成熟',
      promptId: BoundaryActionCoachPromptConfig.consequencesId,
      releasePhase: 'MVP 1.0',
      landed: true,
      subFeatures: <String>['自然后果设计', '后果与惩罚区分', '执行难度评估', '安全风险提醒'],
      aiOutputs: <String>['自然后果', '非报复检查', '执行预案', '分阶段行动'],
      dataObjects: <String>['BoundaryCase', 'ResponsibilityMap'],
    ),
    BoundaryFeatureModule(
      title: '6. AI 角色扮演训练',
      problemSolved: '害怕面对愤怒、内疚、操控。',
      coreValue: '勇气、练习、支持',
      promptId: BoundaryActionCoachPromptConfig.roleplayId,
      releasePhase: '2.0',
      landed: true,
      subFeatures: <String>['10 类角色', '初级模式', '中级反击模式', '高级连续施压', '评分维度'],
      aiOutputs: <String>['对方台词', '用户回应评分', '温柔坚定建议', '过度解释提醒'],
      dataObjects: <String>['BoundaryScriptSet', 'BoundaryGrowthStage'],
    ),
    BoundaryFeatureModule(
      title: '7. 支持系统模块',
      problemSolved: '用户孤立无援，容易退回旧模式。',
      coreValue: '恩典、连接、群体',
      promptId: BoundaryActionCoachPromptConfig.supportId,
      releasePhase: '2.0',
      landed: true,
      subFeatures: <String>['支持者名单', '行动前提醒', '行动后复盘', '问责伙伴', '咨询师/支持小组记录', '紧急安全联系人'],
      aiOutputs: <String>['支持建议', '孤立风险', '复盘提醒', '安全升级建议'],
      dataObjects: <String>['RelationshipProfile', 'BoundaryGrowthStage'],
    ),
    BoundaryFeatureModule(
      title: '8. 自我边界管理',
      problemSolved: '时间、金钱、饮食、情绪失控。',
      coreValue: '管家意识、自律',
      promptId: BoundaryActionCoachPromptConfig.selfBoundaryId,
      releasePhase: '2.0',
      landed: true,
      subFeatures: <String>['时间边界', '金钱边界', '身体边界', '语言边界', '欲望与成瘾风险'],
      aiOutputs: <String>['小限制', '环境设计', '外部支持', '复盘问题'],
      dataObjects: <String>['BoundaryCase', 'BoundaryGrowthStage'],
    ),
    BoundaryFeatureModule(
      title: '9. 成长路径追踪',
      problemSolved: '不知道自己是否进步。',
      coreValue: '主动、成熟、价值驱动',
      promptId: BoundaryActionCoachPromptConfig.growthId,
      releasePhase: 'MVP 1.0',
      landed: true,
      subFeatures: <String>['11 个成长阶段', '当前阶段任务', '本周小不', '本周自由的是', '复盘报告', '价值驱动目标'],
      aiOutputs: <String>['成长阶段', '罪疚/怨气变化', '下周练习', '价值提醒'],
      dataObjects: <String>['BoundaryGrowthStage'],
    ),
    BoundaryFeatureModule(
      title: '10. 学习与案例库',
      problemSolved: '需要理解书中思想与案例。',
      coreValue: '价值体系内化',
      promptId: BoundaryActionCoachPromptConfig.learningId,
      releasePhase: '2.0',
      landed: true,
      subFeatures: <String>['16 个学习主题', '8 类抽象案例卡', '书中概念行动化', '有边界的一天'],
      aiOutputs: <String>['概念卡', '案例原型', '行动练习', '复盘问题'],
      dataObjects: <String>['BoundaryCase', 'BoundaryScriptSet'],
    ),
  ];
}
