import 'will_models.dart';

const List<WillUnitIndex> kWillUnitIndexes = [
  WillUnitIndex(id: 'D-001', moduleCode: 'D', moduleTitle: '导论', title: '欲望、愿望、意志的区分', oneLiner: '当目标被视为可实现时，欲望才进入“意志”状态。', tags: ['目标感', '执行启动']),
  WillUnitIndex(id: 'D-002', moduleCode: 'D', moduleTitle: '导论', title: '意志最直接的对象是身体运动', oneLiner: '意志对外界最直接的作用，不是结果本身，而是先引发身体动作。', tags: ['执行机制', '行动理解']),
  WillUnitIndex(id: 'D-003', moduleCode: 'D', moduleTitle: '导论', title: '自愿运动是次级功能', oneLiner: '任何真正自愿的动作，都建立在先前非自愿动作经验之上。', tags: ['经验学习', '动作习得']),
  WillUnitIndex(id: 'D-004', moduleCode: 'D', moduleTitle: '导论', title: '动作观念来自既往经验', oneLiner: '一个动作必须先被做过，才可能被再次意愿。', tags: ['技能学习', '动作脚本']),
  WillUnitIndex(id: 'D-005', moduleCode: 'D', moduleTitle: '导论', title: '动作可留下多种远端表象', oneLiner: '看见、听见、触到的远端效果，都能构成动作的记忆表象。', tags: ['表征方式', '学习差异']),
  WillUnitIndex(id: 'D-006', moduleCode: 'D', moduleTitle: '导论', title: '动觉印象是动作的本地感觉', oneLiner: '动作发生时，肌肉、关节、皮肤会留下独特的本地感觉。', tags: ['身体觉察', '动作精确']),
  WillUnitIndex(id: 'D-007', moduleCode: 'D', moduleTitle: '导论', title: '姿态感依赖本地动觉印象', oneLiner: '我们能感觉自己的肢体位置，是因为本地动觉系统在工作。', tags: ['姿态感', '身体意识']),
  WillUnitIndex(id: 'D-008', moduleCode: 'D', moduleTitle: '导论', title: '全身感觉丧失时的麻木男孩', oneLiner: '当本地与被动运动感觉丧失时，人会失去对自己动作状态的直接把握。', tags: ['失控感', '身体脱节']),
  WillUnitIndex(id: 'D-009', moduleCode: 'D', moduleTitle: '导论', title: '麻木男孩看不见自己的动作状态', oneLiner: '没有本地感觉时，人会误以为自己正在完成动作。', tags: ['行动错觉', '自我监控']),
  WillUnitIndex(id: 'D-010', moduleCode: 'D', moduleTitle: '导论', title: '类似病例提示问题普遍存在', oneLiner: '麻木并非个例，而是一类可重复观察的现象。', tags: ['诊断意识', '问题识别']),
  WillUnitIndex(id: 'D-011', moduleCode: 'D', moduleTitle: '导论', title: '闭眼后无法判断动作是否发生', oneLiner: '失去动作反馈时，自愿运动会丧失幅度与存在感判断。', tags: ['反馈不足', '闭环缺失']),
  WillUnitIndex(id: 'D-012', moduleCode: 'D', moduleTitle: '导论', title: '另一病例引出不熟练动作问题', oneLiner: '动作越不熟练，越依赖在线感觉反馈。', tags: ['新手困境', '技能迁移']),
  WillUnitIndex(id: 'D-013', moduleCode: 'D', moduleTitle: '导论', title: '不熟练动作离开视觉会瓦解', oneLiner: '闭眼会让不熟练动作停在中途，说明引导性感觉不可缺。', tags: ['学习期动作', '注意中断']),
  WillUnitIndex(id: 'D-014', moduleCode: 'D', moduleTitle: '导论', title: '催眠可复制动作失感', oneLiner: '动作反馈缺失并非只出现在器质病变，也可实验性制造。', tags: ['意识实验', '可塑性']),
  WillUnitIndex(id: 'D-015', moduleCode: 'D', moduleTitle: '导论', title: '连锁动作需要引导性感觉', oneLiner: '动作链若没有每一步的感觉定位，就会很快迷失。', tags: ['流程执行', '复杂任务']),
  WillUnitIndex(id: 'D-016', moduleCode: 'D', moduleTitle: '导论', title: '视觉可暂时替代动觉成为向导', oneLiner: '当动觉失效时，视觉能接管部分动作引导功能。', tags: ['外部提示', '视觉依赖']),
  WillUnitIndex(id: 'D-017', moduleCode: 'D', moduleTitle: '导论', title: '另一病例支持视觉补偿作用', oneLiner: '失去动觉的人仍可依赖视觉完成部分动作。', tags: ['补偿机制', '代偿路径']),
  WillUnitIndex(id: 'D-018', moduleCode: 'D', moduleTitle: '导论', title: '闭眼后对指与合手变得失准', oneLiner: '没有视觉与动觉引导，空间动作会迅速失准。', tags: ['精细动作', '身体定位']),
  WillUnitIndex(id: 'D-019', moduleCode: 'D', moduleTitle: '导论', title: '说话与书写也靠感觉引导', oneLiner: '发音、书写等技能同样依赖远端或本地感觉作线索。', tags: ['表达学习', '技能训练']),
  WillUnitIndex(id: 'D-020', moduleCode: 'D', moduleTitle: '导论', title: '自愿动作至少需要一个动作观念', oneLiner: '想做某动作时，心里至少得有界定该动作的感觉图像。', tags: ['行动前表象', '执行准备']),
  WillUnitIndex(id: 'D-021', moduleCode: 'D', moduleTitle: '导论', title: '简单自愿动作未必需要额外成分', oneLiner: '在最简单的意志行为中，动作观念本身就可能足够。', tags: ['启动', '行动简化']),
  WillUnitIndex(id: 'D-022', moduleCode: 'D', moduleTitle: '导论', title: '传统理论引入神经支配感', oneLiner: '许多人认为，动作前必须感觉到一股向肌肉发出的特殊支配。', tags: ['理论误解', '神秘化意志']),
  WillUnitIndex(id: 'D-023', moduleCode: 'D', moduleTitle: '导论', title: '神经支配感之所以像真的是因精细动作体验', oneLiner: '困难精细动作让人误以为自己感到了“外发电流”。', tags: ['精细控制', '主观错觉']),
  WillUnitIndex(id: 'D-024', moduleCode: 'D', moduleTitle: '导论', title: '作者主张外发放电本身无感觉', oneLiner: '我们能意识到的是周边感觉的预期，不是神经放电本身。', tags: ['去神秘化', '动作表象']),
  WillUnitIndex(id: 'D-025', moduleCode: 'D', moduleTitle: '导论', title: '神经支配感应先被怀疑而非默认存在', oneLiner: '若无必要且无证据，就不该引入这种感觉。', tags: ['理论判断', '概念清理']),
  WillUnitIndex(id: 'D-026', moduleCode: 'D', moduleTitle: '导论', title: '即便没有支配感也足以解释自愿动作', oneLiner: '动作表象已足够承担解释功能。', tags: ['简化模型', '理论替代']),
  WillUnitIndex(id: 'D-027', moduleCode: 'D', moduleTitle: '导论', title: '结果不必先以相似形式包含在原因中', oneLiner: '心理原因并不需要长得像身体结果。', tags: ['因果理解', '错误类比']),
  WillUnitIndex(id: 'D-028', moduleCode: 'D', moduleTitle: '导论', title: '动觉观念完全可能充当最后心理前因', oneLiner: '传入感觉的表象可以直接成为动作前的决定者。', tags: ['表象驱动', '行动前念头']),
  WillUnitIndex(id: 'D-029', moduleCode: 'D', moduleTitle: '导论', title: '先验上更应期待动觉图像而非支配感', oneLiner: '最合理的模型是“有感觉的观念＋无感觉的放电”。', tags: ['模型选择', '理论优先级']),
  WillUnitIndex(id: 'D-030', moduleCode: 'D', moduleTitle: '导论', title: '无用的意识会逐渐退出过程', oneLiner: '技能发展会淘汰那些对行动没有指示价值的感觉。', tags: ['自动化', '熟练化']),
  WillUnitIndex(id: 'D-031', moduleCode: 'D', moduleTitle: '导论', title: '熟练者只想目的，不再想手段', oneLiner: '高手的意识越来越集中在目标，而非具体用力方式。', tags: ['熟练技能', '专家行为']),
  WillUnitIndex(id: 'D-032', moduleCode: 'D', moduleTitle: '导论', title: '最经济的机制是“动作结果图像直接连动作”', oneLiner: '心理线索越短，动作越稳定、越精确。', tags: ['高效行动', '认知负荷']),
  WillUnitIndex(id: 'D-033', moduleCode: 'D', moduleTitle: '导论', title: '支配感理论既不经济也不更精确', oneLiner: '在动作结果图像和实际动作之间再插一步并无好处。', tags: ['冗余中介', '模型简化']),
  WillUnitIndex(id: 'D-034', moduleCode: 'D', moduleTitle: '导论', title: '若真有支配感，内省应能直接抓到它', oneLiner: '直接证据应当来自明确内省区分。', tags: ['证据标准', '内省判断']),
  WillUnitIndex(id: 'D-035', moduleCode: 'D', moduleTitle: '导论', title: '内省抓到的始终是动作结果感觉图像', oneLiner: '抬手、弯指的想法，本质上是“那样做会怎样感觉”的想法。', tags: ['行动想象', '身体意象']),
  WillUnitIndex(id: 'D-036', moduleCode: 'D', moduleTitle: '导论', title: '我们对具体运动放电过程其实高度无意识', oneLiner: '既然不知道每块肌肉如何放电，就难说能感觉到各自支配。', tags: ['无意识机制', '主观局限']),
  WillUnitIndex(id: 'D-037', moduleCode: 'D', moduleTitle: '导论', title: '力度感来自传入感觉而非外发感觉', oneLiner: '用多大力，是由身体回来的复杂感觉界定的。', tags: ['力度控制', '身体反馈']),
  WillUnitIndex(id: 'D-038', moduleCode: 'D', moduleTitle: '导论', title: '剥离动作结果图像后，意志会落入真空', oneLiner: '没有结果感觉的想法，意志就失去方向。', tags: ['目标表象', '行动定位']),
  WillUnitIndex(id: 'D-039', moduleCode: 'D', moduleTitle: '导论', title: '动作前还剩一个恒定系数：fiat', oneLiner: '除了动作结果表象，还可能有“让它发生”的同意成分。', tags: ['同意', '执行许可']),
  WillUnitIndex(id: 'D-040', moduleCode: 'D', moduleTitle: '导论', title: '自愿行为前可辨认的只有结果图像与fiat', oneLiner: '我们没有证据证明还有并行的支配感。', tags: ['意志结构', '心理前态']),
  WillUnitIndex(id: 'D-041', moduleCode: 'D', moduleTitle: '导论', title: '对重量的精细调节也能靠结果预期完成', oneLiner: '举起物体的用力差异，可由预期的感觉结果细致调节。', tags: ['精细控制', '现实适配']),
  WillUnitIndex(id: 'D-042', moduleCode: 'D', moduleTitle: '导论', title: '接下来转向所谓间接证据', oneLiner: '既然内省证据不足，就审查情境证据。', tags: ['证据审查', '论证推进']),
  WillUnitIndex(id: 'D-043', moduleCode: 'D', moduleTitle: '导论', title: '温特用半瘫病例为支配感辩护', oneLiner: '他认为努力感随支配冲动强度而变，而非随实际工作量。', tags: ['半瘫', '努力感解释']),
  WillUnitIndex(id: 'D-044', moduleCode: 'D', moduleTitle: '导论', title: '完全瘫痪似乎更像支配感证据', oneLiner: '肢体不动但人仍感到极度努力。', tags: ['瘫痪', '主观用力']),
  WillUnitIndex(id: 'D-045', moduleCode: 'D', moduleTitle: '导论', title: 'Ferrier 开始反驳温特', oneLiner: '问题在于所谓“无动作”其实很难成立。', tags: ['反证', '证据拆解']),
  WillUnitIndex(id: 'D-046', moduleCode: 'D', moduleTitle: '导论', title: '瘫痪者常在别处做了真实用力', oneLiner: '努力感可能来自健侧或其他部位的实际收缩。', tags: ['代偿', '混入因素']),
  WillUnitIndex(id: 'D-047', moduleCode: 'D', moduleTitle: '导论', title: '即便排除代偿，也能另行解释努力感', oneLiner: '真正关键是看努力感是否总伴随某处真实收缩。', tags: ['验证设计', '努力来源']),
  WillUnitIndex(id: 'D-048', moduleCode: 'D', moduleTitle: '导论', title: '扣扳机实验显示努力感依赖呼吸肌固定', oneLiner: '许多所谓“纯意志努力”其实伴随胸部与声门用力。', tags: ['努力体验', '呼吸参与']),
  WillUnitIndex(id: 'D-049', moduleCode: 'D', moduleTitle: '导论', title: 'Ferrier 认为找不到不靠实际收缩的努力感', oneLiner: '只要有努力感，就总能找到某处真实肌肉活动。', tags: ['肌肉收缩', '努力条件']),
  WillUnitIndex(id: 'D-050', moduleCode: 'D', moduleTitle: '导论', title: '作者接受 Ferrier 的结论', oneLiner: '努力感属于传入结果，而非外发先因。', tags: ['理论定案', '努力来源']),
  WillUnitIndex(id: 'D-051', moduleCode: 'D', moduleTitle: '导论', title: '支配感最后的堡垒转移到眼外肌', oneLiner: '接下来审查视觉眩晕与眼肌麻痹案例。', tags: ['眼肌', '视觉错觉']),
  WillUnitIndex(id: 'D-052', moduleCode: 'D', moduleTitle: '导论', title: '判断物体运动有两种基本情形', oneLiner: '运动知觉取决于视网膜像与眼动判断的组合。', tags: ['知觉结构', '视觉判断']),
  WillUnitIndex(id: 'D-053', moduleCode: 'D', moduleTitle: '导论', title: '情形一：像动而眼静', oneLiner: '若眼不动，视网膜像动就判断物体在动。', tags: ['基础知觉', '运动判断']),
  WillUnitIndex(id: 'D-054', moduleCode: 'D', moduleTitle: '导论', title: '情形二：像静而眼动', oneLiner: '若眼在动而像保持，便觉得自己在追随物体。', tags: ['追随知觉', '眼动']),
  WillUnitIndex(id: 'D-055', moduleCode: 'D', moduleTitle: '导论', title: '视觉眩晕来自对眼动状态的误判', oneLiner: '错把眼动当眼静，或反之，都会制造假运动。', tags: ['错觉机制', '知觉偏差']),
  WillUnitIndex(id: 'D-056', moduleCode: 'D', moduleTitle: '导论', title: '急流与车窗错觉说明“眼在动却以为不动”', oneLiner: '持续不自主眼动会让静物看似移动。', tags: ['视觉眩晕', '余动']),
  WillUnitIndex(id: 'D-057', moduleCode: 'D', moduleTitle: '导论', title: '眼不动却以为在动也会生错觉', oneLiner: '某些眼肌麻痹案例被当成支配感证据。', tags: ['麻痹错觉', '运动归因']),
  WillUnitIndex(id: 'D-058', moduleCode: 'D', moduleTitle: '导论', title: '外直肌麻痹使物体似乎飞走', oneLiner: '眼未真正外转，但患者觉得视线已外转。', tags: ['外直肌', '错位知觉']),
  WillUnitIndex(id: 'D-059', moduleCode: 'D', moduleTitle: '导论', title: '亥姆霍兹据此认为方向判断依赖支配冲动', oneLiner: '他把视线方向知觉归因于转眼时的意志冲动。', tags: ['方向判断', '支配论']),
  WillUnitIndex(id: 'D-060', moduleCode: 'D', moduleTitle: '导论', title: '部分麻痹看起来更支持独立支配感', oneLiner: '同一意志刺激带来较小角度，患者却觉得自己转到了极限。', tags: ['部分麻痹', '主观过估']),
  WillUnitIndex(id: 'D-061', moduleCode: 'D', moduleTitle: '导论', title: '部分麻痹中主观转角大于实际转角', oneLiner: '患者按主观极限去定位目标，因而指向错误。', tags: ['空间偏差', '动作定位']),
  WillUnitIndex(id: 'D-062', moduleCode: 'D', moduleTitle: '导论', title: '石匠敲到手而非凿子是生活例证', oneLiner: '错误的空间定位会直接带来行动偏差。', tags: ['实践后果', '动作误差']),
  WillUnitIndex(id: 'D-063', moduleCode: 'D', moduleTitle: '导论', title: '支持者据此认为只有支配感差异能解释偏差', oneLiner: '因为表面上传入资料看似都一样。', tags: ['论证高潮', '单因归因']),
  WillUnitIndex(id: 'D-064', moduleCode: 'D', moduleTitle: '导论', title: '作者指出他们漏掉了另一只眼的感觉', oneLiner: '被遮住的健眼并非没有贡献。', tags: ['双眼系统', '证据漏洞']),
  WillUnitIndex(id: 'D-065', moduleCode: 'D', moduleTitle: '导论', title: '完全麻痹时健眼极限转动提供强烈传入感觉', oneLiner: '患者其实是用健眼的转动感误判了总体眼位。', tags: ['双眼代偿', '感觉来源']),
  WillUnitIndex(id: 'D-066', moduleCode: 'D', moduleTitle: '导论', title: '接着转向部分麻痹中的视野移位', oneLiner: '问题不在单眼，而在双眼协同。', tags: ['双眼协调', '视野移位']),
  WillUnitIndex(id: 'D-067', moduleCode: 'D', moduleTitle: '导论', title: '患者手指方向跟随的是被遮住那只眼', oneLiner: '行为证据支持“另一眼感觉在起作用”。', tags: ['定位行为', '隐藏线索']),
  WillUnitIndex(id: 'D-068', moduleCode: 'D', moduleTitle: '导论', title: '双眼感觉本来就会被整合使用', oneLiner: '双眼更像一个统一器官，而非两套完全分离的系统。', tags: ['双眼整合', '统一知觉']),
  WillUnitIndex(id: 'D-069', moduleCode: 'D', moduleTitle: '导论', title: '第二类旁证：马赫的流水与油布错觉', oneLiner: '接下来处理另一条被用来支持支配感的观察。', tags: ['Mach', '背景运动']),
  WillUnitIndex(id: 'D-070', moduleCode: 'D', moduleTitle: '导论', title: '马赫用流水和油布装置研究相对运动错觉', oneLiner: '同样相对运动可被归因于环境动或自我动。', tags: ['相对运动', '实验装置']),
  WillUnitIndex(id: 'D-071', moduleCode: 'D', moduleTitle: '导论', title: '马赫提出自己的解释', oneLiner: '他把固定凝视时的错觉归为持续支配作用。', tags: ['解释提出', '理论转折']),
  WillUnitIndex(id: 'D-072', moduleCode: 'D', moduleTitle: '导论', title: '马赫认为固定凝视是支配电流抵消追随冲动', oneLiner: '所以环境看似反向移动。', tags: ['抵消模型', '眼动控制']),
  WillUnitIndex(id: 'D-073', moduleCode: 'D', moduleTitle: '导论', title: '作者认为更自然的解释是“对象/背景切换”', oneLiner: '错觉来自注意结构变化，不必诉诸支配感。', tags: ['注意分配', '背景切换']),
  WillUnitIndex(id: 'D-074', moduleCode: 'D', moduleTitle: '导论', title: '旁证像直接证据一样崩溃', oneLiner: '不仅证明不了支配感，还能被反证实验击倒。', tags: ['旁证失败', '反证']),
  WillUnitIndex(id: 'D-075', moduleCode: 'D', moduleTitle: '导论', title: '麻木病人分不清重量与阻力', oneLiner: '若真能感觉支配，完全麻木时应仍能判断工作量，但事实不是。', tags: ['感觉缺失', '重量判断']),
  WillUnitIndex(id: 'D-076', moduleCode: 'D', moduleTitle: '导论', title: 'Bloch 证明位置感不靠支配意识', oneLiner: '肢体位置与动作空间性质不随“支配多少”而变。', tags: ['位置感', '空间表征']),
  WillUnitIndex(id: 'D-077', moduleCode: 'D', moduleTitle: '导论', title: '真正的主动性应放在选择与同意上', oneLiner: '精神的主动，不在外发电流的感觉，而在观念的选择与拥抱。', tags: ['主动性', '同意']),
  WillUnitIndex(id: 'D-078', moduleCode: 'D', moduleTitle: '导论', title: '接下来问：动作线索究竟可来自哪类感觉', oneLiner: '本地与远端图像，是否都能成为动作线索？', tags: ['线索来源', '感觉分类']),
  WillUnitIndex(id: 'D-079', moduleCode: 'D', moduleTitle: '导论', title: '答案是两类都可以', oneLiner: '动作熟练后，心理线索会越来越远端化。', tags: ['熟练迁移', '表象演化']),
  WillUnitIndex(id: 'D-080', moduleCode: 'D', moduleTitle: '导论', title: '写字时常先“听见词”而非“看见手”', oneLiner: '熟练动作中，本地感觉会迅速退场。', tags: ['写字', '内在表象']),
  WillUnitIndex(id: 'D-081', moduleCode: 'D', moduleTitle: '导论', title: '流畅动作通常只在开头有一个总的 fiat', oneLiner: '之后多由目的观念与引导性感觉链自动推进。', tags: ['流畅执行', '开始许可']),
  WillUnitIndex(id: 'D-082', moduleCode: 'D', moduleTitle: '导论', title: '个体在表象类型上差异很大', oneLiner: '不同人更依赖不同感觉表象，不必强求单一模板。', tags: ['个体差异', '学习风格']),
  WillUnitIndex(id: 'D-083', moduleCode: 'D', moduleTitle: '导论', title: '导论结论：动作观念是可感效果的预期', oneLiner: '它不是支配思想；fiat 的复杂性引向下一节。', tags: ['动作观念', 'fiat过渡']),
  WillUnitIndex(id: 'I-001', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '单纯动作观念是否足以引发动作', oneLiner: '本节要问：想到动作本身，能不能就让它发生。', tags: ['启动', '执行机制']),
  WillUnitIndex(id: 'I-002', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '作者回答：有时足够，有时还需 fiat', oneLiner: '最简单的意志行为可由单纯观念触发。', tags: ['行为复杂度', '同意']),
  WillUnitIndex(id: 'I-003', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '观念—运动作用的定义', oneLiner: '只要想到动作后它立刻发生，就是观念—运动作用。', tags: ['想到就做', '自动执行']),
  WillUnitIndex(id: 'I-004', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '很多日常动作都属观念—运动作用', oneLiner: '掸灰、捡针、说话、走动，常无需明确命令。', tags: ['生活自动性', '微动作']),
  WillUnitIndex(id: 'I-005', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '复杂技能也常由思想流动直接带出', oneLiner: '写字、弹琴、起身、走路，并不需要一连串独立命令。', tags: ['技能流', '自动化']),
  WillUnitIndex(id: 'I-006', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '没有冲突观念时，观念会几乎必然转成动作', oneLiner: '动作之所以能自然跟上，是因为心中没有反向阻滞。', tags: ['低阻力', '行动顺畅']),
  WillUnitIndex(id: 'I-007', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '催眠与模仿显示“空心境”会增强观念—动作转换', oneLiner: '缺少竞争观念时，暗示极易转成行为。', tags: ['暗示性', '模仿']),
  WillUnitIndex(id: 'I-008', moduleCode: 'I', moduleTitle: '观念—运动作用', title: 'Féré 例子说明动觉观念可让中枢提前进入放电准备', oneLiner: '先看、先感、先被动重复，都能增强主动动作。', tags: ['动作预热', '技能激活']),
  WillUnitIndex(id: 'I-009', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '赖床说明很多行动不是靠大战，而是靠观念滑入行动', oneLiner: '真正起身常发生在抑制性观念暂退之时。', tags: ['起床困难', '启动机制']),
  WillUnitIndex(id: 'I-010', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '当抑制性观念消失时，原初行动观念会立刻生效', oneLiner: '问题往往不是没意愿，而是被相反意识压住。', tags: ['拖延', '卡住原因']),
  WillUnitIndex(id: 'I-011', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '观念不行动时，必有对抗观念在场', oneLiner: '行动失败通常不是缺观念，而是观念冲突。', tags: ['拖延', '冲突识别']),
  WillUnitIndex(id: 'I-012', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '即便被压制，动作也常以萌芽形式出现', oneLiner: '随动、紧张、小动作都是观念半启动的迹象。', tags: ['微动作', '身体信号']),
  WillUnitIndex(id: 'I-013', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '“读心术”实为读肌肉', oneLiner: '所谓意志游戏显示观念会留下可被察觉的微收缩。', tags: ['读肌肉', '行为线索']),
  WillUnitIndex(id: 'I-014', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '本节核心：每个动作观念都会在某程度上唤起动作', oneLiner: '除非有别的表象把它挡住。', tags: ['动作倾向', '表象驱动']),
  WillUnitIndex(id: 'I-015', moduleCode: 'I', moduleTitle: '观念—运动作用', title: 'fiat 出现在需要解除阻滞时', oneLiner: '明确“我要做”往往是为了穿过抑制，而非动作的常态条件。', tags: ['决心', '突破阻滞']),
  WillUnitIndex(id: 'I-016', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '意识本身具有冲动性', oneLiner: '感觉与思想不是静态的，它们天然带着通向动作的趋势。', tags: ['意识动力', '行动源头']),
  WillUnitIndex(id: 'I-017', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '抑制动作也不总需要额外命令', oneLiner: '一个相反观念的出现，本身就足以挡住动作。', tags: ['抑制', '反向表象']),
  WillUnitIndex(id: 'I-018', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '动作与不动作都是观念合力的结果', oneLiner: '同一时刻可能有两股细微神经力在角逐输出。', tags: ['冲突结构', '行为生成']),
  WillUnitIndex(id: 'I-019', moduleCode: 'I', moduleTitle: '观念—运动作用', title: '清醒行为可被视为相反神经力量的合成', oneLiner: '所谓“没有动作”，也只是输出被平衡、改道或缩小。', tags: ['行为总图', '输出观']),
  WillUnitIndex(id: 'A-001', moduleCode: 'A', moduleTitle: '审议/权衡后的行动', title: '审议性行动的定义', oneLiner: '当一个行动观念被其他支持或反对的观念包围时，就进入审议。', tags: ['犹豫', '权衡']),
  WillUnitIndex(id: 'A-002', moduleCode: 'A', moduleTitle: '审议/权衡后的行动', title: '审议是前景与背景动机不断替换的过程', oneLiner: '理由轮流上前，但背景理由持续阻止不可逆放电。', tags: ['摇摆', '迟疑']),
  WillUnitIndex(id: 'A-003', moduleCode: 'A', moduleTitle: '审议/权衡后的行动', title: '决定的形式有多种，本节只做现象学素描', oneLiner: '作者先描述体验样态，不先争论背后因果。', tags: ['现象描述', '决定形态']),
  WillUnitIndex(id: 'A-004', moduleCode: 'A', moduleTitle: '审议/权衡后的行动', title: '厌倦犹豫会推动人尽快做决定', oneLiner: '有时我们不是因为理由充分，而是因为讨厌悬而未决。', tags: ['焦躁决策', '仓促拍板']),
  WillUnitIndex(id: 'A-005', moduleCode: 'A', moduleTitle: '审议/权衡后的行动', title: '害怕不可逆会拖延决定', oneLiner: '对后果不可撤销的恐惧，使人不断往后推迟。', tags: ['决策拖延', '后悔恐惧']),
  WillUnitIndex(id: 'A-006', moduleCode: 'A', moduleTitle: '审议/权衡后的行动', title: '一旦决定就想坚持也是恒常动机', oneLiner: '“不想改变主意”会把既成决定本身变成新的理由。', tags: ['固执', '承诺维持']),
  WillUnitIndex(id: 'T-001', moduleCode: 'T', moduleTitle: '决定的五种类型', title: '理性结账型', oneLiner: '理由逐渐结清余额，最后几乎不费力地采纳占优选项。', tags: ['理性决策', '清晰拍板']),
  WillUnitIndex(id: 'T-002', moduleCode: 'T', moduleTitle: '决定的五种类型', title: '外因推动型', oneLiner: '证据未齐，外部偶然因素把人轻轻推向某一边。', tags: ['随势而定', '被环境推着走']),
  WillUnitIndex(id: 'T-003', moduleCode: 'T', moduleTitle: '决定的五种类型', title: '内在自动放电型', oneLiner: '悬置过久后，内在张力突然向某一角落爆发成决定。', tags: ['突决', '憋久爆发']),
  WillUnitIndex(id: 'T-004', moduleCode: 'T', moduleTitle: '决定的五种类型', title: '价值尺度突变型', oneLiner: '一次外部冲击或内在变调，让整套动机突然重新排序。', tags: ['顿悟', '幡然转变']),
  WillUnitIndex(id: 'T-005', moduleCode: 'T', moduleTitle: '决定的五种类型', title: '努力压舱型', oneLiner: '两边都清楚时，靠自我用力把天平亲手压向一边。', tags: ['艰难抉择', '知行一致']),
  WillUnitIndex(id: 'E-001', moduleCode: 'E', moduleTitle: '努力感', title: '意识要足够强才有冲动效力', oneLiner: '不是任何观念都能激发动作为，强度与阈值很关键。', tags: ['弱动机', '启动困难']),
  WillUnitIndex(id: 'E-002', moduleCode: 'E', moduleTitle: '努力感', title: '健康意志有一套常态的动机强弱比例', oneLiner: '近、习惯、本能、快痛等通常更有即刻冲动性。', tags: ['动机结构', '正常比例']),
  WillUnitIndex(id: 'E-003', moduleCode: 'E', moduleTitle: '努力感', title: '努力的正常领域是让非本能动机取胜', oneLiner: '遥远、抽象、不习惯的理由常需努力支撑。', tags: ['长期目标', '自律']),
  WillUnitIndex(id: 'E-004', moduleCode: 'E', moduleTitle: '努力感', title: '意志不健康可表现为爆发或阻塞', oneLiner: '问题可能在蒸汽太强，也可能在刹车太弱或太强。', tags: ['失控', '瘫住']),
  WillUnitIndex(id: 'E-005', moduleCode: 'E', moduleTitle: '努力感', title: '努力在体验上像走“最大阻力线”', oneLiner: '当理想战胜欲望时，人主观上感觉自己是在逆阻力而行。', tags: ['抗诱惑', '意志体验']),
  WillUnitIndex(id: 'X-001', moduleCode: 'X', moduleTitle: '爆发型意志', title: '正常的爆发型气质', oneLiner: '有些人冲动放电极快，顾虑来不及形成。', tags: ['冲动型人格', '行动快']),
  WillUnitIndex(id: 'X-002', moduleCode: 'X', moduleTitle: '爆发型意志', title: '爆发型也可暂时由疲惫或病理引发', oneLiner: '婴儿、耗竭状态、病理状态都会削弱抑制。', tags: ['疲劳失控', '临时爆发']),
  WillUnitIndex(id: 'X-003', moduleCode: 'X', moduleTitle: '爆发型意志', title: 'Clouston：抑制与自控是后天发展的脑力', oneLiner: '儿童、自控不足者和病人体现抑制系统的脆弱。', tags: ['自控发展', '冲动控制']),
  WillUnitIndex(id: 'X-004', moduleCode: 'X', moduleTitle: '爆发型意志', title: '常见醉汉与性放纵也可能属于低阈值泄洪', oneLiner: '不一定是欲望巨大，而可能是通路太容易被点燃。', tags: ['酒瘾', '易激惹']),
  WillUnitIndex(id: 'X-005', moduleCode: 'X', moduleTitle: '爆发型意志', title: '另一类爆发来自病态强大的冲动性观念', oneLiner: '并非刹车弱，而是某个观念本身强到压倒一切。', tags: ['强迫性冲动', '观念压迫']),
  WillUnitIndex(id: 'X-006', moduleCode: 'X', moduleTitle: '爆发型意志', title: 'Glénadal 案例：为防伤亲人而反复自我流放', oneLiner: '一个强迫性伤害观念足以摧毁正常亲情与生活。', tags: ['侵入性念头', '强迫防御']),
  WillUnitIndex(id: 'X-007', moduleCode: 'X', moduleTitle: '爆发型意志', title: '成瘾者的渴求对常人近乎不可想象', oneLiner: '酒精、鸦片等可形成压倒正常权衡的迫切驱力。', tags: ['成瘾', '渴求']),
  WillUnitIndex(id: 'X-008', moduleCode: 'X', moduleTitle: '爆发型意志', title: '极端成瘾案例显示正常理性会被病态食欲碾压', oneLiner: '即便明知荒唐与恶果，仍会被拖去执行。', tags: ['失控', '不可抗冲动']),
  WillUnitIndex(id: 'X-009', moduleCode: 'X', moduleTitle: '爆发型意志', title: '爱情几乎可看作一种普遍单狂', oneLiner: '它能局部劫持整个人格，而别处理性仍保留。', tags: ['爱情执念', '情感绑架']),
  WillUnitIndex(id: 'X-010', moduleCode: 'X', moduleTitle: '爆发型意志', title: 'Alfieri 用严苛自我试炼对抗爱情冲动', oneLiner: '通过隔离、誓约、羞耻屏障来阻断复燃。', tags: ['情感戒断', '自我束缚']),
  WillUnitIndex(id: 'X-011', moduleCode: 'X', moduleTitle: '爆发型意志', title: 'Alfieri 以创作和自我绑缚恢复理性', oneLiner: '替代活动与人为边界能削弱病态激情。', tags: ['替代行为', '结构化防线']),
  WillUnitIndex(id: 'X-012', moduleCode: 'X', moduleTitle: '爆发型意志', title: '强迫观念也可极琐碎却耗尽一生', oneLiner: '洗手、穿衣、查门锁等小念头也能形成长期折磨。', tags: ['强迫检查', '反复确认']),
  WillUnitIndex(id: 'O-001', moduleCode: 'O', moduleTitle: '阻塞型意志', title: '阻塞型意志是动力不足或抑制过度', oneLiner: '不是太快，而是观念碰不到行动的“要害”。', tags: ['明白却不动', '启动无力']),
  WillUnitIndex(id: 'O-002', moduleCode: 'O', moduleTitle: '阻塞型意志', title: 'Guislain：心里会想要，却无法转成真正行动', oneLiner: '“我愿意”卡在门槛上，不能变成冲动性意志。', tags: ['意志瘫住', 'abulia']),
  WillUnitIndex(id: 'O-003', moduleCode: 'O', moduleTitle: '阻塞型意志', title: '动机不起效时，对象也会显得不真实', oneLiner: '现实感与动机效力是连在一起的。', tags: ['无感', '遥远感']),
  WillUnitIndex(id: 'O-004', moduleCode: 'O', moduleTitle: '阻塞型意志', title: '见善不能行是道德悲剧的核心形式', oneLiner: '很多人并非不懂，而是懂的东西永远进不了主调。', tags: ['知行分裂', '理想失效']),
  WillUnitIndex(id: 'O-005', moduleCode: 'O', moduleTitle: '阻塞型意志', title: '努力出现于稀有理想冲动对抗本能习惯时', oneLiner: '它用于压住爆发，也用于克服阻塞。', tags: ['理想动机', '抗惯性']),
  WillUnitIndex(id: 'O-006', moduleCode: 'O', moduleTitle: '阻塞型意志', title: '理想行动在体验上是沿最大阻力线发生的', oneLiner: '欲望像固定牵引，努力像给理想额外加码。', tags: ['自律', '逆流而行']),
  WillUnitIndex(id: 'P-001', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '快乐痛苦会修正并驱动行动', oneLiner: '它们既能强化动作，也能阻断动作。', tags: ['奖励惩罚', '即时反馈']),
  WillUnitIndex(id: 'P-002', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '快痛之力很强，因此曾被误当成唯一动力', oneLiner: '很多理论把一切行动都还原为趋乐避苦。', tags: ['享乐主义', '动机误解']),
  WillUnitIndex(id: 'P-003', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '快乐痛苦不是唯一刺激源', oneLiner: '本能、情绪、知觉对象本身也能直接推动动作。', tags: ['多元动机', '反享乐主义']),
  WillUnitIndex(id: 'P-004', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '伦理上“应该按快乐痛苦行动”不等于心理上“实际上如此”', oneLiner: '规范命题不能代替事实描述。', tags: ['伦理/心理区分', '事实描述']),
  WillUnitIndex(id: 'P-005', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '最初行为与习惯行为常不靠快痛作参照', oneLiner: '很多动作只是神经系统自然溢出。', tags: ['习惯', '自动行为']),
  WillUnitIndex(id: 'P-006', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '违心行动说明人并不总按表象快乐或表象善行动', oneLiner: '有时我们会在压力下答应自己并不想做的事。', tags: ['人情压力', '违心答应']),
  WillUnitIndex(id: 'P-007', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '病态诱惑显示“坏本身”也可能有吸力', oneLiner: '有些行为的魅力就在于它被禁或令人不快。', tags: ['模仿冲动', '禁忌吸引']),
  WillUnitIndex(id: 'P-008', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '固定观念为快乐痛苦理论制造困难', oneLiner: '若观念只引导不推动，就难解释强迫行动。', tags: ['固着观念', '理论缺口']),
  WillUnitIndex(id: 'P-009', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: 'Bain 认为快乐痛苦才是意志真正推动力', oneLiner: '观念本身只提供方向，不提供动力。', tags: ['Bain理论', '动机结构']),
  WillUnitIndex(id: 'P-010', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: 'Bain 主张没有先行快痛便无意志激发', oneLiner: '一切动机都可被还原为某种快痛来源。', tags: ['享乐主义核心', '还原论']),
  WillUnitIndex(id: 'P-011', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '因此 Bain 把例外都排除到“真正自愿冲动”之外', oneLiner: '习惯、自发性、固着观念被视为偏离。', tags: ['定义策略', '概念排斥']),
  WillUnitIndex(id: 'P-012', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: 'Bain 还把无私冲动视为异类', oneLiner: '承认无私行动会破坏快乐理论的整齐性。', tags: ['利他动机', '理论边界']),
  WillUnitIndex(id: 'P-013', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '同情也被他放到准异常位置', oneLiner: '因为它不顺着“为自己快乐而行动”的主流。', tags: ['同情', '利他冲动']),
  WillUnitIndex(id: 'P-014', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '作者批评 Bain 是把一个“种”硬说成整个“属”', oneLiner: '快乐痛苦只是行动泉源的一部分。', tags: ['分类错误', '概念夸张']),
  WillUnitIndex(id: 'P-015', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '不过快痛与行动确实有一层复杂关系', oneLiner: '这也解释了为什么单一快痛理论看上去有诱惑力。', tags: ['表面合理', '理论诱因']),
  WillUnitIndex(id: 'P-016', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '任何冲动被阻断会痛，被顺利释放会有成就快感', oneLiner: '这类快痛会缠绕在本来中性的冲动周围。', tags: ['阻断痛', '释放快']),
  WillUnitIndex(id: 'P-017', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '成就快感不等于被追求的快乐', oneLiner: '很多时候我们追的不是对象，而是冲动释放后的舒服。', tags: ['分心', '止痛型行为']),
  WillUnitIndex(id: 'P-018', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '在复杂场景里，成就快感也可能成为被追求对象', oneLiner: '体育、狩猎、义务完成都可如此。', tags: ['成就感', '热状态']),
  WillUnitIndex(id: 'P-019', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '但不能因此说所有行动都只是为了快乐', oneLiner: '“顺带得到煤耗”不等于“出海只是为了烧煤”。', tags: ['错误反推', '类比批判']),
  WillUnitIndex(id: 'P-020', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '同样也不必把继续行动解释成“为逃避阻断不适”', oneLiner: '根本推动仍是原初冲动与理由。', tags: ['动机分层', '附加增强']),
  WillUnitIndex(id: 'P-021', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '结论：快痛很重要，但绝非唯一动力来源', oneLiner: '必须承认还有大量别的推动与抑制对象。', tags: ['动机多元', '理论结论']),
  WillUnitIndex(id: 'P-022', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '若要给推动条件一个总名词，最好叫“兴趣”', oneLiner: '兴趣比快痛更宽，覆盖习惯、迷恋、烦扰与吸引。', tags: ['interest', '注意占据']),
  WillUnitIndex(id: 'P-023', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '推动的观念就是占据注意的观念', oneLiner: '快痛有效也是因为它们能霸占意识。', tags: ['注意支配', '行动触发']),
  WillUnitIndex(id: 'P-024', moduleCode: 'P', moduleTitle: '快乐与痛苦作为行动的动力', title: '抑制同样依赖相反理由进入意识', oneLiner: '把反对理由想起来，本身就能挡住原冲动。', tags: ['自控', '反向提醒']),
  WillUnitIndex(id: 'R-001', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '意志心理学研究的是“什么让某观念占优”', oneLiner: '一旦动机观念稳定占上风，意志作为心理事实就完成了。', tags: ['注意占优', '意志本质']),
  WillUnitIndex(id: 'R-002', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '动作是否真正实现，并不决定意志是否存在', oneLiner: '喷嚏、写字、移动桌子，心理意愿都可以同样真实。', tags: ['失败行动', '心理完成']),
  WillUnitIndex(id: 'R-003', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '带努力的注意就是意志的核心现象', oneLiner: '意志最本质的成就是把困难对象钉在心前。', tags: ['努力注意', '意志核心']),
  WillUnitIndex(id: 'R-004', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '遥远决议与理论信念也常需持续注意维持', oneLiner: '“以后要做”的意志在心理要素上与即时 fiat 很接近。', tags: ['长期承诺', '信念维持']),
  WillUnitIndex(id: 'R-005', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '激情时难的不是动作，而是让明智观念待得住', oneLiner: '意志的真正难处在心灵层面，不在体力层面。', tags: ['情绪中自控', '热状态']),
  WillUnitIndex(id: 'R-006', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '强烈情绪有自保本能，会驱赶冷理性对象', oneLiner: '激情会把相反意象挤出意识。', tags: ['认知窄化', '情绪劫持']),
  WillUnitIndex(id: 'R-007', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '强意志者敢直视那“细小而冷的声音”', oneLiner: '他不逃避那些会冻结激情的理性考虑。', tags: ['勇于正视', '理性保持']),
  WillUnitIndex(id: 'R-008', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '困难对象一旦被保持，整个意识气质就会改变', oneLiner: '联想和行动会随占优对象而改道。', tags: ['认知重组', '行为转向']),
  WillUnitIndex(id: 'R-009', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '病人短时“绷紧自己”隐藏妄想，说明自控像精神紧绷', oneLiner: '自控需要聚拢与维持，不是轻松自然发生。', tags: ['精神紧张', '自控体验']),
  WillUnitIndex(id: 'R-010', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '意志遇到的唯一内在阻力，就是某观念不肯被注意', oneLiner: '能注意它，就是完成了根本的意志动作。', tags: ['面对困难对象', '注意阻力']),
  WillUnitIndex(id: 'R-011', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '意志首先是自我与自身心灵状态的关系', oneLiner: '它不是自我和外物直接较力，而是先处理内部观念。', tags: ['内在关系', '意志定位']),
  WillUnitIndex(id: 'R-012', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '同意不一定要求观念完全独占意识', oneLiner: '即便有对手在场，人仍可能通过努力同意某对象。', tags: ['同意', '并存冲突']),
  WillUnitIndex(id: 'R-013', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '有时还需第二次努力去坚持已经启动的行动', oneLiner: '对象已占优后，因不可逆预感，抑制观念会再起。', tags: ['临门退缩', '再同意']),
  WillUnitIndex(id: 'R-014', moduleCode: 'R', moduleTitle: '意志是心灵与其“观念”之间的关系', title: '“让它成为现实”是一种不可再化约的主观态度', oneLiner: '陈述式的“是”与命令式的“让它是”是两种终极意识态度。', tags: ['同意本质', '现实化']),
  WillUnitIndex(id: 'F-001', moduleCode: 'F', moduleTitle: '自由意志问题', title: '自由意志讨论要先丢掉“观念互斗小代理”的神话', oneLiner: '真正变化的是整体思想对象，而非小观念在打架。', tags: ['整体对象', '决断转向']),
  WillUnitIndex(id: 'F-002', moduleCode: 'F', moduleTitle: '自由意志问题', title: '活动感可能并不容易与身体紧张分开', oneLiner: '有些人把决断中的活动感还原为存在感或身体感。', tags: ['活动感', '身体参与']),
  WillUnitIndex(id: 'F-003', moduleCode: 'F', moduleTitle: '自由意志问题', title: '作者坚持思维不仅存在，而且有不同样态的力量', oneLiner: '不能把一切都说成“只是存在而无主动性差异”。', tags: ['思想力量', '主动/被动']),
  WillUnitIndex(id: 'F-004', moduleCode: 'F', moduleTitle: '自由意志问题', title: '争论的事实问题只剩：努力量是否可变', oneLiner: '若同一对象下努力多少不固定，就有自由问题。', tags: ['努力变量', '自由定义']),
  WillUnitIndex(id: 'F-005', moduleCode: 'F', moduleTitle: '自由意志问题', title: '严格心理学无法最终裁决自由意志问题', oneLiner: '我们无法数学追溯并证明某次努力只能如此。', tags: ['不可解性', '方法边界']),
  WillUnitIndex(id: 'F-006', moduleCode: 'F', moduleTitle: '自由意志问题', title: '决定论是科学设定，自由则更多是一种道德设定', oneLiner: '两边都各有吸引力，却无决定性证明。', tags: ['科学/道德冲突', '选择']),
  WillUnitIndex(id: 'F-007', moduleCode: 'F', moduleTitle: '自由意志问题', title: '宿命式“我根本没法不同做”的体验并不能证明决定论', oneLiner: '它仍暗含一个被缺席的“本可努力”的想象。', tags: ['宿命感', '伪论证']),
  WillUnitIndex(id: 'F-008', moduleCode: 'F', moduleTitle: '自由意志问题', title: '渐变性使科学倾向把努力也纳入决定论框架', oneLiner: '从反射到努力决断之间边界不清，使统一解释很诱人。', tags: ['连续谱', '科学简化']),
  WillUnitIndex(id: 'F-009', moduleCode: 'F', moduleTitle: '自由意志问题', title: '即便努力自由，心理学作为科学也几乎不受影响', oneLiner: '自由努力在动力学上只像一个微小修正量。', tags: ['科学无损', '方法抽象']),
  WillUnitIndex(id: 'F-010', moduleCode: 'F', moduleTitle: '自由意志问题', title: '但对个人而言，努力感是极其亲密而重大的现实', oneLiner: '它比财富、能力更像“我之为我”的核心。', tags: ['人格核心', '努力自感']),
  WillUnitIndex(id: 'F-011', moduleCode: 'F', moduleTitle: '自由意志问题', title: '宗教与道德生活都依赖“你愿不愿意让它如此”', oneLiner: '最深的问题往往靠无言的同意或拒绝来回答。', tags: ['同意', '存在选择']),
  WillUnitIndex(id: 'W-001', moduleCode: 'W', moduleTitle: '意志的教育', title: '意志教育有广义与狭义两层', oneLiner: '本节只讨论获得“抑制无关冲动、启动有益行动”的能力。', tags: ['训练范围', '教育目标']),
  WillUnitIndex(id: 'W-002', moduleCode: 'W', moduleTitle: '意志的教育', title: '意志教育的核心问题是：动作观念如何引出动作', oneLiner: '而观念又必须先通过盲做被留下。', tags: ['动作习得', '训练原理']),
  WillUnitIndex(id: 'W-003', moduleCode: 'W', moduleTitle: '意志的教育', title: '任何自愿动作都先被反射、本能或随机动作预演', oneLiner: '不会先天拥有动作观念。', tags: ['学习前提', '执行来源']),
  WillUnitIndex(id: 'W-004', moduleCode: 'W', moduleTitle: '意志的教育', title: '生理问题是：为何会从“先运动后感觉”变成“先观念后运动”', oneLiner: '这意味着神经系统形成了新通路。', tags: ['倒转机制', '新路径']),
  WillUnitIndex(id: 'W-005', moduleCode: 'W', moduleTitle: '意志的教育', title: '先天最小阻力通路是单向前向的', oneLiner: '感觉细胞倾向向运动区放电，运动区不直接反向唤醒感觉区。', tags: ['前向方向', '先天结构']),
  WillUnitIndex(id: 'W-006', moduleCode: 'W', moduleTitle: '意志的教育', title: '感觉细胞之间不会先天彼此唤醒', oneLiner: '感觉—感觉联想主要是经验后形成的。', tags: ['联想形成', '后天连接']),
  WillUnitIndex(id: 'W-007', moduleCode: 'W', moduleTitle: '意志的教育', title: '若系统只有肌肉—感觉—运动的闭环，就会走向强直', oneLiner: '没有抑制，动作会自我维持到耗竭。', tags: ['运动环', '强直']),
  WillUnitIndex(id: 'W-008', moduleCode: 'W', moduleTitle: '意志的教育', title: '快痛像对脑过程的“评论系统”', oneLiner: '它们能鼓励或抑制某条排流路径继续下去。', tags: ['快痛调节', '心理-物理']),
  WillUnitIndex(id: 'W-009', moduleCode: 'W', moduleTitle: '意志的教育', title: '新通路形成依赖前向放电对后方细胞的抽排', oneLiner: '后方到前方的纤维因此首次变得可通。', tags: ['新通路', '抽排机制']),
  WillUnitIndex(id: 'W-010', moduleCode: 'W', moduleTitle: '意志的教育', title: '最深通路来自“刚放电过者→正在放电者”', oneLiner: '感觉再次出现时，会更易唤起与之相连的动作观念。', tags: ['经验加深', '联想强化']),
  WillUnitIndex(id: 'W-011', moduleCode: 'W', moduleTitle: '意志的教育', title: '同样原理使动作结果观念成为动作的直接先行条件', oneLiner: 'K→M 会从非先天路径变成习惯路径。', tags: ['习惯化', '观念触发']),
  WillUnitIndex(id: 'W-012', moduleCode: 'W', moduleTitle: '意志的教育', title: '曾作为结果的感觉，后来能反过来当原因', oneLiner: '这就是动作教育的基本生理图式。', tags: ['结果变原因', '学习逆转']),
  WillUnitIndex(id: 'W-013', moduleCode: 'W', moduleTitle: '意志的教育', title: '心理线索不只来自动觉，也可来自视觉或听觉影像', oneLiner: '不同人可能依赖不同感觉通道启动动作。', tags: ['多模态线索', '个体差异']),
  WillUnitIndex(id: 'W-014', moduleCode: 'W', moduleTitle: '意志的教育', title: '现实意志目标多是动作序列而非单次收缩', oneLiner: '通常只意愿第一步，后续由链条自动滚动。', tags: ['流程动作', '自动串联']),
  WillUnitIndex(id: 'W-015', moduleCode: 'W', moduleTitle: '意志的教育', title: '学习动作链是在众多随机顺序里筛出“感觉对”的顺序', oneLiner: '主动学与被动学在机制上相通。', tags: ['序列学习', '技能编排']),
  WillUnitIndex(id: 'W-016', moduleCode: 'W', moduleTitle: '意志的教育', title: '字母表问题的关键不在“想到A说A”，而在“说了A为何接B”', oneLiner: '作者转向解释串联动作中枢如何建立连接。', tags: ['序列衔接', '连锁输出']),
  WillUnitIndex(id: 'W-017', moduleCode: 'W', moduleTitle: '意志的教育', title: '后出现的字母细胞会抽排前一个，从而留下前向联想通路', oneLiner: '这解释了为何 A 之后容易接 B。', tags: ['联想路径', '顺序记忆']),
  WillUnitIndex(id: 'W-018', moduleCode: 'W', moduleTitle: '意志的教育', title: 'A 的观念再起时，会同时激活说A与转向B的通道', oneLiner: '而更强的新通路会打断原始重复环。', tags: ['重复抑制', '顺序推进']),
  WillUnitIndex(id: 'W-019', moduleCode: 'W', moduleTitle: '意志的教育', title: '于是动作序列按 A→B→C 自动展开', oneLiner: '前一步感觉与后一步动作逐渐组织成连锁系统。', tags: ['连锁动作', '习惯运行']),
  WillUnitIndex(id: 'W-020', moduleCode: 'W', moduleTitle: '意志的教育', title: '为何 Sa→Sb 会强于 Sa→Ma，既可能有机械原因，也可能有心理条件', oneLiner: '“我要背字母表”的总体意向会促进正确通路。', tags: ['意向张力', '选择性促进']),
  WillUnitIndex(id: 'W-021', moduleCode: 'W', moduleTitle: '意志的教育', title: '联想之所以通常前向，是因为它按经验顺序形成', oneLiner: '倒背字母表必须另学一套反向通路。', tags: ['前向联想', '逆序学习']),
  WillUnitIndex(id: 'W-022', moduleCode: 'W', moduleTitle: '意志的教育', title: '“孩子与火焰”说明同样原理可解释经验性抑制', oneLiner: '先前灼痛经验会在再见火时提前唤起缩手观念。', tags: ['经验抑制', '危险学习']),
  WillUnitIndex(id: 'W-023', moduleCode: 'W', moduleTitle: '意志的教育', title: '新通路会提前唤起后果观念并打断原运动环', oneLiner: '但在心不在焉或简单情境中，旧运动环仍可能回归。', tags: ['重复词语', '运动环回归']),
  WillUnitIndex(id: 'W-024', moduleCode: 'W', moduleTitle: '意志的教育', title: '“狗学握爪”说明脑损失后旁路支配与旧路径恢复', oneLiner: '只有当错误动作被抑制、正确感觉与期待吻合时，新路径才会加深。', tags: ['旁路形成', '康复学习']),
];

const Map<String, String> kWillModuleLongIntro = {
  'D': '导论是整章的地基：先解释欲望、愿望、意志的差别，再说明动作观念、动觉印象、神经支配感批判，以及为什么动作线索本质上是可感觉结果的预期。学习重点是把“意志”从神秘发令改写为“观念占优 + 必要时的 fiat”。',
  'I': '观念—运动作用是本章最适合落地训练的部分：它把“想到就做”视为意志的基本形式，并说明行动失败往往不是因为没有意愿，而是因为有冲突观念在夺走放电机会。学习重点是识别阻滞、缩小第一步、让正确观念先发生。',
  'A': '这一模块解释人在犹豫、拉扯、前景—背景理由变化中的审议经验。',
  'T': '这一模块把决断按体验形态划为五种，帮助用户识别自己的拍板风格。',
  'E': '这一模块解释努力感为什么出现，以及它为什么常被体验为沿最大阻力线前进。',
  'X': '这一模块处理冲动过快、强迫性观念、成瘾与失控。',
  'O': '这一模块处理明白却动不了、现实感减退和理想失效。',
  'P': '这一模块说明快乐与痛苦很重要，但不是唯一动力；真正推动动作的是占据注意的兴趣对象。',
  'R': '这一模块把意志理解为自我与其观念之间的关系，并把努力注意视为意志核心。',
  'F': '这一模块把自由意志问题缩到“努力量是否可变”，并说明心理学无法最终裁决。',
  'W': '这一模块从新通路、抽排、动作链学习来解释意志如何被教育。',
};

const Map<String, List<String>> kWillModuleStudyGoals = {
  'D': ['看懂“意志”并不是神秘发令', '会区分动作观念、动觉与神经支配感', '知道为什么动作线索来自可感觉结果'],
  'I': ['识别“想到就做”的低阻力动作', '找出阻滞自己的冲突观念', '用最小第一步训练观念—动作转化'],
  'A': ['识别自己处于审议而非行动', '写出前景理由与背景理由', '给悬置中的问题设置拍板条件'],
  'T': ['识别自己的决策风格', '区分理性结账与冲动突决', '知道何时需要 effort 型决定'],
  'E': ['知道努力为何常落在长期目标上', '能识别自己是在走最大阻力线', '区分正常努力与病理失衡'],
  'X': ['识别爆发并不总是欲望太强', '提早给高风险场景加阻尼', '理解强迫性观念的结构'],
  'O': ['识别“明白却不动”', '把大任务缩到可起手', '给理想对象增加现实感'],
  'P': ['区分追求对象与解除不适', '识别即时舒服如何夺走行动', '把注意力放回真正重要的兴趣对象'],
  'R': ['理解意志是让观念站住', '练习对困难对象的同意', '区分注意、同意与行动后果'],
  'F': ['理解自由意志争论的实际问题', '识别宿命感与决定论的区别', '把注意放回你今天能付出的努力'],
  'W': ['把意志教育理解为新通路形成', '会用动作链、线索与反馈训练自己', '理解重复、抽排与习惯固化'],
};


const List<WillUnitIndex> kWillUnitIndexSeed = kWillUnitIndexes;
