import 'will_models.dart';

const int kWillTotalUnits = 209;

const List<WillModuleSection> kWillSections = [
  WillModuleSection(
    id: 'intro',
    title: '导论：意志的发生机制',
    subtitle: '83 个知识单元，解释动作观念、动觉、神经支配感与自愿行为的基础。',
    unitCount: 83,
    highlights: ['动觉印象', '动作观念', '神经支配感批判', '心理线索'],
  ),
  WillModuleSection(
    id: 'ideo_motor',
    title: '观念—运动作用',
    subtitle: '19 个知识单元，解释“想到就做”与冲突观念造成的阻滞。',
    unitCount: 19,
    highlights: ['想到就做', '无冲突观念', '赖床案例', 'fiat 的位置'],
  ),
  WillModuleSection(
    id: 'deliberation',
    title: '审议 / 决断 / 努力',
    subtitle: '16 个知识单元，解释犹豫、五种决定类型与努力感。',
    unitCount: 16,
    highlights: ['前景与背景理由', '五种决定', '努力感', '同意与坚持'],
  ),
  WillModuleSection(
    id: 'imbalance',
    title: '爆发、阻塞与诱惑动力',
    subtitle: '48 个知识单元，解释冲动失控、明知不动与即时舒服的牵引。',
    unitCount: 48,
    highlights: ['爆发型意志', '阻塞型意志', '快乐/痛苦动力', '兴趣与注意'],
  ),
  WillModuleSection(
    id: 'meta_training',
    title: '观念关系、自由意志与意志教育',
    subtitle: '43 个知识单元，解释注意、同意、责任感与新通路训练。',
    unitCount: 43,
    highlights: ['意志与观念', '自由意志', '新通路', '意志教育'],
  ),
];

const List<WillKnowledgeCard> kWillKnowledgeCards = [
  WillKnowledgeCard(
    id: 'intro_003',
    sectionId: 'intro',
    label: 'Intro-003',
    title: '自愿动作是次级功能',
    oneLiner: '人不可能第一次就自愿完成一个从未经验过的动作。',
    meaning: '自愿动作必须以先前的随机、反射或非自愿动作经验为前提；没有经验，便没有动作观念。',
    realScene: '你知道“要去健身”，但第一次做动作时身体并不会自然按正确路径发力。',
    practicalAction: '选一个你想养成的新动作，只练“看、做、感受结果”三次，不评价好坏。',
    reflection: '今天你有没有把“听懂了”误当成“身体已经会了”？',
    tags: ['基础机制', '动作观念', '经验学习'],
  ),
  WillKnowledgeCard(
    id: 'intro_004',
    sectionId: 'intro',
    label: 'Intro-004',
    title: '动作观念来自记忆储备',
    oneLiner: '记忆里必须先储备可做动作的观念，自愿行动才可能发生。',
    meaning: '意志依赖过去动作留下的表象与感觉图像；这套储备是自愿生活的第一先决条件。',
    realScene: '你知道早起重要，但没形成一套“起身—下床—洗漱”的记忆通路，所以总停在床上。',
    practicalAction: '把一个目标动作拆成 3 个身体步骤，连续重复两次。',
    reflection: '你今天的某个失败，是不是因为脑中根本没有清晰的动作图谱？',
    tags: ['基础机制', '记忆', '动作脚本'],
  ),
  WillKnowledgeCard(
    id: 'intro_005',
    sectionId: 'intro',
    label: 'Intro-005',
    title: '同一个动作会留下多种感觉印象',
    oneLiner: '动作不只留下“怎么发力”的感觉，也留下视觉、听觉、触觉等远端效果。',
    meaning: '同一动作可通过远端效果与本地效果被辨识，这让动作表象更丰富、更可被调用。',
    realScene: '打字时你既记得手指节奏，也记得屏幕上字出现的样子。',
    practicalAction: '做一个简单动作，分别记录它“看起来怎样、听起来怎样、身体里怎样”。',
    reflection: '你更容易被这个动作的哪种感觉线索唤起？',
    tags: ['远端感觉', '本地感觉', '动作线索'],
  ),
  WillKnowledgeCard(
    id: 'intro_006',
    sectionId: 'intro',
    label: 'Intro-006',
    title: '动觉印象是动作的本地感觉',
    oneLiner: '来自肌肉、关节、韧带的感觉，让我们知道自己在怎样移动。',
    meaning: '动觉印象构成了动作的驻留效果，是动作识别与再现的重要来源。',
    realScene: '闭眼伸手找杯子时，你仍能大致知道手臂抬到哪里。',
    practicalAction: '闭眼抬起一只手，停 3 秒，再描述肩、肘、腕的位置感。',
    reflection: '你平时做事时，是不是太少利用身体本身给你的反馈？',
    tags: ['动觉', '身体觉察', '本地感觉'],
  ),
  WillKnowledgeCard(
    id: 'intro_007',
    sectionId: 'intro',
    label: 'Intro-007',
    title: '被动运动也能被感觉到',
    oneLiner: '我们能感觉四肢被别人摆成什么姿势，这说明姿态感真实存在。',
    meaning: '姿态感是引导动作的重要条件；当它丧失时，动作会迅速迷失。',
    realScene: '闭眼时你仍知道自己是坐着前倾，还是靠在椅背上。',
    practicalAction: '花 20 秒只感受你现在的坐姿、腿部角度和肩颈状态。',
    reflection: '今天你的身体什么时候已经在“报警”，但你并没注意到？',
    tags: ['姿态感', '被动运动', '自我觉察'],
  ),
  WillKnowledgeCard(
    id: 'intro_015',
    sectionId: 'intro',
    label: 'Intro-015',
    title: '连锁动作需要引导性感觉',
    oneLiner: '一串动作能否顺利进行，取决于每一步是否有感觉在引导下一步。',
    meaning: '动作链若没有每一步的“我现在在哪里”的感觉线索，就会很快走偏。',
    realScene: '系鞋带、开车、做饭，都是由连续感觉引导的动作链。',
    practicalAction: '选一个流程动作，边做边说出每一步是靠什么感觉在引导。',
    reflection: '你今天哪件事会卡住，是因为中间步骤没有清晰线索？',
    tags: ['动作链', '引导性感觉', '流程动作'],
  ),
  WillKnowledgeCard(
    id: 'intro_020',
    sectionId: 'intro',
    label: 'Intro-020',
    title: '自愿动作至少需要动作的心理观念',
    oneLiner: '在意志动作之前，至少得有一个能界定“要做哪一个动作”的心理观念。',
    meaning: '意志不是空泛“我要做点什么”，而是某种可感觉结果的具体图像先出现。',
    realScene: '你真去倒水前，脑中其实已经有“起身、拿杯子、喝水”的模糊图像。',
    practicalAction: '做动作前停 2 秒，写一句“我接下来要让什么现实化”。',
    reflection: '你今天的某个行动失败，是不是因为目标太抽象？',
    tags: ['心理线索', '具体动作', '目标清晰度'],
  ),
  WillKnowledgeCard(
    id: 'intro_021',
    sectionId: 'intro',
    label: 'Intro-021',
    title: '简单自愿动作未必需要额外成分',
    oneLiner: '在最简单的情形里，动作观念本身就足以引出动作。',
    meaning: '并非所有行动都需要强烈决心或额外命令；有时只要观念清楚、无对抗，它就会发生。',
    realScene: '你看见桌面有灰，手就顺势去擦，几乎没下任何命令。',
    practicalAction: '记录今天 3 个“想到就做”的小动作。',
    reflection: '你是不是把所有行动都想成必须靠“狠劲”推动？',
    tags: ['简单意志', '想到就做', '去神秘化'],
  ),
  WillKnowledgeCard(
    id: 'intro_024',
    sectionId: 'intro',
    label: 'Intro-024',
    title: '神经支配感并非必要假设',
    oneLiner: '我们不必假定存在一种特殊的“向肌肉发电流的感觉”来解释意志。',
    meaning: '运动观念可由动作的周边感觉图像解释，所谓神经支配感既缺少必要性，也缺少证据。',
    realScene: '你要写字时，真正先出现的是字形、声音或手感的预期，而不是“神经发令”的体验。',
    practicalAction: '在做一个精细动作前，描述你脑中先出现的是结果图像还是“发力感”。',
    reflection: '你今天是否把“我好像在发力”误当作行动真正的起点？',
    tags: ['神经支配感', '周边感觉', '意志理论'],
  ),
  WillKnowledgeCard(
    id: 'intro_038',
    sectionId: 'intro',
    label: 'Intro-038',
    title: '动作前真正可意识到的是结果图像',
    oneLiner: '把结果感觉抽掉，意识里不会剩下一条清晰的“发令方向”。',
    meaning: '意志的指向是靠动作后果图像来规定的，而不是靠某种神秘内在电流。',
    realScene: '你准备说一句话时，先在心里听见它，而不是先感到“神经往喉咙发令”。',
    practicalAction: '在开口说一句重要的话前，先捕捉你心里最先出现的是声音、字词还是情景。',
    reflection: '你今天要表达某事时，真正引导你的先导图像是什么？',
    tags: ['结果图像', '表达', '动作前意识'],
  ),
  WillKnowledgeCard(
    id: 'intro_040',
    sectionId: 'intro',
    label: 'Intro-040',
    title: '观念加 fiat 构成自愿行为前的心理状态',
    oneLiner: '可辨认的成分主要是动作后果图像；有些时候还会再加一个“让它发生”的同意。',
    meaning: '意志行为前并不复杂：要么只是观念，要么是观念加 fiat。fiat 的难度差异，构成后文重点。',
    realScene: '你已经知道该回复那条消息，但还差一个“现在就发”的同意。',
    practicalAction: '今天对一件该做的小事明确说一句：“我同意现在开始。”',
    reflection: '你今天哪件事不是缺知识，而是缺“同意”？',
    tags: ['fiat', '同意', '行动门槛'],
  ),
  WillKnowledgeCard(
    id: 'intro_083',
    sectionId: 'intro',
    label: 'Intro-083',
    title: '动作观念是对可感效果的预期',
    oneLiner: '自愿动作之前的观念，不是支配思想，而是对动作可感效果的预期。',
    meaning: '这种预期可近可远，可来自本地动觉，也可来自视觉、听觉等远端图像。',
    realScene: '写字时你可能先“听见词”，而不是先感觉手指。',
    practicalAction: '找一个熟练动作，识别你更常依靠的是视觉、听觉还是身体感觉。',
    reflection: '你做熟练动作时，脑中最先出现的是哪类线索？',
    tags: ['远端线索', '熟练动作', '预期图像'],
  ),
  WillKnowledgeCard(
    id: 'ideo_084',
    sectionId: 'ideo_motor',
    label: 'Will-084',
    title: '观念—运动作用作为基本类型',
    oneLiner: '“想到就做”不是怪事，而是意志最简单也最基本的形式。',
    meaning: '作者把观念—运动作用视为理解复杂意志现象的出发点。',
    realScene: '看到地上有纸屑，你顺手捡起，并没经过庄严决策。',
    practicalAction: '今天找一个“想到即做”的动作，记录它为什么几乎没有阻力。',
    reflection: '哪些事你本来能顺手做，却总被你想得过重？',
    tags: ['观念—运动', '基本形式', '低阻力'],
  ),
  WillKnowledgeCard(
    id: 'ideo_086',
    sectionId: 'ideo_motor',
    label: 'Will-086',
    title: '有时单纯观念就足够',
    oneLiner: '不是所有自愿行为都要一个额外的命令，很多时候单纯想到就够了。',
    meaning: 'fiat 不是处处都明显；无对抗时，观念本身就足以让动作发生。',
    realScene: '你想喝水，身体已经走向杯子。',
    practicalAction: '做一次“先不评估，只做第一个物理动作”。',
    reflection: '你今天有没有在还没评估完时，动作就已经开始了？',
    tags: ['观念即动作', '低延迟', '启动'],
  ),
  WillKnowledgeCard(
    id: 'ideo_087',
    sectionId: 'ideo_motor',
    label: 'Will-087',
    title: '想到就做是正常过程',
    oneLiner: '内省里我们只看到：想到那个动作，然后它就做出来了。',
    meaning: '中间当然有神经肌肉过程，但心理上未必经历额外命令。',
    realScene: '谈话中看到袖子上的灰，手已去拍掉。',
    practicalAction: '记录一个你今天“没打断原任务也顺手完成”的动作。',
    reflection: '哪些事你完全可以顺手做，却常等到“正式开始”才做？',
    tags: ['顺手做', '日常意志', '自动化'],
  ),
  WillKnowledgeCard(
    id: 'ideo_089',
    sectionId: 'ideo_motor',
    label: 'Will-089',
    title: '没有冲突观念时动作最容易发生',
    oneLiner: '关键不是有没有观念，而是有没有与它冲突的其他观念。',
    meaning: '只要没有反对声音，动作会沿着观念几乎不可抗地跟上。',
    realScene: '你收拾桌面时很顺，因为脑中没有“先刷会儿手机”的竞争念头。',
    practicalAction: '开始一个任务前，先清掉一个最典型干扰物。',
    reflection: '今天阻止你行动的最强冲突观念是什么？',
    tags: ['冲突观念', '阻滞', '环境清理'],
  ),
  WillKnowledgeCard(
    id: 'ideo_090',
    sectionId: 'ideo_motor',
    label: 'Will-090',
    title: '赖床并不总靠大战起床',
    oneLiner: '许多时候起身不是靠长时间搏斗，而是靠一个没有被反驳的念头突然滑入行动。',
    meaning: '当“暖和/寒冷”的抑制性意识淡下去，起床观念就能立刻发生动作。',
    realScene: '你早晨真正能起床的时刻，往往是突然坐起来，而不是在床上反复责备自己。',
    practicalAction: '明天早晨只要求自己“先坐起来 3 秒”。',
    reflection: '你起不来时，脑中最常放大的阻滞是什么？',
    tags: ['赖床', '启动', '去战斗化'],
  ),
  WillKnowledgeCard(
    id: 'ideo_091',
    sectionId: 'ideo_motor',
    label: 'Will-091',
    title: '观念不行动，多半是被别的观念夺走了冲力',
    oneLiner: '没做成，不等于观念没力量，往往只是另一股观念抢走了放电机会。',
    meaning: '即便被抑制，动作也常以萌芽方式出现，比如轻微紧张、随动、想象性发力。',
    realScene: '你想开口反驳但忍住了，身体却已经绷紧、喉咙发力。',
    practicalAction: '复盘一件没做成的事，写出“想做”和“阻止做”的两列观念。',
    reflection: '今天那个没做成的动作，在身体上有没有以微量方式先发生？',
    tags: ['萌芽动作', '抑制', '观念竞争'],
  ),
  WillKnowledgeCard(
    id: 'ideo_094',
    sectionId: 'ideo_motor',
    label: 'Will-094',
    title: '每个动作表象都会在某种程度上唤起动作',
    oneLiner: '只要想到一个动作，它就会多少推动那个动作。',
    meaning: '观念天然带动作倾向，只是强弱会被对抗观念与注意分配改变。',
    realScene: '看别人打哈欠时，你自己也会轻微想打。',
    practicalAction: '在想做某事时，先观察身体哪一处已开始预备。',
    reflection: '你今天哪一个念头已经在身体里先起了势？',
    tags: ['动作倾向', '模仿', '身体预备'],
  ),
  WillKnowledgeCard(
    id: 'ideo_099',
    sectionId: 'ideo_motor',
    label: 'Will-099',
    title: 'fiat 常出现在解除阻滞的时候',
    oneLiner: '明显的“我决定了”往往不是平时都有，而是在对抗观念被解除时才变得突出。',
    meaning: '无阻滞处不需要强烈 fiat；fiat 的戏剧性，常来自阻力刚被跨过去。',
    realScene: '你一直拖着不发消息，真正按下发送键那一下会觉得“终于过去了”。',
    practicalAction: '今天记录一个你明显“跨过去”的瞬间。',
    reflection: '那个瞬间之前，卡住你的到底是什么？',
    tags: ['fiat', '解除阻滞', '转折点'],
  ),
  WillKnowledgeCard(
    id: 'delib_001',
    sectionId: 'deliberation',
    label: 'Delib-001',
    title: '审议是动机冲突中的摇摆',
    oneLiner: '审议不是没想法，而是多个互相冲突的观念同时占场。',
    meaning: '一个动作建议会与支持、反对它的各种理由同时存在，于是形成犹豫不决。',
    realScene: '你想早点睡，但还想刷会儿手机、又担心明天状态差。',
    practicalAction: '写出一个正在拖住你的决定，以及它背后两组互相拉扯的理由。',
    reflection: '你今天在什么问题上还停留在“检验理由”而不是“服从理由”？',
    tags: ['审议', '犹豫', '理由冲突'],
  ),
  WillKnowledgeCard(
    id: 'delib_005',
    sectionId: 'deliberation',
    label: 'Delib-005',
    title: '前景理由与背景理由',
    oneLiner: '当下最响的理由不一定会赢，因为较暗的背景理由仍像闸门一样在场。',
    meaning: '审议持续时，前景理由不断变换，但背景理由不退，放电就迟迟不发生。',
    realScene: '你一会儿觉得必须辞职，一会儿又被“现实成本”压回去。',
    practicalAction: '把一个决定的显性理由与隐藏理由分别列出来。',
    reflection: '你今天哪个“没说出口的背景理由”最影响行为？',
    tags: ['前景', '背景', '审议结构'],
  ),
  WillKnowledgeCard(
    id: 'decision_001',
    sectionId: 'deliberation',
    label: 'Decision-001',
    title: '理性结账型决定',
    oneLiner: '有时决定不是硬拱出来的，而是证据慢慢结账后自然落定。',
    meaning: '当某种理解方式把情境纳入熟悉原则，行动便可不费力地发生。',
    realScene: '你列清利弊、看清目标后，突然觉得“这事就这样定吧”。',
    practicalAction: '对一个决定做一次“利弊 + 归类”的理性结账。',
    reflection: '你缺的是真理由，还是缺一个更正确的看法框架？',
    tags: ['理性决定', '归类', '稳定原则'],
  ),
  WillKnowledgeCard(
    id: 'decision_003',
    sectionId: 'deliberation',
    label: 'Decision-003',
    title: '突然爆发型决定',
    oneLiner: '有些决定不是外因推动，而是悬置太久后内在突然放电。',
    meaning: '在困境令人难受时，人会以“终于动起来”的内在释放感拥抱一个突然决断。',
    realScene: '你拖了很久没回消息，某一刻突然一口气全发了。',
    practicalAction: '复盘一次“憋久了突然拍板”的经历，找出前面的累积压力。',
    reflection: '这次突然决断，是成熟结账还是被悬置感逼出来？',
    tags: ['突然决定', '放电', '情绪累积'],
  ),
  WillKnowledgeCard(
    id: 'decision_005',
    sectionId: 'deliberation',
    label: 'Decision-005',
    title: '努力压舱型决定',
    oneLiner: '当两边都清醒在场时，最后的决定会伴随沉重用力感。',
    meaning: '这类决定的特征是：你清楚知道自己放弃了什么，并亲手把天平压向一边。',
    realScene: '你明知接受短期痛苦才对，却还得硬压住眼前诱惑。',
    practicalAction: '记录一次“两边都清楚但你硬压过去”的时刻。',
    reflection: '那次你真正付出的，不是体力，而是什么？',
    tags: ['第五类决定', '努力感', '价值冲突'],
  ),
  WillKnowledgeCard(
    id: 'effort_003',
    sectionId: 'deliberation',
    label: 'Effort-003',
    title: '努力主要发生在让困难观念留在心里',
    oneLiner: '困难不在肌肉，而在让更高、更冷静、更不受欢迎的观念站得住。',
    meaning: '努力的本质是注意和同意，而非单纯体力或情绪咬牙。',
    realScene: '你想逃离任务，但仍让“先做 5 分钟”的观念留在脑中。',
    practicalAction: '盯住一个你在逃避的任务标题 30 秒，不切屏。',
    reflection: '你今天有没有给“正确但不讨喜”的观念一点停留时间？',
    tags: ['努力感', '注意', '同意'],
  ),
  WillKnowledgeCard(
    id: 'explosive_002',
    sectionId: 'imbalance',
    label: 'Explosive-002',
    title: '爆发不是坏，而是太快',
    oneLiner: '许多爆发型行为不是更强，而是更快，抑制来不及升起。',
    meaning: '心理视野极端简化时，冲动会像轻扳机一样直接放电。',
    realScene: '你并不是特别想吵架，但一句话上来就回怼了。',
    practicalAction: '冲动来时先延迟 60 秒，不立刻表达。',
    reflection: '今天哪次失控，不是“太坏”，而是“太快”？',
    tags: ['爆发型', '冲动', '延迟'],
  ),
  WillKnowledgeCard(
    id: 'explosive_010',
    sectionId: 'imbalance',
    label: 'Explosive-010',
    title: '有时被带走的不是目标，而是可能性的暗示',
    oneLiner: '某些失控行为并非强烈欲望，而是通路过于容易被点亮。',
    meaning: '看见瓶子、看见入口、看见机会，就足以让行为泄洪。',
    realScene: '你并不真的想刷很久短视频，但一打开就一路滑下去。',
    practicalAction: '记录一次“其实没多想要，但还是做了”的行为。',
    reflection: '是什么线索在你毫无准备时点亮了那条通路？',
    tags: ['线索触发', '通路', '成瘾入口'],
  ),
  WillKnowledgeCard(
    id: 'obstructed_001',
    sectionId: 'imbalance',
    label: 'Obstructed-001',
    title: '阻塞型意志：明白却动不了',
    oneLiner: '问题不是看不见，而是对象虽出现了，却没有足够现实感去刺中行动。',
    meaning: '这类状态里，智力可能清楚，但观念不具有效动机强度。',
    realScene: '你完全知道应该写方案，但就是瘫在椅子上。',
    practicalAction: '把当前任务缩成一个 2 分钟动作，只做第一块。',
    reflection: '你今天没做，是因为不懂，还是因为它没有“刺中你”？',
    tags: ['阻塞型', '启动困难', '现实感'],
  ),
  WillKnowledgeCard(
    id: 'obstructed_004',
    sectionId: 'imbalance',
    label: 'Obstructed-004',
    title: '努力常在理想冲动对抗本能冲动时出现',
    oneLiner: '努力最常见的场景，是较稀有、较高阶的观念去顶住较习惯、较本能的路。',
    meaning: '英雄与神经症者都常需要努力，因为他们都经常站在高阻力线上。',
    realScene: '你克制自己不回怼、不躺平、不立刻舒服一下。',
    practicalAction: '今天找一个你正在走“较大阻力线”的瞬间做记录。',
    reflection: '你今天在抵抗的，究竟是哪种更习惯、更顺手的倾向？',
    tags: ['努力', '理想 vs 欲望', '最大阻力线'],
  ),
  WillKnowledgeCard(
    id: 'obstructed_006',
    sectionId: 'imbalance',
    label: 'Obstructed-006',
    title: '道德行动在体验上像走最大阻力线',
    oneLiner: '当理想取胜时，我们主观上常觉得自己在走更难、更逆的路。',
    meaning: '这正是“战胜诱惑”“克服冲动”语言感觉的来源。',
    realScene: '早睡、健身、闭嘴、坚持写作，都像在逆着更顺手的冲动走。',
    practicalAction: '把一个理想行动写成：我正在抵抗的旧路线是什么？',
    reflection: '你今天的理想行动，哪一部分最像“逆流而上”？',
    tags: ['最大阻力线', '道德行动', '逆流'],
  ),
  WillKnowledgeCard(
    id: 'pleasure_001',
    sectionId: 'imbalance',
    label: 'Pleasure-001',
    title: '快乐与痛苦很强，但不是唯一动力',
    oneLiner: '快乐和痛苦会强力推动或阻止行动，但绝不是所有行动的唯一根源。',
    meaning: '很多本能、情绪、观念—运动行动都不是靠预想快乐才发生。',
    realScene: '你顺手摸手机，不一定是因为很快乐，而可能只是动作沿着惯性发生。',
    practicalAction: '选一件今天做了的小动作，判断它究竟是快乐驱动、习惯驱动还是冲动驱动。',
    reflection: '你有没有把所有行为都解释成“因为我喜欢”？',
    tags: ['快乐', '痛苦', '动力来源'],
  ),
  WillKnowledgeCard(
    id: 'pleasure_006',
    sectionId: 'imbalance',
    label: 'Pleasure-006',
    title: '人有时会被“坏本身”吸引',
    oneLiner: '有些冲动并不追求善或乐，而是被危险、禁止、恶感本身刺激。',
    meaning: '病态冲动与某些日常怪癖说明：行动不总是以“愉快”或“善”为形式。',
    realScene: '你明知会后悔，还是忍不住去点开、去按、去试一下。',
    practicalAction: '记录一次“我并不喜欢，但就是想碰一下”的时刻。',
    reflection: '那个吸引你的，到底是对象本身，还是它的禁忌性？',
    tags: ['禁忌吸引', '坏的诱惑', '冲动'],
  ),
  WillKnowledgeCard(
    id: 'pleasure_017',
    sectionId: 'imbalance',
    label: 'Pleasure-017',
    title: '很多时候追的是解除不适，不是对象本身',
    oneLiner: '你未必真的想要那件东西，你可能只是想停止难受。',
    meaning: '成就快感、释放快感与被追求的快乐常被混淆，因而产生“快乐是唯一动力”的错觉。',
    realScene: '你刷手机并不是因为内容多好，而是因为任务太难受。',
    practicalAction: '下一次想分心时，先写下：我是在追它，还是在逃别的？',
    reflection: '今天哪次行为其实是在止痛，而不是在追求价值？',
    tags: ['解除不适', '即时舒服', '诱惑'],
  ),
  WillKnowledgeCard(
    id: 'pleasure_022',
    sectionId: 'imbalance',
    label: 'Pleasure-022',
    title: '兴趣比快乐/痛苦更适合做总名词',
    oneLiner: '真正决定观念是否推动行动的，总体上更像“它多大程度占据了注意”。',
    meaning: '兴趣包含愉快、痛苦、习惯、迷恋、烦扰等一切能强迫注意占优的东西。',
    realScene: '某件事一旦抓住你全部注意，它几乎天然就带着动作倾向。',
    practicalAction: '今天观察一次：是什么先抓住了你的注意，然后把行为带走？',
    reflection: '你当下最容易被什么样的“兴趣”俘获？',
    tags: ['兴趣', '注意占优', '总动力'],
  ),
  WillKnowledgeCard(
    id: 'relation_003',
    sectionId: 'meta_training',
    label: 'Relation-003',
    title: '意志最核心的工作是让某个观念稳定占上风',
    oneLiner: '一旦动机观念稳定占优，意志的心理工作就基本完成了。',
    meaning: '动作后续能否实现，常只是执行系统的问题；意志的核心是观念占优。',
    realScene: '你真正的突破，不是身体多用力，而是终于让“去做”这件事在心里压过了别的声音。',
    practicalAction: '今天把一个重要任务写成一句最短的主导观念，重复读三遍。',
    reflection: '你今天真正输掉的，是动作，还是主导观念？',
    tags: ['观念占优', '意志核心', '主导观念'],
  ),
  WillKnowledgeCard(
    id: 'relation_005',
    sectionId: 'meta_training',
    label: 'Relation-005',
    title: '注意的努力就是意志的本质现象',
    oneLiner: '意志最自愿的时候，就是把注意牢牢钉在困难对象上。',
    meaning: '带努力的注意，几乎就是作者意义上的意志本身。',
    realScene: '你不再逃开任务页面，而是盯住它，哪怕脑中一直想逃。',
    practicalAction: '对一件逃避中的事做一次 30 秒注意锁定。',
    reflection: '你今天哪一刻真正动用了注意，而不是只是焦虑？',
    tags: ['注意', '努力', '困难对象'],
  ),
  WillKnowledgeCard(
    id: 'relation_014',
    sectionId: 'meta_training',
    label: 'Relation-014',
    title: '“让它成为现实”是一种独特经验',
    oneLiner: '同意不是普通想法，而是一种把对象从“可能”转成“现在就办”的内在态度。',
    meaning: '“是”与“让它是”对应两种终极意识态度；后者就是意志的现实化面向。',
    realScene: '你不是不知道要去运动，而是迟迟没对“今晚就去”说出真正的同意。',
    practicalAction: '对一个小任务明确说一句：让它现在成为现实。',
    reflection: '你今天哪件事一直停在“知道”，没有进入“同意”？',
    tags: ['同意', '现实化', '承诺'],
  ),
  WillKnowledgeCard(
    id: 'free_004',
    sectionId: 'meta_training',
    label: 'Free-004',
    title: '自由意志问题在心理学中聚焦为：努力量是否可变',
    oneLiner: '争论的核心，不是抽象自由，而是同一对象下我们是否能多付出一点努力。',
    meaning: '如果努力量可变，则未来不是全然注定；若完全被对象决定，则一切预定。',
    realScene: '你回看某次失败时，最刺痛的往往是“那时我是不是本可以再多撑一点”。',
    practicalAction: '记录一个今天的分岔点：你觉得自己还能再多做一点吗？',
    reflection: '让你耿耿于怀的，是结果，还是那个“本可以”的感觉？',
    tags: ['自由意志', '努力量', '分岔点'],
  ),
  WillKnowledgeCard(
    id: 'free_010',
    sectionId: 'meta_training',
    label: 'Free-010',
    title: '努力感之所以重要，是因为它最像“我真正贡献了什么”',
    oneLiner: '人在主观上最把努力当成“属于我自己”的核心部分。',
    meaning: '财富、智力、运气都像外物，努力却像自我最深层的贡献。',
    realScene: '你会为一次咬牙坚持而自豪，即使结果不算漂亮。',
    practicalAction: '今晚写下今天最值得你尊重自己的一个努力点。',
    reflection: '今天真正属于“你自己贡献”的，是哪一下？',
    tags: ['努力感', '主体性', '自我价值'],
  ),
  WillKnowledgeCard(
    id: 'edu_003',
    sectionId: 'meta_training',
    label: 'Edu-003',
    title: '意志教育的核心问题是：动作观念如何引出动作',
    oneLiner: '训练意志，不是空喊自律，而是让观念越来越稳定地唤起动作。',
    meaning: '这本质上是新通路形成的问题，即把原本随机、盲目的动作组织成可自愿调用的路径。',
    realScene: '你想建立晨跑习惯，关键不在信念口号，而在把“起床后穿鞋出门”练成通路。',
    practicalAction: '给一个新习惯设计一个固定触发和一个固定第一步。',
    reflection: '你在训练的，是情绪，还是通路？',
    tags: ['意志教育', '新通路', '习惯'],
  ),
  WillKnowledgeCard(
    id: 'edu_015',
    sectionId: 'meta_training',
    label: 'Edu-015',
    title: '学习动作链就是筛选“感觉对的顺序”',
    oneLiner: '习惯形成不是一下学会，而是从许多可能顺序里不断固定那条对的链。',
    meaning: '一开始动作与反馈会很乱，重复后才会形成稳定的前向联想通路。',
    realScene: '刚开始做晨间流程时总乱，连续重复几天后才顺。',
    practicalAction: '把一个重复任务写成 3 步固定顺序，连续做 3 次。',
    reflection: '你今天哪件事之所以费劲，是因为顺序还没被固定？',
    tags: ['习惯链', '顺序学习', '重复'],
  ),
  WillKnowledgeCard(
    id: 'edu_023',
    sectionId: 'meta_training',
    label: 'Edu-023',
    title: '经验会让痛苦观念提前出现，从而抑制旧反应',
    oneLiner: '吃过亏之后，相关感觉观念会提前冒出来，帮助你别再照旧抓火。',
    meaning: '新形成的前向通路让后果感提前进入，从而打断原来的反射/习惯环。',
    realScene: '你曾因熬夜翻车，后来一到深夜就会先想到第二天崩溃。',
    practicalAction: '把一个你总重复踩坑的行为，补上一条“后果先行提醒”。',
    reflection: '你有没有把过去的代价真正变成下次的前置线索？',
    tags: ['后果提前', '抑制旧反应', '经验学习'],
  ),
  WillKnowledgeCard(
    id: 'edu_024',
    sectionId: 'meta_training',
    label: 'Edu-024',
    title: '旁路支配也能靠期待与反馈重新组织',
    oneLiner: '即使旧路径失效，只要新的动作真正满足期待并带来正确反馈，新通路仍能被组织出来。',
    meaning: '意志训练不是一次成功，而是让“正确动作—正确感觉”反复配对直到新路径变成常规。',
    realScene: '旧的学习方法失效后，你不是更努力硬撑，而是重建一条更适合自己的新流程。',
    practicalAction: '挑一个老方法失效的任务，设计一条替代路径并试一次。',
    reflection: '你今天是在硬守旧路，还是在组织新路？',
    tags: ['替代路径', '重组', '训练'],
  ),
];

const List<WillProblemPath> kWillProblemPaths = [
  WillProblemPath(
    title: '明知该做却做不到',
    summary: '通常不是不知道，而是“阻塞型意志”或任务太大、目标太远、现实感太弱。',
    concepts: ['阻塞型意志', '努力感', '意志教育'],
    actions: ['把任务缩成 2 分钟动作', '先盯住任务 30 秒', '写一句 if-then 计划'],
    linkedCardIds: ['obstructed_001', 'effort_003', 'edu_003', 'edu_015'],
  ),
  WillProblemPath(
    title: '总在权衡，一直定不下来',
    summary: '多半处于审议阶段，前景理由不断变化，背景理由始终未退场。',
    concepts: ['审议', '五种决定类型', '同意与 fiat'],
    actions: ['列出前景/背景理由', '设置决定截止点', '记录自己更常用的决定类型'],
    linkedCardIds: ['delib_001', 'delib_005', 'decision_001', 'decision_005'],
  ),
  WillProblemPath(
    title: '冲动一来就控制不住',
    summary: '常见于爆发型意志：不是坏，而是太快，抑制赶不上。',
    concepts: ['爆发型意志', '快乐与痛苦作为行动的动力', '行为替代'],
    actions: ['延迟 60–90 秒', '离开高风险场景', '替代动作：喝水/走动/沉默'],
    linkedCardIds: ['explosive_002', 'explosive_010', 'pleasure_017'],
  ),
  WillProblemPath(
    title: '总被眼前舒服拉走',
    summary: '很多时候追的不是对象，而是“解除不适”的快感。',
    concepts: ['快乐/痛苦动力', '兴趣', '观念占优'],
    actions: ['写下“我是在追它，还是在逃别的？”', '重建即时反馈', '先做最小动作再评估'],
    linkedCardIds: ['pleasure_017', 'pleasure_022', 'relation_003', 'ideo_086'],
  ),
];

const List<WillTaskPlan> kWillTaskPlans = [
  WillTaskPlan(
    title: '10 秒起步',
    trigger: '当你准备拖延一个重要任务时',
    action: '只做第一个物理动作：打开文档 / 坐下 / 穿鞋 / 写标题。',
    feedback: '完成后立刻勾选“已开始”，不要评价质量。',
    review: '今天阻止你开始的主要对抗观念是什么？',
    sampleIf: '如果我坐到桌前还想拖',
    sampleThen: '那么我只打开文档并写下标题。',
    linkedCardIds: ['ideo_086', 'ideo_090', 'obstructed_001'],
  ),
  WillTaskPlan(
    title: '30 秒注意锁定',
    trigger: '当你想逃开一个应做任务时',
    action: '盯住任务标题或任务物品 30 秒，不切换页面。',
    feedback: '记录这 30 秒里最强的反对声音。',
    review: '你有没有给“更高观念”一点站住的时间？',
    sampleIf: '如果我想逃开这件事',
    sampleThen: '那么我先盯住任务标题 30 秒。',
    linkedCardIds: ['effort_003', 'relation_005', 'relation_014'],
  ),
  WillTaskPlan(
    title: '90 秒延迟诱惑',
    trigger: '当你想立刻刷手机/冲动回话/随手点开娱乐内容时',
    action: '先离场或静止 90 秒，再决定。',
    feedback: '记录你真正想要的是对象，还是解除不适。',
    review: '这次冲动是“想得到”，还是“想停止难受”？',
    sampleIf: '如果我想立刻点开短视频',
    sampleThen: '那么我先把手机扣下并计时 90 秒。',
    linkedCardIds: ['explosive_002', 'explosive_010', 'pleasure_017'],
  ),
  WillTaskPlan(
    title: '晚间意志复盘',
    trigger: '每天睡前',
    action: '写下今天最强的主导观念、最强的对抗观念，以及一个努力点。',
    feedback: '生成明天的一条 if-then 计划。',
    review: '明天再遇到同一情境，你打算更早介入在哪里？',
    sampleIf: '如果我明天又在同一情境里卡住',
    sampleThen: '那么我先执行今天复盘出的最小动作。',
    linkedCardIds: ['relation_003', 'free_010', 'edu_024'],
  ),
];

const List<WillWorldZone> kWillWorldZones = [
  WillWorldZone(
    title: '起意场',
    subtitle: '训练“想到就做”的第一步能力。',
    skills: ['最小动作启动', '去除冲突观念', '先开始再评估'],
    realWorldMapping: '适合拖延启动难、总在门槛前耗住的人。',
    missionTitle: '第一步之门',
    missionSteps: ['识别门口最大的拖延念头', '只触碰一次门把手', '把“大任务”改写成一个物理动作', '回到现实完成同构第一步'],
    linkedCardIds: ['ideo_084', 'ideo_086', 'ideo_090'],
  ),
  WillWorldZone(
    title: '努力坡',
    subtitle: '训练把困难但正确的观念留在心里。',
    skills: ['注意锁定', '同意', '努力点记录'],
    realWorldMapping: '适合明知该做，却总被分心、情绪或舒适拉走的人。',
    missionTitle: '把观念留住',
    missionSteps: ['盯住山顶灯塔 30 秒', '说出一句“让它成为现实”', '识别坡上最强的诱退声音', '在现实中复制一次 30 秒锁定'],
    linkedCardIds: ['effort_003', 'relation_005', 'relation_014'],
  ),
  WillWorldZone(
    title: '诱惑市集',
    subtitle: '训练识别“对象”与“止痛感”之间的差别。',
    skills: ['冲动延迟', '替代动作', '解除不适识别'],
    realWorldMapping: '适合刷手机、暴食、冲动消费、逃避任务的人。',
    missionTitle: '照妖镜',
    missionSteps: ['识别最亮的即时奖励摊位', '先照“照妖镜”看真正逃避的东西', '延迟 90 秒', '回到现实执行一次离场或替代动作'],
    linkedCardIds: ['explosive_002', 'pleasure_017', 'pleasure_022'],
  ),
  WillWorldZone(
    title: '阻塞谷',
    subtitle: '训练把“大事”拆成可发生的第一个动作。',
    skills: ['任务缩小', '现实感增强', '目标近化'],
    realWorldMapping: '适合“明白却动不了”的任务阻塞状态。',
    missionTitle: '碎石路',
    missionSteps: ['辨认那块写着“整件大事”的巨石', '把它敲成最小动作碎块', '只搬走一块', '回到现实做一个 2 分钟动作'],
    linkedCardIds: ['obstructed_001', 'obstructed_004', 'edu_003'],
  ),
];
