const List<Map<String, dynamic>> goalConceptSeedCards = [
  {
    'concept_id': 'GC01',
    'segment_id': 'PP12_01',
    'concept_title': "目标切换与学习框架",
    'one_line_definition': "目标设定不是孤立技巧，而是连接改变、压力与幸福感的起点。",
    'what_is_it': "帮助用户理解课程为什么从“改变”转向“目标”。",
    'why_it_matters': "把目标看成一条成长主线，而不是临时任务。",
    'interaction_type': "用户先圈定“我最想改善的一个生活领域”。",
    'interaction_description': "围绕“目标切换与学习框架”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我现在最需要目标介入的是哪一块？\", \"如果不调整，会继续发生什么？\"]",
  },
  {
    'concept_id': 'GC02',
    'segment_id': 'PP12_02',
    'concept_title': "双货币目标观",
    'one_line_definition': "一个好目标既服务成就，也服务幸福。",
    'what_is_it': "帮助用户避免只把目标当成绩工具。",
    'why_it_matters': "目标应同时回答“让我更成功什么”和“让我更幸福什么”。",
    'interaction_type': "双栏填写“成功收益/幸福收益”。",
    'interaction_description': "围绕“双货币目标观”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"这个目标只满足外在指标吗？\", \"它能带来怎样的生命感？\"]",
  },
  {
    'concept_id': 'GC03',
    'segment_id': 'PP12_03',
    'concept_title': "聚焦与资源唤醒",
    'one_line_definition': "目标能把注意力从噪音中拉回关键路径，并调动资源。",
    'what_is_it': "帮助用户把“我没资源”改写成“我还没盘点资源”。",
    'why_it_matters': "目标像聚光灯，也像资源召唤器。",
    'interaction_type': "资源雷达图，盘点已有/可争取/待搜索资源。",
    'interaction_description': "围绕“聚焦与资源唤醒”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我当前最重要的一步是什么？\", \"我忽略了哪些支持条件？\"]",
  },
  {
    'concept_id': 'GC04',
    'segment_id': 'PP12_04',
    'concept_title': "承诺与组织力",
    'one_line_definition': "公开承诺和结构化安排会提升执行概率。",
    'what_is_it': "帮助用户从“只是想想”走向“对外显化”。",
    'why_it_matters': "目标一旦被写下、说出、排序，就更不容易被逃避。",
    'interaction_type': "承诺阶梯：心里想→写下来→告诉他人。",
    'interaction_description': "围绕“承诺与组织力”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我是否给自己留下太多逃跑空间？\", \"我的目标有时间和顺序吗？\"]",
  },
  {
    'concept_id': 'GC05',
    'segment_id': 'PP12_05',
    'concept_title': "why 让人更能扛",
    'one_line_definition': "意义感是对抗挫败、习得性无助和压力的重要支撑。",
    'what_is_it': "帮助用户在受挫时保住目标。",
    'why_it_matters': "当“为什么”清楚时，“怎么熬过去”会更可承受。",
    'interaction_type': "挫折场景下先填写“我为什么值得继续”。",
    'interaction_description': "围绕“why 让人更能扛”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"如果今天受挫，我为什么还要继续？\", \"我的目标背后真正重要的是什么？\"]",
  },
  {
    'concept_id': 'GC06',
    'segment_id': 'PP12_06',
    'concept_title': "积极信念与自我实现",
    'one_line_definition': "被相信并反复强化的目标，会改变人的行动边界。",
    'what_is_it': "帮助用户建立“可做到”的心理图式。",
    'why_it_matters': "目标不是空想，而是会影响行为的期待系统。",
    'interaction_type': "记录“原以为不可能，但后来做到”的经历。",
    'interaction_description': "围绕“积极信念与自我实现”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我在哪些地方先判定了不可能？\", \"如果别人已经做到，它说明什么？\"]",
  },
  {
    'concept_id': 'GC07',
    'segment_id': 'PP12_07',
    'concept_title': "墙与背包",
    'one_line_definition': "障碍不是终点，目标会逼你盘点工具和方法。",
    'what_is_it': "帮助用户把抱怨转成解题。",
    'why_it_matters': "面对墙，重点不是墙在不在，而是背包里有什么。",
    'interaction_type': "障碍-工具匹配练习。",
    'interaction_description': "围绕“墙与背包”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我当前最大的墙是什么？\", \"我的背包里已有哪3样工具？\"]",
  },
  {
    'concept_id': 'GC08',
    'segment_id': 'PP12_08',
    'concept_title': "语言创造世界",
    'one_line_definition': "你如何命名目标和现实，会影响你如何理解和行动。",
    'what_is_it': "帮助用户看到叙事对体验的塑造作用。",
    'why_it_matters': "语言不仅描述现实，也塑造现实。",
    'interaction_type': "把1句消极叙事改写为行动叙事。",
    'interaction_description': "围绕“语言创造世界”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我最近最常对自己说的限制性句子是什么？\", \"它还有别的说法吗？\"]",
  },
  {
    'concept_id': 'GC09',
    'segment_id': 'PP12_09',
    'concept_title': "问题框架决定现实",
    'one_line_definition': "恐惧式提问会把人带入焦虑，意义式提问会把人带入行动。",
    'what_is_it': "帮助用户改变脑中的默认提问。",
    'why_it_matters': "同一情境，用不同问题切入，会活在不同现实里。",
    'interaction_type': "把恐惧问题改写为建设性问题。",
    'interaction_description': "围绕“问题框架决定现实”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我最近最常问的负面问题是什么？\", \"换一种提问后，我会做什么？\"]",
  },
  {
    'concept_id': 'GC10',
    'segment_id': 'PP12_10',
    'concept_title': "承诺是转折点",
    'one_line_definition': "真正开始投入时，路径、机会与支持才会逐渐显现。",
    'what_is_it': "帮助用户跨过长期犹豫。",
    'why_it_matters': "承诺不是情绪，而是开始行动的门槛。",
    'interaction_type': "承诺滑杆：试试/认真/全力。",
    'interaction_description': "围绕“承诺是转折点”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我是不是一直在等“万事俱备”才开始？\", \"如果先开始，会发生什么？\"]",
  },
  {
    'concept_id': 'GC11',
    'segment_id': 'PP12_11',
    'concept_title': "拥有目标比到达目标更重要",
    'one_line_definition': "幸福往往更多来自持续朝向，而不是终点瞬间。",
    'what_is_it': "帮助用户把幸福从终点挪回过程。",
    'why_it_matters': "目标提供的是方向感、投入感与在途感。",
    'interaction_type': "记录今天最有“在路上”感觉的时刻。",
    'interaction_description': "围绕“拥有目标比到达目标更重要”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"这个目标有让我今天更像在生活吗？\", \"我最近是否只盯终点？\"]",
  },
  {
    'concept_id': 'GC12',
    'segment_id': 'PP12_12',
    'concept_title': "过程幸福而非结果执着",
    'one_line_definition': "目标可以有，但幸福不应完全押注在结果上。",
    'what_is_it': "帮助用户降低结果依赖。",
    'why_it_matters': "执着结果容易增加痛苦，重视过程更能保护当下。",
    'interaction_type': "结果依赖度自测。",
    'interaction_description': "围绕“过程幸福而非结果执着”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"如果结果延迟，我是否就否定自己？\", \"过程里我还能得到什么？\"]",
  },
  {
    'concept_id': 'GC13',
    'segment_id': 'PP12_13',
    'concept_title': "幸福在路上",
    'one_line_definition': "真正令人幸福的，不是领奖台，而是参与中的活力。",
    'what_is_it': "帮助用户重新感受过程。",
    'why_it_matters': "过程中的驾驶、练习、创作，本身就有幸福。",
    'interaction_type': "过程高光捕捉。",
    'interaction_description': "围绕“幸福在路上”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"今天哪一刻让我愿意再经历一次？\", \"我是否把过程当成熬过去？\"]",
  },
  {
    'concept_id': 'GC14',
    'segment_id': 'PP12_14',
    'concept_title': "终点幻觉识别",
    'one_line_definition': "不断追逐“到了那里就好了”会制造空虚和成瘾。",
    'what_is_it': "帮助用户识别高成就型空心循环。",
    'why_it_matters': "there is no there：终点一到，新的终点又会出现。",
    'interaction_type': "回看一个达成后迅速空心的目标。",
    'interaction_description': "围绕“终点幻觉识别”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我是不是把下一个目标当成麻醉？\", \"我忽略了什么真正的需要？\"]",
  },
  {
    'concept_id': 'GC15',
    'segment_id': 'PP12_15',
    'concept_title': "爬山式幸福观",
    'one_line_definition': "人生主要发生在上坡路上，而不是山顶。",
    'what_is_it': "帮助用户停止把当下当成“只是过渡”。",
    'why_it_matters': "如果幸福在爬山过程中，就要学会活在过程阶段。",
    'interaction_type': "给当前阶段命名。",
    'interaction_description': "围绕“爬山式幸福观”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我现在这段路有什么价值？\", \"我为何总想快进？\"]",
  },
  {
    'concept_id': 'GC16',
    'segment_id': 'PP12_16',
    'concept_title': "不是所有目标都值得追",
    'one_line_definition': "目标质量比目标数量更重要，关键在于它是不是你的。",
    'what_is_it': "帮助用户区分真目标和假目标。",
    'why_it_matters': "自我一致目标会带来幸福与能量，外控目标常带来耗竭。",
    'interaction_type': "目标来源拆分：我想要/别人要/我害怕。",
    'interaction_description': "围绕“不是所有目标都值得追”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"这个目标是我真正想要的吗？\", \"如果没人评价，我还会追吗？\"]",
  },
  {
    'concept_id': 'GC17',
    'segment_id': 'PP12_17',
    'concept_title': "从能做走向最想做",
    'one_line_definition': "四层筛选能帮助人从能力清单中找到最想投入的方向。",
    'what_is_it': "帮助用户从“我会什么”走向“我最想要什么”。",
    'why_it_matters': "能做不等于该做，最重要的是筛出最想做。",
    'interaction_type': "四层漏斗拖拽。",
    'interaction_description': "围绕“从能做走向最想做”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我是否长期停在“能做”层面？\", \"什么是我最不愿放弃的？\"]",
  },
  {
    'concept_id': 'GC18',
    'segment_id': 'PP12_18',
    'concept_title': "意义感就是灵性经验",
    'one_line_definition': "当你做自己认为重要的事时，你就在经历灵性。",
    'what_is_it': "帮助用户把灵性理解为重要性感而非抽象标签。",
    'why_it_matters': "灵性取决于动机与重要性，不取决于职业外壳。",
    'interaction_type': "连续追问“为什么重要”。",
    'interaction_description': "围绕“意义感就是灵性经验”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"这件事对我为什么重要？\", \"我是在追形式，还是在追意义？\"]",
  },
  {
    'concept_id': 'GC19',
    'segment_id': 'PP12_19',
    'concept_title': "追随热情也能改善世界",
    'one_line_definition': "自我一致并不等于自私，真实热情常能转化为贡献。",
    'what_is_it': "帮助用户把个人热情与社会价值连接。",
    'why_it_matters': "越真实的投入，越可能形成可持续贡献。",
    'interaction_type': "热情-贡献交叉图。",
    'interaction_description': "围绕“追随热情也能改善世界”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我喜欢的事能帮助谁？\", \"我能把兴趣转化成什么价值？\"]",
  },
  {
    'concept_id': 'GC20',
    'segment_id': 'PP12_20',
    'concept_title': "不要把延迟满足延迟一辈子",
    'one_line_definition': "必要的延迟满足可以接受，但不能让它变成永久搁置生命。",
    'what_is_it': "帮助用户识别长期 rat race。",
    'why_it_matters': "短期忍耐可以服务成长，长期自我搁置会让生命失真。",
    'interaction_type': "延迟满足边界检查。",
    'interaction_description': "围绕“不要把延迟满足延迟一辈子”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我是在策略性等待，还是习惯性拖延自己的人生？\", \"我何时能开始真正重要的事？\"]",
  },
  {
    'concept_id': 'GC21',
    'segment_id': 'PP12_21',
    'concept_title': "Carpe Diem 抓住当下",
    'one_line_definition': "真正想做的事，不应永远停留在未来。",
    'what_is_it': "帮助用户把重要之事前置到今天。",
    'why_it_matters': "抓住今天，不是否认计划，而是不把生命无限后推。",
    'interaction_type': "“以后再说”清单清理。",
    'interaction_description': "围绕“Carpe Diem 抓住当下”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我最不该再拖延的事是什么？\", \"今天能前进一步吗？\"]",
  },
  {
    'concept_id': 'GC22',
    'segment_id': 'ST13_01',
    'concept_title': "把自我一致性继续讲深",
    'one_line_definition': "Carpe Diem 之后，课程继续往更深层的自我一致性展开。",
    'what_is_it': "帮助用户知道第13集是对前面目标主题的深化。",
    'why_it_matters': "这里开始把“什么目标值得追”讲得更细。",
    'interaction_type': "填写“我最想继续深挖的目标主题”。",
    'interaction_description': "围绕“把自我一致性继续讲深”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我最想进一步理解自己的哪一类目标？\", \"我最困惑的是哪一部分？\"]",
  },
  {
    'concept_id': 'GC23',
    'segment_id': 'ST13_02',
    'concept_title': "自我一致性目标的收益",
    'one_line_definition': "自我一致目标会带来幸福、减少内耗、提高成功概率。",
    'what_is_it': "帮助用户理解为什么要优先追求自我一致目标。",
    'why_it_matters': "它能提升过程幸福、缓解焦虑和不确定，并提高投入。",
    'interaction_type': "收益分层图：幸福/冲突/成功。",
    'interaction_description': "围绕“自我一致性目标的收益”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我现在最大的内耗来自哪里？\", \"更一致的目标是否会减轻它？\"]",
  },
  {
    'concept_id': 'GC24',
    'segment_id': 'ST13_03',
    'concept_title': "一致性会自我强化并涓滴扩散",
    'one_line_definition': "当人做对了目标，积极效应会溢出到别的领域。",
    'what_is_it': "帮助用户看到“一个点亮的角落”如何带动整体生活。",
    'why_it_matters': "自我一致会形成增强回路，也会对其他任务产生正向影响。",
    'interaction_type': "生活联动图。",
    'interaction_description': "围绕“一致性会自我强化并涓滴扩散”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"哪件让我活起来的事正在带动其他领域？\", \"我是否低估了它的价值？\"]",
  },
  {
    'concept_id': 'GC25',
    'segment_id': 'ST13_04',
    'concept_title': "选择就是生命力",
    'one_line_definition': "做自己想做的事、保有选择权，会改善幸福、健康和生命力。",
    'what_is_it': "帮助用户重视“选择”本身。",
    'why_it_matters': "不是所有照顾都对人成长有利，适度自主才会让人活起来。",
    'interaction_type': "选择权指数打分。",
    'interaction_description': "围绕“选择就是生命力”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我生活中哪些地方过于被安排？\", \"我今天能主动选什么？\"]",
  },
  {
    'concept_id': 'GC26',
    'segment_id': 'ST13_05',
    'concept_title': "VIA：给优势和美德命名",
    'one_line_definition': "VIA 是识别人格优势与美德的框架，帮助人理解“我擅长什么、重视什么、热爱什么”。",
    'what_is_it': "帮助用户建立优势语言。",
    'why_it_matters': "目标与旅程都可以通过优势来实现一致。",
    'interaction_type': "优势词卡识别。",
    'interaction_description': "围绕“VIA：给优势和美德命名”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我最常被别人肯定的品质是什么？\", \"我有哪些天然优势？\"]",
  },
  {
    'concept_id': 'GC27',
    'segment_id': 'ST13_06',
    'concept_title': "识别核心优势的三个标准",
    'one_line_definition': "真实的我、有能量、能成长，是辨认核心优势的重要标准。",
    'what_is_it': "帮助用户从众多优点中筛出真正的 signature strengths。",
    'why_it_matters': "不是所有优势都同样核心，要聚焦最自然、回报最高的部分。",
    'interaction_type': "三标准评分表。",
    'interaction_description': "围绕“识别核心优势的三个标准”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"什么特质最像我？\", \"什么事让我做了更有劲？\"]",
  },
  {
    'concept_id': 'GC28',
    'segment_id': 'ST13_07',
    'concept_title': "两套优势练习",
    'one_line_definition': "优势既可以用来建立能力，也可以直接拿来解决问题。",
    'what_is_it': "帮助用户把优势从“知道”变成“使用”。",
    'why_it_matters': "通过持续使用优势，人会更幸福、更抗压，也更能解题。",
    'interaction_type': "7日优势挑战 + 问题匹配。",
    'interaction_description': "围绕“两套优势练习”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我有没有把优势变成习惯？\", \"我最近一个问题可以借哪个优势来解？\"]",
  },
  {
    'concept_id': 'GC29',
    'segment_id': 'ST13_08',
    'concept_title': "Job / Career / Calling",
    'one_line_definition': "同一份工作或学习，可以被活成糊口、晋升赛道或使命。",
    'what_is_it': "帮助用户重看职业与人生方向。",
    'why_it_matters': "calling 不只关乎做什么，更关乎你如何理解它。",
    'interaction_type': "三种工作取向重写。",
    'interaction_description': "围绕“Job / Career / Calling”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我现在主要活在哪种取向里？\", \"我能否把一部分工作重写出意义？\"]",
  },
  {
    'concept_id': 'GC30',
    'segment_id': 'ST13_09',
    'concept_title': "不要逃避你的使命声音",
    'one_line_definition': "人常因害怕、环境期待或安全感而逃避 vocation。",
    'what_is_it': "帮助用户正视内在召唤。",
    'why_it_matters': "真正高尚的事不是迎合评价，而是诚实倾听内在声音。",
    'interaction_type': "内在声音/外在声音对话。",
    'interaction_description': "围绕“不要逃避你的使命声音”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"如果没人评价，我会想做什么？\", \"我最害怕听见的答案是什么？\"]",
  },
  {
    'concept_id': 'GC31',
    'segment_id': 'ST13_10',
    'concept_title': "想想你不能没有什么",
    'one_line_definition': "与其只想能忍什么，不如想自己不能没有什么。",
    'what_is_it': "帮助用户靠近真正重要的生命主题。",
    'why_it_matters': "“不能没有什么”比“还能将就什么”更接近核心。",
    'interaction_type': "不能没有什么清单。",
    'interaction_description': "围绕“想想你不能没有什么”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"什么是我不能没有的？\", \"如果失去它，我会感到自己不再是自己吗？\"]",
  },
  {
    'concept_id': 'GC32',
    'segment_id': 'ST13_11',
    'concept_title': "目标设定的基本技巧",
    'one_line_definition': "写下来、设 lifeline、具体化，目标才能真正服务旅程。",
    'what_is_it': "帮助用户把目标从愿望变为结构化对象。",
    'why_it_matters': "目标的关键不是结果本身，而是它是否激发和解放你。",
    'interaction_type': "目标工坊表单。",
    'interaction_description': "围绕“目标设定的基本技巧”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我的目标写下来了吗？\", \"它是否具体、可衡量、带来能量？\"]",
  },
  {
    'concept_id': 'GC33',
    'segment_id': 'ST13_12',
    'concept_title': "伸展目标能点燃人",
    'one_line_definition': "适度拉伸的目标比太容易或太模糊的目标更能激发人。",
    'what_is_it': "帮助用户校准挑战度。",
    'why_it_matters': "肯尼迪登月说明：鼓舞性的目标能点燃系统。",
    'interaction_type': "挑战度滑杆。",
    'interaction_description': "围绕“伸展目标能点燃人”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我的目标太轻还是太重？\", \"它真的点燃我了吗？\"]",
  },
  {
    'concept_id': 'GC34',
    'segment_id': 'ST13_13',
    'concept_title': "看见路径会增强信念",
    'one_line_definition': "只看结果会让人觉得不可能；看见路径才更敢相信自己能做到。",
    'what_is_it': "帮助用户增强自我效能感。",
    'why_it_matters': "相信自己能做到，是长期成功的重要预测因子之一。",
    'interaction_type': "结果/路径双视角对比。",
    'interaction_description': "围绕“看见路径会增强信念”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我是不是只盯成功者的结果？\", \"我了解他们走过的路吗？\"]",
  },
  {
    'concept_id': 'GC35',
    'segment_id': 'ST13_14',
    'concept_title': "把大目标拆成台阶、计划与仪式",
    'one_line_definition': "长期目标需要被拆成台阶，并通过计划与仪式转成可执行路径。",
    'what_is_it': "帮助用户把“巨大的高度”变成可走的楼梯。",
    'why_it_matters': "一步一步的结构，比抽象大目标更能让人相信自己做得到。",
    'interaction_type': "台阶地图 + 仪式设计。",
    'interaction_description': "围绕“把大目标拆成台阶、计划与仪式”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我的目标可以拆成哪些层级？\", \"我需要什么固定仪式来支持它？\"]",
  },
  {
    'concept_id': 'GC36',
    'segment_id': 'ST13_15',
    'concept_title': "从目标过渡到压力主题",
    'one_line_definition': "课程在这里从目标自然过渡到压力，说明执行系统离不开压力管理。",
    'what_is_it': "帮助用户理解后续为什么要讲压力。",
    'why_it_matters': "目标不是孤立存在，能否持续推进取决于人与压力的关系。",
    'interaction_type': "过渡提示卡。",
    'interaction_description': "围绕“从目标过渡到压力主题”设置一个低门槛互动，帮助用户先理解，再行动。",
    'reflection_json': "[\"我当前最大的压力点是什么？\", \"它正在怎样影响我的目标执行？\"]",
  },
];

const List<Map<String, dynamic>> goalActionSeedTemplates = [
  {
    'action_id': 'GA01',
    'segment_id': 'PP12_01',
    'concept_id': 'GC01',
    'action_title': "锁定一个当前最想改善的生活领域。",
    'action_level': "微行动",
    'goal_of_action': "把“目标切换与学习框架”从理解推进到一次现实实践。",
    'steps_json': "[\"写下一个最困扰你的现实问题\", \"写下你希望它朝哪个方向变化\", \"把这个方向命名\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA02',
    'segment_id': 'PP12_02',
    'concept_id': 'GC02',
    'action_title': "为一个目标写出双重收益。",
    'action_level': "标准行动",
    'goal_of_action': "把“双货币目标观”从理解推进到一次现实实践。",
    'steps_json': "[\"写下一个目标\", \"左栏写3个现实收益\", \"右栏写3个幸福/意义收益\", \"比较哪边更薄弱\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA03',
    'segment_id': 'PP12_03',
    'concept_id': 'GC03',
    'action_title': "盘点服务当前目标的资源。",
    'action_level': "标准行动",
    'goal_of_action': "把“聚焦与资源唤醒”从理解推进到一次现实实践。",
    'steps_json': "[\"为当前目标列出1个关键指标\", \"列出3个已有资源\", \"列出2个可争取资源\", \"安排1个本周要行动的资源请求\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA04',
    'segment_id': 'PP12_04',
    'concept_id': 'GC04',
    'action_title': "做一次可见承诺。",
    'action_level': "标准行动",
    'goal_of_action': "把“承诺与组织力”从理解推进到一次现实实践。",
    'steps_json': "[\"把本周目标写下来\", \"安排一个推进时间块\", \"告诉1位可信任的人你会在何时推进\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA05',
    'segment_id': 'PP12_05',
    'concept_id': 'GC05',
    'action_title': "制作抗崩溃 why 卡。",
    'action_level': "标准行动",
    'goal_of_action': "把“why 让人更能扛”从理解推进到一次现实实践。",
    'steps_json': "[\"写一张卡片，列出这个目标对我重要的3个原因\", \"把卡片放在随时能看到的位置\", \"以后想放弃时先读一遍\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA06',
    'segment_id': 'PP12_06',
    'concept_id': 'GC06',
    'action_title': "回收自己的可行性证据。",
    'action_level': "标准行动",
    'goal_of_action': "把“积极信念与自我实现”从理解推进到一次现实实践。",
    'steps_json': "[\"写下1件你曾经以为做不到后来做到的事\", \"总结其中的关键转折\", \"把这段经历挂到当前目标上\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA07',
    'segment_id': 'PP12_07',
    'concept_id': 'GC07',
    'action_title': "为当前障碍列工具清单。",
    'action_level': "进阶行动",
    'goal_of_action': "把“墙与背包”从理解推进到一次现实实践。",
    'steps_json': "[\"写下当前最大障碍\", \"列出3个解决工具\", \"列出1个可求助对象\", \"列出1个今天能试的动作\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA08',
    'segment_id': 'PP12_08',
    'concept_id': 'GC08',
    'action_title': "改写一句限制性语言。",
    'action_level': "微行动",
    'goal_of_action': "把“语言创造世界”从理解推进到一次现实实践。",
    'steps_json': "[\"写下1句你最近常说的限制性语言\", \"把它改写成更具体、更可行动的表达\", \"再补上一个下一步动作\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA09',
    'segment_id': 'PP12_09',
    'concept_id': 'GC09',
    'action_title': "改写一个焦虑问题。",
    'action_level': "标准行动",
    'goal_of_action': "把“问题框架决定现实”从理解推进到一次现实实践。",
    'steps_json': "[\"选一个最近让你焦虑的任务\", \"列出3个恐惧问题\", \"把它们改写成3个目标/意义问题\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA10',
    'segment_id': 'PP12_10',
    'concept_id': 'GC10',
    'action_title': "做一次7天承诺实验。",
    'action_level': "标准行动",
    'goal_of_action': "把“承诺是转折点”从理解推进到一次现实实践。",
    'steps_json': "[\"选一个停滞目标\", \"给自己7天固定投入\", \"每天记录投入后的新发现\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA11',
    'segment_id': 'PP12_11',
    'concept_id': 'GC11',
    'action_title': "记录今日方向感。",
    'action_level': "标准行动",
    'goal_of_action': "把“拥有目标比到达目标更重要”从理解推进到一次现实实践。",
    'steps_json': "[\"今天结束前写下1个让你感觉“我在往重要方向前进”的瞬间\", \"补充当时在做什么\", \"记录那一刻的感受\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA12',
    'segment_id': 'PP12_12',
    'concept_id': 'GC12',
    'action_title': "写下不依赖结果的收益。",
    'action_level': "标准行动",
    'goal_of_action': "把“过程幸福而非结果执着”从理解推进到一次现实实践。",
    'steps_json': "[\"选择一个重要目标\", \"写下“即使暂未达成，我仍获得了……”至少3条\", \"读一遍并挑出最打动你的1条\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA13',
    'segment_id': 'PP12_13',
    'concept_id': 'GC13',
    'action_title': "收集一个过程高光。",
    'action_level': "标准行动",
    'goal_of_action': "把“幸福在路上”从理解推进到一次现实实践。",
    'steps_json': "[\"今天完成任务后记录1个过程中让你有生命感的细节\", \"写下它为什么重要\", \"下次刻意增加类似时刻\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA14',
    'segment_id': 'PP12_14',
    'concept_id': 'GC14',
    'action_title': "做一次终点后复盘。",
    'action_level': "标准行动",
    'goal_of_action': "把“终点幻觉识别”从理解推进到一次现实实践。",
    'steps_json': "[\"回顾1个完成后很快空掉的目标\", \"写下它当时期待满足什么\", \"写下它没满足的深层需要\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA15',
    'segment_id': 'PP12_15',
    'concept_id': 'GC15',
    'action_title': "为当前阶段赋义。",
    'action_level': "标准行动",
    'goal_of_action': "把“爬山式幸福观”从理解推进到一次现实实践。",
    'steps_json': "[\"给你当前的人生阶段起一个名字\", \"写下它的价值\", \"写下这段路正在训练你什么\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA16',
    'segment_id': 'PP12_16',
    'concept_id': 'GC16',
    'action_title': "辨认一个最不像自己的目标。",
    'action_level': "标准行动",
    'goal_of_action': "把“不是所有目标都值得追”从理解推进到一次现实实践。",
    'steps_json': "[\"列出当前3个目标\", \"分别标记内在驱动/外在期待/恐惧驱动的占比\", \"圈出最不像自己的那个\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA17',
    'segment_id': 'PP12_17',
    'concept_id': 'GC17',
    'action_title': "做一次四层筛选。",
    'action_level': "进阶行动",
    'goal_of_action': "把“从能做走向最想做”从理解推进到一次现实实践。",
    'steps_json': "[\"列10件你能做的事\", \"逐层筛到“想做/真的想做/最想做”\", \"留下1-2个最重要方向\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA18',
    'segment_id': 'PP12_18',
    'concept_id': 'GC18',
    'action_title': "深挖一个目标的重要性。",
    'action_level': "标准行动",
    'goal_of_action': "把“意义感就是灵性经验”从理解推进到一次现实实践。",
    'steps_json': "[\"对当前目标连续追问3次“为什么重要”\", \"直到出现更深层答案\", \"把最深的一层写下来\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA19',
    'segment_id': 'PP12_19',
    'concept_id': 'GC19',
    'action_title': "找一个热情与贡献交点。",
    'action_level': "标准行动",
    'goal_of_action': "把“追随热情也能改善世界”从理解推进到一次现实实践。",
    'steps_json': "[\"写出你真正喜欢的3件事\", \"写出它们各自可能帮助的人或领域\", \"圈出1个最值得继续探索的交点\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA20',
    'segment_id': 'PP12_20',
    'concept_id': 'GC20',
    'action_title': "找出一个被拖太久的重要事项。",
    'action_level': "标准行动",
    'goal_of_action': "把“不要把延迟满足延迟一辈子”从理解推进到一次现实实践。",
    'steps_json': "[\"写下1件被你以“以后再说”推迟很久的事\", \"写下继续推迟的代价\", \"安排一个本周最小起步动作\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA21',
    'segment_id': 'PP12_21',
    'concept_id': 'GC21',
    'action_title': "把一件重要事拉回今天。",
    'action_level': "微行动",
    'goal_of_action': "把“Carpe Diem 抓住当下”从理解推进到一次现实实践。",
    'steps_json': "[\"选一件长期拖延的重要事\", \"定义今天能做的最小一步\", \"今天之内完成它\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA22',
    'segment_id': 'ST13_01',
    'concept_id': 'GC22',
    'action_title': "确认一个要继续深挖的方向。",
    'action_level': "标准行动",
    'goal_of_action': "把“把自我一致性继续讲深”从理解推进到一次现实实践。",
    'steps_json': "[\"从目标/过程/优势/使命中选1个你最想搞清楚的主题\", \"写下原因\", \"把它设为本周学习重点\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA23',
    'segment_id': 'ST13_02',
    'concept_id': 'GC23',
    'action_title': "定位一个被不一致目标放大的内耗。",
    'action_level': "标准行动",
    'goal_of_action': "把“自我一致性目标的收益”从理解推进到一次现实实践。",
    'steps_json': "[\"写下1个让你焦虑的目标\", \"分析它是否因“不像自己”而更难受\", \"写下1个可调整方向\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA24',
    'segment_id': 'ST13_03',
    'concept_id': 'GC24',
    'action_title': "做一次涓滴效应观察。",
    'action_level': "进阶行动",
    'goal_of_action': "把“一致性会自我强化并涓滴扩散”从理解推进到一次现实实践。",
    'steps_json': "[\"连续3天做一个高一致性活动\", \"记录它对其他任务的影响\", \"总结最明显的一条联动\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA25',
    'segment_id': 'ST13_04',
    'concept_id': 'GC25',
    'action_title': "完成一次主动选择。",
    'action_level': "标准行动",
    'goal_of_action': "把“选择就是生命力”从理解推进到一次现实实践。",
    'steps_json': "[\"今天在一件小事上主动做决定\", \"记录这种感觉\", \"观察它是否让你更有生命力\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA26',
    'segment_id': 'ST13_05',
    'concept_id': 'GC26',
    'action_title': "初步建立个人优势词库。",
    'action_level': "微行动",
    'goal_of_action': "把“VIA：给优势和美德命名”从理解推进到一次现实实践。",
    'steps_json': "[\"写下5个别人常认可你的特质\", \"判断哪些更像人格优势\", \"留下最有共鸣的3个\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA27',
    'segment_id': 'ST13_06',
    'concept_id': 'GC27',
    'action_title': "筛出4-6个核心优势。",
    'action_level': "标准行动",
    'goal_of_action': "把“识别核心优势的三个标准”从理解推进到一次现实实践。",
    'steps_json': "[\"从你想到的10个优势中，用三个标准打分\", \"筛出4-6个最核心的\", \"写下每个优势最像你的理由\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA28',
    'segment_id': 'ST13_07',
    'concept_id': 'GC28',
    'action_title': "做一轮优势实践。",
    'action_level': "标准行动",
    'goal_of_action': "把“两套优势练习”从理解推进到一次现实实践。",
    'steps_json': "[\"选1个核心优势\", \"连续7天每天用一个新方式实践\", \"另选1个现实问题，用这个优势设计解法\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA29',
    'segment_id': 'ST13_08',
    'concept_id': 'GC29',
    'action_title': "用三种视角重看当前工作。",
    'action_level': "标准行动",
    'goal_of_action': "把“Job / Career / Calling”从理解推进到一次现实实践。",
    'steps_json': "[\"分别用job、career、calling三种方式重写你现在的工作或学习\", \"比较感受差异\", \"选出最需要强化的一种视角\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA30',
    'segment_id': 'ST13_09',
    'concept_id': 'GC30',
    'action_title': "做一次 vocation 自问。",
    'action_level': "进阶行动",
    'goal_of_action': "把“不要逃避你的使命声音”从理解推进到一次现实实践。",
    'steps_json': "[\"写下“我的内在声音在呼唤什么”\", \"写下“我最害怕承认的是什么”\", \"比较两者之间的距离\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA31',
    'segment_id': 'ST13_10',
    'concept_id': 'GC31',
    'action_title': "写一张不能没有什么清单。",
    'action_level': "标准行动",
    'goal_of_action': "把“想想你不能没有什么”从理解推进到一次现实实践。",
    'steps_json': "[\"列出3件你不能没有的东西\", \"解释它们为什么构成你的核心\", \"圈出最不可替代的一项\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA32',
    'segment_id': 'ST13_11',
    'concept_id': 'GC32',
    'action_title': "把一个愿望改写成目标。",
    'action_level': "标准行动",
    'goal_of_action': "把“目标设定的基本技巧”从理解推进到一次现实实践。",
    'steps_json': "[\"写下1个目标的why\", \"写下lifeline\", \"写下具体指标\", \"写下下一步行动\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA33',
    'segment_id': 'ST13_12',
    'concept_id': 'GC33',
    'action_title': "给目标做拉伸度评估。",
    'action_level': "标准行动",
    'goal_of_action': "把“伸展目标能点燃人”从理解推进到一次现实实践。",
    'steps_json': "[\"给当前目标按0-10打拉伸分\", \"如果过低就升级一步\", \"如果过高就拆成阶段\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA34',
    'segment_id': 'ST13_13',
    'concept_id': 'GC34',
    'action_title': "补一份路径视角。",
    'action_level': "进阶行动",
    'goal_of_action': "把“看见路径会增强信念”从理解推进到一次现实实践。",
    'steps_json': "[\"找一个你佩服的人\", \"写下他成功之前可能经历的失败、挣扎和路径细节\", \"写下这对你的启发\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA35',
    'segment_id': 'ST13_14',
    'concept_id': 'GC35',
    'action_title': "做一次目标台阶化。",
    'action_level': "微行动",
    'goal_of_action': "把“把大目标拆成台阶、计划与仪式”从理解推进到一次现实实践。",
    'steps_json': "[\"把1个长期目标拆成长期/中期/短期/本周/明天\", \"再写1个固定仪式\", \"把明天第一步安排进日程\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
  {
    'action_id': 'GA36',
    'segment_id': 'ST13_15',
    'concept_id': 'GC36',
    'action_title': "做一次压力接口记录。",
    'action_level': "进阶行动",
    'goal_of_action': "把“从目标过渡到压力主题”从理解推进到一次现实实践。",
    'steps_json': "[\"写下当前最影响目标推进的一种压力\", \"记录它通常在什么时刻出现\", \"记录它最容易打断你的哪一步\"]",
    'duration_min': 15,
    'failure_plan': "如果今天做不完整，就先只做第一步，并在结束前留下明天的下一步。",
    'feedback_json': "[\"完成情况\", \"做完后的感受\", \"下一次要调整什么\"]",
  },
];