import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../external_data/todo_goal_pages.dart';
import 'shame_transform_ai_service.dart';
import 'shame_transform_dao.dart';
import 'shame_transform_models.dart';

class ShameTransformHomePage extends StatefulWidget { const ShameTransformHomePage({super.key}); @override State<ShameTransformHomePage> createState() => _ShameTransformHomePageState(); }
class _ShameTransformHomePageState extends State<ShameTransformHomePage> {
  final _dao = ShameTransformDao(); List<ShameEvent> _events = []; bool _loading = true;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { final items=await _dao.listEvents(); if(mounted)setState((){_events=items;_loading=false;}); }
  @override Widget build(BuildContext context) => Scaffold(backgroundColor: const Color(0xfff7f3ee), appBar: AppBar(title: const Text('足下真实自我'), backgroundColor: const Color(0xfff7f3ee), actions:[IconButton(tooltip:'Todo 目标系统',onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const TodoGoalHomePage())),icon:const Icon(Icons.flag_outlined))]), body:_loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,36),children:[_hero(),const SizedBox(height:18),_todayCard(),const SizedBox(height:18),_sectionTitle('开始一次转化','先稳定，再看见，最后行动'),const SizedBox(height:10),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),mainAxisSpacing:12,crossAxisSpacing:12,childAspectRatio:1.08,children:[_entry(Icons.spa_outlined,'1 分钟急救','强烈羞耻时先回到当下',const Color(0xffd8eee8),()=>_openFlow('羞耻急救',firstAid:true)),_entry(Icons.edit_note,'记录羞耻事件','分开事实、解释与身份审判',const Color(0xffffe4d5),()=>_openFlow('羞耻事件记录')),_entry(Icons.flag_outlined,'目标羞耻扫描','把 Todo 从人格审判带回现实',const Color(0xffe2e5f7),()=>_openFlow('Todo 目标羞耻转化')),_entry(Icons.record_voice_over_outlined,'外化批判声音','留下保护，拿掉羞辱',const Color(0xffffedbd),()=>_openFlow('内在批判声音外化'))]),const SizedBox(height:22),_sectionTitle('行动证据墙','不是鸡汤，是你真实做过的事'),const SizedBox(height:10),if(_events.isEmpty)_emptyEvidence() else ..._events.take(8).map(_evidenceCard)])));
  Widget _hero()=>Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:const Color(0xff203a35),borderRadius:BorderRadius.circular(28)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('HEALING SHAME · 行动系统',style:TextStyle(color:Color(0xffa9d5c7),fontSize:12,fontWeight:FontWeight.w800,letterSpacing:1.1)),SizedBox(height:14),Text('我不是错误本身',style:TextStyle(color:Colors.white,fontSize:29,fontWeight:FontWeight.w900)),SizedBox(height:8),Text('我是有限但有价值的人。看见羞耻，承担责任，保护边界，再做一个现实小行动。',style:TextStyle(color:Colors.white70,height:1.55,fontSize:15))]));
  Widget _todayCard()=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:const Color(0xffe6ddd2))),child:Row(children:[const CircleAvatar(radius:25,backgroundColor:Color(0xffffe8dc),child:Icon(Icons.directions_walk,color:Color(0xffa75035))),const SizedBox(width:14),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('今日练习',style:TextStyle(fontWeight:FontWeight.w900,fontSize:17)),SizedBox(height:4),Text('不追求完美，只把一次羞耻转化为一次行动。',style:TextStyle(color:Color(0xff6f665e),height:1.4))])),Text('${_events.where((e)=>DateTime.fromMillisecondsSinceEpoch(e.createdAt).day==DateTime.now().day).length} 次',style:const TextStyle(fontWeight:FontWeight.w800,color:Color(0xff567a70)))]));
  Widget _sectionTitle(String a,String b)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(b,style:const TextStyle(color:Color(0xff766f69)))]);
  Widget _entry(IconData icon,String title,String sub,Color color,VoidCallback tap)=>InkWell(onTap:tap,borderRadius:BorderRadius.circular(22),child:Ink(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:color,borderRadius:BorderRadius.circular(22)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,size:30,color:const Color(0xff263b37)),const Spacer(),Text(title,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16)),const SizedBox(height:5),Text(sub,maxLines:2,style:const TextStyle(fontSize:12,height:1.35,color:Color(0xff5f5a55)))])));
  Widget _emptyEvidence()=>Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:const Text('完成一次最小行动后，把它变成证据：\n“我虽然感到羞耻，但我没有完全逃避。”',style:TextStyle(height:1.6,color:Color(0xff665f59))));
  Widget _evidenceCard(ShameEvent e)=>Dismissible(key:ValueKey(e.id),direction:DismissDirection.endToStart,onDismissed:(_){_dao.delete(e.id);_load();},background:Container(alignment:Alignment.centerRight,padding:const EdgeInsets.only(right:20),color:Colors.red.shade300,child:const Icon(Icons.delete_outline,color:Colors.white)),child:Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.verified_outlined,color:Color(0xff568275)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.evidenceSentence.isEmpty?e.minimumAction:e.evidenceSentence,style:const TextStyle(fontWeight:FontWeight.w700,height:1.4)),const SizedBox(height:6),Text('${DateFormat('M月d日 HH:mm').format(DateTime.fromMillisecondsSinceEpoch(e.createdAt))} · ${e.eventFact}',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:12,color:Color(0xff847b73))) ]))])));
  Future<void> _openFlow(String scene,{bool firstAid=false}) async { await Navigator.push(context,MaterialPageRoute(builder:(_)=>ShameTransformFlowPage(scene:scene,firstAid:firstAid))); _load(); }
}

class ShameTransformFlowPage extends StatefulWidget { const ShameTransformFlowPage({super.key,required this.scene,this.firstAid=false}); final String scene; final bool firstAid; @override State<ShameTransformFlowPage> createState()=>_ShameTransformFlowPageState(); }
class _ShameTransformFlowPageState extends State<ShameTransformFlowPage>{ final _input=TextEditingController(),_ai=ShameTransformAiService(),_dao=ShameTransformDao(); double _intensity=5; bool _busy=false; ShameAiResult? _result;
 @override void dispose(){_input.dispose();super.dispose();}
 Future<void> _analyze()async{if(_input.text.trim().isEmpty)return;setState(()=>_busy=true);final r=await _ai.analyze(scene:widget.scene,input:_input.text.trim(),intensity:_intensity.round());if(mounted)setState((){_result=r;_busy=false;});}
 Future<void> _save()async{final r=_result;if(r==null)return;final now=DateTime.now().millisecondsSinceEpoch;await _dao.save(ShameEvent(id:'shame_$now',createdAt:now,intensity:_intensity.round(),eventFact:r.facts.isEmpty?_input.text.trim():r.facts.first,toxicLanguage:r.toxicLanguages.join('；'),emotion:'',bodyReaction:'',responsibility:r.responsibility,notResponsibility:r.notResponsibility,healthyRewrite:r.healthyVersion,minimumAction:r.minimumAction,evidenceSentence:r.evidenceSentence));if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('已写入行动证据墙')));Navigator.pop(context);}}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xfff7f3ee),appBar:AppBar(title:Text(widget.scene),backgroundColor:const Color(0xfff7f3ee)),body:ListView(padding:const EdgeInsets.all(18),children:[if(widget.firstAid)_grounding(),Text(widget.firstAid?'现在最刺痛你的那句话是什么？':widget.scene=='Todo 目标羞耻转化'?'写下目标，以及它让你怎样评价自己':'发生了什么？脑中最刺痛的一句话是什么？',style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:12),TextField(controller:_input,minLines:4,maxLines:8,decoration:InputDecoration(hintText:widget.firstAid?'例如：我又搞砸了，大家一定看不起我':'尽量写具体事件，不需要写得完整。',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none))),const SizedBox(height:14),Text('当前强度 ${_intensity.round()} / 10',style:const TextStyle(fontWeight:FontWeight.w700)),Slider(value:_intensity,min:0,max:10,divisions:10,activeColor:const Color(0xff4d776c),onChanged:(v)=>setState(()=>_intensity=v)),FilledButton.icon(onPressed:_busy?null:_analyze,style:FilledButton.styleFrom(backgroundColor:const Color(0xff25443d),padding:const EdgeInsets.symmetric(vertical:15)),icon:_busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.auto_awesome),label:Text(_busy?'正在把身份审判还原为现实问题…':'开始转化')),if(_result!=null)...[const SizedBox(height:22),_resultView(_result!),const SizedBox(height:12),FilledButton.tonalIcon(onPressed:_save,icon:const Icon(Icons.verified_outlined),label:const Text('完成行动后，写入证据墙'))]]));
 Widget _grounding()=>Container(margin:const EdgeInsets.only(bottom:18),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:const Color(0xffdceee8),borderRadius:BorderRadius.circular(20)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('先不分析，只回到当下',style:TextStyle(fontWeight:FontWeight.w900,fontSize:17)),SizedBox(height:8),Text('双脚踩地，慢慢呼气三次。看见身边 3 个物体，然后提醒自己：发生了一件痛苦的事，不等于我就是这件事。',style:TextStyle(height:1.55))]));
 Widget _resultView(ShameAiResult r)=>Column(children:[_card('核心锚点',r.valueAnchor,Icons.anchor),_card('事实 ≠ 解释',([...r.facts.map((e)=>'事实：$e'),...r.interpretations.map((e)=>'解释：$e')]).join('\n'),Icons.call_split),_card('健康羞耻改写','${r.healthyVersion}\n\n${r.identitySentence}',Icons.favorite_outline),_card('责任边界','我承担：${r.responsibility}\n\n我不背负：${r.notResponsibility}',Icons.balance),_card('今日最小行动','${r.minimumAction}\n\n更小版本：${r.fallback}',Icons.directions_walk),_card('行动后证据',r.evidenceSentence,Icons.verified_outlined)]);
 Widget _card(String title,String text,IconData icon)=>Container(width:double.infinity,margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0xffe8dfd5))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(icon,size:20,color:const Color(0xff557a70)),const SizedBox(width:8),Text(title,style:const TextStyle(fontWeight:FontWeight.w900))]),const SizedBox(height:9),Text(text.trim().isEmpty?'等待更多信息，由你确认。':text,style:const TextStyle(height:1.55,color:Color(0xff504a45)))])); }
