#!/usr/bin/env python3
"""Generate synchronized Zhixing Tree V2 knowledge and Dart catalog artifacts."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "assets/zhixing_tree/knowledge_systems_v2_0.json"
PREVIOUS_KNOWLEDGE = REPO / "assets/zhixing_tree/knowledge_v1_2.md"
KNOWLEDGE = REPO / "assets/zhixing_tree/knowledge_v2_0.md"
MANIFEST = REPO / "assets/zhixing_tree/knowledge_manifest_v2_0.json"
DART = REPO / "lib/zhixing_tree/zhixing_thinker_catalog.g.dart"


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def dart_string(value: str) -> str:
    return (
        "'"
        + value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("$", "\\$")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        + "'"
    )


def dart_string_list(values: list[str], indent: int = 0) -> str:
    prefix = " " * indent
    if not values:
        return "<String>[]"
    body = ",\n".join(
        f"{prefix}  {dart_string(value)}" for value in values
    )
    return f"<String>[\n{body},\n{prefix}]"


def generate_dart(payload: dict, catalog_sha256: str) -> str:
    lines = [
        "// GENERATED CODE - DO NOT MODIFY BY HAND.",
        "// Generated by tools/zhixing_tree/generate_knowledge_v2.py.",
        "",
        "part of 'zhixing_thinker_catalog.dart';",
        "",
        f"const String zxGeneratedCatalogSha256 = {dart_string(catalog_sha256)};",
        f"const String zxGeneratedKnowledgeVersion = {dart_string(payload['knowledge_version'])};",
        "",
        "const List<String> zxGeneratedCommonGround = <String>[",
    ]
    lines.extend(
        f"  {dart_string(value)}," for value in payload["common_ground"]
    )
    lines.extend(["];", "", "const Map<String, String> zxGeneratedEvolutionStageGuidance = <String, String>{"])
    lines.extend(
        f"  {dart_string(item['stage'])}: {dart_string(item['guidance'])},"
        for item in payload["evolution_stage_guidance"]
    )
    lines.extend(["};", "", "const Map<String, String> zxGeneratedDecisionRoutes = <String, String>{"])
    lines.extend(
        f"  {dart_string(item['route'])}: {dart_string(item['guidance'])},"
        for item in payload["decision_routes"]
    )
    lines.extend(["};", "", "const List<ZxThinkerGuide> zxGeneratedGuides = <ZxThinkerGuide>["])

    scalar_fields = [
        "systemId",
        "displayName",
        "thinker",
        "category",
        "evolutionStage",
        "primaryLensId",
        "knowledgeView",
        "actionView",
        "splitDiagnosis",
        "transformationPath",
        "actionFeedback",
        "yangmingConnection",
        "inheritedLimit",
        "qualitativeLeap",
        "synthesisOutcome",
        "workSynthesis",
        "distinctiveFocus",
        "decisionCue",
        "primarySourceFoundation",
    ]
    list_fields = [
        "sourceIds",
        "lensIds",
        "coreValues",
        "coreIdeas",
        "sevenLoopRoles",
        "buildsOnSystemIds",
        "relatedSystemIds",
        "tensions",
        "commonGroundWithYangming",
        "differencesFromYangming",
    ]

    for system in payload["systems"]:
        lines.append("  ZxThinkerGuide(")
        lines.append(f"    sequence: {system['sequence']},")
        for field in scalar_fields:
            lines.append(
                f"    {field}: {dart_string(system[field])},"
            )
        for field in list_fields:
            value = dart_string_list(system[field], indent=4)
            lines.append(f"    {field}: {value},")
        lines.append(
            "    evidenceHighlights: <ZxThinkerEvidence>["
        )
        for item in system["evidenceHighlights"]:
            lines.extend(
                [
                    "      ZxThinkerEvidence(",
                    f"        evidenceId: {dart_string(item['evidence_id'])},",
                    f"        sourceId: {dart_string(item['source_id'])},",
                    f"        locator: {dart_string(item['locator'])},",
                    f"        claim: {dart_string(item['claim'])},",
                    f"        summary: {dart_string(item['summary'])},",
                    f"        use: {dart_string(item['use'])},",
                    f"        boundary: {dart_string(item['boundary'])},",
                    f"        evidenceLayer: {dart_string(item['evidence_layer'])},",
                    "      ),",
                ]
            )
        lines.extend(["    ],", "  ),"])
    lines.extend(["];", ""])
    return "\n".join(lines)


def markdown_table_row(values: list[object]) -> str:
    return "| " + " | ".join(str(value).replace("|", "｜") for value in values) + " |"


def validate_payload(payload: dict) -> None:
    works = payload["works"]
    lenses = payload["lenses"]
    systems = payload["systems"]
    if len(works) != payload["source_count"] or len(works) != 22:
        raise ValueError("V2 source must contain exactly 22 works.")
    if len(lenses) != 22:
        raise ValueError("V2 source must contain exactly 22 mechanism lenses.")
    if len(systems) != payload["system_count"] or len(systems) != 17:
        raise ValueError("V2 source must contain exactly 17 integrated systems.")
    if [system["sequence"] for system in systems] != list(range(1, 18)):
        raise ValueError("Integrated system sequence must be 1 through 17.")
    if systems[0]["systemId"] != "yangming":
        raise ValueError("The integrated path must start with Wang Yangming.")

    work_ids = [work["source_id"] for work in works]
    lens_ids = [lens["lens_id"] for lens in lenses]
    covered_lenses: list[str] = []
    evidence_locators: set[str] = set()
    for system in systems:
        if len(system["coreIdeas"]) < 8:
            raise ValueError(f"{system['systemId']} has fewer than 8 core ideas.")
        if len(system["evidenceHighlights"]) < 8:
            raise ValueError(
                f"{system['systemId']} has fewer than 8 evidence highlights."
            )
        if not system["commonGroundWithYangming"]:
            raise ValueError(f"{system['systemId']} lacks common-ground analysis.")
        if not system["differencesFromYangming"]:
            raise ValueError(f"{system['systemId']} lacks difference analysis.")
        if not set(system["sourceIds"]).issubset(work_ids):
            raise ValueError(f"{system['systemId']} references a missing work.")
        covered_lenses.extend(system["lensIds"])
        for evidence in system["evidenceHighlights"]:
            if evidence["source_id"] not in system["sourceIds"]:
                raise ValueError(
                    f"{system['systemId']} contains cross-system evidence "
                    f"{evidence['locator']}."
                )
            evidence_locators.add(evidence["locator"])
    if sorted(covered_lenses) != sorted(lens_ids):
        raise ValueError("The 17 systems must cover every lens exactly once.")
    if len(evidence_locators) != payload["evidence_count"]:
        raise ValueError(
            "Evidence count does not match the unique locator catalog."
        )
    if len(set(work_ids)) != len(work_ids) or len(set(lens_ids)) != len(lens_ids):
        raise ValueError("Work and lens identifiers must be unique.")


def generate_markdown(payload: dict, previous: str) -> str:
    total_records = sum(
        int(work["extract_record_count"]) for work in payload["works"]
    )
    lines = [
        f"# {payload['knowledge_title']}",
        "",
        f"- 知识版本：{payload['knowledge_version']}",
        f"- 原著/材料：{payload['source_count']}部",
        f"- 作者/理论融合体系：{payload['system_count']}套",
        f"- 重点原著证据：{payload['evidence_count']}条",
        f"- 可回定位抽取记录：{total_records}条",
        "- 核心主线：以王阳明知行合一为根，每次引入其他思想都说明上一层缺口、共同点、差异、质变和行动落地。",
        "",
        "> 本版严格区分：A原著证据、B来源内综合、C跨源综合、D产品推论。产品不得把C/D层内容冒充任一作者原意。",
        "",
        "## 证据分层",
        "",
        "| 层级 | 定义 |",
        "|---|---|",
    ]
    lines.extend(
        markdown_table_row([key, value])
        for key, value in payload["evidence_policy"].items()
    )
    lines.extend(
        [
            "",
            "## 22部来源重新打开与抽取审计",
            "",
            "| Source ID | 作者/材料 | 作品 | 版本 | 文本记录 | 重点证据 | 状态 | SHA-256 |",
            "|---|---|---|---|---:|---:|---|---|",
        ]
    )
    for work in payload["works"]:
        lines.append(
            markdown_table_row(
                [
                    work["source_id"],
                    work["author"],
                    work["title"],
                    work["edition"],
                    work["extract_record_count"],
                    work["primary_evidence_count"],
                    work["source_status"],
                    work["source_sha256"],
                ]
            )
        )

    lines.extend(["", "## 共同主线", ""])
    lines.extend(f"- {value}" for value in payload["common_ground"])
    lines.extend(
        [
            "",
            "## 17次认知与行动升级",
            "",
            "| 序号 | 思想体系 | 来源 | 本次质变 |",
            "|---:|---|---|---|",
        ]
    )
    for system in payload["systems"]:
        lines.append(
            markdown_table_row(
                [
                    system["sequence"],
                    system["displayName"],
                    "、".join(system["sourceIds"]),
                    system["qualitativeLeap"],
                ]
            )
        )

    for system in payload["systems"]:
        lines.extend(
            [
                "",
                f"# {system['sequence']}. {system['displayName']}",
                "",
                f"**原著基础：**{system['primarySourceFoundation']}",
                "",
                f"**上一层仍未解决：**{system['inheritedLimit']}",
                "",
                f"**本次质变：**{system['qualitativeLeap']}",
                "",
                "## 核心价值体系",
                "",
                "、".join(system["coreValues"]),
                "",
                "## 围绕知行合一的完整核心思想",
                "",
            ]
        )
        lines.extend(f"{index}. {idea}" for index, idea in enumerate(system["coreIdeas"], 1))
        lines.extend(
            [
                "",
                "## 知、行与知行分裂",
                "",
                f"- **怎样理解知：**{system['knowledgeView']}",
                f"- **怎样理解行：**{system['actionView']}",
                f"- **为何分裂：**{system['splitDiagnosis']}",
                "",
                "## 与王阳明主线的共同点",
                "",
            ]
        )
        lines.extend(f"- {value}" for value in system["commonGroundWithYangming"])
        lines.extend(["", "## 与王阳明主线的差异", ""])
        lines.extend(f"- {value}" for value in system["differencesFromYangming"])
        lines.extend(
            [
                "",
                "## 转化、反馈与跨书融合",
                "",
                f"- **从知到行：**{system['transformationPath']}",
                f"- **行动回写认识：**{system['actionFeedback']}",
                f"- **与王阳明关系：**{system['yangmingConnection']}",
                f"- **同作者/同体系著作融合：**{system['workSynthesis']}",
                f"- **融合后形成：**{system['synthesisOutcome']}",
                f"- **适用决策线索：**{system['decisionCue']}",
                "",
                "## 真实张力与误用边界",
                "",
            ]
        )
        lines.extend(f"- {value}" for value in system["tensions"])
        lines.extend(
            [
                "",
                "## 原著证据链",
                "",
                "| 定位键 | 原著主张/来源内综合 | 证据摘要 | 产品用途 | 边界 |",
                "|---|---|---|---|---|",
            ]
        )
        for item in system["evidenceHighlights"]:
            lines.append(
                markdown_table_row(
                    [
                        item["locator"],
                        item["claim"],
                        item["summary"],
                        item["use"],
                        item["boundary"],
                    ]
                )
            )

    lines.extend(
        [
            "",
            "# V1.2累计知识库原文（历史层，定位键保持不变）",
            "",
            "> 以下完整保留V1.2累计知识库，防止旧证据、边界和版本记录被新结构静默覆盖；V2.0新增部分位于上方。",
            "",
            previous.rstrip(),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    source_raw = SOURCE.read_text(encoding="utf-8")
    payload = json.loads(source_raw)
    validate_payload(payload)
    previous = PREVIOUS_KNOWLEDGE.read_text(encoding="utf-8")
    catalog_sha256 = sha256_text(source_raw)

    knowledge = generate_markdown(payload, previous)
    for lens in payload["lenses"]:
        for locator in lens["evidence_links"]:
            if locator not in knowledge:
                raise ValueError(
                    f"Lens {lens['lens_id']} references missing locator {locator}."
                )
    KNOWLEDGE.write_text(knowledge, encoding="utf-8")
    content_sha256 = sha256_text(knowledge)

    manifest = {
        "manifest": {
            "package_id": "zhixing-tree-core",
            "version": payload["knowledge_version"],
            "rule_version": "2.0.0",
            "published_at": payload["generated_at"],
            "source_count": payload["source_count"],
            "system_count": payload["system_count"],
            "evidence_count": payload["evidence_count"],
            "review_status": "primary_source_reanalysis",
            "content_sha256": content_sha256,
            "catalog_sha256": catalog_sha256,
            "integrity_scheme": "sha256-bundled-content-and-catalog",
            "content_asset": "assets/zhixing_tree/knowledge_v2_0.md",
            "catalog_asset": "assets/zhixing_tree/knowledge_systems_v2_0.json",
        },
        "works": payload["works"],
        "lenses": payload["lenses"],
    }
    MANIFEST.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    DART.write_text(
        generate_dart(payload, catalog_sha256),
        encoding="utf-8",
    )
    print(
        f"Generated {KNOWLEDGE.relative_to(REPO)}, "
        f"{MANIFEST.relative_to(REPO)}, and {DART.relative_to(REPO)}"
    )


if __name__ == "__main__":
    main()
